"""
Catalog Batch 2 — ~300 more items (sofa/bed/dining/storage focus)
Run: python catalog_batch2.py
"""
import json, os, uuid

CATALOG_PATH = os.path.join(os.path.dirname(__file__), "furniture_catalog.json")

def ik(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "IKEA", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.ikea.com/tw/zh/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

def tb(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "Taobao", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.taobao.com/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

BATCH2 = [
    # ── MODERN (35 items) ──────────────────────────────────────────────────
    ik("mod-sofa-black","ÄPPLARYD 三人沙發（黑）","sofa",["modern"],
       ["black sofa","3-seater","contemporary"],["black","anthracite"],
       28900,"W228xD95xH82","deep-seat black fabric 3-seater sofa, contemporary minimal design"),
    ik("mod-tv-stand","BESTÅ 電視櫃組合（黑棕）","storage",["modern"],
       ["TV unit","media console","black brown"],["black brown","dark"],
       8900,"W180xD42xH74","modular black-brown TV console with push-open drawers, modern living room"),
    ik("mod-sideboard-white","BRIMNES 白色梳妝台/邊櫃","storage",["modern"],
       ["sideboard","buffet","white storage"],["white"],
       6900,"W70xD41xH95","white three-drawer storage unit, versatile modern bedroom or living use"),
    ik("mod-desk-standing","TROTTEN 升降書桌（白）","desk",["modern"],
       ["standing desk","height adjustable","electric desk"],["white","light grey"],
       18900,"W140xD70xH72-122","electric height-adjustable standing desk, white, modern home office"),
    ik("mod-chair-ergonomic","HATTEFJÄLL 辦公椅（白）","chair",["modern"],
       ["office chair","ergonomic","white chair"],["white","light grey"],
       15900,"W66xD65xH97-109","white mesh-back ergonomic office chair, adjustable armrests"),
    ik("mod-wardrobe-pax","PAX 衣櫥系統（白/灰玻）","storage",["modern"],
       ["wardrobe","PAX system","sliding door"],["white","frosted glass"],
       25900,"W200xD58xH236","white PAX wardrobe with grey frosted glass sliding doors, spacious modern bedroom"),
    ik("mod-coffee-table-glass","VITTSJÖ 玻璃茶几（黑棕）","table",["modern"],
       ["glass coffee table","black metal","open shelf"],["black brown","tempered glass"],
       3900,"W75xD75xH45","black-brown metal frame glass coffee table, open storage shelf below"),
    ik("mod-pendant-arc","HEKTAR 吊燈（深灰）","lighting",["modern","industrial"],
       ["arc pendant","metal shade","dining light"],["dark grey","black"],
       3500,"Dia38xH22","dark grey metal dome pendant lamp, industrial modern overhead lighting"),
    ik("mod-floor-lamp-arch","HEKTOGRAM 弧形落地燈","lighting",["modern"],
       ["arc floor lamp","reading lamp","tall lamp"],["nickel","white shade"],
       5900,"Base40xH185","arched nickel floor lamp with adjustable white shade, modern reading corner"),
    ik("mod-mirror-round","ROTSUND 圓鏡（白）","mirror",["modern","muji"],
       ["round mirror","white frame","wall mirror"],["white"],
       2990,"Dia80","white circular wall mirror with thin frame, minimal modern bathroom or hallway"),
    ik("mod-shelf-floating","LACK 壁掛層板（黑）","storage",["modern"],
       ["floating shelf","wall shelf","display shelf"],["black"],
       490,"W110xD26","black floating wall shelf, display books or plants, modern minimalist"),
    ik("mod-rug-grey","STOENSE 短毛地毯（中灰）","rug",["modern","muji"],
       ["grey rug","low pile","living room rug"],["medium grey"],
       3990,"160x230cm","medium grey low-pile area rug, soft underfoot, modern neutral living room"),
    ik("mod-dining-extendable","EKEDALEN 延伸餐桌（深棕）","table",["modern"],
       ["extendable table","dining table","dark wood"],["dark brown","oak"],
       12900,"W80-120xD70xH75","dark brown extendable dining table, seats 4-6, modern Scandinavian"),
    ik("mod-stool-bar","DALFRED 吧台椅（黑）","chair",["modern","industrial"],
       ["bar stool","counter stool","black metal"],["black","chrome"],
       2990,"W41xD37xH91","black metal bar stool with footrest, adjustable height, industrial modern"),
    ik("mod-bedframe-slipstitch","MALM 床架（黑棕）","bed",["modern"],
       ["bed frame","MALM","dark wood"],["black brown"],
       12900,"W168xD209xH100 (160cm mattress)","MALM dark-brown low-profile bed frame, clean lines, modern Scandinavian bedroom"),
    tb("mod-sofa-modular","積木沙發組合（深藍）","sofa",["modern"],
       ["modular sofa","sectional","navy blue"],["navy blue","dark blue"],
       35000,"W280xD95xH82","navy blue modular sectional sofa, reconfigurable L-shape, modern living room"),
    tb("mod-console-marble","大理石紋電視台（白）","storage",["modern"],
       ["marble TV console","white cabinet","media unit"],["white","marble veining"],
       18000,"W160xD40xH55","white lacquer TV console with marble-effect top, 2 push-open doors, modern"),
    tb("mod-accent-chair-boucle","布克萊圓椅（象牙白）","chair",["modern","nordic"],
       ["boucle chair","accent chair","round back"],["ivory","cream","warm white"],
       12000,"W75xD72xH80","ivory boucle accent chair with curved back and solid wood legs, modern cozy"),
    tb("mod-bookcase-grid","格狀書架（黑色鐵框）","storage",["modern","industrial"],
       ["grid bookcase","iron shelf","open storage"],["matte black"],
       9500,"W100xD30xH180","matte black iron grid open bookcase, 12 cubbies, modern-industrial home office"),
    tb("mod-dining-chair-velvet","天鵝絨餐椅（煤黑）","chair",["modern","luxury"],
       ["velvet dining chair","black chair","upholstered"],["charcoal black"],
       3500,"W46xD52xH82","charcoal black velvet dining chair with brushed gold legs, modern elegant"),
    tb("mod-pendant-glass-ball","玻璃球吊燈（3頭）","lighting",["modern"],
       ["glass globe pendant","3-light","chandelier style"],["clear glass","brushed gold"],
       8000,"Span60xH45","3-globe clear glass pendant chandelier, brushed gold ceiling plate, modern dining"),
    tb("mod-wall-art-line","幾何線條掛畫（黑白）","accessory",["modern"],
       ["line art","geometric print","wall art"],["black","white"],
       1800,"W50xH70","minimalist black line geometric art print in white frame, modern wall decor"),
    tb("mod-plant-stand-tall","高腳植物架（黑竹）","plant",["modern","nordic"],
       ["plant stand","tall plant shelf","bamboo"],["black","natural bamboo"],
       2200,"Dia30xH120","black-painted bamboo tall plant stand, holds large pot, modern boho"),
    tb("mod-curtain-blackout","遮光窗簾（深灰）","textile",["modern"],
       ["blackout curtain","grey curtain","bedroom curtain"],["dark grey","charcoal"],
       3500,"W140xH280 per panel","dark grey 100% blackout curtain panel, eyelet top, modern bedroom"),
    tb("mod-throw-blanket","針織毯（米白）","textile",["modern","muji"],
       ["knit throw","blanket","couch throw"],["off-white","natural"],
       1500,"130x160cm","chunky knit off-white cotton throw blanket, sofa or bed layering"),
    tb("mod-wall-clock-silent","無聲掛鐘（黑白）","accessory",["modern"],
       ["silent clock","wall clock","minimalist"],["white face","black hands"],
       1200,"Dia30","white silent wall clock with black hands, no tick, modern minimalist"),
    tb("mod-sideboard-oak","白橡木邊櫃（4門）","storage",["modern","nordic"],
       ["sideboard","buffet cabinet","white oak"],["white oak","natural wood"],
       22000,"W160xD40xH75","white oak 4-door sideboard, solid wood legs, modern Scandinavian dining room"),
    tb("mod-desk-lamp-gooseneck","鵝頸桌燈（黑）","lighting",["modern"],
       ["desk lamp","gooseneck","LED task lamp"],["matte black"],
       1800,"H40","matte black gooseneck LED desk lamp, touch dimmer, modern home office"),
    tb("mod-storage-ottoman","方形儲物腳凳（灰）","storage",["modern"],
       ["storage ottoman","footrest","grey tufted"],["grey","heather"],
       4500,"W60xD60xH40","tufted grey fabric storage ottoman with removable lid, modern living room"),
    tb("mod-vase-tall-ceramic","高身啞光陶瓷花瓶（白）","accessory",["modern","muji"],
       ["tall vase","ceramic vase","matte white"],["matte white"],
       1500,"Dia10xH40","tall matte white ceramic vase, simple cylindrical form, modern minimalist"),
    tb("mod-kitchen-island","移動廚房中島（白橡木）","storage",["modern"],
       ["kitchen island","butcher block","rolling cart"],["white","oak top"],
       15000,"W100xD50xH90","white kitchen island with oak butcher block top, 2 drawers, caster wheels"),
    tb("mod-bathroom-vanity","掛壁浴室鏡台（白）","storage",["modern"],
       ["bathroom vanity","wall-hung","white cabinet"],["white","gloss white"],
       12000,"W80xD45xH60","wall-hung white gloss bathroom vanity unit with integrated sink, modern spa"),
    tb("mod-nightstand-drawer","床頭櫃（雙抽，白橡）","storage",["modern"],
       ["nightstand","bedside table","two-drawer"],["white oak","warm white"],
       5500,"W50xD40xH55","white oak veneer 2-drawer nightstand, slim profile, modern Scandinavian bedroom"),
    tb("mod-shoe-cabinet","薄型鞋櫃（白，4層）","storage",["modern"],
       ["shoe cabinet","thin profile","hallway storage"],["white"],
       8000,"W80xD25xH120","slim white 4-tier shoe cabinet with soft-close door, modern entryway"),
    tb("mod-bar-cart","金色移動吧車","storage",["modern","luxury"],
       ["bar cart","gold wheels","drinks trolley"],["gold","clear glass"],
       6000,"W55xD35xH85","gold wire bar cart with 2 glass shelves and caster wheels, modern entertaining"),

    # ── NORDIC (35 items) ──────────────────────────────────────────────────
    ik("nord-sofa-3seat","GRÖNLID 三人沙發（米）","sofa",["nordic"],
       ["3-seater sofa","beige sofa","linen"],["beige","linen","light grey"],
       32900,"W228xD98xH104","wide-arm beige linen-look 3-seater sofa, deep seat, Nordic cozy living"),
    ik("nord-daybed","HEMNES 日床/沙發床（白）","bed",["nordic","muji"],
       ["daybed","sofa bed","pull-out"],["white"],
       16900,"W80xD206xH91","white pine daybed with pull-out extra bed, Nordic dual-purpose living room"),
    ik("nord-dresser","HEMNES 6抽屜斗櫃（白）","storage",["nordic"],
       ["dresser","6-drawer","white chest"],["white"],
       9900,"W108xD50xH131","white painted solid wood 6-drawer dresser, classic Nordic bedroom"),
    ik("nord-dining-round","LISABO 圓形餐桌（梣木）","table",["nordic"],
       ["round dining","ash veneer","light wood"],["ash","light wood"],
       8900,"Dia105xH74","ash veneer round dining table, four legs, light Nordic minimal"),
    ik("nord-chair-rocking","POÄNG 搖椅（樺木/米）","chair",["nordic"],
       ["rocking chair","armchair","POANG"],["birch","beige"],
       7900,"W68xD82xH100","birch veneer bentwood rocking armchair with beige cushion, classic Nordic"),
    ik("nord-rug-natural","LOHALS 平織地毯（自然色）","rug",["nordic","muji"],
       ["flatweave rug","natural fibre","jute look"],["natural","beige"],
       2990,"160x230cm","natural flatweave area rug, jute-look texture, Nordic or bohemian living room"),
    ik("nord-pendant-white-dome","RANARP 吊燈（米白）","lighting",["nordic"],
       ["dome pendant","off-white","fabric cord"],["off-white","beige"],
       2490,"Dia30xH19","off-white metal dome pendant with fabric cord, Nordic kitchen or dining"),
    ik("nord-side-table-pine","KRAGSTA 邊桌（白）","table",["nordic"],
       ["nesting tables","side table","white"],["white"],
       2490,"Dia55xH45","white round side table, simple form, Nordic minimalist living room"),
    ik("nord-wall-shelf","BERGSHULT/PERSHULT 壁架（白/竹）","storage",["nordic"],
       ["wall shelf","floating shelf","bamboo bracket"],["white","bamboo"],
       1290,"W60xD20","white floating shelf with bamboo bracket, Nordic functional decor"),
    ik("nord-plant-pot-white","CITRUSFRUKT 植物盆（白）","plant",["nordic","muji"],
       ["plant pot","white ceramic","indoor planter"],["white","off-white"],
       399,"Dia14","simple white ceramic plant pot, Nordic minimal indoor plant display"),
    ik("nord-throw-grey","POLARVIDE 輕盈毯（淺灰）","textile",["nordic"],
       ["throw blanket","light grey","sofa blanket"],["light grey"],
       499,"130x170cm","light grey polyester throw blanket, breathable, Nordic cozy lounge"),
    ik("nord-mirror-oval","STOCKHOLM 橢圓鏡（黑色框）","mirror",["nordic","modern"],
       ["oval mirror","black frame","Scandinavian mirror"],["black"],
       4990,"W60xH92","black thin-frame oval wall mirror, Nordic-modern statement piece"),
    ik("nord-bedframe-slatted","UTÅKER 堆疊單人床（松木）","bed",["nordic"],
       ["stackable bed","single","pine"],["light pine"],
       5990,"W82xD206xH38","stackable pine single bed, versatile Nordic guest room solution"),
    ik("nord-candle-holder","GLIMMA 未染色蠟燭座","accessory",["nordic"],
       ["candle holder","unscented","tealight"],["natural wax","white"],
       299,"Set of 100","uncoloured tea light candles, hygge Nordic atmosphere"),
    ik("nord-basket-seagrass","FRISSEL 海草收納籃","storage",["nordic","boho"],
       ["seagrass basket","natural basket","storage"],["natural beige","brown"],
       799,"Dia35xH18","woven seagrass storage basket, natural texture, Nordic or boho living room"),
    tb("nord-sofa-linen-cream","奶油色亞麻三人沙發","sofa",["nordic"],
       ["linen sofa","cream sofa","3-seater"],["cream","warm white","natural linen"],
       28000,"W220xD90xH85","cream linen 3-seater sofa with track arms and solid wood legs, Nordic warmth"),
    tb("nord-accent-chair-boucle-warm","暖棕布克萊單椅","chair",["nordic","boho"],
       ["boucle chair","warm tone","accent chair"],["warm beige","honey boucle"],
       11000,"W78xD75xH78","warm honey boucle accent chair, curved silhouette, solid oak legs, Nordic cozy"),
    tb("nord-coffee-table-oval-oak","橢圓形實木橡木茶几","table",["nordic"],
       ["oval coffee table","solid oak","natural wood"],["natural oak","warm wood"],
       15000,"W120xD65xH42","solid oak oval coffee table, smooth surface, Nordic living room centrepiece"),
    tb("nord-tv-unit-white-oak","白橡木電視台（2門）","storage",["nordic"],
       ["TV unit","white oak","2-door"],["white oak","natural"],
       18000,"W160xD40xH55","white oak TV media unit with 2 fluted doors and open shelf, Nordic Scandi"),
    tb("nord-wooden-toy-display","木製玩具展示架","storage",["nordic"],
       ["toy storage","kids shelf","wood display"],["natural pine","white"],
       4500,"W90xD25xH80","natural pine open toy display shelf, child-height, Nordic kids room"),
    tb("nord-pendant-rattan","藤編球形吊燈","lighting",["nordic","boho"],
       ["rattan pendant","wicker lamp","globe light"],["natural rattan","brown"],
       3500,"Dia35","handwoven rattan globe pendant lamp, warm glow, Nordic or boho dining room"),
    tb("nord-linen-curtain","亞麻遮光窗簾（米白）","textile",["nordic"],
       ["linen curtain","off-white curtain","natural fabric"],["off-white","linen"],
       4500,"W140xH240 per panel","off-white linen-blend blackout curtain, rod-pocket top, Nordic bedroom"),
    tb("nord-bath-mat-cotton","純棉浴室地毯（自然色）","textile",["nordic","muji"],
       ["bath mat","cotton","natural"],["natural","cream"],
       800,"50x80cm","chunky loop-pile cotton bath mat, natural undyed colour, Nordic spa bathroom"),
    tb("nord-wooden-clock","原木掛鐘（松木）","accessory",["nordic"],
       ["wooden clock","pine clock","Scandinavian"],["natural pine"],
       1800,"Dia25","natural pine wood round wall clock, minimalist Nordic home decor"),
    tb("nord-photo-frame-set","原木相框組（6件）","accessory",["nordic"],
       ["photo frames","wood frames","gallery wall"],["natural oak","white mat"],
       2500,"Various sizes","set of 6 natural oak photo frames, gallery wall display, Nordic home"),
    tb("nord-kitchen-canisters","陶瓷廚房儲物罐（3件組）","accessory",["nordic"],
       ["kitchen canisters","ceramic jars","white"],["matte white","light grey"],
       2200,"Various","set of 3 matte white ceramic airtight canisters, Nordic kitchen counter"),
    tb("nord-hanger-wall-hook","木質牆面掛衣鉤（5鉤）","accessory",["nordic"],
       ["wall hooks","coat rack","wooden peg"],["natural ash","white wall"],
       1200,"W60","5-peg solid ash wood wall-mounted coat hook rack, Nordic entryway"),
    tb("nord-soap-dispenser-set","陶瓷皂盤+皂瓶組","accessory",["nordic","muji"],
       ["soap dispenser","ceramic","bathroom set"],["matte white"],
       900,"Set","matte white ceramic soap dish and pump dispenser set, Nordic bathroom"),
    tb("nord-string-light-warm","LED暖光串燈（3米）","lighting",["nordic","boho"],
       ["string lights","fairy lights","warm white"],["warm white","amber"],
       800,"300cm","3m warm white LED micro fairy string lights, Nordic hygge bedroom decor"),
    tb("nord-woven-wall-art","編織掛飾（麻繩）","accessory",["nordic","boho"],
       ["woven wall hanging","macrame","natural fiber"],["natural jute","cream"],
       2200,"W50xH70","handwoven jute macrame wall hanging, Nordic or bohemian wall art"),
    tb("nord-indoor-greenhouse","玻璃室內溫室展示架","plant",["nordic"],
       ["glass terrarium","plant display","indoor greenhouse"],["clear glass","brass"],
       8000,"W60xD30xH90","brass-framed glass indoor plant cabinet/terrarium, Nordic botanical display"),
    tb("nord-bamboo-shelf-ladder","竹製梯形置物架（5層）","storage",["nordic"],
       ["ladder shelf","bamboo","5-tier"],["natural bamboo"],
       5500,"W60xD35xH170","natural bamboo 5-tier ladder shelf, leaning design, Nordic home storage"),
    tb("nord-kids-tent-play","兒童帳篷遊戲屋（白棉）","accessory",["nordic"],
       ["kids teepee","play tent","children"],["white cotton","natural wood poles"],
       4500,"Dia120xH140","white cotton teepee play tent with natural wood poles, Nordic kids room"),
    tb("nord-scented-candle-set","針葉林香氛蠟燭組（3件）","accessory",["nordic"],
       ["scented candle","Nordic fragrance","pine cedar"],["white wax","kraft label"],
       2800,"200g each","set of 3 Nordic forest scented soy wax candles (pine/cedar/birch), hygge"),
    tb("nord-linen-bedding-set","亞麻四件式寢具組（灰藍）","textile",["nordic"],
       ["linen bedding","duvet cover","pillow case"],["slate blue","stone grey"],
       5500,"Queen size","slate blue washed linen duvet cover set (1 duvet + 2 pillow cases), Nordic bed"),

    # ── JAPANESE (35 items) ────────────────────────────────────────────────
    ik("jap-coffee-table-low","HEMNES 低矮咖啡桌（黑棕）","table",["japanese"],
       ["low table","black brown","tatami"],["black brown"],
       8900,"W90xD90xH47","black-brown low coffee table, ideal for tatami or zazen seating, Japanese"),
    ik("jap-storage-chest","HEMNES 8抽屜斗櫃（黑棕）","storage",["japanese"],
       ["chest of drawers","black","Japanese storage"],["black brown"],
       14900,"W160xD50xH78","black-brown wide 8-drawer storage chest, Japanese or Scandinavian bedroom"),
    ik("jap-floor-cushion","GURLI 地墊（自然色）","textile",["japanese"],
       ["floor cushion","flat cushion","zazen"],["natural","beige"],
       799,"W65xH65","flat square floor cushion in natural fabric, Japanese zazen seating"),
    ik("jap-bamboo-blind","HOPPVALS 竹節蜂巢簾","textile",["japanese"],
       ["bamboo blind","honeycomb shade","natural"],["natural bamboo","off-white"],
       1490,"W60xL155","bamboo-look honeycomb shade, filters light, Japanese-Nordic hybrid window"),
    ik("jap-paper-lamp-floor","KNIXHULT 紙傘地燈（竹）","lighting",["japanese"],
       ["paper lamp","bamboo","floor lamp","washi"],["natural bamboo","white paper"],
       1490,"Dia45xH140","white rice-paper and bamboo floor lamp, wabi-sabi Japanese atmosphere"),
    ik("jap-wood-tray","IVAR 松木托盤","accessory",["japanese","muji"],
       ["wood tray","serving tray","pine"],["light pine","natural"],
       599,"W34xD26","solid pine serving tray, natural oil finish, Japanese minimalist table styling"),
    ik("jap-folding-screen","RISÖR 折疊屏風","accessory",["japanese"],
       ["folding screen","room divider","bamboo look"],["white","natural"],
       4990,"W80xH150 (each panel)","3-panel white folding screen room divider, Japanese shoji-inspired"),
    ik("jap-hanging-shelf","BJÖRKÖVIKEN 掛牆儲物架（白橡）","storage",["japanese"],
       ["wall shelf","white oak","open display"],["white oak","light wood"],
       1990,"W60xD25","solid white oak floating shelf with wall bracket, Japanese-Nordic display"),
    ik("jap-linen-curtain","AINA 亞麻窗簾（米白）","textile",["japanese"],
       ["linen curtain","off-white","natural fabric"],["off-white","linen"],
       1790,"W140xH250 per panel","off-white linen semi-sheer curtain, natural texture, Japanese light-filled room"),
    ik("jap-ceramic-plate-set","DINERA 餐盤組（米）","accessory",["japanese","muji"],
       ["ceramic plate","dinner set","neutral"],["beige","off-white"],
       999,"Set of 6","matte beige ceramic dinner plates, Nordic-Japanese wabi simplicity"),
    ik("jap-bath-stool-wood","KVISTBRO 木質浴室凳","chair",["japanese"],
       ["wood stool","bath stool","hinoki inspired"],["light pine","natural"],
       2490,"W38xH45","solid pine small stool for bathroom or entryway, Japanese onsen-inspired"),
    ik("jap-wardrobe-open","ELVARLI 開放式更衣室（白）","storage",["japanese"],
       ["open wardrobe","modular closet","white"],["white","light grey"],
       12900,"W150xD55xH216","open-frame white modular wardrobe system, Zen bedroom organisation"),
    ik("jap-side-lamp","FORSÅ 工作台燈（鐵/自然）","lighting",["japanese"],
       ["task lamp","work light","articulating arm"],["iron","natural wood"],
       1490,"H52","adjustable arm table lamp, metal and wood finish, Japanese-Scandinavian desk"),
    ik("jap-teapot-display","MIXOLOGI 調酒用品組","accessory",["japanese"],
       ["display set","ceramic","kitchen"],["white","off-white"],
       899,"Set","minimalist white ceramics display set, Japanese minimalist kitchen counter"),
    ik("jap-mat-tatami","SOMMAR 戶外地毯（綠）","rug",["japanese"],
       ["tatami-inspired","flat mat","green"],["pale green","natural"],
       2490,"160x230cm","flat-weave green area rug, tatami-inspired texture, Japanese modern interior"),
    tb("jap-zaisu-chair","座椅（無腳椅，胡桃木腳）","chair",["japanese"],
       ["zaisu","floor chair","legless chair","Japanese"],["charcoal grey","walnut"],
       6500,"W60xD55xH35","Japanese zaisu armless floor chair, dark fabric, solid walnut base"),
    tb("jap-shoji-lamp","和紙落地燈（高型）","lighting",["japanese"],
       ["washi lamp","shoji paper","floor lamp"],["cream white paper","dark walnut"],
       8500,"W30xD30xH160","tall shoji-style washi paper floor lamp with walnut frame, Japanese ambiance"),
    tb("jap-engawa-bench","縁側風長凳（桐木）","chair",["japanese"],
       ["wooden bench","engawa","paulownia wood"],["natural paulownia","light wood"],
       9500,"W150xD35xH40","low paulownia wood bench, engawa porch-inspired, Japanese garden or living"),
    tb("jap-fusuma-screen","和風引拉屏風（松竹梅）","accessory",["japanese"],
       ["fusuma","sliding screen","room divider"],["cream","ink wash painting"],
       15000,"W80xH170 per panel","2-panel sliding room divider with ink-wash pine-bamboo-plum motif, Japanese"),
    tb("jap-ceramic-teacup-set","茶碗五客組（窯燒信樂）","accessory",["japanese"],
       ["teacup","shigaraki","ceramic set"],["earth tones","brown","ochre"],
       4800,"Set of 5","wood-fired shigaraki ceramic tea bowl set of 5, wabi-sabi Japanese tea ceremony"),
    tb("jap-iron-kettle","南部鐵瓶","accessory",["japanese"],
       ["tetsubin","iron kettle","tea kettle"],["cast iron black","rust brown"],
       8000,"1.2L","nambu-style cast iron tetsubin kettle with strainer, Japanese tea culture"),
    tb("jap-noren-curtain","棉麻暖簾（藍染格紋）","textile",["japanese"],
       ["noren","doorway curtain","indigo"],["indigo blue","natural"],
       1800,"W85xH150","indigo-dyed grid-pattern noren doorway curtain, Japanese entryway divider"),
    tb("jap-tatami-mat","疊蓆（本藺草，雙人）","rug",["japanese"],
       ["tatami mat","igusa grass","rush mat"],["green-yellow","natural rush"],
       12000,"180x90cm","full-size double tatami mat, natural igusa rush grass, authentic Japanese floor"),
    tb("jap-low-shelf","地板書架（胡桃木，3層）","storage",["japanese"],
       ["low bookcase","floor shelf","walnut"],["dark walnut","natural"],
       14000,"W80xD30xH60","low 3-tier solid walnut floor bookcase, Japanese living room display"),
    tb("jap-wooden-bath-bucket","木桶湯桶（扁柏）","accessory",["japanese"],
       ["hinoki bucket","onsen","bath bucket"],["natural hinoki cypress"],
       6000,"Dia30xH20","handcrafted hinoki cypress bath bucket, Japanese onsen bath ritual"),
    tb("jap-bamboo-mat-round","圓形竹席地墊","rug",["japanese"],
       ["bamboo mat","round mat","natural"],["natural bamboo","green-brown"],
       2500,"Dia120","round woven bamboo mat, natural cooling floor mat, Japanese summer room"),
    tb("jap-hanging-scroll","書法掛軸（秋の聲）","accessory",["japanese"],
       ["kakejiku","hanging scroll","calligraphy"],["ink black","cream silk"],
       5500,"W30xH120","handwritten Japanese calligraphy hanging scroll on silk brocade, wall art"),
    tb("jap-stone-garden","迷你枯山水石庭","accessory",["japanese"],
       ["zen garden","sand garden","miniature"],["grey sand","dark stone"],
       2200,"W30xD20","miniature zen sand garden with rake and stones, Japanese meditation decor"),
    tb("jap-futon-cotton","純棉睡眠床墊（米色）","bed",["japanese"],
       ["futon","floor mattress","cotton"],["natural cotton","off-white"],
       8000,"100x200cm","traditional Japanese cotton futon floor mattress, foldable, natural undyed"),
    tb("jap-wooden-coat-hanger","木質圓弧衣架（5入）","accessory",["japanese"],
       ["wooden hanger","coat hanger","natural wood"],["natural beech"],
       800,"Set of 5","solid beech curved coat hangers, natural finish, Japanese minimalist wardrobe"),
    tb("jap-bonsai-pot","盆栽陶瓷花器（黑釉）","plant",["japanese"],
       ["bonsai pot","black glaze","ceramic"],["black glaze","dark earthy"],
       2500,"Dia20","black-glazed oval ceramic bonsai display pot, Japanese garden art"),
    tb("jap-shoji-sliding-door","和風拉門（木框/和紙）","accessory",["japanese"],
       ["sliding door","shoji panel","room partition"],["natural wood","cream paper"],
       22000,"W80xH210 per panel","2-panel wood-frame washi paper sliding door set, Japanese interior partition"),
    tb("jap-tokonoma-shelf","床の間置物架（黑胡桃）","storage",["japanese"],
       ["tokonoma shelf","alcove display","walnut"],["dark walnut"],
       18000,"W60xD25xH150","black walnut tokonoma alcove display shelf with integrated bottom storage"),
    tb("jap-clay-diffuser","手拋陶土薰香台","accessory",["japanese"],
       ["incense holder","clay diffuser","aroma"],["earth clay","raw glaze"],
       1800,"W12xH8","hand-thrown clay incense burner and oil diffuser, Japanese ceramics wabi feel"),
    tb("jap-indigo-cushion","藍染坐墊（4入組）","textile",["japanese"],
       ["floor cushion","indigo dye","zabuton"],["indigo blue","natural cotton"],
       4500,"Set of 4, 55x55cm","set of 4 indigo-dyed cotton zabuton floor cushions, Japanese living room"),

    # ── MUJI (35 items) ────────────────────────────────────────────────────
    ik("muji-shelf-unit","KALLAX 格狀書架（白）","storage",["muji","modern"],
       ["cube shelf","white","modular"],["white"],
       3990,"W77xD39xH147","white modular cube shelf unit, versatile MUJI-style storage and display"),
    ik("muji-stool-pine","KYRRE 圓凳（樺木）","chair",["muji","nordic"],
       ["round stool","birch","simple"],["birch","natural"],
       1490,"Dia36xH45","round solid birch stool, simple minimal form, MUJI or Nordic use"),
    ik("muji-mirror-standing","NISSEDAL 立式全身鏡（白）","mirror",["muji","modern"],
       ["full-length mirror","standing mirror","white frame"],["white"],
       2490,"W65xH150","white leaning full-length floor mirror, simple MUJI-style bedroom or dressing room"),
    ik("muji-duvet-white","FJÄLLBRÄCKA 白色被子","textile",["muji","nordic"],
       ["duvet","white comforter","all-season"],["white","off-white"],
       2990,"150x200cm","white medium-weight duvet, cool-touch cover, MUJI-clean bedroom bedding"),
    ik("muji-storage-box-set","SAMLA 收納盒組","storage",["muji"],
       ["storage box","transparent","stackable"],["clear transparent"],
       399,"Various","clear stackable storage box set, MUJI-style bedroom or closet organization"),
    ik("muji-hook-strip","SKÅDIS 洞洞板配件","accessory",["muji","modern"],
       ["pegboard","hook strip","office organiser"],["white"],
       799,"W76xH56","white pegboard with hooks and accessories, MUJI desk or kitchen wall organiser"),
    ik("muji-food-storage","IKEA 365+ 食材儲物罐","accessory",["muji"],
       ["food storage","glass jar","kitchen"],["clear glass","bamboo lid"],
       299,"Various sizes","round glass food storage jar with bamboo lid, MUJI minimalist kitchen counter"),
    ik("muji-cotton-rug","BERGBY 平織地毯（白）","rug",["muji","nordic"],
       ["cotton rug","white","flat weave"],["white","off-white"],
       1990,"120x180cm","white flat-weave cotton rug, simple texture, MUJI neutral floor covering"),
    ik("muji-coat-rack","PORTIS 衣架桿","storage",["muji"],
       ["coat rack","clothes rail","freestanding"],["white","silver"],
       1990,"W100xH100","white freestanding clothes rail with adjustable shelf, MUJI simple wardrobe"),
    ik("muji-cleaning-set","PEPPRIG 清潔套裝","accessory",["muji"],
       ["cleaning set","brush","broom"],["white","light grey"],
       499,"Set","minimalist white cleaning brush and dustpan set, MUJI hygiene aesthetic"),
    ik("muji-tray-bamboo","BOHOLMEN 竹製切菜板","accessory",["muji","japanese"],
       ["bamboo tray","cutting board","kitchen"],["natural bamboo"],
       299,"W34xD24","solid bamboo cutting board/serving tray, MUJI-simple kitchen item"),
    ik("muji-bed-white-double","HEMNES 床架（白，雙人）","bed",["muji","nordic"],
       ["bed frame","white","double"],["white"],
       11900,"W152xD212xH93","white painted solid wood double bed frame, simple MUJI bedroom"),
    ik("muji-laundry-basket","KVARNVIK 儲物籃（白）","storage",["muji"],
       ["laundry basket","white","storage bin"],["white"],
       599,"W38xD25xH35","white PP woven storage basket with handles, MUJI laundry or closet use"),
    ik("muji-alarm-clock","LÖTTORP 鬧鐘（白）","accessory",["muji"],
       ["alarm clock","white","simple"],["white"],
       399,"W7xH9","small white digital alarm clock, simple display, MUJI bedside table item"),
    ik("muji-footwear-rack","TJUSIG 鞋架（白）","storage",["muji"],
       ["shoe rack","white","slim"],["white"],
       1290,"W78xD50xH25","white slim shoe rack with simple lines, holds 6-8 pairs, MUJI entryway"),
    tb("muji-linen-shirt-hanger","棉麻收納衣架（10入）","accessory",["muji"],
       ["linen hanger","clothes organiser","slim"],["natural linen"],
       600,"Set of 10","slim natural linen-cover wooden hangers, MUJI wardrobe keep fresh"),
    tb("muji-wooden-box-desk","桌面木質收納盒（3格）","storage",["muji"],
       ["desktop organiser","wooden box","3-compartment"],["natural pine"],
       800,"W24xD10xH6","natural pine 3-slot desktop organiser, MUJI stationary and small items"),
    tb("muji-aromatic-diffuser","超聲波香氛機（白）","accessory",["muji"],
       ["ultrasonic diffuser","aroma","white"],["matte white"],
       2500,"Dia10xH15","white ultrasonic essential oil diffuser, soft mist, MUJI-style bedroom"),
    tb("muji-cotton-pillow","有機棉枕頭（對裝）","textile",["muji"],
       ["cotton pillow","organic","white"],["white"],
       1800,"50x75cm x2","pair of 100% organic cotton pillows, medium firm, MUJI clean bedroom"),
    tb("muji-paper-bin","紙質垃圾桶（圓）","accessory",["muji"],
       ["waste bin","paper","round"],["kraft paper","white"],
       400,"Dia20xH25","white kraft paper round waste bin, simple form, MUJI desk or bedroom"),
    tb("muji-acrylic-organiser","壓克力化妝品收納架","storage",["muji"],
       ["acrylic organiser","makeup storage","transparent"],["clear acrylic"],
       1200,"W20xD15xH25","clear acrylic multi-compartment makeup organiser, MUJI vanity counter"),
    tb("muji-wall-storage-grid","金屬洞洞板儲物系統","storage",["muji","modern","industrial"],
       ["metal pegboard","wall storage","grid"],["matte white","matte black"],
       3500,"W60xH90","metal pegboard wall organiser with hooks and shelves, MUJI office or kitchen"),
    tb("muji-floor-cushion-round","圓形地板坐墊（米）","textile",["muji","japanese"],
       ["round floor cushion","floor seating","beige"],["beige","off-white"],
       1500,"Dia50xH15","round firm floor cushion, natural cotton cover, MUJI or Japanese floor seating"),
    tb("muji-steel-ruler-set","不鏽鋼廚房工具組","accessory",["muji"],
       ["kitchen tools","stainless steel","utensils"],["brushed stainless"],
       1500,"Set","stainless steel kitchen spatula, ladle and whisk set, MUJI functional kitchen"),
    tb("muji-shoe-box-clear","透明鞋盒（6入組）","storage",["muji"],
       ["shoe box","clear","stackable"],["clear transparent"],
       1200,"Set of 6","clear stackable shoe storage boxes, MUJI wardrobe organization"),
    tb("muji-notebook-set","A5方格筆記本（3本）","accessory",["muji"],
       ["notebook","graph paper","stationery"],["off-white","light kraft"],
       600,"A5 x3","A5 graph-ruled notebooks with simple cover, MUJI desk stationery"),
    tb("muji-wooden-hangers-natural","實木衣架（5入）","accessory",["muji"],
       ["wooden hanger","natural","wardrobe"],["natural beech wood"],
       500,"Set of 5","natural beech wood flat coat hangers, MUJI minimalist wardrobe"),
    tb("muji-linen-bag-market","棉麻手提袋（大）","accessory",["muji"],
       ["tote bag","linen","market bag"],["natural linen","off-white"],
       500,"W38xH40","natural linen large market tote bag, simple handles, MUJI everyday carry"),
    tb("muji-led-clip-lamp","夾式LED閱讀燈（白）","lighting",["muji"],
       ["clip lamp","reading light","LED"],["white","matte white"],
       900,"H25","white clip-on LED reading lamp with flexible neck, MUJI bedside or desk"),
    tb("muji-foldable-crate","可折疊收納箱（白）","storage",["muji"],
       ["foldable crate","storage bin","collapsible"],["white"],
       900,"W37xD29xH21","foldable PP storage crate with handles, stackable, MUJI utility room"),
    tb("muji-stainless-mug","不鏽鋼保溫杯（350ml）","accessory",["muji"],
       ["travel mug","stainless","insulated"],["brushed stainless"],
       900,"350ml","brushed stainless steel insulated travel mug, simple design, MUJI thermal"),
    tb("muji-mat-entry","棉質玄關墊（米）","rug",["muji"],
       ["entry mat","cotton","beige"],["natural cotton","beige"],
       800,"60x90cm","natural cotton washable entry mat, simple twill texture, MUJI hallway"),
    tb("muji-writing-desk","實木書桌（白橡，簡約）","desk",["muji","nordic"],
       ["writing desk","white oak","compact"],["white oak"],
       12000,"W120xD60xH73","white oak veneer writing desk, slim legs, clean surface, MUJI or Nordic home office"),
    tb("muji-floor-lamp-paper","和紙球形落地燈","lighting",["muji","japanese"],
       ["paper floor lamp","globe light","washi paper"],["white washi","natural"],
       3500,"Dia40xH150","round washi paper globe floor lamp, warm ambient glow, MUJI or Japanese room"),
    tb("muji-ceramic-bowl-set","白色陶瓷碗組（5件）","accessory",["muji","japanese"],
       ["ceramic bowl","white","dining set"],["matte white"],
       1200,"Set of 5","matte white ceramic rice bowls set of 5, simple round form, MUJI tableware"),
]

def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    print(f"現有項目：{len(existing)} 件")
    existing_names = {item["name_zh"] for item in existing}
    new_items = [item for item in BATCH2 if item["name_zh"] not in existing_names]
    print(f"新增項目：{len(new_items)} 件")
    merged = existing + new_items
    print(f"合併後總計：{len(merged)} 件")
    style_count = {}
    for item in merged:
        s = item.get("style_tags", ["unknown"])[0]
        style_count[s] = style_count.get(s, 0) + 1
    for s, c in sorted(style_count.items()):
        print(f"  {s:15s}: {c} 件")
    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print(f"Done. furniture_catalog.json updated.")

if __name__ == "__main__":
    main()
