"""
Catalog Batch 4 — ~350 more items (all 9 styles, filling gaps)
"""
import json, os

CATALOG_PATH = os.path.join(os.path.dirname(__file__), "furniture_catalog.json")

def tb(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "Taobao", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.taobao.com/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

def ik(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "IKEA", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.ikea.com/tw/zh/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

BATCH4 = [
    # ── MODERN (40 items) ──────────────────────────────────────────────────
    tb("mod2-marble-island-pendant","大理石中島吊燈（線型）","lighting",["modern"],
       ["linear pendant","over island","marble"],["white marble shade","brass"],
       12000,"W80xH15","linear white marble-effect shade pendant lamp, modern kitchen island task lighting"),
    tb("mod2-sideboard-oak-4drawer","橡木四抽邊櫃","storage",["modern"],
       ["sideboard","oak","4-drawer"],["natural oak","warm wood"],
       18000,"W120xD40xH80","4-drawer solid oak sideboard, clean lines, modern living room or bedroom"),
    tb("mod2-floating-vanity","浮壁式化妝台（白橡）","storage",["modern"],
       ["floating vanity","wall-mount","makeup desk"],["white oak","matte white"],
       14000,"W100xD40xH50","wall-mounted white oak floating vanity with integrated mirror, modern bedroom"),
    tb("mod2-curved-sectional","曲線弧形沙發（米白）","sofa",["modern"],
       ["curved sectional","modular","arc sofa"],["cream","warm beige"],
       68000,"W320xD150xH75","cream fabric curved modular sectional sofa, contemporary arc silhouette"),
    tb("mod2-terrazzo-coffee","水磨石茶几（黑腿）","table",["modern"],
       ["terrazzo","coffee table","speckled"],["terrazzo white-grey","matte black legs"],
       15000,"W100xD55xH42","white terrazzo top coffee table on matte black powder-coated steel legs"),
    tb("mod2-oak-dining-bench","橡木木板餐椅長凳","chair",["modern"],
       ["dining bench","oak","solid wood"],["natural oak"],
       8500,"W140xD35xH45","solid oak dining bench, clean contemporary design, pairs with any dining table"),
    tb("mod2-globe-pendant-smoked","煙薰玻璃球燈（吊燈）","lighting",["modern"],
       ["smoked glass globe","pendant","sphere"],["smoked grey","gunmetal"],
       7000,"Dia25","smoked glass sphere pendant lamp with gunmetal fitting, modern minimalist ceiling light"),
    tb("mod2-arch-floor-lamp","弓形落地燈（黑啞光）","lighting",["modern"],
       ["arc floor lamp","black","reading"],["matte black"],
       9500,"H185","sleek matte black arc floor lamp with slim profile, modern reading or accent light"),
    tb("mod2-platform-bed-storage","收納儲物床台（灰色布藝）","bed",["modern"],
       ["storage bed","platform","grey upholstered"],["grey fabric","charcoal"],
       38000,"W183xD213xH35 (king)","king-size grey upholstered platform bed with 4 under-bed drawers, modern storage"),
    tb("mod2-dining-marble-6seat","白大理石6人餐桌","table",["modern"],
       ["marble dining","6-seater","white"],["white marble","brushed chrome"],
       45000,"W180xD90xH76","white marble-look sintered stone top 6-seater dining table on chrome legs, modern"),
    tb("mod2-acacia-console-table","金合歡木玄關桌","table",["modern","nordic"],
       ["console table","acacia","live edge"],["natural acacia","black steel"],
       9500,"W120xD35xH82","live-edge acacia wood console table on slim black steel legs, modern organic"),
    tb("mod2-vertical-storage-tower","垂直收納高塔（白，5層）","storage",["modern","muji"],
       ["storage tower","5-tier","slim"],["white"],
       6500,"W40xD30xH180","slim white 5-tier vertical storage tower, modern hallway or bathroom organiser"),
    tb("mod2-frameless-mirror-bath","無框浴室鏡（LED邊光）","mirror",["modern"],
       ["frameless mirror","LED edge","bathroom"],["edge-lit white LED"],
       9000,"W80xH60","frameless bathroom mirror with continuous LED edge lighting, modern en-suite"),
    tb("mod2-boucle-ottoman-rect","長方形布克萊腳凳（米）","chair",["modern"],
       ["boucle ottoman","rectangular","footstool"],["ivory boucle","natural"],
       6000,"W80xD40xH38","rectangular ivory boucle upholstered footrest ottoman, modern lounge"),
    tb("mod2-loop-rug-wool","羊毛環編地毯（深灰）","rug",["modern"],
       ["loop rug","wool","dark grey"],["dark grey","charcoal"],
       18000,"200x290cm","dark grey 100% wool loop-pile area rug, heavy and luxurious, modern living room"),
    tb("mod2-pendant-black-cone","錐形黑色金屬吊燈","lighting",["modern"],
       ["cone pendant","matte black","metal"],["matte black"],
       3500,"Dia20xH25","matte black cone-shade metal pendant lamp, modern kitchen or bedside"),
    tb("mod2-floating-shelf-set","黑色浮空層板組（3片）","storage",["modern"],
       ["floating shelves","set of 3","black"],["matte black"],
       3500,"Set of 3 (80/60/40cm)","set of 3 matte black floating wall shelves in graduating lengths, modern display"),
    tb("mod2-nightstand-wall-hung","壁掛式床頭桌","storage",["modern"],
       ["wall-hung nightstand","floating","bedside"],["white oak","natural"],
       6000,"W50xD30xH25","wall-mounted floating bedside table with single drawer, modern minimalist bedroom"),
    tb("mod2-ergonomic-chair-white","人體工學椅（全白網布）","chair",["modern"],
       ["ergonomic chair","white","mesh back"],["white","light grey"],
       22000,"W68xD65xH100-112","full-white mesh ergonomic task chair, lumbar support, modern home office"),
    tb("mod2-glass-top-desk","玻璃桌面書桌（黑框）","desk",["modern"],
       ["glass desk","black frame","tempered"],["tempered clear glass","matte black"],
       8500,"W120xD60xH75","tempered clear glass desk on matte black steel frame, modern minimal home office"),
    tb("mod2-outdoor-lounge-sofa","戶外耐候沙發（深灰）","sofa",["modern"],
       ["outdoor sofa","all-weather","dark grey"],["dark grey","charcoal"],
       35000,"W200xD80xH70","weatherproof deep grey PE rattan outdoor sofa with quick-dry cushions, modern terrace"),
    tb("mod2-stainless-kitchen-rack","不鏽鋼廚房掛架（牆式）","storage",["modern"],
       ["kitchen rack","stainless","wall mount"],["brushed stainless"],
       2500,"W60xH30","wall-mounted brushed stainless steel kitchen utensil hanging rail, modern kitchen"),
    tb("mod2-wireless-charger-nightstand","無線充電床頭櫃","storage",["modern"],
       ["nightstand","wireless charging","modern tech"],["white","light grey"],
       8500,"W50xD40xH55","white nightstand with integrated Qi wireless charging pad on top, modern smart bedroom"),
    tb("mod2-pendant-mesh-gold","金色網格球燈","lighting",["modern","luxury"],
       ["mesh globe pendant","gold","modern"],["brushed gold","mesh"],
       8000,"Dia35","brushed gold mesh sphere pendant lamp, modern-luxury dining or bedroom"),
    tb("mod2-tv-unit-floating","懸浮電視台（白色，帶隔板）","storage",["modern"],
       ["floating TV unit","white","with dividers"],["white","light wood"],
       22000,"W180xD35xH45","wall-mounted white floating TV unit with internal wooden dividers, modern living room"),
    tb("mod2-accent-wall-panel","木紋牆面裝飾板（人字拼）","accessory",["modern"],
       ["herringbone panel","wood accent wall","DIY"],["natural oak","warm wood"],
       5000,"W120xH60 per panel","herringbone-pattern oak veneer wall panel for feature wall, modern interior DIY"),
    tb("mod2-cube-bench-storage","收納方塊矮凳（組合式）","storage",["modern"],
       ["cube bench","modular","storage ottoman"],["white","grey"],
       4500,"W45xD45xH45 each","modular white storage cube bench, can be combined in various configurations"),
    tb("mod2-thin-bedframe-oak","薄形橡木雙人床架","bed",["modern","nordic"],
       ["bed frame","thin profile","oak"],["natural oak","light wood"],
       28000,"W153xD213 (queen)","slim-profile natural oak queen bed frame, low 20cm headboard, modern minimal"),
    tb("mod2-grey-sofa-loveseat","灰色雙人小沙發","sofa",["modern"],
       ["loveseat","compact","grey"],["mid grey","heather"],
       18000,"W155xD82xH80","compact 2-seater mid-grey fabric sofa, slim track arms, modern apartment living"),
    tb("mod2-plant-stand-set","梯形植物架組合（3件）","plant",["modern"],
       ["plant stand","set of 3","tiered"],["matte black","walnut"],
       5500,"Set of 3","set of 3 black steel and walnut plant stands in graduating heights, modern display"),
    tb("mod2-roller-blind-grey","捲簾遮光簾（淺灰）","textile",["modern"],
       ["roller blind","light grey","blackout"],["light grey","off-white"],
       2500,"W120xH210","light grey blackout roller blind, spring-loaded, modern minimalist window treatment"),
    tb("mod2-doorbell-intercom","智能門鈴對講機（白）","accessory",["modern"],
       ["video doorbell","smart home","white"],["white","glossy white"],
       3500,"Standard","white smart video doorbell with intercom, modern connected home"),
    tb("mod2-abstract-wall-art-lg","大幅抽象畫（黑白金）","accessory",["modern"],
       ["wall art","abstract","large canvas"],["black","white","gold leaf"],
       12000,"W100xH140","oversized abstract canvas print with black, white and gold leaf accents, modern wall art"),
    tb("mod2-entryway-bench-storage","玄關儲物長凳（含掛鉤）","storage",["modern"],
       ["entryway bench","shoe storage","hooks"],["white","natural oak seat"],
       9000,"W100xD35xH135","entryway bench with 3 hooks above and shoe storage below, modern hallway unit"),
    tb("mod2-linen-chair-nat","亞麻椅（自然色，木脚）","chair",["modern","nordic"],
       ["linen chair","natural","wood legs"],["natural linen","light ash legs"],
       8000,"W65xD72xH80","natural linen armchair with solid ash wood legs, modern-Nordic reading chair"),
    tb("mod2-round-dining-table-oak","圓形橡木餐桌","table",["modern","nordic"],
       ["round dining","oak","4-seater"],["natural oak"],
       22000,"Dia120xH75","solid oak round dining table, seats 4, contemporary clean design"),
    tb("mod2-bar-unit-walnut","胡桃木吧台區","storage",["modern"],
       ["bar unit","walnut","drinks cabinet"],["dark walnut","matte black"],
       28000,"W90xD45xH120","dark walnut bar drinks cabinet with stemware rack and LED interior, modern living room"),
    tb("mod2-nesting-side-tables","嵌套邊桌組（3件，玻璃）","table",["modern"],
       ["nesting tables","glass top","3-piece"],["tempered glass","brushed chrome"],
       9500,"Set of 3","set of 3 round tempered glass-top nesting side tables on chrome frames, modern"),
    tb("mod2-grey-wool-blanket","灰色羊毛毯（厚重）","textile",["modern"],
       ["wool blanket","grey","heavy weight"],["medium grey","charcoal"],
       4500,"130x180cm","heavyweight 100% merino wool throw blanket in grey, modern luxury comfort"),
    tb("mod2-pendant-3light-brushed","3頭刷金吊燈","lighting",["modern","luxury"],
       ["3-light pendant","brushed gold","modern"],["brushed gold","smoke glass"],
       9500,"W60xH25","3-shade brushed gold pendant light with smoked glass diffusers, modern dining or kitchen"),

    # ── NORDIC (40 items) ──────────────────────────────────────────────────
    tb("nord2-sheepskin-throw","羊毛皮毯（白色）","textile",["nordic"],
       ["sheepskin","white fur","cozy"],["pure white","ivory"],
       5500,"60x90cm","genuine sheepskin white throw blanket, draped on sofa or chair, Nordic cosy hygge"),
    tb("nord2-pine-bookcase","松木敞開式書架（5層）","storage",["nordic"],
       ["open bookcase","pine","5-shelf"],["natural pine","honey wood"],
       9500,"W80xD30xH180","natural pine 5-shelf open bookcase, simple sturdy design, Nordic living room display"),
    tb("nord2-boucle-sofa-natural","布克萊L型沙發（自然色）","sofa",["nordic"],
       ["boucle sectional","L-shape","natural"],["natural boucle","warm white"],
       58000,"W300xD160xH78","natural boucle fabric L-shaped sectional sofa, plush and warm, Nordic living room"),
    tb("nord2-pendant-wood-shade","木製燈罩吊燈","lighting",["nordic"],
       ["wood shade pendant","natural","warm glow"],["natural oak veneer"],
       5500,"Dia25","natural oak veneer drum-shade pendant lamp, warm diffuse glow, Nordic dining or kitchen"),
    tb("nord2-wax-candles","蜂蠟柱蠟燭（3支）","accessory",["nordic"],
       ["beeswax candles","pillar","natural"],["warm honey yellow","natural wax"],
       1200,"Set of 3 (H10/15/20)","set of 3 natural beeswax pillar candles, Nordic hygge dining or mantel"),
    tb("nord2-mushroom-lamp","蘑菇形陶瓷台燈（米白）","lighting",["nordic","muji"],
       ["mushroom lamp","ceramic","soft glow"],["matte cream","off-white"],
       4500,"H30","matte cream ceramic mushroom table lamp, soft warm glow, Nordic bedroom or side table"),
    tb("nord2-pegboard-white-oak","白橡洞洞板收納系統","storage",["nordic","muji"],
       ["pegboard","white oak","organiser"],["white oak","natural"],
       6000,"W60xH60","white oak pegboard wall organiser with accessories kit, Nordic functional home office"),
    tb("nord2-sofa-table-narrow","沙發背後細長桌（實木）","table",["nordic"],
       ["sofa table","narrow console","solid wood"],["natural ash","light wood"],
       8000,"W150xD25xH75","slim solid ash wood sofa console table, behind-sofa styling, Nordic living room"),
    tb("nord2-herb-garden-indoor","室內香草花園（木製托盤）","plant",["nordic"],
       ["herb garden","indoor","wooden tray"],["natural pine","green herbs"],
       3500,"W50xD20","small pine tray herb growing kit with 4 pots, Nordic kitchen windowsill"),
    tb("nord2-knit-pouf","手編針織蒲墩（米白）","chair",["nordic","boho"],
       ["knit pouf","chunky","footrest"],["cream white","ivory"],
       5000,"Dia55xH35","oversized chunky hand-knit cotton pouf, Nordic or boho living room footrest"),
    tb("nord2-art-botanical","北歐植物掛畫（4件組）","accessory",["nordic"],
       ["botanical art","4-piece","gallery"],["sage green","off-white","warm wood frame"],
       4500,"Set of 4, A4","set of 4 botanical art prints in warm wood frames, Nordic gallery wall collection"),
    tb("nord2-natural-linen-bed","水洗亞麻寢具（4件，海霧藍）","textile",["nordic"],
       ["linen bedding","sea mist blue","washed"],["dusty blue","sea mist"],
       6000,"Queen size","stonewashed linen 4-piece bedding set in sea mist blue, Nordic relaxed bedroom"),
    tb("nord2-stacking-stools","可堆疊圓凳（3件，松木）","chair",["nordic","muji"],
       ["stacking stools","round","pine"],["natural pine"],
       6000,"Set of 3, Dia35xH45","set of 3 natural pine stackable round stools, Nordic versatile extra seating"),
    tb("nord2-arch-floor-lamp-nat","弓形落地燈（自然木座）","lighting",["nordic"],
       ["arc floor lamp","wood base","linen shade"],["natural ash base","cream shade"],
       10000,"H175","arched natural ash wood base floor lamp with cream linen shade, Nordic warm reading light"),
    tb("nord2-recycled-glass-vase","再生玻璃花瓶（綠灰）","accessory",["nordic"],
       ["recycled glass","vase","sustainable"],["sea green","grey green"],
       1800,"H25","recycled glass vase in sea green, sustainable Nordic home decor with organic bubble texture"),
    tb("nord2-ladder-blanket-rack","梯形毛毯架（白橡）","storage",["nordic"],
       ["ladder blanket rack","white oak","lean"],["natural white oak"],
       4500,"W50xH120","leaning white oak ladder blanket display rack, Nordic bedroom or living room"),
    tb("nord2-wool-seat-cushion","羊毛坐墊（灰，4件）","textile",["nordic"],
       ["wool cushion","grey","dining chair pad"],["warm grey","heather"],
       4000,"Set of 4, 40x40cm","set of 4 grey wool dining chair seat cushions with ties, Nordic dining room"),
    tb("nord2-white-bedside-lamp","白瓷床頭燈（弧頸）","lighting",["nordic","muji"],
       ["bedside lamp","white ceramic","gooseneck"],["matte white","natural linen shade"],
       3500,"H35","white ceramic base flexible-neck bedside table lamp, Nordic minimal bedroom"),
    tb("nord2-oak-bench-storage","橡木儲物長凳","chair",["nordic"],
       ["bench with storage","oak","hallway"],["natural oak","white cushion"],
       12000,"W100xD35xH45","natural oak storage bench with lift-lid and upholstered seat, Nordic hallway or bedroom"),
    tb("nord2-shower-curtain-linen","亞麻浴簾（米色）","textile",["nordic"],
       ["shower curtain","linen","natural"],["natural linen","off-white"],
       2500,"W180xH200","natural linen shower curtain, rust-resistant brass grommets, Nordic bathroom"),
    tb("nord2-tea-light-holder-set","玻璃蠟燭座組（6件）","accessory",["nordic"],
       ["tealight holder","glass","set of 6"],["clear glass","frosted"],
       1200,"Set of 6","set of 6 clear glass tealight holders, simple Nordic hygge table setting"),
    tb("nord2-ceramic-vase-set","北歐陶瓷花瓶組（3件）","accessory",["nordic"],
       ["ceramic vase","set of 3","Nordic"],["matte white","dusty blue","sage green"],
       3500,"Set of 3 (H15/20/25)","set of 3 Nordic-style matte ceramic vases in white, dusty blue and sage green"),
    tb("nord2-fabric-bed-grey","布藝大床（淺灰，有頭板）","bed",["nordic"],
       ["upholstered bed","light grey","headboard"],["light grey","warm grey"],
       32000,"W153xD213 (queen)","light grey fabric-upholstered queen bed with channel-tufted headboard, Nordic cozy"),
    tb("nord2-outdoor-cushion-grey","戶外座墊（北歐灰，4件）","textile",["nordic"],
       ["outdoor cushion","grey","Nordic"],["light grey","warm grey"],
       4000,"Set of 4, 45x45cm","set of 4 light grey outdoor cushions, UV and water resistant, Nordic terrace"),
    tb("nord2-hanging-basket-wall","牆掛式植物吊籃（3個）","plant",["nordic","boho"],
       ["wall planter","hanging basket","cotton rope"],["natural cotton rope","white"],
       2500,"Set of 3","set of 3 cotton rope wall-hanging plant baskets, Nordic or boho indoor garden"),
    tb("nord2-abstract-landscape","北歐風景抽象畫","accessory",["nordic"],
       ["abstract art","landscape","Nordic print"],["dusty blue","cream","grey"],
       5500,"W80xH60","framed Nordic abstract landscape art print in dusty blue and cream, living room wall art"),
    tb("nord2-bar-stool-natural","白橡木吧台椅","chair",["nordic"],
       ["bar stool","white oak","counter"],["natural white oak"],
       8000,"W40xD40xH75","solid white oak counter-height bar stool, minimal rounded seat, Nordic kitchen"),
    tb("nord2-linen-napkin-set","亞麻餐巾（6件，石灰綠）","textile",["nordic"],
       ["linen napkins","sage green","set of 6"],["sage green","natural linen"],
       1500,"Set of 6, 45x45cm","set of 6 sage green washed linen dinner napkins, Nordic table setting"),
    tb("nord2-soap-stone-dish","皂石肥皂碟","accessory",["nordic","muji"],
       ["soapstone dish","natural stone","soap holder"],["grey soapstone"],
       800,"W12xD8","hand-carved grey soapstone soap dish, minimal Nordic bathroom accessory"),
    tb("nord2-wall-lantern-indoor","室內壁掛燈籠（黑色）","lighting",["nordic"],
       ["indoor wall lantern","black metal","candle"],["matte black","clear glass"],
       3500,"H30","matte black indoor wall-mounted lantern, glass panels, Nordic cosy corridor light"),
    tb("nord2-pine-dining-bench2","松木餐椅長凳（木紋清晰）","chair",["nordic"],
       ["dining bench","pine","natural"],["natural pine","honey tone"],
       6500,"W140xD35xH45","natural pine dining bench with visible wood grain, sturdy legs, Nordic farmhouse"),
    tb("nord2-felt-basket-set","羊毛氈收納籃（3件套，灰）","storage",["nordic","muji"],
       ["felt basket","grey","set of 3"],["warm grey felt"],
       2500,"Set of 3","set of 3 grey wool felt storage baskets with rolled edges, Nordic minimalist organiser"),
    tb("nord2-wooden-candle-stand","木質蠟燭座（高低各一）","accessory",["nordic"],
       ["candle stand","wood","pillar holder"],["natural ash","light wood"],
       1800,"Set of 2 (H10+H20)","pair of solid ash wood pillar candle stands in two heights, Nordic mantel display"),
    tb("nord2-mirror-three-panel","三折木框鏡（白橡）","mirror",["nordic"],
       ["tri-fold mirror","white oak","vanity"],["white oak","natural"],
       8000,"W90xH60 (open)","tri-fold white oak vanity mirror, freestanding or wall-mount, Nordic dressing table"),
    tb("nord2-sheepskin-rug-small","小羊皮地墊（天然）","rug",["nordic"],
       ["sheepskin rug","natural","small"],["natural ivory","cream"],
       4500,"60x90cm (approx)","genuine natural sheepskin small area rug, Nordic bedside or chair accent"),
    tb("nord2-bed-canopy-sheer","單人床透明紗幔","textile",["nordic","boho"],
       ["bed canopy","sheer","fairy"],["white sheer","gauze"],
       2500,"200x400cm of fabric","white sheer gauze bed canopy drape, single bed fairy-tale Nordic children's room"),
    tb("nord2-clock-minimalist","極簡木圓掛鐘（無刻度）","accessory",["nordic","muji"],
       ["minimal clock","no numbers","wood"],["natural wood","black hands"],
       2000,"Dia30","natural wood wall clock with no numerals, black hands only, Nordic minimalist"),
    tb("nord2-footstool-boucle","布克萊圓形腳凳","chair",["nordic"],
       ["footstool","boucle","round"],["warm cream boucle"],
       5000,"Dia45xH35","warm cream boucle round footstool, solid wood legs, Nordic living room comfort"),
    tb("nord2-linen-apron","棉麻廚師圍裙（自然色）","accessory",["nordic","muji"],
       ["linen apron","natural","kitchen"],["natural linen"],
       900,"One size","natural linen and cotton cross-back kitchen apron, Nordic functional home"),
    tb("nord2-wood-pepper-grinder","實木胡椒研磨器","accessory",["nordic","muji"],
       ["pepper grinder","wood","kitchen"],["natural beech","chrome top"],
       1200,"H22","solid beech wood manual pepper grinder, Nordic kitchen essentials"),
    tb("nord2-photo-clip-string","原木照片夾燈串","lighting",["nordic"],
       ["string lights","photo clip","fairy"],["warm white LED","natural wood clips"],
       1500,"300cm","3m warm-white LED string lights with 15 natural wood photo clips, Nordic bedroom display"),

    # ── JAPANESE (30 items) ────────────────────────────────────────────────
    tb("jap2-paper-sliding-wall","和紙折疊牆","accessory",["japanese"],
       ["paper folding wall","accordion","room divider"],["natural washi","cream"],
       12000,"W200xH210","pleated washi paper accordion-fold room divider, Japanese modern interior partition"),
    tb("jap2-cedar-shelf","杉木多功能置物架（3層）","storage",["japanese"],
       ["cedar shelf","natural","3-tier"],["natural cedar","pale wood"],
       7500,"W80xD25xH90","natural cedar 3-tier display shelf, aromatic wood, Japanese minimalist home"),
    tb("jap2-indigo-throw","藍染紋樣棉被（雙人）","textile",["japanese"],
       ["indigo cotton quilt","Japanese pattern","double"],["indigo navy","cream"],
       9000,"Queen size","double-size indigo-dyed Japanese cotton quilt with shibori pattern, wabi bedroom"),
    tb("jap2-bamboo-bath-tray","竹製浴缸置物架","accessory",["japanese"],
       ["bath tray","bamboo","expandable"],["natural bamboo"],
       2500,"Adjustable W65-90","expandable bamboo bathtub caddy tray, Japanese onsen-inspired bathroom styling"),
    tb("jap2-washi-tape-set","和紙膠帶裝飾組（10色）","accessory",["japanese"],
       ["washi tape","decorative","Japanese craft"],["multicolour Japanese patterns"],
       800,"Set of 10","set of 10 Japanese washi tape rolls in traditional patterns, craft and home decor"),
    tb("jap2-raku-bowl","樂燒陶碗（黑）","accessory",["japanese"],
       ["raku bowl","black glaze","tea bowl"],["black raku glaze"],
       3500,"Dia12","hand-formed black raku-fired tea bowl, wabi-sabi Japanese tea ceremony artefact"),
    tb("jap2-bamboo-room-divider","竹節屏風（6扇，180cm高）","accessory",["japanese"],
       ["bamboo divider","6-panel","natural"],["natural bamboo","dark lacquer frame"],
       18000,"W30 per panel x6, H180","6-panel natural bamboo folding room divider with lacquered wood frame, Japanese"),
    tb("jap2-zen-fountain","室內禪意水景","accessory",["japanese"],
       ["indoor fountain","zen","water feature"],["grey slate","bamboo spout"],
       8500,"W40xD30xH50","grey slate indoor tabletop zen water fountain with bamboo spout, Japanese meditation"),
    tb("jap2-wooden-sake-set","木漆器清酒套組","accessory",["japanese"],
       ["sake set","lacquerware","Japan"],["natural wood","red lacquer"],
       4500,"Set (1 carafe + 4 cups)","natural wood lacquered sake serving set (tokkuri + 4 ochoko cups), Japanese dining"),
    tb("jap2-cotton-futon-quilt","純棉被（日式傳統）","textile",["japanese"],
       ["futon quilt","Japanese cotton","traditional"],["white cotton","natural"],
       6500,"Queen size","traditional Japanese-style 100% cotton kake-buton quilt, foldable, minimalist bedroom"),
    tb("jap2-wooden-door-knob","和風木製門把（一對）","accessory",["japanese"],
       ["wooden door knob","pair","Japanese"],["natural walnut","dark wood"],
       1200,"Pair","solid walnut round wooden door knobs pair, Japanese interior hardware"),
    tb("jap2-bamboo-laundry-basket","竹製洗衣籃（帶蓋）","storage",["japanese"],
       ["bamboo laundry","lidded basket","natural"],["natural bamboo"],
       5000,"W45xD35xH60","lidded natural bamboo woven laundry basket, Japanese bathroom organisation"),
    tb("jap2-low-dining-table","日式低矮餐桌（黑胡桃）","table",["japanese"],
       ["low table","zazen dining","walnut"],["dark walnut","black lacquer"],
       22000,"W120xD80xH35","dark walnut low Japanese dining table for floor seating, zazen or traditional"),
    tb("jap2-paper-lantern-floor","和紙地板燈（方形）","lighting",["japanese"],
       ["paper lantern","square","floor"],["white washi","natural frame"],
       4500,"W30xD30xH60","square washi-paper floor lantern with bamboo frame, Japanese atmospheric room light"),
    tb("jap2-cedar-bath-stool","扁柏浴室凳（4腿）","chair",["japanese"],
       ["cedar stool","bathroom","hinoki"],["natural hinoki cedar"],
       7500,"W35xD25xH35","4-leg natural hinoki cedar bath stool, aromatic Japanese bathroom or sauna"),
    tb("jap2-ikebana-vase","生花花道花器（瘦高）","plant",["japanese"],
       ["ikebana vase","flower arrangement","ceramics"],["matte grey","earth tone"],
       3500,"H40","tall slim matte grey ceramic ikebana flower arrangement vase, Japanese minimalist"),
    tb("jap2-traditional-screen","伝統折蒔絵屏風（2扇）","accessory",["japanese"],
       ["byobu","maki-e","folding screen"],["gold leaf","black lacquer","maki-e motif"],
       45000,"W60 each x2, H150","2-panel traditional maki-e lacquered byobu folding screen with gold leaf motifs"),
    tb("jap2-clay-water-kettle","土器急須（大）","accessory",["japanese"],
       ["clay teapot","kyusu","Japanese tea"],["dark clay","earth brown"],
       4000,"600ml","large dark clay kyusu Japanese teapot with stainless strainer, minimalist Japanese tea"),
    tb("jap2-coir-tatami-edge","棕絲榻榻米邊框墊","rug",["japanese"],
       ["tatami edge","coir mat","floor"],["natural coir","dark binding"],
       5000,"90x90cm","natural coir rush-grass floor mat with traditional tatami dark binding edge, Japanese room"),
    tb("jap2-cedar-soap-dish","扁柏皂盤","accessory",["japanese"],
       ["hinoki dish","soap holder","cedar"],["pale cedar wood"],
       900,"W12xD8","natural hinoki cedar soap dish, aromatic Japanese bathroom accessory"),
    tb("jap2-wood-chopstick-rest","陶製筷架（6件組）","accessory",["japanese"],
       ["chopstick rest","ceramic","Japanese dining"],["white","celadon green"],
       800,"Set of 6","set of 6 celadon green ceramic chopstick rests, Japanese table setting"),
    tb("jap2-indigo-noren-linen","靛藍亞麻暖簾（大型）","textile",["japanese"],
       ["noren curtain","large","indigo linen"],["indigo blue","natural linen"],
       3500,"W90xH180","large indigo-dyed linen noren doorway curtain, Japanese café or home kitchen"),
    tb("jap2-round-basket-japanese","圓形藺草收納盒","storage",["japanese"],
       ["round basket","rush grass","Japanese"],["natural rush","dark handle"],
       1800,"Dia30xH20","round woven rush-grass lidded storage basket, Japanese household organiser"),
    tb("jap2-wood-slab-shelf","單板原木掛板（胡桃）","storage",["japanese"],
       ["wood slab shelf","live edge","walnut","single"],["dark walnut","live edge"],
       5500,"W60xD18","single live-edge walnut wood floating wall shelf, Japanese organic display"),
    tb("jap2-paper-window-film","和紙窗貼膜（霧面竹紋）","textile",["japanese"],
       ["window film","washi","bamboo pattern"],["frosted white","bamboo motif"],
       1500,"W90xH200 per roll","frosted bamboo-pattern adhesive washi window film, Japanese interior privacy"),
    tb("jap2-wood-tray-handle","桐木把手托盤","accessory",["japanese","muji"],
       ["wooden tray","handles","paulownia"],["natural paulownia","light cream"],
       2500,"W45xD30","lightweight paulownia wood serving tray with integrated handles, Japanese minimalist"),
    tb("jap2-stone-garden-tray","石庭禪意擺飾盤","accessory",["japanese"],
       ["zen garden tray","stone","sand"],["grey stone","white sand","dark pebbles"],
       3000,"W40xD30","stone and sand zen garden tray with miniature rake and pebbles, Japanese wabi-sabi"),
    tb("jap2-bamboo-ladder","竹製踏梯（4格）","storage",["japanese"],
       ["bamboo ladder","step","display"],["natural bamboo","dark joint"],
       6000,"W40xH120","4-step natural bamboo display ladder, Japanese shop or home styling rack"),
    tb("jap2-silk-pillow-embroidery","刺繡絲綢抱枕（梅花）","textile",["japanese"],
       ["silk cushion","embroidered","plum blossom"],["ivory silk","pink embroidery"],
       3500,"45x45cm","ivory silk cushion with hand-embroidered pink plum blossom motif, Japanese bedroom"),
    tb("jap2-wooden-jewelry-box","桐木飾品盒（帶鏡）","storage",["japanese"],
       ["jewelry box","paulownia","mirror"],["natural paulownia"],
       5500,"W25xD20xH15","natural paulownia wood jewellery box with velvet lining and interior mirror, Japanese"),

    # ── MUJI (30 items) ────────────────────────────────────────────────────
    tb("muji2-white-ceramic-pot","白色陶瓷餐具組（12件）","accessory",["muji"],
       ["ceramic tableware","white","12-piece"],["matte white"],
       6000,"Set of 12","12-piece matte white ceramic tableware set, clean MUJI-style dining table"),
    tb("muji2-glass-food-containers","玻璃儲物罐（套裝5件）","storage",["muji"],
       ["glass containers","food storage","5-piece"],["clear glass","bamboo lid"],
       2500,"Set of 5 (200-1000ml)","5-piece clear glass food storage jars with bamboo lids, MUJI kitchen pantry"),
    tb("muji2-cotton-storage-bag","棉質儲物袋（5入）","storage",["muji"],
       ["cotton bag","storage","natural"],["natural cotton","beige"],
       800,"Set of 5","natural cotton drawstring storage bags, MUJI wardrobe or travel organisation"),
    tb("muji2-bamboo-toothbrush","竹柄牙刷（4入）","accessory",["muji"],
       ["bamboo toothbrush","eco","4-pack"],["natural bamboo","black bristle"],
       600,"Set of 4","bamboo handle soft-bristle toothbrush set of 4, MUJI eco-friendly bathroom"),
    tb("muji2-recycled-notebook","再生紙記事本（3本）","accessory",["muji"],
       ["recycled notebook","A5","3-pack"],["recycled brown kraft"],
       500,"A5 x3","3-pack A5 recycled kraft paper notebooks, MUJI sustainable stationery"),
    tb("muji2-linen-table-runner","棉麻桌旗（米色）","textile",["muji"],
       ["table runner","linen","beige"],["natural beige linen"],
       800,"W30xL150","natural linen table runner in beige, simple MUJI dining table styling"),
    tb("muji2-clear-shelf-dividers","透明壓克力層架分隔板（6入）","storage",["muji"],
       ["shelf dividers","acrylic","clear"],["clear acrylic"],
       600,"Set of 6","clear acrylic shelf dividers for organised MUJI-style wardrobe or bookcase"),
    tb("muji2-wood-bed-tray","木製床上小托盤","accessory",["muji"],
       ["bed tray","wood","small"],["natural beech"],
       1200,"W30xD22","small solid beech wood bed tray for breakfast or laptop, MUJI minimalist"),
    tb("muji2-rubber-wood-stool","橡木方凳（可疊）","chair",["muji"],
       ["square stool","rubber wood","stackable"],["natural rubber wood"],
       2200,"W38xD38xH45","solid rubber wood stackable square stool, MUJI versatile seating or side table"),
    tb("muji2-led-night-light","感應LED小夜燈","lighting",["muji"],
       ["night light","motion sensor","LED"],["white","soft glow"],
       600,"H10","white motion-sensor LED plug-in night light, MUJI quiet bedroom or corridor"),
    tb("muji2-steel-pen-holder","不鏽鋼筆筒","accessory",["muji"],
       ["pen holder","stainless","desk"],["brushed stainless"],
       600,"Dia8xH10","brushed stainless steel cylindrical pen and pencil holder, MUJI desk organisation"),
    tb("muji2-wall-mount-hook-5","白色壁掛5鉤衣鉤板","accessory",["muji"],
       ["wall hooks","white","5 hooks"],["white"],
       800,"W60","white painted 5-peg wall-mounted hook board, MUJI entryway or bedroom"),
    tb("muji2-cotton-eye-mask","純棉眼罩（2入）","textile",["muji"],
       ["eye mask","cotton","sleep"],["white cotton","grey"],
       500,"Set of 2","soft white cotton sleep eye mask set of 2, MUJI restful sleep essential"),
    tb("muji2-clear-makeup-organiser","透明收納盒組（化妝桌）","storage",["muji"],
       ["makeup organiser","clear","stackable"],["clear transparent"],
       1800,"Set 6 pieces","6-piece clear acrylic makeup and vanity organiser set, MUJI dressing table"),
    tb("muji2-natural-loofah","天然絲瓜絡沐浴球","accessory",["muji"],
       ["loofah","natural","bath"],["natural cream loofah"],
       400,"Standard","natural dried loofah bath sponge, MUJI eco bathroom accessory"),
    tb("muji2-linen-storage-cube","棉麻收納方格盒（2件）","storage",["muji"],
       ["storage cube","linen","fabric box"],["natural linen","beige"],
       1200,"Set of 2, W30xD30xH30","set of 2 natural linen collapsible storage cube boxes, MUJI shelving insert"),
    tb("muji2-slim-white-wardrobe","超薄白色衣櫃（2門）","storage",["muji"],
       ["slim wardrobe","white","2-door"],["white"],
       18000,"W80xD45xH180","slim 2-door white painted wardrobe, clean lines, MUJI minimalist bedroom"),
    tb("muji2-cast-iron-pot-round","圓形鑄鐵鍋（24cm）","accessory",["muji"],
       ["cast iron pot","24cm","Dutch oven"],["matte black","enameled"],
       5500,"24cm","matte black enameled cast iron round Dutch oven, MUJI-style kitchen cookware"),
    tb("muji2-drawer-dividers","抽屜分格板（可調，3件）","storage",["muji"],
       ["drawer dividers","adjustable","organiser"],["white","cream"],
       600,"Set of 3, adjustable","set of 3 adjustable white drawer dividers, MUJI bedroom or kitchen organisation"),
    tb("muji2-white-hangers-20pack","白色植絨衣架（20入）","accessory",["muji"],
       ["velvet hangers","white","20-pack"],["white velvet"],
       1000,"Set of 20","white velvet non-slip clothes hangers set of 20, MUJI slim wardrobe essentials"),
    tb("muji2-wooden-toilet-brush","木柄馬桶刷（天然毛）","accessory",["muji"],
       ["toilet brush","wood handle","natural fiber"],["natural wood handle","white fibre"],
       1200,"H40","natural wood handle toilet brush with plant-fibre bristles and ceramic holder, MUJI bathroom"),
    tb("muji2-linen-window-shade","棉麻拉捲窗簾（米）","textile",["muji"],
       ["roller shade","linen","semi-sheer"],["natural linen","beige"],
       3500,"W90xH180","semi-sheer natural linen roller blind, spring mechanism, MUJI minimal window treatment"),
    tb("muji2-white-plant-trough","白色長型植栽槽","plant",["muji"],
       ["planter trough","white ceramic","rectangular"],["matte white"],
       2000,"W40xD10xH12","matte white rectangular ceramic planter trough for herbs or succulents, MUJI kitchen"),
    tb("muji2-cork-bath-mat","軟木浴室地墊","textile",["muji","nordic"],
       ["cork bath mat","natural","anti-slip"],["natural cork brown"],
       1200,"60x40cm","natural cork anti-slip bath mat, water-resistant, MUJI eco-friendly bathroom"),
    tb("muji2-simple-dish-rack","極簡不鏽鋼碗碟架","storage",["muji"],
       ["dish rack","stainless","minimalist"],["brushed stainless"],
       1800,"W35xD25xH20","compact brushed stainless steel dish-drying rack, MUJI clean kitchen counter"),
    tb("muji2-wax-tablet-candle","長型香氛平板蠟燭","accessory",["muji"],
       ["tablet candle","scented","flat"],["off-white","cream wax"],
       1200,"W15xH3","flat slab soy wax scented candle in off-white, MUJI minimalist table or shelf decor"),
    tb("muji2-oak-desk-organiser","橡木桌面收納組（5件）","storage",["muji"],
       ["desk organiser","oak","5-piece"],["natural oak"],
       3500,"Set of 5","5-piece natural oak desk organiser set (tray, pen stand, phone holder, note clip, small bin), MUJI"),
    tb("muji2-shower-shelf-stainless","不鏽鋼浴室角架","storage",["muji"],
       ["shower shelf","stainless","corner"],["brushed stainless"],
       1500,"W25xD25xH10","brushed stainless steel corner shower shelf, no-drill adhesive mount, MUJI bathroom"),
    tb("muji2-linen-bread-bag","棉麻麵包收納袋","accessory",["muji"],
       ["bread bag","linen","drawstring"],["natural linen"],
       500,"W25xH35","natural linen drawstring bread and food storage bag, MUJI sustainable kitchen"),
    tb("muji2-pine-towel-rack","松木毛巾架（壁掛）","storage",["muji","nordic"],
       ["towel rack","pine","wall mount"],["natural pine"],
       1800,"W60xH15","wall-mounted natural pine 3-bar towel rack, MUJI or Nordic bathroom"),
]

def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    print(f"Current: {len(existing)}")
    existing_names = {item["name_zh"] for item in existing}
    new_items = [item for item in BATCH4 if item["name_zh"] not in existing_names]
    print(f"Adding: {len(new_items)}")
    merged = existing + new_items
    print(f"Total: {len(merged)}")
    style_count = {}
    for item in merged:
        s = item.get("style_tags", ["unknown"])[0]
        style_count[s] = style_count.get(s, 0) + 1
    for s, c in sorted(style_count.items()):
        print(f"  {s:15s}: {c}")
    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print("Done.")

if __name__ == "__main__":
    main()
