"""
Catalog Batch 5 — ~400 more items to reach 1350+
"""
import json, os

CATALOG_PATH = os.path.join(os.path.dirname(__file__), "furniture_catalog.json")

def tb(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "Taobao", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.taobao.com/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

def ik(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "IKEA", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.ikea.com/tw/zh/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

BATCH5 = [
    # ── LUXURY (45 items) ──────────────────────────────────────────────────
    tb("lux2-ivory-sofa-chaise","象牙白貴妃躺沙發（金腳）","sofa",["luxury"],
       ["chaise sofa","ivory","gold legs"],["ivory velvet","brushed gold"],
       65000,"W270xD95xH82","ivory velvet right-hand chaise sectional sofa on brushed gold legs, luxury Hollywood"),
    tb("lux2-geometric-ceiling","幾何金屬天花燈（9頭）","lighting",["luxury","art-deco"],
       ["ceiling light","geometric","9-arm"],["gold","smoky glass"],
       28000,"Dia70xH45","9-arm brushed gold geometric ceiling light with smoky glass globes, luxury statement"),
    tb("lux2-marble-shelf-floating","大理石浮板層架（3片）","storage",["luxury"],
       ["marble shelf","floating","set of 3"],["white marble","gold bracket"],
       18000,"Set of 3 (60/80/100cm)","white marble floating shelves on gold wall brackets, luxury bathroom or living room"),
    tb("lux2-vanity-illuminated","好萊塢燈泡梳妝鏡","mirror",["luxury"],
       ["Hollywood mirror","vanity","bulb"],["gold","warm bulb"],
       18000,"W80xH100","Hollywood-style vanity mirror with warm LED bulbs around frame, luxury dressing room"),
    tb("lux2-tufted-bed-tall","超高床頭板鈕扣床（雙人）","bed",["luxury"],
       ["tall headboard","button tufted","queen"],["champagne velvet","silver stud"],
       55000,"W153xD213xH180 (queen)","queen platform bed with towering button-tufted champagne velvet headboard, luxury"),
    tb("lux2-onyx-desk-lamp","黑玉石台燈","lighting",["luxury"],
       ["onyx lamp","stone base","luxury desk"],["black onyx","gold shade"],
       15000,"H45","genuine black onyx stone base table lamp with gold metal conical shade, luxury desk"),
    tb("lux2-floating-fireplace","懸掛式生物乙醇壁爐","accessory",["luxury"],
       ["wall fireplace","bioethanol","modern"],["matte black","clear fire"],
       35000,"W100xH50","wall-mounted bioethanol fireplace with tempered glass front, luxury modern interior"),
    tb("lux2-marble-waterfall-coffee","瀑布式大理石茶几","table",["luxury"],
       ["waterfall coffee table","marble","monolithic"],["Carrara white marble"],
       45000,"W120xD60xH42","full Carrara marble waterfall coffee table, monolithic slab construction, luxury living"),
    tb("lux2-gold-leaf-console","金箔嵌面玄關桌","table",["luxury","art-deco"],
       ["gold leaf console","luxury","foyer"],["antique gold leaf","mirrored glass top"],
       35000,"W130xD40xH85","gold-leaf applied console table with mirrored glass top, luxury foyer statement"),
    tb("lux2-velvet-opera-chair","天鵝絨歌劇院單椅","chair",["luxury","art-deco"],
       ["opera chair","wing back","velvet"],["royal purple velvet","gold"],
       22000,"W80xD78xH100","royal purple velvet wing-back opera chair with carved gold legs, luxury drama"),
    tb("lux2-crystal-floor-lamp","水晶落地燈","lighting",["luxury"],
       ["crystal floor lamp","gold","luxury"],["K9 crystal","brushed gold"],
       28000,"H170","K9 crystal multi-tier floor lamp with brushed gold frame, luxury living or bedroom"),
    tb("lux2-plinth-display","白色展示台（方柱）","accessory",["luxury","modern"],
       ["plinth","display pedestal","marble look"],["matte white marble-effect"],
       8000,"W30xD30xH90","white marble-effect square display plinth pedestal, luxury gallery or sculpture stand"),
    tb("lux2-champagne-bedding","香檳色緞面床品（6件）","textile",["luxury"],
       ["sateen bedding","champagne","6-piece"],["champagne gold","warm ivory"],
       18000,"King size 6-piece","6-piece champagne gold jacquard sateen bedding set, luxury master bedroom"),
    tb("lux2-jade-sculpture","玉石擺件（抽象）","accessory",["luxury"],
       ["jade sculpture","green stone","art"],["nephrite green","marble white"],
       22000,"H25","natural nephrite jade abstract carved sculpture, luxury shelf or coffee table display"),
    tb("lux2-brass-bookend-lion","黃銅獅頭書擋","accessory",["luxury"],
       ["lion bookend","brass","heavy"],["polished brass"],
       5500,"Pair, H15","pair of polished brass lion-head bookends, heavy solid cast, luxury study"),
    tb("lux2-cashmere-blanket","純喀什米爾毯（駱駝色）","textile",["luxury"],
       ["cashmere blanket","camel","luxury"],["camel tan","warm beige"],
       22000,"130x160cm","100% grade-A cashmere throw blanket in camel, ultra-soft, luxury bedroom or sofa"),
    tb("lux2-gold-towel-hoop","黃銅圓環毛巾架","accessory",["luxury"],
       ["towel ring","brass hoop","bathroom"],["polished brass"],
       2500,"Dia20","solid polished brass round towel ring wall mount, luxury bathroom hardware"),
    tb("lux2-velvet-dining-bench-lux","天鵝絨餐廳長凳（錦緞圖案）","chair",["luxury"],
       ["dining bench","brocade velvet","pattern"],["brocade gold pattern","navy"],
       16000,"W140xD40xH48","gold brocade-pattern velvet dining bench, luxury dining room seating"),
    tb("lux2-champagne-candles","香檳香氛蠟燭（3件套）","accessory",["luxury"],
       ["luxury candle","champagne scent","boxed"],["champagne wax","gold label"],
       5500,"Set of 3, 250g each","set of 3 luxury champagne-scented soy wax candles in gold-rimmed glass, gift box"),
    tb("lux2-marble-wine-cooler","大理石冰酒桶","accessory",["luxury"],
       ["wine cooler","marble","champagne bucket"],["white marble","gold band"],
       8500,"Dia22xH28","solid white marble champagne and wine cooler bucket with gold rim, luxury dining"),
    tb("lux2-gallery-light","畫廊射燈（可調角度，4頭）","lighting",["luxury"],
       ["gallery spot light","adjustable","art light"],["brushed gold","white"],
       9500,"90cm track, 4 heads","brushed gold adjustable gallery track spotlights, luxury art display lighting"),
    tb("lux2-chesterfield-sofa","棕色柴斯特菲爾德沙發","sofa",["luxury"],
       ["Chesterfield","brown leather","tufted"],["cognac brown leather","dark wood"],
       88000,"W220xD90xH82","deep button-tufted cognac brown genuine leather Chesterfield sofa, luxury classic"),
    tb("lux2-baroque-chandelier","巴洛克式枝形吊燈（18頭）","lighting",["luxury","art-deco"],
       ["baroque chandelier","18-arm","crystal"],["gold","crystal"],
       85000,"Dia120xH100","18-arm baroque-style crystal chandelier, antique gold finish, luxury dining room"),
    tb("lux2-onyx-bathroom","黑瑪瑙浴室台面板","accessory",["luxury"],
       ["onyx vanity top","stone slab","luxury"],["translucent honey onyx"],
       55000,"Custom to order","custom backlit honey onyx stone vanity countertop, luxury en-suite centrepiece"),
    tb("lux2-lacquer-wardrobe","法式光澤亮白衣櫃（4門）","storage",["luxury"],
       ["wardrobe","white lacquer","4-door"],["gloss white lacquer","gold handles"],
       65000,"W200xD60xH220","4-door floor-to-ceiling gloss white lacquer French wardrobe with gold bar handles"),
    tb("lux2-fur-bench","人造皮草床尾凳","chair",["luxury"],
       ["fur bench","fluffy","bedroom"],["ivory faux fur","brushed silver legs"],
       12000,"W120xD40xH48","ivory faux fur upholstered bedroom bench on brushed silver legs, luxury glam"),
    tb("lux2-gold-mirror-hall","金色全身玄關鏡","mirror",["luxury"],
       ["full-length mirror","gold frame","hall"],["ornate gold","antique gold"],
       18000,"W60xH180","ornate antique-gold carved frame full-length hall mirror, luxury entryway"),
    tb("lux2-velvet-curtain-gold","金色天鵝絨窗簾（一對）","textile",["luxury"],
       ["gold velvet curtain","pair","luxury"],["deep gold","champagne"],
       18000,"W140xH280 per panel (pair)","deep gold velvet blackout curtain pair with gold rod and finials, luxury bedroom"),
    tb("lux2-marble-arch-shelf","大理石拱形書架","storage",["luxury"],
       ["arch bookcase","marble","white"],["white marble-effect","brass trim"],
       35000,"W100xD35xH180","white marble-effect arch-top bookcase with brass inner trim, luxury living room"),
    tb("lux2-cashmere-rug","喀什米爾羊毛地毯（手工）","rug",["luxury"],
       ["cashmere wool rug","hand-knotted","ivory"],["ivory","cream","sage"],
       85000,"200x300cm","hand-knotted cashmere wool area rug in ivory and sage, ultra-soft, luxury bedroom"),
    tb("lux2-crystal-perfume-tray","水晶香水托盤","accessory",["luxury"],
       ["perfume tray","crystal","vanity"],["clear crystal","gold trim"],
       6500,"W35xD25","clear crystal cut-glass vanity tray for perfume bottles, luxury dressing table"),
    tb("lux2-night-light-gold-cage","黃銅鳥籠夜燈","lighting",["luxury"],
       ["birdcage lamp","brass","bedside"],["brass cage","warm amber bulb"],
       5500,"H40","decorative brass birdcage table lamp with warm amber filament bulb, luxury bedside"),
    tb("lux2-marble-umbrella-stand","大理石雨傘架","accessory",["luxury"],
       ["umbrella stand","marble","hallway"],["white marble","gold rim"],
       8500,"Dia25xH65","cylindrical white marble umbrella stand with gold rim, luxury entryway"),
    tb("lux2-antique-brass-faucet","古典黃銅浴室龍頭組","accessory",["luxury"],
       ["faucet","antique brass","basin tap"],["antique brass","polished"],
       9500,"Standard","antique polished brass basin faucet set, classic luxury bathroom fitting"),
    tb("lux2-silk-wallpaper","絲絨浮雕壁紙（每卷）","accessory",["luxury"],
       ["silk wallpaper","damask","embossed"],["champagne gold","cream"],
       5500,"W53cmxL10m per roll","champagne gold silk-look embossed damask wallpaper, luxury bedroom feature wall"),
    tb("lux2-gold-letter-opener","黃銅鑲玉信刀","accessory",["luxury"],
       ["letter opener","brass jade","desk"],["polished brass","green jade"],
       3500,"L25","solid brass letter opener with jade handle inlay, luxury study desk accessory"),
    tb("lux2-marble-fireplace-insert","大理石假壁爐嵌件","accessory",["luxury"],
       ["fireplace insert","electric","marble surround"],["white marble","flame effect"],
       22000,"W90xH70","white marble surround electric fireplace insert with LED flame effect, luxury living"),
    tb("lux2-pedestal-bowl-brass","黃銅底座玻璃碗（桌面擺件）","accessory",["luxury"],
       ["brass pedestal bowl","glass","decorative"],["polished brass","clear glass"],
       4500,"Dia30xH20","polished brass pedestal with handblown clear glass bowl, luxury coffee table object"),
    tb("lux2-crystal-knob-set","水晶門把手組（10件）","accessory",["luxury"],
       ["crystal door knob","10-piece","hardware"],["clear crystal","gold base"],
       12000,"Set of 10","clear crystal ball door knobs on gold base set of 10, luxury residential hardware"),
    tb("lux2-plush-duvet","1000支埃及棉被（加大）","textile",["luxury"],
       ["Egyptian cotton duvet","1000TC","king"],["pure white","ivory"],
       22000,"King size","1000 thread-count Egyptian long-staple cotton duvet cover, ultra-fine luxury bedding"),
    tb("lux2-golden-deer-sculpture","金色鹿雕塑（桌上型）","accessory",["luxury"],
       ["deer sculpture","gold","decorative"],["polished gold","antique gold"],
       5500,"H35","polished gold-finish resin deer sculpture, luxury shelf or side table statement piece"),
    tb("lux2-velvet-breakfast-tray","天鵝絨床上早餐托盤","accessory",["luxury"],
       ["breakfast tray","velvet lined","luxury"],["ivory velvet lining","gold frame"],
       4500,"W60xD35","gold-frame breakfast serving tray with ivory velvet liner, luxury hotel bedroom styling"),
    tb("lux2-canopy-round","圓形帷幔天篷（金線）","textile",["luxury"],
       ["round canopy","bed crown","gold thread"],["sheer ivory","gold embroidery"],
       8500,"Dia150","round ceiling-mounted bed crown canopy in ivory sheer with gold thread embroidery, luxury"),
    tb("lux2-marble-bath-mat","大理石浴室腳踏石","accessory",["luxury"],
       ["marble bath mat","stone","bathroom"],["white marble","warm grey veins"],
       12000,"60x40cm","solid white marble slab bathroom floor mat, polished surface, luxury en-suite"),
    tb("lux2-art-print-gold-abstract","金箔抽象畫（180cm高）","accessory",["luxury"],
       ["gold abstract art","tall canvas","oversized"],["gold leaf","black","white"],
       22000,"W90xH180","tall oversized gold-leaf and black abstract canvas art, luxury living room statement"),

    # ── ART-DECO (40 items) ────────────────────────────────────────────────
    tb("ad2-palm-leaf-wallpaper","棕櫚葉金色壁紙（每卷）","accessory",["art-deco"],
       ["palm leaf wallpaper","gold","botanical"],["gold","black","jungle green"],
       4500,"W53cmxL10m","gold palm leaf on black background wallpaper, art deco botanical feature wall"),
    tb("ad2-stepped-bookcase","階梯形書架（黑金）","storage",["art-deco"],
       ["stepped bookcase","asymmetric","black gold"],["matte black","gold shelf edge"],
       22000,"W100xH180","stepped asymmetric open bookcase in matte black with gold shelf trim, art deco"),
    tb("ad2-zebra-throw","斑馬紋天鵝絨毯（黑白）","textile",["art-deco"],
       ["zebra throw","black white","velvet"],["black","white","zebra"],
       4500,"130x160cm","black and white velvet zebra-print throw blanket, Hollywood Regency art deco decor"),
    tb("ad2-peacock-chair","孔雀椅（天然藤）","chair",["art-deco","boho"],
       ["peacock chair","rattan","large fan"],["natural rattan","gold stand"],
       22000,"Dia100xH180 (with stand)","natural rattan fan peacock chair on gold iron stand, art deco or boho statement"),
    tb("ad2-table-lamp-pyramid","金字塔形台燈（黃銅）","lighting",["art-deco"],
       ["pyramid lamp","brass","geometric base"],["antique brass","black shade"],
       7500,"H45","brass pyramid-form table lamp base with black conical shade, art deco desk or side table"),
    tb("ad2-lacquer-dresser","黑漆面梳妝台（六抽）","storage",["art-deco"],
       ["black lacquer dresser","6-drawer","vanity"],["black gloss","chrome handles"],
       38000,"W100xD45xH80","high-gloss black lacquer 6-drawer dresser with chrome bar handles, art deco bedroom"),
    tb("ad2-velvet-sofa-midnight","午夜藍絲絨2.5人沙發","sofa",["art-deco"],
       ["midnight blue sofa","velvet","2.5-seater"],["midnight navy","dark blue"],
       45000,"W190xD86xH82","midnight navy velvet 2.5-seater sofa with curved back and gold legs, art deco glamour"),
    tb("ad2-ceiling-fan-art","金色藝術裝飾天花扇","accessory",["art-deco"],
       ["ceiling fan","gold","decorative"],["brushed gold","bronze"],
       12000,"Dia130","brushed gold ceiling fan with art deco geometric blades, luxury functional"),
    tb("ad2-nesting-table-lacquer","黑漆嵌套邊桌（3件）","table",["art-deco"],
       ["nesting tables","black lacquer","3-piece"],["black lacquer","gold edge"],
       16000,"Set of 3","3-piece black lacquer nesting side tables with gold edge trim, art deco living room"),
    tb("ad2-wall-clock-large","大型金色藝術鐘（60cm）","accessory",["art-deco"],
       ["wall clock","gold","large"],["antique gold","black dial"],
       8500,"Dia60","oversized antique gold art deco wall clock with black sunburst face, statement piece"),
    tb("ad2-smoked-floor-lamp","煙燻玻璃落地燈","lighting",["art-deco"],
       ["smoked glass floor lamp","column","art deco"],["smoked amber","antique brass"],
       16000,"H160","smoked amber glass column floor lamp on antique brass base, art deco living room"),
    tb("ad2-diamond-rug","菱形圖案羊毛地毯（黑金）","rug",["art-deco"],
       ["diamond rug","wool","geometric"],["black","gold","ivory"],
       32000,"200x300cm","wool art deco diamond lattice rug in black and gold, bold floor statement"),
    tb("ad2-bar-cabinet-mirrored","鏡面吧台酒櫃","storage",["art-deco"],
       ["mirrored bar cabinet","drinks","glamour"],["mirror glass","gold frame"],
       45000,"W100xD45xH130","mirrored glass bar cabinet with gold frame and interior LED, art deco glamour"),
    tb("ad2-velvet-headboard-high","超高天鵝絨床頭板（酒紅）","bed",["art-deco"],
       ["tall headboard","velvet","wine red"],["deep wine red velvet","gold nail"],
       22000,"W180xH150","deep wine-red velvet extra-tall headboard with gold nail-head trim, art deco bedroom"),
    tb("ad2-geometric-side-table","幾何三腳邊桌（黃銅）","table",["art-deco"],
       ["geometric side table","brass","tripod"],["polished brass"],
       9500,"W45xH55","polished brass geometric tripod side table, art deco or mid-century accent"),
    tb("ad2-scallop-wall-tiles","扇形牆磚（金色馬賽克）","accessory",["art-deco"],
       ["scallop tile","fish scale","gold mosaic"],["gold metallic","champagne"],
       4500,"Sheet 30x30cm","gold metallic scallop fish-scale mosaic wall tiles, art deco bathroom backsplash"),
    tb("ad2-velvet-footstool-teal","孔雀藍圓形坐墩","chair",["art-deco"],
       ["footstool","peacock teal","velvet"],["peacock teal","gold legs"],
       7000,"Dia55xH40","peacock teal velvet button-tufted round footstool on gold legs, art deco"),
    tb("ad2-black-faucet-art","黑色藝術水龍頭組","accessory",["art-deco","industrial"],
       ["matte black faucet","geometric","basin tap"],["matte black"],
       8500,"Standard","matte black geometric art deco basin mixer tap set, statement bathroom fitting"),
    tb("ad2-chandelier-sputnik","衛星球形吊燈（12臂）","lighting",["art-deco","modern"],
       ["sputnik chandelier","12-arm","gold"],["brushed gold"],
       22000,"Dia80","12-arm brushed gold sputnik chandelier, mid-century art deco hybrid ceiling statement"),
    tb("ad2-velvet-bench-long","長型天鵝絨休息椅凳（祖母綠）","chair",["art-deco"],
       ["velvet bench","emerald","long"],["emerald velvet","gold legs"],
       18000,"W140xD45xH48","emerald velvet long bench seat on gold legs, art deco corridor or dining"),
    tb("ad2-gold-picture-frame-lg","超大金色畫框（空白）","accessory",["art-deco"],
       ["picture frame","gold","oversized"],["ornate gold","cream mat"],
       6500,"W80xH100","oversized ornate gold picture frame, art deco gallery or statement mirror application"),
    tb("ad2-art-deco-table-clock","藝術鐘（黑白大理石底）","accessory",["art-deco"],
       ["table clock","marble base","art deco"],["black marble","gold hands","white face"],
       5500,"W20xH15","art deco table clock on black marble base, gold hands and numerals, desk or mantel"),
    tb("ad2-smoked-mirror-console","煙薰鏡面玄關桌","table",["art-deco"],
       ["smoked mirror console","table","hallway"],["smoked mirror","brass edge"],
       28000,"W120xD35xH85","smoked mirror-top console table with brass-edge frame, art deco foyer"),
    tb("ad2-velvet-curtain-royal","皇家紫天鵝絨窗簾","textile",["art-deco"],
       ["royal purple velvet","curtain","blackout"],["royal purple","deep violet"],
       14000,"W140xH280 per panel","royal purple velvet blackout curtain with gold holdback, art deco drama"),
    tb("ad2-metallic-accent-table","金屬色拼桌（2件）","table",["art-deco"],
       ["metallic accent tables","gold silver","pair"],["gold finish","silver finish"],
       12000,"Pair, Dia40xH55+50","pair of metallic gold and silver round side tables, art deco eclectic accent"),
    tb("ad2-geometric-lamp-desk","幾何桌燈（六角銅色）","lighting",["art-deco"],
       ["geometric lamp","hexagon","copper"],["antique copper","honeycomb shade"],
       6000,"H40","hexagonal copper-finished art deco table lamp, geometric metal shade, desk or bedside"),
    tb("ad2-fan-headboard","折扇形天鵝絨床頭板","bed",["art-deco"],
       ["fan headboard","velvet","fan shape"],["dusty rose velvet","gold stud"],
       18000,"W180xH130","large fan-shaped dusty rose velvet headboard with gold stud border, art deco bedroom"),
    tb("ad2-feather-floor-decor","白孔雀羽毛裝飾擺件","accessory",["art-deco"],
       ["peacock feather","white","decorative"],["white feathers","gold vase"],
       3500,"H80","arrangement of white peacock feathers in gold pedestal vase, Hollywood Regency art deco"),
    tb("ad2-glass-bar-cart","金色玻璃吧台推車（2層）","storage",["art-deco"],
       ["gold bar cart","glass shelves","wheels"],["antique gold","clear glass"],
       9500,"W60xD40xH90","antique gold metal bar cart with 2 glass shelves and brass caster wheels, art deco"),
    tb("ad2-velvet-dining-room-set","天鵝絨餐廳套裝（桌+6椅）","chair",["art-deco"],
       ["dining set","velvet chairs","art deco"],["black table","emerald velvet"],
       95000,"Table W180 + 6 chairs","black marble-top dining table with 6 emerald velvet gold-leg chairs, art deco dining"),
    tb("ad2-crystal-decanter","水晶威士忌酒瓶組","accessory",["art-deco"],
       ["crystal decanter","whisky set","barware"],["cut crystal","clear"],
       5500,"Decanter + 2 glasses","cut crystal whisky decanter and 2 glasses set, art deco bar display"),
    tb("ad2-tiger-print-rug","老虎條紋地毯","rug",["art-deco","luxury"],
       ["tiger print","animal rug","bold"],["amber gold","black"],
       22000,"160x240cm","bold tiger-stripe animal-print area rug in amber and black, art deco or glam living"),
    tb("ad2-black-lacquer-side-chest","黑漆床頭小抽屜柜","storage",["art-deco"],
       ["bedside chest","lacquer","2-drawer"],["black lacquer","chrome"],
       9500,"W50xD40xH60","black lacquer 2-drawer bedside chest with chrome bar handle, art deco bedroom"),
    tb("ad2-velvet-sofa-arm-gold","金臂扶手單人椅（寶石藍）","chair",["art-deco"],
       ["armchair","jewel blue","gold arm"],["jewel blue velvet","gold arm"],
       16000,"W78xD76xH85","jewel-blue velvet armchair with solid gold-finish wood arms, Hollywood Regency art deco"),
    tb("ad2-chrome-bath-fixture","鍍鉻藝術浴室龍頭組","accessory",["art-deco"],
       ["chrome faucet","art deco","bathroom fixtures"],["polished chrome"],
       12000,"Standard","polished chrome art deco bathroom fixture set (tap, shower head, towel bar), vintage glamour"),
    tb("ad2-oval-velvet-ottoman","橢圓天鵝絨腳凳（酒紅）","chair",["art-deco"],
       ["oval ottoman","wine red","velvet"],["wine red","burgundy velvet","gold legs"],
       9500,"W90xD55xH42","wine red velvet oval ottoman on gold legs, art deco lounge or bedroom"),
    tb("ad2-art-deco-poster-set","裝飾藝術海報（6件框裝）","accessory",["art-deco"],
       ["art deco poster","framed","set of 6"],["gold frame","graphic print"],
       6000,"Set of 6, A3","set of 6 classic art deco travel poster prints in gold frames, gallery wall"),
    tb("ad2-snake-skin-rug","蛇紋地毯（金銀色）","rug",["art-deco"],
       ["snakeskin rug","silver gold","metallic"],["metallic silver","gold"],
       18000,"160x240cm","silver and gold metallic snakeskin-print area rug, art deco or glam living room"),
    tb("ad2-column-floor-lamp","柱形大理石落地燈","lighting",["art-deco","luxury"],
       ["column lamp","marble","floor"],["white marble","antique brass"],
       22000,"H160","white marble column floor lamp with antique brass crown, art deco or classical interior"),
    tb("ad2-velvet-curtain-champagne","香檳色絲絨窗簾","textile",["art-deco"],
       ["champagne velvet","curtain","pair"],["champagne","warm gold"],
       12000,"W140xH280 per panel","champagne gold silk-touch velvet curtain panel with gold holdback, art deco bedroom"),
    tb("ad2-vanity-chair-velvet","梳妝椅（天鵝絨圓背）","chair",["art-deco"],
       ["vanity chair","round back","velvet"],["blush velvet","gold frame"],
       8500,"W55xD55xH85","blush velvet round-back vanity chair on gold X-base, art deco glamour dressing room"),

    # ── BOHO (40 items) ────────────────────────────────────────────────────
    tb("boho2-macrame-chair-swing","麻繩編織搖椅","chair",["boho"],
       ["macrame swing","hanging chair","natural rope"],["natural cotton rope","oak pole"],
       9500,"W80xH100","natural cotton macrame hanging swing chair with oak spreader bar, boho garden or porch"),
    tb("boho2-patchwork-quilt","手工拼布被（彩色）","textile",["boho"],
       ["patchwork quilt","handmade","colourful"],["multicolour patches","cotton"],
       5500,"Queen size","hand-stitched cotton patchwork quilt in mixed boho colours, cozy bedspread"),
    tb("boho2-rattan-tray-set","藤編托盤套組（3件）","accessory",["boho"],
       ["rattan tray","set of 3","natural"],["natural rattan","brown"],
       3000,"Set of 3, various","3-piece nesting natural rattan serving trays, boho kitchen or coffee table styling"),
    tb("boho2-floor-lamp-fringed","流蘇藤球落地燈","lighting",["boho"],
       ["fringed floor lamp","rattan ball","bohemian"],["natural rattan","cotton fringe"],
       7500,"H155","rattan ball shade floor lamp with cotton fringe detail, warm boho ambiance"),
    tb("boho2-moroccan-rug-red","摩洛哥柏柏爾地毯（紅色）","rug",["boho"],
       ["Berber rug","Moroccan","red"],["red","cream","tribal pattern"],
       28000,"180x270cm","handwoven Moroccan Berber wool rug, red and cream geometric tribal pattern, boho living"),
    tb("boho2-large-plants-ceramic","大型龜背芋（連陶盆）","plant",["boho"],
       ["monstera","large plant","ceramic pot"],["deep green","terracotta pot"],
       4500,"H120 (approx)","large monstera deliciosa plant in terracotta pot, boho tropical indoor jungle"),
    tb("boho2-hanging-rattan-lamp","圓形藤編懸掛燈（Dia60）","lighting",["boho"],
       ["rattan pendant","large","ceiling"],["natural rattan","warm light"],
       7500,"Dia60","large woven rattan sphere ceiling pendant lamp, boho warm ambient dining or living"),
    tb("boho2-pampas-arrangement","蒲葦草乾燥花束擺設","plant",["boho","nordic"],
       ["pampas","dried flowers","arrangement"],["cream","blush pink","natural"],
       3500,"H80 arrangement","curated dried pampas grass and wildflower arrangement in ceramic pot, boho interior"),
    tb("boho2-canvas-art-earthy","大型地球色系油畫","accessory",["boho"],
       ["earth tone art","large canvas","abstract"],["terracotta","ochre","olive"],
       9500,"W100xH120","large abstract oil painting canvas in earthy terracotta and ochre, boho living room"),
    tb("boho2-wicker-laundry","柳條洗衣籃（帶布袋）","storage",["boho"],
       ["wicker laundry","basket","linen liner"],["natural wicker","linen"],
       4500,"W50xD40xH65","natural wicker laundry hamper with removable linen bag, boho bathroom"),
    tb("boho2-jute-bath-mat","黃麻浴室地毯（圓）","textile",["boho"],
       ["jute bath mat","round","natural"],["natural jute","golden brown"],
       1200,"Dia60","round natural jute bath mat, boho or coastal bathroom floor"),
    tb("boho2-rainbow-wall-hanging","彩虹棉繩壁掛","accessory",["boho"],
       ["rainbow wall art","cotton rope","colourful"],["rainbow multicolour","cream rope"],
       2500,"W60xH80","cotton rope rainbow wall hanging in boho multicolour, children's room or boho nursery"),
    tb("boho2-beaded-curtain","串珠門帘（木珠+棉線）","textile",["boho"],
       ["bead curtain","wood beads","doorway"],["natural wood beads","cream cotton"],
       3000,"W90xH200","natural wood bead and cream cotton doorway curtain, boho room divider or window"),
    tb("boho2-ethnic-pillowcase","民族刺繡抱枕套（4件）","textile",["boho"],
       ["ethnic cushion","embroidered","4-piece"],["mixed boho colours"],
       3500,"Set of 4, 45x45cm","4-piece embroidered ethnic-pattern cushion cover set in boho mixed colours"),
    tb("boho2-sisal-rug-xl","劍麻大地毯（加大）","rug",["boho"],
       ["sisal rug","natural","XL"],["natural sisal","golden"],
       22000,"260x340cm","extra-large natural sisal area rug, chunky boucle texture, boho or coastal living room"),
    tb("boho2-rattan-mirror-oval","藤編橢圓鏡","mirror",["boho","nordic"],
       ["rattan mirror","oval","woven"],["natural rattan","honey brown"],
       6000,"W55xH85","oval natural rattan woven-frame wall mirror, boho bedroom or bathroom"),
    tb("boho2-vintage-suitcase-stacked","摩洛哥皮箱疊放邊几","table",["boho","industrial"],
       ["stacked suitcase","vintage","side table"],["faded brown leather","tan"],
       9500,"Stack H55","stack of 3 aged brown leather Moroccan-style suitcases as boho side table display"),
    tb("boho2-tie-dye-bedding","蠟染寢具（波西米亞風）","textile",["boho"],
       ["tie-dye bedding","bohemian","cotton"],["indigo blue","rust orange","cream"],
       5000,"Queen size set","boho tie-dye cotton duvet cover set in indigo and rust, relaxed bedroom style"),
    tb("boho2-rattan-tray-stand","藤編架空茶几組（2件）","table",["boho"],
       ["rattan tray table","set of 2","natural"],["natural rattan","dark wood legs"],
       8000,"Set of 2","set of 2 natural rattan tray top side tables on removable stand legs, boho living room"),
    tb("boho2-floor-mirror-rattan","落地藤框全身鏡","mirror",["boho"],
       ["floor mirror","rattan frame","full length"],["natural rattan","honey"],
       9500,"W65xH175","natural rattan frame full-length leaning floor mirror, boho bedroom statement"),
    tb("boho2-festival-lights-outdoor","室外彩燈串（3米，E27）","lighting",["boho"],
       ["outdoor string lights","globe","E27"],["warm white","amber"],
       3500,"300cm, 10 sockets","3m outdoor E27 globe string lights, warm white, boho garden or terrace party"),
    tb("boho2-wood-feather-mobile","木珠羽毛掛飾（嬰兒房）","accessory",["boho"],
       ["mobile","feathers","nursery"],["natural wood beads","white feathers"],
       2000,"H50","natural wood bead and feather hanging mobile, boho nursery ceiling decor"),
    tb("boho2-handmade-throw-tassels","流蘇手工毯（赭紅）","textile",["boho"],
       ["tassel throw","handmade","rust red"],["brick red","rust","cream tassel"],
       3000,"130x180cm","handmade cotton brick-red throw with long cream tassel edge, boho sofa or chair"),
    tb("boho2-copper-incense-holder","銅製線香燃燒台","accessory",["boho"],
       ["incense holder","copper","backflow"],["antique copper"],
       1200,"H10","antique copper waterfall backflow incense holder, boho or zen decor"),
    tb("boho2-cactus-print-wall","仙人掌圖案版畫（3件）","accessory",["boho"],
       ["cactus print","wall art","desert"],["sage green","burnt orange","terracotta"],
       2500,"Set of 3, A4","set of 3 desert cactus botanical art prints in simple frames, boho wall gallery"),
    tb("boho2-bamboo-light-string","竹製串燈（鳥形）","lighting",["boho","nordic"],
       ["bamboo bird string","decorative","light string"],["natural bamboo","warm LED"],
       1500,"200cm","2m warm-LED bamboo bird-shaped decorative light string, boho bedroom or patio"),
    tb("boho2-seagrass-bench","海草編織長凳","chair",["boho","mediterranean"],
       ["seagrass bench","woven","coastal"],["natural seagrass","dark wood legs"],
       8500,"W120xD35xH45","natural seagrass woven long bench on dark wood legs, boho or coastal living room"),
    tb("boho2-moon-phase-wall","月相銀色掛牆裝飾","accessory",["boho"],
       ["moon phase","silver","wall art"],["brushed silver","natural wood"],
       2500,"W60xH15","12-phase moon cycle wall hanging in brushed silver on wooden rod, boho bedroom"),
    tb("boho2-crystal-geode-table","天然水晶洞台面（邊桌）","table",["boho","luxury"],
       ["crystal geode","amethyst","side table"],["purple amethyst","gold base"],
       22000,"Dia30xH55","natural amethyst crystal geode slab side table on brushed gold metal base, boho luxury"),
    tb("boho2-hanging-shelf-rope","麻繩懸掛層架（3層）","storage",["boho"],
       ["rope shelf","hanging","3-tier"],["natural rope","light wood boards"],
       3500,"W60, 3 shelves","3-tier hanging rope and wood plank wall shelf, boho or natural kitchen display"),
    tb("boho2-ethnic-rug-runner","部落長條地毯（走廊）","rug",["boho"],
       ["tribal runner","narrow","hallway"],["earthy tones","geometric"],
       4500,"80x240cm","narrow ethnic tribal-pattern wool runner rug, boho hallway or kitchen passage"),
    tb("boho2-terracotta-incense-tower","赭石塔型薰香瓶","accessory",["boho"],
       ["incense tower","terracotta","aroma"],["terracotta clay"],
       1200,"H15","terracotta clay tower incense stick holder with collection tray, boho earthy meditation"),
    tb("boho2-hanging-lantern-macrame","麻繩掛燈籠","lighting",["boho"],
       ["macrame lantern","hanging","candle"],["natural rope","clear glass"],
       2500,"H40","natural cotton macrame hanging glass lantern, boho outdoor or indoor candle holder"),
    tb("boho2-fringed-pillow-set","長流蘇抱枕（4件，米）","textile",["boho"],
       ["fringe pillow","4-piece","cream"],["natural cream","ivory fringe"],
       4500,"Set of 4, 50x50cm","set of 4 cream linen cushions with long natural fringe trim, boho living room"),
    tb("boho2-wooden-camera-shelf","木製相機展示架","storage",["boho","industrial"],
       ["camera shelf","vintage","display"],["reclaimed pine","natural"],
       4000,"W60xH25","reclaimed pine wood display shelf for vintage camera or book collection, boho industrial"),
    tb("boho2-rattan-wardrobe","藤製半透明衣柜","storage",["boho"],
       ["rattan wardrobe","2-door","natural"],["natural rattan","dark wood"],
       28000,"W90xD45xH185","natural rattan panel 2-door wardrobe, dark wood frame, boho or tropical bedroom"),
    tb("boho2-fabric-pendant-indent","手工布藝吊燈（靛藍）","lighting",["boho"],
       ["fabric pendant","indigo dye","handmade"],["indigo blue","natural cotton"],
       5500,"Dia40","hand-dyed indigo cotton fabric wrapped pendant lamp, boho or global style"),
    tb("boho2-meditation-cushion-set","冥想蒲團組（靠背+坐墊）","textile",["boho","japanese"],
       ["meditation cushion","zafu","set"],["terracotta","sage green"],
       4500,"Set (zafu + zabuton)","meditation zafu round cushion and zabuton floor mat set, boho or zen practice"),
    tb("boho2-cactus-neon-light","仙人掌霓虹燈","lighting",["boho"],
       ["cactus neon","LED","fun"],["warm green neon","acrylic backing"],
       4000,"H40","green LED neon cactus light on acrylic backing, boho or eclectic wall decor"),
    tb("boho2-feather-and-bead-wall","羽毛珠飾壁掛組","accessory",["boho"],
       ["feather wall hanging","beads","natural"],["natural feathers","wood beads"],
       2000,"W50xH70","layered feather and wood-bead boho wall hanging, bedroom or living room natural decor"),

    # ── INDUSTRIAL (40 items) ──────────────────────────────────────────────
    tb("ind2-steel-dining-table-round","圓形鋼板餐桌","table",["industrial"],
       ["round dining","steel top","industrial"],["brushed steel","matte black"],
       18000,"Dia120xH76","brushed steel round dining table on X-cross matte black base, industrial dining room"),
    tb("ind2-metal-cage-shelving","鐵籠書架（大型，8格）","storage",["industrial"],
       ["cage shelf","8-cube","metal"],["matte black","raw steel"],
       18000,"W200xD35xH180","large 8-cube matte black metal grid open shelving unit, industrial loft storage"),
    tb("ind2-factory-table-lamp","工廠調節臂台燈（青銅）","lighting",["industrial"],
       ["factory lamp","articulated","bronze"],["aged bronze","industrial"],
       4500,"H50","aged bronze articulated arm factory desk lamp with industrial adjustment, workshop or desk"),
    tb("ind2-vintage-trunk-coffee","復古鐵皮行李箱茶几","table",["industrial","boho"],
       ["trunk coffee table","tin","vintage"],["aged tin","brown leather strap"],
       9000,"W100xD55xH45","vintage-style aged tin trunk repurposed as industrial boho coffee table"),
    tb("ind2-scaffolding-bookcase","腳手架管式書架","storage",["industrial"],
       ["scaffold bookcase","pipe","5-shelf"],["black iron pipe","reclaimed pine"],
       16000,"W120xD35xH180","5-shelf black iron scaffold pipe and reclaimed pine bookcase, industrial"),
    tb("ind2-concrete-pendant","水泥吊燈（方形）","lighting",["industrial"],
       ["concrete pendant","square","minimalist"],["raw grey concrete","black cord"],
       3500,"W15xD15xH10","square raw concrete pendant lamp, exposed black cord, industrial minimalist"),
    tb("ind2-raw-oak-dining","原始橡木原木餐桌（含樹皮）","table",["industrial"],
       ["live edge dining","bark","raw oak"],["natural oak","bark edge"],
       45000,"W200xD90xH76","live-edge solid oak slab dining table retaining natural bark edge, industrial raw"),
    tb("ind2-bolt-coffee-table","工業鉚釘鐵腳茶几","table",["industrial"],
       ["bolt coffee table","rivet","industrial"],["welded steel","aged steel"],
       12000,"W100xD60xH45","bolt-riveted steel industrial coffee table, raw welded finish, heavy duty"),
    tb("ind2-black-mesh-desk","黑色金屬網格書桌","desk",["industrial","modern"],
       ["mesh desk","black steel","open"],["matte black steel mesh"],
       8500,"W140xD60xH75","matte black steel mesh-panel writing desk, open frame structure, industrial home office"),
    tb("ind2-warehouse-clock","倉庫風大掛鐘（90cm）","accessory",["industrial"],
       ["warehouse clock","oversized","iron"],["distressed iron","black"],
       5500,"Dia90","oversized 90cm diameter distressed iron wall clock, industrial warehouse loft statement"),
    tb("ind2-riveted-coffee-stool","鉚釘工廠咖啡凳","chair",["industrial"],
       ["rivet stool","factory","coffee bar"],["distressed black iron","raw steel"],
       4500,"Dia35xH65","adjustable rivet-detail factory stool for industrial bar or coffee shop counter"),
    tb("ind2-hanging-cargo-lamp","貨運容器燈泡吊燈（6頭）","lighting",["industrial"],
       ["cargo pendant","6-bulb","bar light"],["matte black","amber bulb"],
       15000,"W120xH25","6-head matte black cargo-bar style pendant light, industrial kitchen island or bar"),
    tb("ind2-wire-framed-shelves","工業鐵架書架（窄型）","storage",["industrial"],
       ["iron wire shelf","narrow","floating"],["black wire","dark wood"],
       6500,"W40xD20xH150","narrow black wire-frame wall-mounted shelving unit, industrial office corner"),
    tb("ind2-concrete-bookend","水泥書擋（一對）","accessory",["industrial"],
       ["concrete bookend","pair","raw"],["raw grey concrete"],
       1500,"Pair, H12","pair of poured raw concrete L-shaped bookends, industrial desk styling"),
    tb("ind2-metal-box-storage","金屬工具箱改造收納箱","storage",["industrial"],
       ["metal box","toolbox style","storage"],["matte black","aged steel"],
       4500,"W40xD25xH20","toolbox-style steel storage box with latched lid, industrial home or workshop"),
    tb("ind2-leather-strap-shelf","真皮繩索懸掛層板","storage",["industrial","boho"],
       ["leather strap shelf","hanging","natural"],["dark brown leather","black board"],
       5000,"W80, 2 shelves","2-tier solid board shelves suspended by thick dark leather straps, industrial boho"),
    tb("ind2-vintage-industrial-fan","復古工業立扇（銅色）","accessory",["industrial"],
       ["industrial fan","copper finish","vintage"],["antique copper","black"],
       8500,"H45","antique copper finish 3-blade vintage industrial desk fan, decorative and functional"),
    tb("ind2-raw-steel-chair","生鋼折疊餐椅（6張）","chair",["industrial"],
       ["raw steel chair","folding","6-pack"],["raw steel","aged finish"],
       18000,"Set of 6","set of 6 raw steel folding dining chairs, unfinished patina, industrial cafe or home"),
    tb("ind2-wall-mounted-tool-desk","牆掛折疊工作台","desk",["industrial"],
       ["fold-down desk","wall mount","space saving"],["raw pine","black steel bracket"],
       6000,"W80xD40 (open)","fold-down wall-mounted pine work surface on black steel Murphy-desk bracket"),
    tb("ind2-pipe-table-lamp","鐵管台燈（2頭，可調）","lighting",["industrial"],
       ["pipe lamp","2-head","adjustable"],["black iron pipe","bare bulb"],
       5500,"W50xH45","2-head adjustable black iron pipe table lamp, industrial bare-bulb aesthetic"),
    tb("ind2-brick-floor-lamp","磚紅水泥落地燈","lighting",["industrial"],
       ["concrete floor lamp","brick color","industrial"],["brick red concrete","black"],
       9500,"H155","brick-red painted concrete column floor lamp, black fitting, industrial art"),
    tb("ind2-wood-iron-headboard","木板鐵框床頭板","bed",["industrial"],
       ["headboard","wood slat","black iron"],["natural pine slats","matte black iron"],
       8500,"W180xH90","natural pine slat panel headboard in matte black iron frame, industrial bedroom"),
    tb("ind2-cast-iron-pot-rack","鑄鐵鍋架（天花懸掛）","storage",["industrial"],
       ["pot rack","ceiling hung","cast iron"],["matte black iron"],
       9500,"W90xD50","matte black cast iron ceiling-hung pot and pan rack, industrial kitchen display storage"),
    tb("ind2-galvanized-bucket-planter","鍍鋅水桶花器組（3件）","plant",["industrial"],
       ["galvanized bucket","planter","set of 3"],["silver galvanized"],
       2000,"Set of 3, various sizes","set of 3 galvanized steel bucket planters, industrial loft or urban garden decor"),
    tb("ind2-utility-cart-black","多功能工具推車（黑，3層）","storage",["industrial","modern"],
       ["utility cart","3-tier","black wheels"],["matte black"],
       5500,"W50xD35xH85","matte black 3-shelf rolling utility cart, industrial or modern home or office"),
    tb("ind2-oversized-gear-decor","超大齒輪牆飾","accessory",["industrial"],
       ["gear decor","oversized","wall art"],["rusted iron","dark brown"],
       6500,"Dia80","extra-large antique rusted iron gear wall art, industrial feature wall statement piece"),
    tb("ind2-metal-window-frame","黑色金屬窗格牆板","accessory",["industrial"],
       ["metal window frame","decorative","black"],["matte black steel"],
       5500,"W80xH120","matte black steel multi-pane decorative window frame wall panel, industrial loft"),
    tb("ind2-industrial-bath-shelf","工業風浴室置物架（鐵木）","storage",["industrial"],
       ["bathroom shelf","iron wood","industrial"],["matte black iron","natural pine"],
       4500,"W60xH80","black iron and pine 3-shelf bathroom wall ladder rack, industrial bathroom storage"),
    tb("ind2-factory-sofa-grey","工業風深灰布沙發","sofa",["industrial","modern"],
       ["industrial sofa","dark grey","2-seater"],["dark charcoal grey","matte black legs"],
       22000,"W175xD82xH78","deep charcoal grey 2-seater sofa on low matte black metal legs, industrial modern"),
    tb("ind2-raw-concrete-lamp-base","水泥台燈底座（DIY）","lighting",["industrial"],
       ["concrete lamp base","DIY","table lamp"],["raw grey concrete","brass fitting"],
       2500,"H25","raw poured concrete table lamp base with brass bulb fitting, industrial DIY styling"),
    tb("ind2-metal-duct-floor-lamp","金屬管道落地燈（三彎管）","lighting",["industrial"],
       ["duct floor lamp","triple bend","industrial"],["matte black iron pipe","bare bulb"],
       9000,"H170","triple-bend matte black iron pipe floor lamp with 3 Edison bulbs, industrial loft"),
    tb("ind2-distressed-wood-mirror","做舊木框鏡（長方）","mirror",["industrial","boho"],
       ["distressed wood mirror","rectangle","barn wood"],["reclaimed barn wood","grey-brown"],
       7500,"W60xH100","reclaimed barn wood frame rectangular wall mirror, industrial rustic bedroom or living room"),
    tb("ind2-chain-chandelier","鐵鏈吊燈（多角）","lighting",["industrial"],
       ["chain chandelier","industrial","multi-arm"],["dark iron chain","vintage brass"],
       22000,"Span80xH80","multi-arm chain and vintage brass Edison-bulb chandelier, industrial dining room"),
    tb("ind2-metal-staircase-shelf","樓梯形金屬展示架","storage",["industrial","modern"],
       ["staircase shelf","metal","tiered"],["matte black steel","natural oak"],
       9500,"W50xH120","black steel staircase display shelf with 5 oak board steps, industrial home display"),
    tb("ind2-lockers-narrow","窄型金屬置物柜（3格）","storage",["industrial"],
       ["narrow locker","3-door","metal"],["dark grey","gunmetal"],
       9500,"W45xD35xH180","3-door narrow gunmetal metal locker cabinet, industrial bedroom or mudroom"),
    tb("ind2-pipe-coat-stand","鐵管衣帽架（T型）","storage",["industrial"],
       ["coat stand","T-shape","iron pipe"],["black iron pipe","reclaimed wood base"],
       5500,"H175","T-shaped black iron pipe freestanding coat and hat stand with reclaimed wood base, industrial"),
    tb("ind2-raw-steel-bin","工業風垃圾桶（銀色）","accessory",["industrial"],
       ["steel bin","industrial","round"],["brushed steel","black lid"],
       1800,"H40","brushed steel round pedal waste bin, industrial kitchen or office"),
    tb("ind2-metal-newspaper-rack","鐵製報紙架（附輪）","storage",["industrial"],
       ["newspaper rack","rolling","metal"],["black iron","wood base"],
       4500,"W40xH70","rolling black iron newspaper and magazine rack, industrial home or office reading corner"),
    tb("ind2-concrete-fireplace","混凝土壁爐台（電熱）","accessory",["industrial"],
       ["concrete fireplace","electric","modern industrial"],["raw concrete","black grate"],
       28000,"W100xH75","raw concrete finish electric fireplace surround, industrial or modern loft living room"),
    tb("ind2-mesh-locker-basket","金屬網格抽屜籃（6格）","storage",["industrial"],
       ["wire drawer","6-basket","locker"],["matte black wire mesh"],
       8500,"W60xD35xH120","6-basket matte black wire mesh locker unit, industrial workshop or utility storage"),

    # ── MEDITERRANEAN (35 items) ────────────────────────────────────────────
    tb("med2-white-plaster-bench","白石灰磚砌長凳","chair",["mediterranean"],
       ["plaster bench","white","Mediterranean built-in"],["chalk white plaster"],
       6500,"W150xD40xH45","whitewashed plaster-look long bench, Mediterranean carved stone aesthetic"),
    tb("med2-blue-pot-tall","地中海藍色高盆（橄欖缸）","plant",["mediterranean"],
       ["tall blue pot","olive jar","ceramic"],["cobalt blue","hand-painted"],
       5500,"H60xDia40","tall cobalt blue hand-painted Mediterranean olive jar ceramic planter"),
    tb("med2-rope-light-ceiling","白色麻繩燈串（吊頂）","lighting",["mediterranean"],
       ["rope light","ceiling","festoon"],["natural rope","warm white"],
       3500,"500cm","5m natural rope-wrapped festoon ceiling string lights, Mediterranean terrace or kitchen"),
    tb("med2-linen-sunbed-cushion","戶外躺椅亞麻墊（白）","textile",["mediterranean"],
       ["sunlounger cushion","white linen","outdoor"],["white linen","stripe"],
       4000,"200x60cm","white linen sunlounger cushion with blue stripe trim, Mediterranean poolside or patio"),
    tb("med2-arch-plant-stand","拱形植物架（白色）","plant",["mediterranean"],
       ["arch plant stand","white","metal"],["matte white","arched"],
       5500,"W60xD30xH90","white arched metal plant display stand with 2 shelves, Mediterranean garden or porch"),
    tb("med2-blue-linen-bedding","深藍水洗亞麻寢具（4件）","textile",["mediterranean"],
       ["linen bedding","deep blue","stonewashed"],["deep navy","dark blue"],
       6000,"Queen size 4-piece","deep navy stonewashed linen 4-piece bedding set, Mediterranean coastal bedroom"),
    tb("med2-wicker-chair-hanging","白藤懸掛椅（戶外）","chair",["mediterranean"],
       ["wicker hanging chair","outdoor","white"],["white wicker","natural cushion"],
       18000,"Dia80xH180 (with frame)","white wicker hanging egg chair with natural cushion, Mediterranean patio or garden"),
    tb("med2-mosaic-mirror","馬賽克裝飾鏡","mirror",["mediterranean"],
       ["mosaic mirror","hand-laid","blue white"],["cobalt mosaic","white grout"],
       6500,"Dia70","hand-laid cobalt blue and white mosaic tile circular wall mirror, Mediterranean bathroom"),
    tb("med2-outdoor-dining-table","實心柚木戶外餐桌","table",["mediterranean"],
       ["outdoor dining table","teak","8-seater"],["natural teak","warm wood"],
       45000,"W200xD100xH76","solid teak 8-seater outdoor dining table, Mediterranean villa alfresco dining"),
    tb("med2-ceramic-lamp-hand","手繪陶瓷台燈（藍花）","lighting",["mediterranean"],
       ["ceramic lamp","blue flower","hand-painted"],["white ceramic","cobalt blue"],
       6000,"H40","white ceramic table lamp with hand-painted cobalt blue floral motif, Mediterranean bedroom"),
    tb("med2-outdoor-sofa-white","白色戶外沙發組（3件）","sofa",["mediterranean"],
       ["outdoor sofa","white","rattan"],["white PE rattan","white cushion"],
       55000,"3-piece set","3-piece white PE rattan outdoor sofa set with white cushions, Mediterranean terrace"),
    tb("med2-blue-tile-table","西班牙藍瓷磚桌（圓，戶外）","table",["mediterranean"],
       ["tile table","outdoor","blue white round"],["hand-painted blue","white grout"],
       9500,"Dia80xH75","round hand-painted blue azulejo tile-top outdoor bistro table, Mediterranean patio"),
    tb("med2-fish-wall-art","魚群鍛鐵牆飾","accessory",["mediterranean"],
       ["fish wall art","wrought iron","coastal"],["antique black iron"],
       3500,"W80xH50","antique black wrought-iron school-of-fish wall art, Mediterranean coastal or boho"),
    tb("med2-white-deck-chair","白色Adirondack木椅","chair",["mediterranean","nordic"],
       ["adirondack chair","white","outdoor"],["white painted wood"],
       5500,"W80xD90xH95","white painted solid wood Adirondack outdoor chair, Mediterranean or Nordic garden"),
    tb("med2-clay-water-fountain","陶土壁掛水景","accessory",["mediterranean"],
       ["wall fountain","clay","indoor outdoor"],["terracotta clay","natural"],
       12000,"W40xD20xH60","terracotta wall-mounted water fountain, Mediterranean garden or courtyard feature"),
    tb("med2-striped-outdoor-awning","藍白條紋戶外遮陽布","textile",["mediterranean"],
       ["awning","blue white stripe","outdoor shade"],["cobalt blue","white"],
       8000,"W300xH150","blue and white striped outdoor awning shade sail, Mediterranean terrace sun protection"),
    tb("med2-painted-wood-cabinet","手繪地中海藍木櫃","storage",["mediterranean"],
       ["hand-painted cabinet","Mediterranean blue","4-door"],["cobalt blue","antique white"],
       28000,"W150xD45xH85","4-door hand-painted Mediterranean cobalt blue distressed cabinet, dining or living room"),
    tb("med2-sunflower-tile-panel","向日葵馬賽克壁板","accessory",["mediterranean"],
       ["sunflower mosaic","tile panel","Spanish"],["yellow sunflower","cobalt"],
       4500,"W30xH30","hand-crafted Spanish sunflower ceramic mosaic tile wall panel, Mediterranean kitchen"),
    tb("med2-terracotta-dinnerware","赭石陶器餐具組（16件）","accessory",["mediterranean"],
       ["terracotta dinnerware","16-piece","rustic"],["terracotta","clay red"],
       8000,"16-piece set","16-piece rustic terracotta clay dinnerware set (plates + bowls + cups), Mediterranean dining"),
    tb("med2-ceramic-kitchen-canisters","地中海陶製廚房罐（3件）","accessory",["mediterranean"],
       ["ceramic canisters","Mediterranean","kitchen"],["cobalt blue","hand-painted"],
       3500,"Set of 3","set of 3 hand-painted cobalt blue ceramic kitchen storage canisters, Mediterranean kitchen"),
    tb("med2-wood-shutter-door","地中海木拉門（一對）","accessory",["mediterranean"],
       ["wooden shutters","doors","pair","Mediterranean"],["ocean blue","distressed"],
       9500,"Pair W40xH210","pair of Mediterranean blue distressed wood closet shutter doors, wardrobe DIY"),
    tb("med2-outdoor-rug-striped","條紋戶外地毯（藍白）","rug",["mediterranean"],
       ["outdoor rug","striped","patio"],["blue white","navy stripe"],
       7000,"200x300cm","washable blue and white stripe outdoor rug, Mediterranean patio or poolside"),
    tb("med2-olive-wood-serving","橄欖木砧板+沙拉匙組","accessory",["mediterranean"],
       ["olive wood","serving board","salad spoon"],["natural olive wood"],
       3000,"Board + pair of spoons","natural olive wood cutting board with salad serving spoon pair, Mediterranean kitchen"),
    tb("med2-cobalt-table-cloth","地中海藍桌布（亞麻）","textile",["mediterranean"],
       ["tablecloth","cobalt blue","linen"],["cobalt blue","white"],
       2000,"W140xH180","cobalt blue linen tablecloth, Mediterranean alfresco or indoor dining"),
    tb("med2-citrus-candle-set","柑橘香氛蠟燭組（3件）","accessory",["mediterranean"],
       ["citrus candle","lemon orange","set"],["yellow lemon","orange"],
       2500,"Set of 3, 150g each","Mediterranean citrus scented soy candles (lemon, orange, bergamot) set of 3"),
    tb("med2-whitewash-coffee-table","白石灰圓形茶几","table",["mediterranean"],
       ["whitewash coffee table","round","coastal"],["whitewash white","lime wash"],
       8000,"Dia80xH42","round whitewash lime-finished wood coffee table, Mediterranean or Nordic coastal"),
    tb("med2-outdoor-planter-terracotta","大型戶外赭石花盆（一對）","plant",["mediterranean"],
       ["outdoor planter","large","pair"],["terracotta clay","aged"],
       8000,"Pair, Dia50xH60","pair of large aged terracotta outdoor planters, Mediterranean garden centrepiece"),
    tb("med2-white-rope-pendant","白麻繩吊燈（簇狀）","lighting",["mediterranean","boho"],
       ["rope pendant","white","cluster"],["white cotton rope","warm bulb"],
       5500,"Dia35","white cotton rope cluster pendant lamp, Mediterranean or boho dining room"),
    tb("med2-glazed-fishbowl","地中海釉面金魚缸","plant",["mediterranean"],
       ["fishbowl","glazed","cobalt"],["cobalt blue glaze","ocean blue"],
       4500,"Dia40","large cobalt-glazed ceramic bowl repurposed as fishbowl or planter, Mediterranean decor"),
    tb("med2-linen-robe","棉亞麻浴袍（米色）","textile",["mediterranean","muji"],
       ["bathrobe","linen cotton","natural"],["natural linen","beige"],
       3500,"One size","natural linen-cotton waffle bathrobe, Mediterranean or Nordic spa bathroom"),
    tb("med2-blue-garden-bench","戶外藍色木製花園凳","chair",["mediterranean"],
       ["garden bench","blue painted","outdoor"],["cobalt blue","white"],
       9500,"W120xD38xH88","cobalt blue painted solid wood outdoor garden bench, Mediterranean garden"),
    tb("med2-rope-basket-xl","超大麻繩儲物籃（帶把）","storage",["mediterranean","boho"],
       ["rope basket","XL","with handles"],["natural cotton rope","cream"],
       5000,"Dia55xH45","extra-large natural cotton rope coiled storage basket with two handles, Mediterranean boho"),
    tb("med2-stone-garden-statue","石雕花園擺設（小天使）","accessory",["mediterranean"],
       ["garden statue","stone","cherub"],["aged limestone","grey stone"],
       8500,"H40","aged limestone-finish small cherub garden statue, Mediterranean or classical garden decor"),
    tb("med2-ceramic-wall-tiles-blue","藍色幾何陶磚（廚房壁）","accessory",["mediterranean"],
       ["ceramic wall tile","geometric","blue"],["cobalt blue","turquoise","sky blue"],
       4500,"Sheet 30x30cm (12 tiles)","cobalt blue geometric hand-painted ceramic wall tiles, Mediterranean kitchen backsplash"),
    tb("med2-wooden-arch-mirror","白拱形木鏡（室外用）","mirror",["mediterranean"],
       ["arch mirror","white wood","outdoor"],["white painted wood"],
       9500,"W70xH130","white painted wood arch-top wall mirror, weather-resistant, Mediterranean outdoor or indoor"),
    tb("med2-seaside-mural","地中海海灣壁畫（畫布）","accessory",["mediterranean"],
       ["mural canvas","seaside","Mediterranean village"],["aqua blue","white","terracotta"],
       12000,"W120xH80","coastal Mediterranean village scene oil painting on canvas, dining or living room"),
]

def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    print(f"Current: {len(existing)}")
    existing_names = {item["name_zh"] for item in existing}
    new_items = [item for item in BATCH5 if item["name_zh"] not in existing_names]
    print(f"Adding: {len(new_items)}")
    merged = existing + new_items
    print(f"Total: {len(merged)}")
    style_count = {}
    for item in merged:
        s = item.get("style_tags", ["unknown"])[0]
        style_count[s] = style_count.get(s, 0) + 1
    for s, c in sorted(style_count.items()):
        print(f"  {s:15s}: {c}")
    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print("Done.")

if __name__ == "__main__":
    main()
