"""
Catalog Batch 6 — ~400 items, all 9 styles, diverse categories
"""
import json, os

CATALOG_PATH = os.path.join(os.path.dirname(__file__), "furniture_catalog.json")

def tb(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "Taobao", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.taobao.com/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

def ik(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "IKEA", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.ikea.com/tw/zh/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

BATCH6 = [
    # ── MODERN (45 items) ──────────────────────────────────────────────────
    tb("mod3-half-moon-console","半月形玄關桌（黑色）","table",["modern"],
       ["half-moon console","semicircle","black"],["matte black"],
       6500,"W80xD40xH82","matte black half-moon console table, minimal footprint, modern entryway or hallway"),
    tb("mod3-compact-sofa-green","墨綠雙人沙發（緊湊型）","sofa",["modern"],
       ["compact sofa","forest green","2-seater"],["forest green","dark sage"],
       22000,"W155xD80xH78","forest green 2-seater compact sofa on solid wood legs, modern apartment living"),
    tb("mod3-l-shaped-desk","L型電腦桌（白橡）","desk",["modern"],
       ["L-shaped desk","corner desk","white oak"],["white oak","warm wood"],
       18000,"W160xD120xH75","white oak L-shaped corner computer desk, modern home office"),
    tb("mod3-wall-art-3panels","三聯抽象畫組","accessory",["modern"],
       ["triptych wall art","3-panel","abstract"],["charcoal","cream","gold"],
       9500,"3x W40xH80","3-panel abstract canvas art set in charcoal and gold, modern living room wall"),
    tb("mod3-outdoor-daybed","戶外躺臥雙人床（深灰）","bed",["modern"],
       ["outdoor daybed","all-weather","lounge"],["dark grey PE rattan","white cushion"],
       35000,"W200xD100xH70","all-weather PE rattan outdoor daybed with cushions, modern terrace or poolside"),
    tb("mod3-breakfast-bar","廚房半高吧台（白橡）","table",["modern"],
       ["breakfast bar","kitchen counter","white oak"],["white oak","matte white"],
       22000,"W120xD45xH105","white oak peninsula breakfast bar unit for kitchen, modern open plan"),
    tb("mod3-neon-tube-light","柔性霓虹管燈（U型，白）","lighting",["modern"],
       ["neon tube","LED","wall art"],["warm white neon","black acrylic"],
       4500,"W50xH30","warm white LED neon U-shaped tube light on black acrylic, modern minimalist wall decor"),
    tb("mod3-murphy-bed-sofa","壁床沙發（白色，附桌）","bed",["modern"],
       ["murphy bed","sofa bed","wall bed"],["white","light grey sofa"],
       55000,"W160xH230 (folded)","white Murphy wall bed with integrated sofa and fold-down desk, modern studio"),
    tb("mod3-velvet-bench-grey","灰色絲絨長凳（黑金屬脚）","chair",["modern"],
       ["velvet bench","grey","metal legs"],["light grey velvet","matte black legs"],
       8500,"W100xD38xH46","light grey velvet bench on matte black metal legs, modern hallway or bedroom"),
    tb("mod3-lounge-chair-egg","蛋形休閒單椅（白）","chair",["modern"],
       ["egg chair","white","lounge"],["white fibreglass shell","white cushion"],
       28000,"W85xD79xH107","white fibreglass egg lounge chair with white cushion, mid-century modern icon"),
    tb("mod3-grid-wardrobe","格狀組合衣柜（白，4門）","storage",["modern"],
       ["modular wardrobe","grid door","4-door"],["white"],
       32000,"W200xD60xH220","4-door white wardrobe with grid-pattern glass panels, modern bedroom"),
    tb("mod3-concrete-book-ends","水泥幾何書擋（3角，對裝）","accessory",["modern","industrial"],
       ["concrete bookend","triangle","geometric"],["grey concrete"],
       1200,"Pair H12","pair of triangular concrete bookends, modern-industrial desk styling"),
    tb("mod3-tech-charging-station","多設備桌面充電站（白）","accessory",["modern"],
       ["charging station","multi-device","tech"],["white","glossy white"],
       3500,"W25xH15","5-port white desktop charging station with wireless pad, modern smart home desk"),
    tb("mod3-sofa-rounded-back","圓背沙發（奶油，3人）","sofa",["modern"],
       ["round back sofa","cream","curved"],["cream bouclé","warm ivory"],
       42000,"W225xD92xH80","cream boucle round-back 3-seater sofa, curved silhouette, contemporary modern"),
    tb("mod3-art-gallery-wall","現代藝廊掛畫組（9件）","accessory",["modern"],
       ["gallery wall","9-piece","mixed media"],["black white gold","modern prints"],
       12000,"9-piece set, various","9-piece modern gallery wall print set with frames, geometric and abstract mix"),
    tb("mod3-tall-sideboard-white","高身白色邊櫃（6門）","storage",["modern"],
       ["tall sideboard","white","6-door"],["matte white","brushed chrome handles"],
       28000,"W180xD45xH120","6-door tall white buffet cabinet with chrome bar handles, modern dining room"),
    tb("mod3-pedestal-table-tulip","鬱金香底座大理石桌","table",["modern"],
       ["tulip table","marble top","pedestal"],["white Carrara marble","white glossy base"],
       22000,"Dia100xH73","white marble top tulip pedestal dining table, Saarinen-inspired mid-century modern"),
    tb("mod3-task-chair-mesh-blk","全黑網椅（高背）","chair",["modern"],
       ["mesh task chair","high back","black"],["matte black","dark grey mesh"],
       16000,"W68xD65xH110-125","all-black high-back mesh ergonomic task chair, modern professional home office"),
    tb("mod3-smart-bulb-set","智慧彩色燈泡組（4入）","lighting",["modern"],
       ["smart bulb","colour changing","E27"],["warm white","multicolour option"],
       4500,"Set of 4, E27","4-pack E27 WiFi smart colour-changing LED bulbs, modern connected home"),
    tb("mod3-room-divider-glass","玻璃鋼框移動隔間","accessory",["modern"],
       ["room divider","glass panel","steel"],["clear glass","matte black steel"],
       28000,"W180xH200 per panel","clear glass and matte black steel room divider panel, modern open-plan space"),
    tb("mod3-shoe-rack-spinning","旋轉鞋架（30雙）","storage",["modern"],
       ["rotating shoe rack","30 pairs","space saving"],["white","chrome"],
       8500,"Dia55xH175","rotating vertical shoe rack, holds 30 pairs, modern space-saving bedroom or hallway"),
    tb("mod3-tv-wall-swivel","電視壁掛架（可旋轉，65吋）","accessory",["modern"],
       ["TV wall mount","swivel","65 inch"],["black metal"],
       5500,"Fits up to 65in","heavy-duty swivel and tilt TV wall bracket for up to 65in, modern living room"),
    tb("mod3-pendant-3way-adj","三燈可調角度餐燈","lighting",["modern"],
       ["3-way pendant","adjustable","dining"],["brushed silver","white"],
       12000,"W80xH30","3-shade adjustable-arm pendant dining light, brushed silver, modern dining room"),
    tb("mod3-accent-wall-geo","幾何牆面裝飾板（黑）","accessory",["modern"],
       ["geometric wall panel","3D texture","black"],["matte black PU"],
       3500,"W60xH60 per panel","matte black 3D geometric wall panel tile, DIY feature wall, modern interior"),
    tb("mod3-dining-table-terrazzo","水磨石圓形餐桌","table",["modern"],
       ["terrazzo dining","round","colourful"],["multi-chip terrazzo","white cement"],
       18000,"Dia120xH75","terrazzo round dining table, colourful stone chips in white cement, modern playful"),
    tb("mod3-bed-under-light","床底間接照明帶（暖光）","lighting",["modern"],
       ["under-bed LED","ambient","indirect"],["warm amber LED"],
       1800,"300cm (per roll)","warm amber LED strip light for under-bed indirect lighting, modern bedroom ambiance"),
    tb("mod3-hallway-mirror-tall","玄關高鏡（黑色，全身）","mirror",["modern"],
       ["tall mirror","hallway","full-length"],["matte black frame"],
       8000,"W40xH180","matte black slim-frame full-length hallway mirror, modern entryway"),
    tb("mod3-ladder-shelf-black","黑色梯形展示架（5層）","storage",["modern","industrial"],
       ["ladder shelf","5-tier","black"],["matte black","dark walnut"],
       7000,"W55xH180","matte black metal frame 5-tier ladder shelf with walnut boards, modern display"),
    tb("mod3-kitchen-open-shelving","廚房開放式壁架（2層）","storage",["modern"],
       ["kitchen shelf","open","wall-mount"],["matte black steel","white oak board"],
       6500,"W90xH60","2-tier wall-mounted kitchen open shelving on matte black steel brackets with white oak boards"),
    tb("mod3-sofa-throw-pillow-set","現代感靠枕組（5件）","textile",["modern"],
       ["throw pillows","5-piece","modern"],["charcoal","ivory","gold","sage"],
       4500,"5-piece set, 45x45cm","5-piece modern cushion cover set in charcoal, ivory, sage and gold, living room"),
    tb("mod3-hanging-bed-ropes","繩索懸掛床（單人）","bed",["modern","boho"],
       ["hanging bed","swing bed","rope"],["natural hemp rope","pine slat"],
       12000,"W100xL200","single hanging platform bed suspended by natural hemp rope, modern boho loft"),
    tb("mod3-fold-dining-set","折疊餐桌椅組（4人，白）","table",["modern"],
       ["folding dining set","4-person","white"],["white","light grey"],
       8500,"Table W80+4 chairs","space-saving white folding dining table and 4 chair set, modern small apartment"),
    tb("mod3-abstract-sculpture","抽象金屬雕塑（大，黑）","accessory",["modern"],
       ["abstract sculpture","metal","tall"],["matte black"],
       8500,"H60","tall matte black abstract metal sculpture, modern statement coffee table or shelf art"),
    tb("mod3-concealed-storage-sofa","隱藏儲物沙發（米，L型）","sofa",["modern"],
       ["storage sofa","L-shape","hidden drawer"],["light beige","cream"],
       48000,"W280xD160xH78","L-shaped cream fabric sofa with hidden storage drawers in chaise base, modern"),
    tb("mod3-white-globe-floor-lamp","白色球形落地燈","lighting",["modern","muji"],
       ["globe floor lamp","white","spherical"],["matte white"],
       5500,"Dia50xH155","matte white spherical floor lamp on slim white stem, modern minimalist living room"),
    tb("mod3-minimalist-coat-hanger","極簡掛衣鉤（線形，5鉤）","accessory",["modern"],
       ["coat hanger","linear","5-hook"],["brushed brass","white wall"],
       1500,"W50","5-hook brushed brass linear wall-mounted coat hook rail, modern entryway"),
    tb("mod3-velvet-dining-chair-grey","淺灰絲絨餐椅（6張）","chair",["modern"],
       ["velvet dining chair","light grey","6-piece"],["light grey velvet","brushed gold legs"],
       22000,"Set of 6","6 light grey velvet dining chairs on brushed gold legs, modern elegant dining"),
    tb("mod3-grey-marble-bathroom","灰色大理石浴室台（吊掛）","storage",["modern"],
       ["bathroom vanity","grey marble","wall-hung"],["grey marble top","white gloss"],
       28000,"W100xD46xH60","wall-hung white gloss bathroom vanity with grey marble top and undermount sink, modern"),
    tb("mod3-grid-bed-frame","格狀金屬床頭板（黑，雙人）","bed",["modern","industrial"],
       ["grid headboard","black iron","double"],["matte black iron grid"],
       9500,"W153xD213 (queen)","black iron grid panel queen bed frame, low profile, modern industrial bedroom"),
    tb("mod3-low-media-unit","低矮電視機台（3m，白橡木）","storage",["modern","nordic"],
       ["long media unit","white oak","low"],["white oak","natural wood"],
       45000,"W300xD40xH45","3m long low-profile white oak media unit with push-open doors, modern scandi living"),
    tb("mod3-boucle-bed-queen","布克萊床架（女王，米）","bed",["modern"],
       ["boucle bed","upholstered","cream"],["cream boucle","warm ivory"],
       38000,"W153xD213 (queen)","cream boucle fabric upholstered queen bed, low silhouette, contemporary cozy modern"),
    tb("mod3-tall-glass-pendant","細頸玻璃球吊燈","lighting",["modern"],
       ["glass pendant","teardrop","tall neck"],["clear glass","brushed gold fitting"],
       5000,"H35xDia15","clear glass teardrop pendant with brushed gold fitting, modern Scandinavian dining"),
    tb("mod3-floating-office-shelf","浮壁式辦公隔板架","storage",["modern"],
       ["floating shelf","office","monitor stand"],["white oak","white"],
       8000,"W120xD25xH80","floating wall-mounted L-shaped shelf system for monitor and desk, modern home office"),
    tb("mod3-ceramic-diffuser-lamp","陶瓷擴香台燈（灰）","lighting",["modern","muji"],
       ["aroma diffuser lamp","ceramic","grey"],["matte grey"],
       4500,"H25","matte grey ceramic LED aroma diffuser and night lamp combo, modern bedroom"),
    tb("mod3-velvet-storage-headboard","天鵝絨床頭板置物型","bed",["modern"],
       ["storage headboard","velvet","shelf"],["slate grey velvet","natural oak shelf"],
       18000,"W180xH100","slate grey velvet headboard with integrated oak shelf and USB charging, modern"),
    tb("mod3-modular-kitchen-cart","模組廚房推車（白橡，附抽屜）","storage",["modern"],
       ["kitchen cart","modular","oak top"],["white","oak top","chrome handle"],
       16000,"W80xD50xH92","modular kitchen cart with oak top, 2 drawers and bottom shelf, modern kitchen island"),

    # ── NORDIC (40 items) ──────────────────────────────────────────────────
    tb("nord3-sauna-bench","桑拿浴木質長凳（芬蘭杉）","chair",["nordic"],
       ["sauna bench","Finnish spruce","spa"],["natural spruce","blond wood"],
       9500,"W150xD30xH45","Finnish spruce wood sauna bench, Nordic spa bathroom or sauna room"),
    tb("nord3-candle-arch-window","拱形窗型蠟燭台（白）","accessory",["nordic"],
       ["candle arch","window","white metal"],["white powder coat","warm glow"],
       2500,"W40xH30","white metal arch window-shaped candle holder, traditional Nordic advent light"),
    tb("nord3-abstract-print-2up","北歐抽象二聯畫","accessory",["nordic"],
       ["abstract diptych","2-panel","Nordic"],["dusty blue","cream","sage"],
       4500,"2x W50xH70","2-panel Nordic abstract art diptych in dusty blue and sage, framed gallery wall"),
    tb("nord3-long-dining-table","大型實木長餐桌（10人）","table",["nordic"],
       ["farmhouse table","long","10-seater"],["natural pine","whitewash"],
       45000,"W280xD90xH76","solid pine long farmhouse dining table, seats 10, Nordic gathering centrepiece"),
    tb("nord3-wooden-advent-calendar","木製降臨節日曆盒","accessory",["nordic"],
       ["advent calendar","wood","Christmas"],["natural pine","numbered"],
       3500,"W40xH25","24-drawer pine wood advent calendar display box, Nordic seasonal home decor"),
    tb("nord3-linen-duvet-stripe","亞麻條紋寢具組（藍灰）","textile",["nordic"],
       ["linen duvet","stripe","blue grey"],["slate blue","grey stripe","linen"],
       6000,"Queen size set","blue-grey stripe washed linen duvet cover set, Nordic calm bedroom"),
    tb("nord3-wood-trivet-set","木製鍋墊組（3件，松木）","accessory",["nordic"],
       ["trivet set","wood","kitchen"],["natural pine","light wood"],
       800,"Set of 3","set of 3 natural pine wood trivets in graduating sizes, Nordic functional kitchen"),
    tb("nord3-pendant-wabi","侘寂陶瓷吊燈（米白）","lighting",["nordic","muji"],
       ["wabi-sabi pendant","ceramic","off-white"],["matte off-white ceramic"],
       5500,"Dia20","hand-shaped matte ceramic pendant lamp, organic irregular form, Nordic wabi-sabi kitchen"),
    tb("nord3-laundry-bag-linen","棉麻洗衣袋（大）","storage",["nordic","muji"],
       ["laundry bag","linen","drawstring"],["natural linen","oatmeal"],
       900,"W50xH70","oversized natural linen drawstring laundry bag, Nordic laundry room organiser"),
    tb("nord3-door-stop-wood","原木門擋（山形）","accessory",["nordic"],
       ["door stop","wood","mountain"],["natural pine","mountain silhouette"],
       600,"H8","mountain-shaped natural pine wood door stop, Nordic hygge home accent"),
    tb("nord3-birch-log-coaster","樺木切片杯墊（6件）","accessory",["nordic"],
       ["birch coaster","natural","6-pack"],["natural birch","bark edge"],
       800,"Set of 6, Dia10","set of 6 natural birch slice coasters with bark edge, Nordic cabin table styling"),
    tb("nord3-white-storage-cube-lid","白色掀蓋儲物方盒","storage",["nordic","muji"],
       ["lidded box","white","cube"],["white painted wood"],
       2500,"W30xD30xH30","white painted wood lift-lid storage cube box, Nordic or MUJI bedroom organiser"),
    tb("nord3-pine-kitchen-caddy","松木廚房餐具收納筒","storage",["nordic"],
       ["kitchen caddy","pine","utensil holder"],["natural pine","light wood"],
       1200,"Dia12xH15","natural pine wood kitchen utensil caddy holder, Nordic functional kitchen counter"),
    tb("nord3-sage-green-cushion-set","鼠尾草綠靠枕（4件組）","textile",["nordic"],
       ["cushion set","sage green","linen"],["sage green","natural linen"],
       3500,"Set of 4, 45x45cm","set of 4 sage green linen cushion covers with Nordic simple stitching"),
    tb("nord3-wood-bathtub-rack","木製浴缸跨架","accessory",["nordic"],
       ["bathtub caddy","wood","expandable"],["natural bamboo","pine"],
       2500,"Adjustable W70-90","expandable natural wood bathtub caddy with tablet and cup slots, Nordic spa"),
    tb("nord3-linen-apron-cooking","棉麻廚師圍裙（深藍）","accessory",["nordic"],
       ["cooking apron","linen","navy"],["navy blue","natural linen"],
       1200,"One size","navy blue linen kitchen apron with adjustable neck strap, Nordic home cooking"),
    tb("nord3-cabin-blanket","格紋艙室毯（深紅+格紋）","textile",["nordic"],
       ["cabin blanket","check","wool blend"],["dark red check","cream","forest green"],
       4500,"130x180cm","wool-blend tartan check blanket in Nordic cabin red and green, cosy sofa throw"),
    tb("nord3-cream-sheer-curtain","奶油色薄紗窗簾（4片）","textile",["nordic"],
       ["sheer curtain","cream","4 panels"],["cream","off-white"],
       6000,"4x W140xH250","cream semi-sheer linen-look curtain panel set of 4, airy Nordic living room light"),
    tb("nord3-pine-wall-key-hook","松木鑰匙掛架（6鉤）","accessory",["nordic"],
       ["key hook","pine","6-peg"],["natural pine"],
       800,"W40","6-peg natural pine wall-mounted key and small item hook rack, Nordic entryway"),
    tb("nord3-felt-placemat-set","羊毛氈餐墊（6件，灰）","accessory",["nordic"],
       ["placemat","wool felt","grey"],["warm grey felt"],
       1800,"Set of 6, 30x45cm","set of 6 grey wool felt dining placemats, Nordic table setting"),
    tb("nord3-pine-drying-rack","松木晾衣架（折疊）","storage",["nordic","muji"],
       ["drying rack","pine","folding"],["natural pine"],
       2200,"W80 (open)","natural pine folding indoor clothes drying rack, Nordic functional laundry"),
    tb("nord3-cloud-lamp-children","雲朵造型壁燈（童房）","lighting",["nordic"],
       ["cloud lamp","children","wall light"],["white","soft warm glow"],
       2500,"W30xH20","white cloud-shaped LED wall lamp, Nordic children's bedroom nightlight"),
    tb("nord3-terrarium-glass-open","開放式玻璃植物屋","plant",["nordic"],
       ["open terrarium","geometric","glass"],["clear glass","brass frame"],
       5000,"W25xD25xH30","geometric clear glass and brass open terrarium for succulents, Nordic plant display"),
    tb("nord3-pine-bookshelf-cube","松木方格書架（9格）","storage",["nordic"],
       ["cube bookcase","pine","9-cube"],["natural pine","honey wood"],
       12000,"W90xD30xH90","9-cube natural pine open bookcase, versatile Nordic living room or children's room"),
    tb("nord3-grey-wool-runner","羊毛走廊地毯（長條）","rug",["nordic"],
       ["wool runner","grey","hallway"],["heather grey","warm grey"],
       8000,"60x200cm","grey wool hallway runner rug, simple stripe texture, Nordic entryway or corridor"),
    tb("nord3-white-metal-planter","白色金屬花器（圓，3件）","plant",["nordic"],
       ["metal planter","white","3-piece"],["matte white","white powder coat"],
       2500,"Set of 3, Dia15-25","set of 3 white matte metal round planters in graduating sizes, Nordic plant display"),
    tb("nord3-bar-cabinet-white","白色吧台區（可鎖）","storage",["nordic"],
       ["bar cabinet","white","lockable"],["white lacquer","brushed chrome"],
       18000,"W80xD40xH100","white lacquer lockable drinks cabinet, Nordic living room wine and spirits storage"),
    tb("nord3-wooden-fruit-bowl","實木沙拉碗（大型）","accessory",["nordic"],
       ["wooden fruit bowl","large","salad"],["natural light wood","beech"],
       2500,"Dia35","large natural beech wood fruit and salad bowl, Nordic dining table centrepiece"),
    tb("nord3-pendant-amber-glass","琥珀色玻璃吊燈","lighting",["nordic"],
       ["amber glass pendant","warm","globe"],["amber glass","brass fitting"],
       6000,"Dia20","amber glass globe pendant with brass fitting, warm Nordic living or dining room light"),
    tb("nord3-scandi-shelf-leaning","斜靠書架（白橡，5層）","storage",["nordic"],
       ["leaning shelf","white oak","5-tier"],["white oak","natural"],
       12000,"W60xH180","5-tier white oak leaning bookcase, floor to ceiling display, Nordic living room"),
    tb("nord3-linen-drawstring-bag-set","亞麻束口袋組（7件）","storage",["nordic","muji"],
       ["linen bag set","drawstring","organiser"],["natural linen","white"],
       1200,"Set of 7, various sizes","7-piece natural linen drawstring organiser bags, Nordic wardrobe or travel"),
    tb("nord3-oak-cutting-board","橡木大砧板（附手把）","accessory",["nordic"],
       ["cutting board","oak","handle"],["natural oak","warm wood"],
       2200,"W40xH25","solid oak chopping board with integrated handle, Nordic kitchen essential"),
    tb("nord3-white-table-lamp-wood","白色陶瓷+原木台燈","lighting",["nordic"],
       ["table lamp","white ceramic","wood accent"],["matte white","natural wood"],
       4500,"H40","white ceramic table lamp with natural wood neck detail and white linen shade, Nordic bedside"),
    tb("nord3-grey-sofa-wide","寬大灰色L型沙發","sofa",["nordic"],
       ["L-shaped sofa","wide","grey fabric"],["light grey","warm grey"],
       52000,"W300xD170xH78","light grey fabric L-shape sofa with chaise, wide deep seat, Nordic family living"),
    tb("nord3-outdoor-bench-teak","柚木戶外長凳","chair",["nordic","mediterranean"],
       ["outdoor bench","teak","garden"],["natural teak","weathered"],
       12000,"W150xD38xH45","solid teak outdoor garden bench, weathers to silver, Nordic or coastal garden"),
    tb("nord3-round-tray-serving","原木圓形托盤","accessory",["nordic","muji"],
       ["round tray","oak","serving"],["natural oak","light wood"],
       1800,"Dia35","solid oak round serving tray with raised edge, Nordic home coffee table or ottoman tray"),
    tb("nord3-cotton-waffle-throw","棉質蜂窩格毯（米白）","textile",["nordic"],
       ["waffle throw","cotton","off-white"],["off-white","natural cotton"],
       2000,"130x160cm","off-white cotton waffle-weave throw blanket, Nordic bathroom or bedroom layering"),
    tb("nord3-bedside-sconce-pair","床頭壁燈（一對，白橡）","lighting",["nordic"],
       ["wall sconce","pair","bedside"],["natural white oak","warm white"],
       6000,"Pair H20","pair of natural white oak wall-mounted reading sconces, Nordic bedroom beside"),
    tb("nord3-large-storage-bench","儲物長凳（木蓋，白）","storage",["nordic"],
       ["storage bench","lid","white"],["white painted wood"],
       12000,"W160xD45xH48","large white painted wood storage bench with hinged lid, Nordic hallway or foot-of-bed"),
    tb("nord3-craft-supply-cabinet","手工藝品收納柜（多格）","storage",["nordic","muji"],
       ["craft cabinet","multi-drawer","storage"],["white","natural wood"],
       15000,"W60xD35xH120","20-drawer white craft and art supply storage cabinet, Nordic home studio"),
    tb("nord3-hanging-shelf-brass","黃銅掛桿層架（3層）","storage",["nordic"],
       ["hanging shelf","brass rod","3-tier"],["brushed brass","natural oak"],
       8500,"W80, 3 shelves","3-tier oak shelves suspended from brushed brass ceiling rod, Nordic kitchen or bathroom"),

    # ── JAPANESE (35 items) ────────────────────────────────────────────────
    tb("jap3-hinoki-bath-plank","扁柏浴缸踏板","accessory",["japanese"],
       ["hinoki bath","step","wood panel"],["natural hinoki pale"],
       4500,"W60xD25","natural hinoki cypress wood bath step board, Japanese onsen bathroom ritual"),
    tb("jap3-washi-lamp-square","和紙方燈台（桌上）","lighting",["japanese"],
       ["washi desk lamp","square","paper"],["white washi","dark walnut"],
       3500,"W15xD15xH25","square washi paper table lantern with walnut frame, Japanese room accent light"),
    tb("jap3-tea-ceremony-set","茶道具全套（木盆+茶碗）","accessory",["japanese"],
       ["tea ceremony","full set","chakin"],["natural wood","cream ceramic"],
       9500,"Full set","Japanese tea ceremony set with chakin cloth, chakin basin, whisk, and 2 bowls"),
    tb("jap3-wooden-stool-step","木製矮梯凳（2格）","chair",["japanese","muji"],
       ["step stool","wood","2-step"],["natural pine","light wood"],
       3000,"W35xD25xH35","solid pine 2-step stool, kitchen or library, Japanese-MUJI minimal form"),
    tb("jap3-nori-drying-rack","廚房海苔晾架（竹）","accessory",["japanese"],
       ["nori rack","bamboo","kitchen"],["natural bamboo"],
       1200,"W30xH20","bamboo drying rack for nori and herbs, Japanese traditional kitchen tool"),
    tb("jap3-katana-wall-rack","武士刀架（壁掛，檜木）","accessory",["japanese"],
       ["katana rack","wall mount","hinoki"],["natural hinoki","dark lacquer"],
       4500,"W40xH15","wall-mounted hinoki wood display rack for katana or decorative sword, Japanese aesthetic"),
    tb("jap3-ikebana-moribana","花道花盆（剣山+低盤）","plant",["japanese"],
       ["moribana","kenzan","ikebana bowl"],["matte grey ceramic","metal kenzan"],
       3500,"Set (kenzan + shallow bowl)","Japanese ikebana moribana set with metal kenzan frog and wide shallow ceramic bowl"),
    tb("jap3-rice-paper-lantern-round","和紙圓燈籠（吊頂）","lighting",["japanese"],
       ["round lantern","paper","ceiling"],["white washi","natural cord"],
       2000,"Dia40","round white washi paper ceiling lantern, traditional Japanese room atmospheric lighting"),
    tb("jap3-paulownia-trinket-box","桐木飾品小匣","storage",["japanese"],
       ["trinket box","paulownia","small"],["natural paulownia"],
       1500,"W15xD10xH8","small natural paulownia wood keepsake box with fitted lid, Japanese minimalist storage"),
    tb("jap3-bamboo-serving-tray","竹製長托盤","accessory",["japanese"],
       ["bamboo tray","long","serving"],["natural bamboo","dark rim"],
       1800,"W50xD20","long natural bamboo serving tray with carved handles, Japanese kitchen or dining"),
    tb("jap3-stone-wash-basin","石製手洗盆（圓形）","accessory",["japanese"],
       ["stone basin","hand wash","round"],["natural river stone","grey"],
       12000,"Dia35xH15","round natural river stone hand-wash basin, Japanese garden or spa bathroom"),
    tb("jap3-zabuton-4pack","坐禪蒲團（4入，墨綠）","textile",["japanese"],
       ["zabuton","meditation mat","4-pack"],["dark green","indigo"],
       6000,"Set of 4, 60x60cm","set of 4 dark green zabuton floor sitting cushions, Japanese meditation or tea room"),
    tb("jap3-bamboo-bathroom-stool","竹製浴室圓凳","chair",["japanese"],
       ["bamboo stool","bathroom","round"],["natural bamboo"],
       2500,"Dia30xH45","round natural bamboo bathroom stool, Japanese onsen-inspired spa bathroom"),
    tb("jap3-ebony-incense-box","烏木香盒","accessory",["japanese"],
       ["incense box","ebony","storage"],["dark ebony wood"],
       3000,"W20xD10xH5","dark ebony wood incense stick storage box with sliding lid, Japanese zen ritual"),
    tb("jap3-folded-kimono-display","和服掛架（展示型）","accessory",["japanese"],
       ["kimono stand","display","wooden"],["natural paulownia","lacquered"],
       8500,"H120","natural paulownia wood kimono display stand, Japanese traditional art or fashion decor"),
    tb("jap3-sand-garden-tray-lg","大型枯山水沙盤","accessory",["japanese"],
       ["zen garden","large","sand tray"],["white sand","dark stone","bamboo rake"],
       5500,"W50xD35","large desktop zen sand garden with bamboo rake and selection of stones, Japanese meditation"),
    tb("jap3-cedar-closet-lining","杉木衣櫃芳香條（10入）","accessory",["japanese"],
       ["cedar strips","closet","aromatic"],["natural cedar","pale"],
       800,"Set of 10","aromatic cedar wood closet lining strips, natural moth repellent, Japanese wardrobe care"),
    tb("jap3-rice-paper-roll","和紙壁紙（一卷）","accessory",["japanese"],
       ["washi wallpaper","natural","texture"],["natural white","cream washi"],
       2500,"W53cmxL10m","natural washi rice paper textured wallpaper, Japanese interior feature wall"),
    tb("jap3-lacquer-bento-box","漆器便當盒（雙層）","accessory",["japanese"],
       ["bento box","lacquerware","2-tier"],["dark red lacquer","black inner"],
       4500,"W22xD15xH12","2-tier dark red lacquerware bento box, traditional Japanese lunch carrier or display"),
    tb("jap3-bamboo-reading-stand","竹製閱讀架","accessory",["japanese"],
       ["book stand","bamboo","reading"],["natural bamboo"],
       2000,"W30xD20","natural bamboo book and tablet reading stand, adjustable angle, Japanese study"),
    tb("jap3-wooden-chopsticks-set","和木筷子套組（8雙，桐木）","accessory",["japanese"],
       ["chopsticks","paulownia","gift set"],["natural paulownia","light wood"],
       2000,"Set of 8 pairs","natural paulownia wood chopstick set of 8 pairs in wooden box, Japanese dining"),
    tb("jap3-black-stone-lamp","黑色石燈籠（室內小型）","lighting",["japanese"],
       ["stone lantern","black","indoor small"],["dark slate stone"],
       5500,"H30","dark slate stone indoor garden lantern, Japanese toro-inspired decorative light"),
    tb("jap3-yukata-display-hanger","浴衣展示架","accessory",["japanese"],
       ["yukata hanger","display","rack"],["natural pine","chrome rod"],
       3000,"W50xH120","pine wood horizontal bar display hanger for yukata or clothes art, Japanese bedroom"),
    tb("jap3-clay-water-jug","手拋土器水壺","accessory",["japanese"],
       ["clay jug","hand-thrown","water"],["dark earth clay","wabi"],
       3000,"1L","hand-thrown dark clay ceramic water jug, Japanese wabi-sabi kitchen display or use"),
    tb("jap3-pine-low-shelf","松木低矮展示書架（4層）","storage",["japanese","muji"],
       ["low bookcase","pine","4-tier"],["natural pine"],
       9000,"W80xD30xH60","4-tier natural pine low-profile floor bookcase, Japanese living room display"),
    tb("jap3-tatami-room-border","榻榻米房間邊框裝飾","accessory",["japanese"],
       ["tatami frame","room edge","border"],["dark lacquer border","natural rush"],
       8000,"Per room (4 strips)","dark lacquer wood border strips for tatami room perimeter edge, Japanese interior"),
    tb("jap3-morning-ritual-tray","日式晨間儀式托盤","accessory",["japanese"],
       ["morning tray","ritual","Japanese"],["natural paulownia","ceramic"],
       2500,"W35xD25","paulownia wood tray set with small ceramic cup and incense holder, Japanese morning ritual"),
    tb("jap3-bamboo-pendant-cone","竹編錐形燈罩吊燈","lighting",["japanese"],
       ["bamboo cone pendant","Japanese","conical"],["natural bamboo"],
       5000,"Dia25xH40","hand-woven bamboo conical pendant lamp shade, warm glow, Japanese or boho dining"),
    tb("jap3-cast-iron-wind-chime","南部鐵器風鈴","accessory",["japanese"],
       ["wind chime","cast iron","nambu"],["dark cast iron","natural cord"],
       2500,"H12","nambu-style traditional cast iron wind bell, Japanese outdoor or indoor hanging decor"),
    tb("jap3-grass-tatami-runner","藺草走廊條毯","rug",["japanese"],
       ["tatami runner","igusa grass","natural"],["natural rush grass","green-gold"],
       3500,"60x180cm","natural igusa rush grass tatami hallway runner mat, Japanese corridor floor cover"),
    tb("jap3-black-lacquer-tray","黑漆圓形托盤","accessory",["japanese"],
       ["lacquer tray","round","black"],["black lacquer","gold rim"],
       2800,"Dia35","round black lacquer serving tray with gold rim, Japanese traditional dining or display"),
    tb("jap3-indoor-bamboo-grove","室內竹叢盆栽","plant",["japanese"],
       ["bamboo","indoor plant","grove"],["deep green bamboo","dark pot"],
       5500,"H120 (approx)","indoor lucky bamboo grove in dark ceramic pot, Japanese zen living room"),
    tb("jap3-katana-knife-set","日本料理刀具組（3件）","accessory",["japanese"],
       ["kitchen knives","Japanese","set"],["silver blade","pakkawood handle"],
       8500,"Set of 3","3-piece Japanese kitchen knife set with pakkawood handle, chef's gyuto, santoku, paring"),
    tb("jap3-woven-hemp-mat","大麻編織地墊（自然）","rug",["japanese","boho"],
       ["hemp mat","woven","natural"],["natural hemp brown"],
       4500,"120x180cm","natural hand-woven hemp area mat, earthy texture, Japanese or bohemian floor covering"),
    tb("jap3-tatami-cushion-set6","坐墊6件組（淺卡其）","textile",["japanese"],
       ["floor cushion","tatami","6-pack"],["light khaki","natural cotton"],
       6500,"Set of 6, 55x55cm","set of 6 light khaki cotton flat zabuton floor cushions, Japanese tea room seating"),

    # ── MUJI (35 items) ────────────────────────────────────────────────────
    tb("muji3-steel-ruler","30cm不鏽鋼直尺","accessory",["muji"],
       ["stainless ruler","desk","30cm"],["brushed stainless"],
       400,"30cm","brushed stainless 30cm ruler with mm markings, MUJI precision desk tool"),
    tb("muji3-ceramic-mug","白瓷馬克杯（350ml）","accessory",["muji"],
       ["ceramic mug","white","350ml"],["matte white"],
       500,"350ml","simple matte white ceramic mug, MUJI clean form, everyday kitchen staple"),
    tb("muji3-wooden-coaster","原木杯墊（4件，橡木）","accessory",["muji"],
       ["oak coaster","set of 4","round"],["natural oak"],
       600,"Set of 4, Dia10","set of 4 natural solid oak round coasters, MUJI minimalist table protection"),
    tb("muji3-cotton-face-towel","純棉洗臉巾（4入，白）","textile",["muji"],
       ["face towel","cotton","white"],["white cotton"],
       600,"Set of 4, 34x34cm","set of 4 white 100% cotton face towels, MUJI soft and simple bathroom"),
    tb("muji3-wall-calendar-frame","木框月曆掛架","accessory",["muji"],
       ["calendar frame","wood","wall"],["natural pine","white"],
       900,"W22xH30","natural pine frame for A4 monthly wall calendar, MUJI functional home office"),
    tb("muji3-glass-water-pitcher","玻璃水壺（1.5L）","accessory",["muji"],
       ["glass pitcher","1.5L","water"],["clear glass"],
       1200,"1.5L","simple clear glass water pitcher with lid, MUJI kitchen table essential"),
    tb("muji3-linen-pillow-case","亞麻枕套（2入，米）","textile",["muji"],
       ["linen pillowcase","2-pack","natural"],["natural linen","beige"],
       1200,"Set of 2, 50x75cm","set of 2 natural linen pillowcases in beige, MUJI simple bedroom linens"),
    tb("muji3-wall-hook-clear","透明壁掛鉤（8入）","accessory",["muji"],
       ["clear hook","adhesive","8-pack"],["clear transparent"],
       400,"Set of 8","8-pack clear adhesive wall hooks, no-drill, MUJI minimal storage solution"),
    tb("muji3-cotton-hand-towel","純棉手巾（白，4入）","textile",["muji"],
       ["hand towel","white cotton","4-pack"],["white"],
       800,"Set of 4, 35x75cm","set of 4 white 100% cotton hand towels, MUJI functional bathroom"),
    tb("muji3-pencil-case","棉質筆袋（横型）","accessory",["muji"],
       ["pencil case","horizontal","cotton"],["natural cotton","beige"],
       600,"W20xH9","natural cotton horizontal pencil case with zipper, MUJI school or office"),
    tb("muji3-pp-drawer-storage","PP抽屜式收納箱（6格）","storage",["muji"],
       ["PP drawer","6-unit","clear"],["clear white","off-white PP"],
       2200,"W37xD26xH90","6-unit polypropylene clear drawer storage tower, MUJI classic organiser system"),
    tb("muji3-aroma-candle-wood","原木香氛蠟燭（白樺木）","accessory",["muji"],
       ["aroma candle","birch","natural"],["off-white soy wax","natural wood lid"],
       1800,"250g","birch and cedar scented soy wax candle with natural wood lid, MUJI clean fragrance"),
    tb("muji3-desk-fan-white","白色桌上型風扇","accessory",["muji"],
       ["desk fan","white","USB"],["white","minimal"],
       2500,"H25","white USB-powered desk fan, minimal circular form, MUJI cool home office"),
    tb("muji3-wall-shelf-pine","松木壁板（90cm）","storage",["muji","nordic"],
       ["wall shelf","pine","90cm"],["natural pine"],
       900,"W90xD12","natural pine floating wall shelf, simple bracket, MUJI functional display"),
    tb("muji3-laundry-bag-cotton","棉質洗衣袋（網，3件）","storage",["muji"],
       ["laundry bag","mesh","3-pack"],["white mesh","natural cotton"],
       500,"Set of 3","set of 3 cotton mesh laundry wash bags, MUJI delicates care"),
    tb("muji3-soy-wax-tea-light","大豆蠟燭蠟燭（30入）","accessory",["muji"],
       ["tealight","soy wax","30-pack"],["off-white","natural"],
       1000,"Set of 30","30-pack natural soy wax tealight candles, MUJI clean ambiance"),
    tb("muji3-food-wrap-beeswax","蜂蠟食物保鮮膜（3件）","accessory",["muji"],
       ["beeswax wrap","eco","food"],["honeycomb yellow","green pattern"],
       800,"Set of 3, S/M/L","3-piece beeswax food wrap set in S/M/L, MUJI eco kitchen sustainable"),
    tb("muji3-white-lamp-minimalist","極簡白色圓燈","lighting",["muji"],
       ["round lamp","white","minimal"],["pure white"],
       3500,"Dia25","pure white round ball table lamp, soft diffused glow, MUJI or Nordic bedside"),
    tb("muji3-steel-spatula-set","不鏽鋼廚具組（3件）","accessory",["muji"],
       ["spatula set","stainless","kitchen"],["brushed stainless"],
       1200,"Set of 3","3-piece brushed stainless steel kitchen spatula set, MUJI functional cooking tools"),
    tb("muji3-linen-bag-small","棉麻小手提袋","accessory",["muji"],
       ["small tote","linen","everyday"],["natural linen"],
       400,"W25xH25","small natural linen tote bag, MUJI daily carry or produce bag"),
    tb("muji3-hinged-box-pine","松木翻蓋小盒（3件）","storage",["muji"],
       ["hinged box","pine","3-piece"],["natural pine"],
       800,"Set of 3, various","set of 3 natural pine hinged-lid keepsake boxes, MUJI desk or vanity organiser"),
    tb("muji3-sofa-table-white-leg","白腳板沙發後桌","table",["muji","modern"],
       ["sofa table","white leg","narrow"],["white","natural oak top"],
       6000,"W130xD25xH75","slim white-leg sofa console table with oak top, MUJI behind-sofa styling"),
    tb("muji3-reusable-cotton-bag","再生棉布環保袋","accessory",["muji"],
       ["reusable bag","cotton","eco"],["natural cotton","off-white"],
       300,"W35xH40","natural cotton large reusable shopping bag, MUJI sustainable kitchen and market"),
    tb("muji3-small-alarm-analog","圓形指針小鬧鐘","accessory",["muji"],
       ["alarm clock","analog","round"],["white","chrome"],
       600,"Dia8xH6","small white round analog alarm clock, silent sweep hands, MUJI bedside table"),
    tb("muji3-ceramic-soap-pump","陶瓷皂液瓶（白，350ml）","accessory",["muji"],
       ["soap pump","ceramic","white"],["matte white"],
       800,"350ml","matte white ceramic soap dispenser pump bottle, MUJI bathroom or kitchen"),
    tb("muji3-wire-tension-rod","室內伸縮晾衣桿（2入）","storage",["muji"],
       ["tension rod","clothes","indoor"],["white","chrome"],
       500,"Set of 2, adjustable","set of 2 white telescoping tension rods for indoor clothes drying, MUJI utility"),
    tb("muji3-cotton-gloves-white","白棉手套（3雙）","accessory",["muji"],
       ["cotton gloves","white","cleaning"],["white cotton"],
       400,"Set of 3 pairs","white cotton household gloves, MUJI cleaning or jewellery handling"),
    tb("muji3-magnetic-whiteboard","白色磁力白板（A4）","accessory",["muji"],
       ["whiteboard","magnetic","A4"],["white"],
       800,"A4","A4 white magnetic whiteboard with marker holder, MUJI desk organisation"),
    tb("muji3-iron-file-holder","鐵製檔案夾座","storage",["muji"],
       ["file holder","iron","desk"],["brushed stainless","white"],
       800,"W12xH25","brushed stainless steel A4 document file holder, MUJI office desk"),
    tb("muji3-cotton-pillow-insert","棉質枕心（2入，45x45）","textile",["muji"],
       ["pillow insert","cotton","square"],["white cotton"],
       1200,"Set of 2, 45x45cm","set of 2 standard 45x45cm white cotton cushion inserts, MUJI bedroom or living room"),
    tb("muji3-pine-paper-tray","松木A4紙張托盤（2層）","storage",["muji"],
       ["paper tray","pine","2-tier"],["natural pine"],
       1500,"W25xD35xH15","2-tier natural pine A4 document and paper in-out tray, MUJI home office desk"),
    tb("muji3-small-notebook-set","小型空白記事本（5冊）","accessory",["muji"],
       ["pocket notebook","blank","5-pack"],["off-white","natural paper"],
       500,"A6 x5","5-pack A6 blank pocket notebooks, recycled paper, MUJI everyday carry stationery"),
    tb("muji3-hinoki-soap","扁柏香皂（3入）","accessory",["muji","japanese"],
       ["hinoki soap","cedar","natural"],["pale green","natural"],
       900,"Set of 3, 100g each","natural hinoki cypress wood-scented soap bars set of 3, MUJI or Japanese bathroom"),
    tb("muji3-wire-basket-white","白色鐵絲收納籃（大）","storage",["muji"],
       ["wire basket","large","white"],["white wire"],
       1200,"W35xD25xH20","large white wire mesh open storage basket, MUJI kitchen pantry or shelving"),
    tb("muji3-bamboo-towel-rack","竹製洗手間掛架（帶圈）","storage",["muji","nordic"],
       ["towel rack","bamboo","ring"],["natural bamboo"],
       1800,"W60xH40","natural bamboo wall-mounted bathroom towel rack with ring holder, MUJI eco bathroom"),
]

def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    print(f"Current: {len(existing)}")
    existing_names = {item["name_zh"] for item in existing}
    new_items = [item for item in BATCH6 if item["name_zh"] not in existing_names]
    print(f"Adding: {len(new_items)}")
    merged = existing + new_items
    print(f"Total: {len(merged)}")
    style_count = {}
    for item in merged:
        s = item.get("style_tags", ["unknown"])[0]
        style_count[s] = style_count.get(s, 0) + 1
    for s, c in sorted(style_count.items()):
        print(f"  {s:15s}: {c}")
    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print("Done.")

if __name__ == "__main__":
    main()
