"""
furniture_catalog 擴充包
在 generate_catalog.py 基礎上補充每個風格更多品項
目標：每種風格 50+ 件，共 450+ 件
執行：python catalog_extended.py  → 合併寫入 furniture_catalog.json
"""
import json
import os

def tb(id_, name_zh, cat, styles, keywords, colors, price, dims, flux):
    return {"id": f"tb-{id_}", "name_zh": name_zh, "brand": "淘寶精選",
            "category": cat, "style_tags": styles, "keywords": keywords,
            "colors": colors, "price_twd": price, "image_url": "",
            "purchase_url": f"https://s.taobao.com/search?q={name_zh[:20].replace(' ','+')}",
            "dimensions": dims, "flux_descriptor": flux}

def ik(id_, name_zh, cat, styles, keywords, colors, price, dims, flux):
    img = f"https://www.ikea.com/tw/zh/images/products/{id_}__s5.jpg"
    code = id_.split("-")[0].upper()
    url = f"https://www.ikea.com/tw/zh/search/?q={code}"
    return {"id": f"ikea-{id_}", "name_zh": name_zh, "brand": "IKEA",
            "category": cat, "style_tags": styles, "keywords": keywords,
            "colors": colors, "price_twd": price, "image_url": img,
            "purchase_url": url, "dimensions": dims, "flux_descriptor": flux}

EXTRA = [

# ══════════════════════════════════════════════════════════
# MODERN 現代簡約 — 補充 30 件
# ══════════════════════════════════════════════════════════
ik("vimle-sofa-grey","VIMLE L型沙發（灰色）","sofa",["modern"],
   ["sectional","L-shape sofa","modular sofa"],["grey","medium grey"],
   28900,"W252xD164xH83","grey modular L-shape sofa, broad arms, contemporary modern"),
ik("ektorp-sofa-white","EKTORP 三人沙發（白）","sofa",["modern","muji"],
   ["white sofa","classic sofa","removable cover"],["white","off-white"],
   16900,"W218xD88xH88","white 3-seater sofa, removable cover, clean modern classic"),
ik("kivik-sofa-beige","KIVIK 三人沙發（米色）","sofa",["modern","nordic"],
   ["3-seater","wide sofa","deep seat"],["beige","light grey"],
   19900,"W228xD83xH83","wide deep-seat sofa, relaxed modern living"),
ik("finnala-sofa","FINNALA 三人沙發（深灰）","sofa",["modern"],
   ["modern sofa","deep seat","dark sofa"],["dark grey","anthracite"],
   21900,"W221xD92xH84","modern deep-seat sofa, clean lines, dark grey upholstery"),
ik("ekedalen-dining","EKEDALEN 延伸餐桌","table",["modern","nordic"],
   ["extendable dining table","white table","oak table"],["white","oak"],
   9990,"W80/120xD70xH75","extendable dining table, seats 4-6, modern Scandinavian"),
ik("stornäs-table","STORNÄS 餐桌（仿古棕）","table",["modern","industrial"],
   ["dark dining table","solid wood","rustic modern"],["antique stain","dark brown"],
   12900,"W201xD78xH74","solid birch dark dining table, seats 6-8, modern rustic"),
ik("brimnes-bed-white","BRIMNES 床架含床頭收納（白）","bed",["modern","muji"],
   ["storage bed","headboard storage","white bed"],["white"],
   14900,"W160xD200","white bed frame with headboard shelving, modern functional"),
ik("malm-bed-oak","MALM 低床架（橡木貼皮）","bed",["modern","muji"],
   ["low bed frame","oak veneer","platform bed"],["oak veneer"],
   7990,"W160xD200","low-profile oak veneer bed frame, minimalist modern"),
ik("pello-chair","PELLO 搖椅（米白）","chair",["modern","nordic"],
   ["rocking chair","armchair","lounge chair"],["off-white","beige"],
   3990,"W73xD80xH100","padded rocking armchair, off-white, relaxed modern lounging"),
ik("nockeby-sofa","NOCKEBY 三人沙發（米灰）","sofa",["modern"],
   ["beige sofa","classic sofa","linen sofa"],["beige grey","sand"],
   19900,"W225xD98xH86","classic 3-seater sofa, sand beige, timeless modern"),
tb("mod-console-table","極簡玄關長台（白橡木+黑腳）","table",["modern"],
   ["console table","entryway table","hallway table"],["white oak","matte black"],
   6800,"W120xD35xH80","slim console table, white oak top, black metal legs, modern entry"),
tb("mod-bar-cart","黑框吧台推車（玻璃層板）","storage",["modern"],
   ["bar cart","drinks trolley","glass shelf cart"],["matte black","clear glass"],
   4500,"W60xD40xH90","black metal bar cart, tempered glass shelves, modern entertaining"),
tb("mod-accent-chair","冰淇淋椅（弧形絨布）","chair",["modern"],
   ["accent chair","curved chair","velvet chair"],["dusty pink","sage green","dove grey"],
   8800,"W70xD75xH80","curved velvet accent lounge chair, tapered legs, modern soft"),
tb("mod-dining-set","白橡木4人餐桌椅組","table",["modern","nordic"],
   ["dining set","table and chairs","4-person dining"],["white oak","beige"],
   28000,"W140xD80xH75+chairs","solid white oak dining table with 4 linen chairs set"),
tb("mod-pendant-dining","黑色圓形餐桌吊燈（大）","lighting",["modern"],
   ["dining pendant","circle pendant","bold pendant"],["matte black"],
   6500,"Dia50","large matte black circular pendant, over dining table, modern drama"),
tb("mod-tv-unit-floating","懸浮木質電視牆","storage",["modern"],
   ["floating TV wall","media wall","built-in TV"],["warm white oak","white"],
   35000,"W300xH120","floor-to-ceiling floating media wall unit, oak panels, modern built-in"),
tb("mod-geometric-rug","幾何圖案地毯（灰白）","rug",["modern"],
   ["geometric rug","abstract rug","grey rug"],["grey","white","charcoal"],
   7200,"200x290","low-pile geometric pattern rug, grey-white, modern living room"),
tb("mod-kitchen-island","移動式廚房島台（白+木面）","storage",["modern"],
   ["kitchen island","portable island","butcher block"],["white","birch top"],
   9800,"W120xD60xH90","mobile kitchen island, white cabinet, birch butcher block top"),
tb("mod-wall-art-set","現代抽象掛畫三聯組","accessory",["modern"],
   ["wall art","abstract print","gallery wall"],["black","white","warm grey"],
   3200,"40x60 each","minimalist abstract art print set of 3, modern gallery wall"),
tb("mod-round-mirror-lg","大圓形無框掛鏡（Dia80）","mirror",["modern"],
   ["frameless mirror","round mirror","large mirror"],["clear glass"],
   4800,"Dia80","frameless large round wall mirror, clean modern edge"),
tb("mod-oak-bookshelf","白橡木高書架（開放式）","shelving",["modern"],
   ["open bookcase","oak bookcase","tall shelf"],["white oak"],
   8500,"W80xD30xH200","solid oak tall open bookcase, adjustable shelves, modern library"),
tb("mod-plant-stand-set","黑色細腳植物架組（3件）","plant",["modern"],
   ["plant stand","planter stand","indoor garden"],["matte black"],
   3600,"various heights","matte black steel tiered plant stands, modern indoor garden"),
tb("mod-velvet-curtain","深灰絨布窗簾（全遮光）","curtain",["modern"],
   ["velvet curtain","blackout","dark curtain"],["charcoal","dark grey","navy"],
   6800,"W250xH270","heavyweight velvet blackout curtain, charcoal, modern bedroom"),
tb("mod-scandi-clock","北歐風大字體掛鐘（木+金）","accessory",["modern","nordic"],
   ["wall clock","Scandinavian clock","wood clock"],["natural wood","gold"],
   2200,"Dia40","large face Scandinavian wall clock, natural wood frame, gold hands"),
tb("mod-desk-lamp","可調色溫LED桌燈（USB充電）","lighting",["modern","muji"],
   ["LED desk lamp","adjustable lamp","smart lamp"],["white","matte black"],
   1800,"H45","touch-control LED desk lamp, CCT adjustable, USB-C, modern workspace"),
tb("mod-kitchen-bar-stool","白色簡約吧椅（腳踏環）","chair",["modern"],
   ["bar stool","counter stool","kitchen stool"],["white","light grey"],
   3200,"H65-75","adjustable white bar stool with footrest, modern kitchen"),
tb("mod-wardrobe-slide","拉門白色衣櫃（240x200）","storage",["modern","muji"],
   ["sliding wardrobe","white closet","bedroom storage"],["white","mirror door"],
   28000,"W240xD60xH200","white sliding door wardrobe, optional mirror door, modern bedroom"),
tb("mod-sofa-table","沙發後側長台（金屬+木）","table",["modern"],
   ["sofa table","behind sofa","long console"],["oak","black metal"],
   5500,"W160xD30xH75","slim sofa-back console, oak top, black metal legs"),
tb("mod-linen-bedding","棉麻四件式寢具組（米白）","accessory",["modern","muji","nordic"],
   ["bedding set","linen bedding","duvet cover"],["off-white","light grey","sage"],
   3800,"180x210","stonewashed cotton-linen duvet cover set, minimalist bedroom"),
tb("mod-bathroom-shelf","浴室黑鐵壁掛置物架","storage",["modern","industrial"],
   ["bathroom shelf","black shelf","wall shelf"],["matte black"],
   1800,"W60xD15","matte black iron bathroom wall shelf, 2-tier, modern"),

# ══════════════════════════════════════════════════════════
# JAPANESE 日式侘寂 — 補充 30 件
# ══════════════════════════════════════════════════════════
tb("jp-noren-curtain","日式暖簾門簾（麻布）","curtain",["japanese","muji"],
   ["noren curtain","Japanese door curtain","fabric divider"],["natural linen","indigo"],
   1600,"W85xH150","linen noren door curtain, Japanese kanji or solid, wabi-sabi divider"),
tb("jp-ceramic-dinnerware","手作陶器餐具組（6件）","accessory",["japanese"],
   ["ceramic dishes","handmade pottery","wabi-sabi tableware"],["matte clay","ash glaze","celadon"],
   4800,"various","hand-thrown ceramic dinnerware set, irregular glaze, Japanese craftsmanship"),
tb("jp-bonsai-stand","原木盆栽展示台","plant",["japanese"],
   ["bonsai stand","plant display","wooden shelf"],["natural cedar","dark walnut"],
   2800,"W60xD20xH30","solid wood bonsai display shelf, low asymmetric, Japanese garden"),
tb("jp-incense-set","線香香爐套組（陶土）","accessory",["japanese"],
   ["incense holder","ceramic burner","zen accessory"],["matte clay","dark grey"],
   1200,"Dia10xH5","ceramic incense holder set, Japanese Zen ritual, earthy tone"),
tb("jp-wood-soap-dish","原木皂碟（柏木）","accessory",["japanese","muji"],
   ["wood soap dish","cypress tray","bathroom decor"],["natural cypress"],
   480,"W12xD8","solid hinoki cypress soap dish, natural wood scent, Japanese bath"),
tb("jp-shoji-lamp","和紙方形桌燈（原木框）","lighting",["japanese","muji"],
   ["shoji lamp","paper table lamp","Japanese lamp"],["natural wood","cream white"],
   2600,"W20xD20xH30","square shoji table lamp, washi paper panels, natural wood frame"),
tb("jp-zazen-mat","禪坐冥想厚坐墊（亞麻）","chair",["japanese"],
   ["meditation cushion","zafu","zen cushion"],["dark navy","charcoal","natural linen"],
   2800,"Dia35xH15","round filled zafu meditation cushion, linen cover, Japanese practice"),
tb("jp-iron-teapot","南部鐵器茶壺（小）","accessory",["japanese"],
   ["iron teapot","tetsubin","Japanese tea"],["matte black iron"],
   3500,"0.3L","cast iron mini teapot, traditional Nanbu ironware, Japanese tea ceremony"),
tb("jp-linen-bedding","亞麻水洗寢具組（煙灰）","accessory",["japanese","muji"],
   ["linen bedding","washed linen","duvet cover"],["smoke grey","warm white","dusty sage"],
   5200,"180x210","enzyme-washed linen duvet set, soft relaxed texture, Japanese minimal"),
tb("jp-wooden-hanger","原木衣架組（10入）","accessory",["japanese","muji"],
   ["wood hanger","natural hanger","wardrobe accessory"],["natural beech"],
   1200,"43cm","solid beech wood clothes hangers, slim non-slip, Japanese functional"),
tb("jp-floor-lamp-washi","和紙圓柱落地燈","lighting",["japanese"],
   ["washi floor lamp","cylindrical lamp","paper lamp"],["cream","warm white"],
   3800,"W30xH150","washi paper cylindrical floor lamp, warm 3000K, Japanese atmosphere"),
tb("jp-bamboo-blind","竹捲簾（遮光50%）","curtain",["japanese","muji"],
   ["bamboo blind","roll shade","window covering"],["natural bamboo","dark walnut stain"],
   2200,"W120xH180 each","50% light filter bamboo roll-up shade, Japanese window treatment"),
tb("jp-sliding-door","木框推拉移門（霧面玻璃）","accessory",["japanese"],
   ["sliding door","room divider","Japanese door"],["white oak","frosted glass"],
   18000,"W80xH200per panel","white oak frame sliding door, frosted glass panel, Japanese space division"),
tb("jp-tatami-platform","仿榻榻米臥榻平台（帶抽屜）","bed",["japanese"],
   ["tatami platform","floor bed","Japanese storage platform"],["natural wood","tatami insert"],
   22000,"W200xD140xH20","low wooden platform with tatami insert and storage drawer, Japanese bedroom"),
tb("jp-ceramic-vase-lg","粗糙面大型陶花器","plant",["japanese"],
   ["ceramic vase","large planter","organic shape"],["rough clay","earth"],
   5800,"Dia25xH50","large hand-coiled ceramic vessel, rough texture, wabi-sabi interior plant"),
tb("jp-indoor-plant-set","室內觀葉植物組（盆+架）","plant",["japanese"],
   ["indoor plant","pothos","fern","spider plant"],["green","various"],
   3200,"various","indoor foliage plant set with clay pots, Japanese green corner"),
tb("jp-stone-bath-mat","矽藻土石質吸水地墊","accessory",["japanese","muji"],
   ["diatomite mat","stone bath mat","fast dry mat"],["natural grey","cream"],
   1800,"W40xD60","diatomite stone bath mat, fast-drying, Japanese bathroom minimalism"),
tb("jp-wood-magazine","原木木質雜誌架","storage",["japanese","muji"],
   ["magazine holder","book storage","solid wood"],["walnut","oak","ash"],
   3200,"W35xD20xH50","solid wood floor magazine rack, angled design, Japanese minimal"),
tb("jp-hanging-scroll","書法掛軸（禪意字）","accessory",["japanese"],
   ["hanging scroll","kakejiku","zen art"],["natural paper","black ink"],
   2800,"W35xH120","handwritten Zen calligraphy hanging scroll, traditional Japanese kakejiku"),
tb("jp-linen-apron","麻布無袖圍裙（廚房/工坊）","accessory",["japanese","muji"],
   ["linen apron","work apron","Japanese kitchen"],["natural linen","dark navy"],
   1400,"adjustable","linen cross-back apron, natural or navy, Japanese kitchen aesthetic"),
tb("jp-timber-tv-board","深木色地板電視矮板","storage",["japanese"],
   ["low TV board","floor cabinet","Japanese media"],["dark walnut","teak"],
   12000,"W180xD40xH30","ultra-low solid dark wood TV board, floor-level Japanese living"),
tb("jp-natural-clock","原木無數字靜音掛鐘","accessory",["japanese","muji"],
   ["silent clock","wood clock","minimalist clock"],["natural oak","white face"],
   1600,"Dia30","solid oak silent sweep clock, no numbers, Japanese minimal"),
tb("jp-rush-mat","藺草編織地毯（淡綠）","rug",["japanese"],
   ["rush mat","sea grass rug","natural mat"],["pale green","natural"],
   3800,"160x240","woven sea rush rug, soft pale green tone, natural Japanese interior"),
tb("jp-rope-basket","繩編收納籃（大）","storage",["japanese","muji","boho"],
   ["rope basket","cotton basket","storage"],["natural white","natural cotton"],
   2400,"Dia50xH40","chunky cotton rope woven basket, Japanese-minimal storage"),
tb("jp-tatami-storage","榻榻米收納盒蓋組","storage",["japanese"],
   ["tatami box","floor storage","Japanese chest"],["natural rush","wood edge"],
   3600,"W60xD40xH20","rush grass lidded storage chest, low profile, Japanese tatami room"),
tb("jp-shou-sugi-shelf","燒杉木壁掛層板","shelving",["japanese"],
   ["charred wood shelf","shou sugi ban","dark wood shelf"],["charred black","natural wood grain"],
   4200,"W80xD22","shou sugi ban charred cedar wall shelf, Japanese fire treatment"),
tb("jp-paper-lantern","和紙燈籠吊燈（圓形）","lighting",["japanese"],
   ["paper lantern","akari","Japanese pendant"],["cream white","natural paper"],
   1800,"Dia40","traditional washi paper round lantern, Japanese warm ambient"),
tb("jp-bamboo-partition","竹製隔斷屏風（四片）","accessory",["japanese"],
   ["bamboo screen","room divider","natural partition"],["natural bamboo"],
   12000,"W160xH180 total","4-panel natural bamboo room divider screen, Japanese interior"),
tb("jp-stone-coaster","天然石杯墊組（4入）","accessory",["japanese"],
   ["stone coaster","marble coaster","table accessory"],["slate","granite","marble"],
   980,"Dia10","natural stone coaster set of 4, irregular shape, Japanese wabi-sabi"),
tb("jp-hinoki-stool","檜木沐浴椅凳","chair",["japanese","muji"],
   ["hinoki stool","bath stool","cedar bench"],["natural hinoki"],
   3200,"W35xD25xH45","solid hinoki cypress bath stool, natural grain, Japanese spa"),

# ══════════════════════════════════════════════════════════
# LUXURY 輕奢現代 — 補充 30 件
# ══════════════════════════════════════════════════════════
tb("lux-wine-rack","壁掛式紅酒展示架（黃銅）","storage",["luxury"],
   ["wine rack","wall wine holder","brass rack"],["brushed brass","gold"],
   8800,"W80xD15","wall-mounted brass wine rack, 12-bottle display, luxury dining"),
tb("lux-crystal-table-lamp","水晶柱桌燈（金底座）","lighting",["luxury"],
   ["crystal table lamp","gold base lamp","luxury bedside"],["clear crystal","gold","brass"],
   6800,"H55","faceted crystal column table lamp, brushed gold base, luxury nightstand"),
tb("lux-marble-console","白大理石玄關台（細金腳）","table",["luxury","art-deco"],
   ["marble console","entry table","luxury hallway"],["white marble","gold"],
   18000,"W120xD40xH82","Carrara marble top console, slim gold metal legs, luxury entry"),
tb("lux-round-velvet-bed","圓弧絨布床架（奶茶色）","bed",["luxury"],
   ["curved bed","velvet bed frame","luxury bedroom"],["latte","champagne","dusty rose"],
   36000,"W180xD200","curved sculptural velvet upholstered bed frame, luxury bedroom statement"),
tb("lux-art-deco-lamp","藝術雕塑落地燈（白雲石）","lighting",["luxury"],
   ["sculpture lamp","onyx lamp","luxury floor lamp"],["white onyx","brushed gold"],
   15000,"H170","white onyx stone floor lamp, gold metal structure, luxury sculptural"),
tb("lux-sheepskin-rug","純冰島羊毛地毯（大）","rug",["luxury","nordic"],
   ["sheepskin rug","luxury rug","natural fiber"],["ivory","champagne","platinum"],
   18000,"200x290","Icelandic wool luxury area rug, ultra-dense pile, luxury bedroom"),
tb("lux-velvet-bench","絨布床尾凳（黃銅腳）","chair",["luxury"],
   ["bed bench","velvet ottoman","bedroom bench"],["champagne","dusty rose","navy"],
   9500,"W120xD40xH48","tufted velvet bedroom bench, brushed brass legs, luxury bedroom"),
tb("lux-marble-shower-mat","大理石紋浴室地墊","accessory",["luxury"],
   ["marble bath mat","luxury bathroom","stone mat"],["white marble pattern"],
   2800,"W60xD90","marble-print high-pile bath rug, luxury spa bathroom"),
tb("lux-designer-clock","設計師掛鐘（金色指針+大理石面）","accessory",["luxury"],
   ["designer clock","marble wall clock","luxury clock"],["white marble face","gold"],
   5500,"Dia40","white marble face wall clock, brushed gold hands, luxury decor"),
tb("lux-bar-unit","輕奢酒吧展示酒架（黑胡桃+金）","storage",["luxury"],
   ["bar unit","liquor cabinet","wine display"],["dark walnut","brushed brass"],
   42000,"W120xD45xH200","floor-to-ceiling walnut bar unit, brass rail, glass display, luxury"),
tb("lux-pendant-cluster","玻璃球多頭吊燈組","lighting",["luxury"],
   ["glass ball pendant","cluster light","statement ceiling"],["clear glass","brass","gold"],
   22000,"cluster dia80","multi-arm glass sphere pendant cluster, brass armature, luxury ceiling"),
tb("lux-throw-pillow-set","奢華刺繡抱枕組（3件）","accessory",["luxury"],
   ["luxury pillow","embroidered pillow","designer cushion"],["champagne","gold thread","ivory"],
   3800,"45x45","hand-embroidered luxury throw pillow set, gold thread detail"),
tb("lux-lacquer-tray","漆器展示托盤（黑+金邊）","accessory",["luxury"],
   ["lacquer tray","luxury tray","coffee table display"],["gloss black","gold rim"],
   3200,"W45xD30","lacquered display tray, matte black with gold edge, luxury table styling"),
tb("lux-fireplace-electric","嵌壁式電子壁爐（水霧）","accessory",["luxury"],
   ["electric fireplace","water vapor","luxury feature"],["black","chrome"],
   28000,"W90xH50","recessed water mist electric fireplace, realistic flame effect, luxury"),
tb("lux-marble-bookends","白大理石書擋（一對）","accessory",["luxury"],
   ["marble bookend","luxury desk","book organizer"],["white marble","brass"],
   2200,"W15xH18 each","white Carrara marble bookends, brass base strip, luxury study"),
tb("lux-chaise-lounge","絨布貴妃椅（勃艮第）","chair",["luxury"],
   ["chaise lounge","fainting couch","luxury chair"],["burgundy","emerald","champagne"],
   22000,"W165xD70xH80","curved velvet chaise lounge, button tufted, luxury bedroom"),
tb("lux-crystal-vase","大型水晶玻璃花瓶","accessory",["luxury"],
   ["crystal vase","luxury vase","glass vase"],["crystal clear","smoke grey"],
   4500,"H60","tall crystal glass vase, heavy base, luxury floral display"),
tb("lux-wall-panel","布藝軟包牆板（菱格紋）","accessory",["luxury"],
   ["wall panel","upholstered panel","bedroom wall"],["champagne","dusty rose","grey"],
   18000,"per panel W60xH60","diamond-quilted upholstered wall panel, luxury bedroom feature wall"),
tb("lux-gold-bath-set","黃金五金衛浴套組","accessory",["luxury"],
   ["gold faucet","luxury bathroom","brushed gold fixtures"],["brushed gold","rose gold"],
   12000,"set","brushed gold bathroom hardware set, faucet + towel ring + hooks"),
tb("lux-ottoman-large","超大方形絨布腳凳（附托盤）","chair",["luxury"],
   ["large ottoman","coffee table ottoman","velvet footstool"],["light taupe","champagne","charcoal"],
   15000,"W100xD100xH42","oversized square velvet ottoman with serving tray, luxury multifunctional"),
tb("lux-silk-curtain","蠶絲混紡窗簾（香檳金）","curtain",["luxury"],
   ["silk curtain","luxury drape","sheer shimmer"],["champagne gold","ivory","blush"],
   12000,"W250xH280","silk-blend luminous curtain, champagne shimmer, luxury bedroom window"),
tb("lux-marble-side-round","圓形大理石疊石邊几（2件組）","table",["luxury"],
   ["marble side table","stacking table","stone coffee"],["white marble","travertine"],
   16000,"Dia35+Dia25","stacking round marble side tables, two heights, luxury living"),
tb("lux-art-canvas","抽象油畫原作（大型）","accessory",["luxury"],
   ["original painting","canvas art","abstract painting"],["gold","navy","cream"],
   28000,"W100xH120","original abstract oil painting on canvas, gallery-worthy luxury wall art"),
tb("lux-hanging-chair","白色半圓懸吊椅（羊毛坐墊）","chair",["luxury","boho"],
   ["hanging chair","swing chair","pod chair"],["white","ivory","gold frame"],
   22000,"Dia90","white rattan half-moon hanging pod chair, shearling cushion, luxury boho"),
tb("lux-plant-marble-pot","大理石紋高腳花器","plant",["luxury"],
   ["marble planter","pedestal pot","luxury plant"],["white marble","brushed gold rim"],
   5800,"Dia20xH80 total","marble-finish tall pedestal plant stand + pot, luxury interior"),
tb("lux-bathroom-shelf","黃銅壁掛浴室置物架（3層）","storage",["luxury"],
   ["brass bathroom shelf","gold shelf","luxury bathroom"],["brushed brass","gold"],
   6800,"W40xH90","brushed brass 3-tier bathroom ladder shelf, luxury spa"),
tb("lux-round-dining","圓形白大理石餐桌（金底座）","table",["luxury"],
   ["round dining","marble table","gold base"],["white marble","brushed gold"],
   38000,"Dia130","round white marble dining table, brushed gold pedestal, luxury dining"),
tb("lux-velvet-dining-bench","天鵝絨餐椅長凳","chair",["luxury"],
   ["dining bench","velvet bench","upholstered bench"],["dusty mauve","deep teal"],
   12000,"W160xD40xH48","velvet upholstered dining bench, luxury dining room seating"),
tb("lux-neon-art","霓虹燈管藝術裝置","accessory",["luxury","art-deco"],
   ["neon sign","LED neon art","luxury decor"],["warm white","gold","rose"],
   8800,"custom","custom neon art installation, warm LED tube, luxury statement wall"),
tb("lux-crystal-handle","水晶門把手套組","accessory",["luxury"],
   ["crystal door handle","luxury hardware","door knob"],["clear crystal","gold"],
   3200,"set of 2","faceted crystal door handles with brushed gold base, luxury interiors"),

# ══════════════════════════════════════════════════════════
# NORDIC 北歐 — 補充 30 件
# ══════════════════════════════════════════════════════════
ik("äpplarö-bench","ÄPPLARÖ 戶外長凳（松木）","chair",["nordic"],
   ["outdoor bench","pine bench","garden bench"],["pine","outdoor"],
   3990,"W116xD44xH74","solid pine outdoor bench, Scandinavian garden minimal"),
ik("boastad-bookcase","BOASTAD 書架（橡木）","shelving",["nordic","modern"],
   ["oak bookcase","wall bookcase","display shelf"],["oak veneer"],
   5990,"W80xD32xH158","oak veneer bookcase, Scandinavian minimal display"),
ik("svelvik-mirror","SVELVIK 全身鏡（白）","mirror",["nordic","muji"],
   ["full length mirror","leaning mirror","standing mirror"],["white"],
   1990,"W50xH160","white full-length leaning mirror, clean Scandinavian frame"),
ik("tillreda-cart","TILLREDA 廚房推車（深藍）","storage",["nordic","muji"],
   ["kitchen cart","mobile cart","blue trolley"],["dark blue","black"],
   2490,"W50xD35xH86","portable kitchen cart, dark blue, Scandinavian functional kitchen"),
ik("mittzon-desk","MITTZON 書桌（白橡木/黑）","table",["nordic","modern"],
   ["work desk","office desk","standing desk"],["white stained oak","black"],
   13990,"W120xD60xH75-120","height-adjustable work desk, white oak surface, Scandinavian workspace"),
tb("no-pendant-rattan-lg","藤編大圓燈罩吊燈（自然色）","lighting",["nordic","boho"],
   ["rattan pendant","natural pendant","oversized shade"],["natural rattan"],
   4200,"Dia60","oversized natural rattan dome pendant, Scandinavian boho bedroom"),
tb("no-pine-dining-set","松木6人餐桌+藤椅組","table",["nordic"],
   ["dining set","pine table","rattan chairs"],["pine","natural rattan"],
   32000,"W180xD90xH75","solid pine dining table with 6 rattan chairs, Scandinavian dining"),
tb("no-cotton-rope-rug","棉繩編織地毯（Dia140圓形）","rug",["nordic","boho"],
   ["cotton rope rug","hand-woven rug","round rug"],["cream","white","sage"],
   5500,"Dia140","hand-woven cotton rope round rug, Scandinavian hygge floor"),
tb("no-rocking-chair","實木搖椅（棉坐墊）","chair",["nordic"],
   ["rocking chair","wooden rocker","hygge chair"],["natural oak","linen cushion"],
   8800,"W65xD85xH105","solid oak adult rocking chair, removable linen cushion, hygge"),
tb("no-loft-bed","北歐風高架床（含書桌）","bed",["nordic"],
   ["loft bed","cabin bed","study bed"],["pine","white"],
   22000,"W90xD200+desk","solid pine loft bed with integrated study desk, Scandinavian kids"),
tb("no-wall-clock-minimal","極簡北歐掛鐘（大）","accessory",["nordic","muji"],
   ["minimalist clock","wall clock","Scandinavian clock"],["white","pale wood"],
   1800,"Dia40","clean dial wall clock, pale wood frame, no clutter, Scandinavian minimal"),
tb("no-storage-ladder","竹製梯式置物架（5格）","storage",["nordic","japanese"],
   ["ladder shelf","leaning bookcase","bamboo storage"],["natural bamboo","white"],
   3800,"W60xD38xH180","5-tier bamboo ladder shelf, leans against wall, Scandinavian minimal"),
tb("no-kids-toy-bin","布藝可折疊玩具收納箱（4個）","storage",["nordic"],
   ["toy storage","fabric bin","kids storage"],["white","grey","sage","dusty pink"],
   1800,"W30xD30xH30 each","collapsible fabric storage cube set, Scandinavian kids room"),
tb("no-throw-wool","美麗諾羊毛毯子（人字紋）","accessory",["nordic"],
   ["merino throw","wool blanket","herringbone"],["cream","charcoal","pale blue"],
   5800,"130x180","100% merino wool herringbone throw, ultra-soft hygge blanket"),
tb("no-pegboard","松木插孔收納牆板（附配件）","storage",["nordic","muji"],
   ["pegboard","wall organizer","hook board"],["natural pine","white"],
   2800,"W60xH60 + accessories","natural pine pegboard with 10 accessories, Scandinavian workspace"),
tb("no-ceramic-mug-set","陶瓷馬克杯組（4件，啞光）","accessory",["nordic","japanese"],
   ["ceramic mug","matte mug","Scandinavian cup"],["matte white","sage","dusty pink","charcoal"],
   2400,"Dia8xH10 each","set of 4 matte ceramic mugs, Scandinavian café aesthetic"),
tb("no-herb-garden","木質窗台香草種植盒","plant",["nordic"],
   ["herb garden","indoor planter","windowsill garden"],["pine","natural"],
   1600,"W40xD12xH8 x3","pine wood indoor herb garden planter set of 3, Scandinavian kitchen"),
tb("no-gallery-set","北歐黑框相框組（9件）","accessory",["nordic","modern"],
   ["photo frame set","gallery wall","black frame"],["matte black"],
   3200,"various 13x18 to 30x40","matte black photo frame set of 9, Scandinavian gallery wall"),
tb("no-acrylic-lamp","亞克力半球桌燈（充電式）","lighting",["nordic","modern"],
   ["acrylic lamp","portable lamp","wireless lamp"],["frosted white","clear"],
   3600,"Dia18xH12","rechargeable frosted acrylic half-sphere table lamp, Scandinavian"),
tb("no-outdoor-rug","灰色戶外防水地毯","rug",["nordic"],
   ["outdoor rug","patio rug","waterproof mat"],["grey","blue grey"],
   5500,"200x290","grey flatweave outdoor rug, UV and water resistant, Scandinavian terrace"),
tb("no-wood-candle-holder","原木多孔蠟燭台","accessory",["nordic"],
   ["candle holder","wood candle","hygge candle"],["light oak","birch"],
   1600,"W30xD8xH5","natural wood multi-hole candle holder, hygge atmosphere"),
tb("no-cotton-pillow-set","北歐棉質抱枕套組（4件）","accessory",["nordic"],
   ["pillow cover","cushion set","Scandinavian textile"],["sage","dusty rose","off-white","light blue"],
   2200,"50x50 each","enzyme-washed cotton pillow cover set, Nordic color palette"),
tb("no-oak-side-table","橡木小圓邊几（可堆疊）","table",["nordic","modern"],
   ["side table","stacking table","oak round"],["light oak"],
   2800,"Dia45xH45","stackable solid oak round side table, Scandinavian clean"),
tb("no-wall-shelves-x3","白色浮動壁板層架（3片組）","shelving",["nordic","muji"],
   ["floating shelf","white shelf","wall display"],["white","pine"],
   1800,"W40xD12 each","set of 3 white floating wall shelves, minimal Scandinavian display"),
tb("no-reading-nook","靠窗閱讀角落坐墊套組","chair",["nordic"],
   ["window cushion","reading nook","bay window seat"],["sage","grey","dusty rose"],
   3800,"W120xD50 custom","custom windowsill reading cushion set, hygge corner nook"),
tb("no-soap-dispenser","陶瓷給皂機（北歐風）","accessory",["nordic","muji"],
   ["soap dispenser","bathroom accessory","ceramic pump"],["matte white","sage"],
   680,"H18","matte white or sage ceramic soap dispenser, Scandinavian bathroom"),
tb("no-plant-macrame","羊毛毯掛式植物吊網","plant",["nordic","boho"],
   ["plant hanger","macrame hanger","wall plant"],["natural cotton","cream"],
   1200,"H50","cotton macrame wall hanging plant holder, Scandinavian boho"),
tb("no-magazine-tray","竹製桌面分類托盤（3格）","storage",["nordic","muji"],
   ["desk tray","bamboo organizer","desk accessory"],["natural bamboo"],
   1400,"W36xD28xH6","natural bamboo 3-slot desk organizer tray, Scandinavian workspace"),
tb("no-stair-storage","樓梯轉角三角書架","shelving",["nordic"],
   ["stair shelf","corner bookcase","triangle shelf"],["pine","white"],
   6800,"variable","solid pine stair-step corner shelving, Scandinavian hallway storage"),
tb("no-velvet-cushion-lg","大方形絨布地墊坐墊","chair",["nordic","boho"],
   ["large floor cushion","velvet pouf","seating cushion"],["dusty rose","sage green","grey"],
   3800,"W70xD70xH15","oversized square velvet floor cushion, Scandinavian hygge seating"),

# ══════════════════════════════════════════════════════════
# INDUSTRIAL 工業風 — 補充 30 件
# ══════════════════════════════════════════════════════════
tb("ind-loft-bed","工業風黑管高架床（附鋼梯）","bed",["industrial"],
   ["loft bed","pipe bed","iron loft"],["matte black iron"],
   28000,"W120xD200+ladder","matte black iron pipe loft bed with steel ladder, industrial loft"),
tb("ind-vintage-map-globe","復古仿皮地球儀（桌擺）","accessory",["industrial"],
   ["globe decor","vintage globe","desk accessory"],["aged leather","antique"],
   2800,"Dia25xH35","vintage-finish faux leather globe, antique brass stand, industrial study"),
tb("ind-steel-desk","黑鋼工作書桌（含抽屜）","table",["industrial","modern"],
   ["steel desk","industrial desk","work table"],["matte black steel","reclaimed wood top"],
   16000,"W140xD70xH76","black steel frame desk, reclaimed wood top, 2 drawers, industrial"),
tb("ind-cage-pendant","工廠鳥籠形吊燈","lighting",["industrial"],
   ["cage pendant","industrial cage","factory lamp"],["antique black","rust"],
   2200,"Dia25","cage-frame industrial pendant, Edison compatible, antique black"),
tb("ind-metal-stool-set","工業風金屬圓凳（4件組）","chair",["industrial"],
   ["metal stool","round stool","industrial seating"],["black","rust patina"],
   8800,"H45/60/75 each","stackable metal round stool set of 4, various heights, industrial"),
tb("ind-pipe-desk-lamp","黑管鉚釘桌燈（夾式）","lighting",["industrial"],
   ["pipe lamp","clamp light","desk lamp"],["matte black","antique bronze"],
   1600,"H35 arm","pipe-joint articulated clamp desk lamp, industrial workshop"),
tb("ind-locker","工業風5格置物櫃（灰色）","storage",["industrial"],
   ["metal locker","school locker","industrial cabinet"],["grey","olive green","black"],
   12000,"W50xD35xH180","5-door metal storage locker, ventilation slots, industrial loft"),
tb("ind-corten-planter","耐候鋼花器（方形）","plant",["industrial"],
   ["corten planter","weathering steel","industrial garden"],["rust brown","corten"],
   4800,"W30xD30xH40","corten weathering steel square planter, natural rust patina, industrial"),
tb("ind-neon-sign","霓虹工業風招牌燈（定制）","lighting",["industrial"],
   ["neon sign","LED neon","bar sign"],["warm white","red","blue","yellow"],
   8800,"custom","custom LED neon sign, bar or workshop quote, industrial decor"),
tb("ind-barbell-bookend","啞鈴造型鐵鑄書擋","accessory",["industrial"],
   ["barbell bookend","iron decor","industrial accessory"],["cast iron","antique"],
   1400,"L20xH10","cast iron barbell-shape bookends, industrial gym-loft aesthetic"),
tb("ind-ceiling-fan-ind","工業風吊扇燈（5葉黑）","lighting",["industrial"],
   ["industrial ceiling fan","fan light","dark fan"],["matte black"],
   8800,"Dia130","matte black 5-blade industrial ceiling fan with light, factory loft"),
tb("ind-metal-shelving","角鐵沖孔板工業風貨架","shelving",["industrial"],
   ["industrial shelving","metal rack","warehouse shelf"],["black","galvanized"],
   8800,"W90xD40xH180","angle iron perforated panel shelving, industrial warehouse"),
tb("ind-mirror-round-ind","黑框圓鏡（裂縫金屬感）","mirror",["industrial"],
   ["black round mirror","industrial mirror","metal frame"],["matte black","aged iron"],
   3800,"Dia70","aged black iron round wall mirror, industrial bathroom or bedroom"),
tb("ind-sofa-leather","做舊真皮三人沙發（棕褐）","sofa",["industrial"],
   ["distressed leather sofa","3-seater leather","vintage sofa"],["cognac","dark brown","tan"],
   38000,"W220xD95xH85","genuine distressed leather 3-seater, rolled arms, industrial man cave"),
tb("ind-toolbox-storage","工具箱造型收納抽屜","storage",["industrial"],
   ["toolbox cabinet","vintage storage","industrial drawer"],["yellow","red","black"],
   8500,"W60xD35xH50","vintage toolbox-style 3-drawer storage unit, industrial workshop"),
tb("ind-steel-mirror","黑色矩形鋼框鏡","mirror",["industrial","modern"],
   ["black rectangle mirror","steel frame mirror","industrial mirror"],["matte black"],
   3200,"W60xH90","matte black steel tube frame rectangle mirror, industrial or modern"),
tb("ind-iron-wine-rack","鍛鐵壁掛紅酒架（12瓶）","storage",["industrial"],
   ["iron wine rack","wall wine holder","bottle rack"],["matte black iron"],
   4500,"W60xH60","wall-mounted black iron wine rack, 12 bottle capacity, industrial"),
tb("ind-cargo-sofa","貨車輪胎皮椅（玩味工業）","chair",["industrial"],
   ["tire chair","upcycle chair","industrial lounge"],["aged black rubber","cognac"],
   15000,"W80xD70xH75","upcycled tire-base leather armchair, industrial creative"),
tb("ind-raw-edge-table","圓形鋼腳原木板茶几","table",["industrial"],
   ["live edge coffee table","natural slab","steel legs"],["natural wood edge","black steel"],
   12000,"Dia90xH45","natural live-edge wood slab round coffee table, black steel rod legs"),
tb("ind-mesh-chair","工業風網椅（辦公/餐椅）","chair",["industrial","modern"],
   ["mesh chair","ergonomic chair","wire chair"],["black mesh","chrome"],
   5800,"W55xD60xH85","black steel mesh ergonomic chair, industrial modern workspace"),
tb("ind-pipe-shelf-bath","工業風浴室鐵管毛巾架","storage",["industrial"],
   ["pipe towel rack","bathroom industrial","iron rack"],["black pipe"],
   2200,"W60xH40","black iron pipe wall-mount bathroom towel rack, industrial style"),
tb("ind-street-lamp","復古路燈造型落地燈","lighting",["industrial"],
   ["street lamp","retro floor lamp","vintage lamp"],["antique black","bronze"],
   8800,"H165","antique-finish street lamp floor light, industrial loft statement"),
tb("ind-vintage-rug-dark","深色古著圖案地毯","rug",["industrial","boho"],
   ["vintage rug","dark rug","distressed rug"],["charcoal","rust","antique red"],
   9500,"200x290","distressed vintage-look rug, dark palette, industrial apartment"),
tb("ind-cage-bookshelf","金屬籠架式書架","shelving",["industrial"],
   ["cage shelf","wire bookcase","metal mesh bookcase"],["black","dark rust"],
   14000,"W100xD35xH180","open cage wire-frame bookcase, industrial statement piece"),
tb("ind-trunk-coffee","軍旅風金屬行李箱咖啡桌","table",["industrial","boho"],
   ["trunk table","military chest","storage coffee table"],["olive green","army green"],
   9500,"W80xD50xH45","military-style metal chest trunk coffee table, industrial army loft"),

# ══════════════════════════════════════════════════════════
# MEDITERRANEAN 地中海 — 補充 25 件
# ══════════════════════════════════════════════════════════
tb("med-hammock-stand","棉繩吊床+木架組","chair",["mediterranean","boho"],
   ["hammock","outdoor hanging","cotton hammock"],["natural cotton","blue white stripe"],
   8800,"W200xH130","cotton rope hammock with bamboo spreader bars and A-frame stand"),
tb("med-outdoor-table","戶外拼磚馬賽克圓桌","table",["mediterranean"],
   ["mosaic outdoor table","patio table","tile top"],["blue","white","turquoise"],
   12000,"Dia80xH72","hand-painted mosaic tile round outdoor table, Mediterranean patio"),
tb("med-lantern-cluster","鍛鐵燈籠組（3件）","lighting",["mediterranean"],
   ["lantern set","iron lantern","candle lantern"],["antique black","amber"],
   3800,"various sizes","wrought iron lantern set of 3, candle or LED, Mediterranean terrace"),
tb("med-coastal-art","海岸線藍白掛畫組（3聯）","accessory",["mediterranean"],
   ["coastal art","blue white print","Mediterranean decor"],["ocean blue","white"],
   3200,"30x40 each","Mediterranean coastal abstract print set of 3, blue and white"),
tb("med-blue-pot-tree","地中海藍色高筒花器（150cm）","plant",["mediterranean"],
   ["tall planter","blue ceramic","Mediterranean garden"],["cobalt blue","terracotta"],
   6800,"Dia35xH60","tall cobalt blue ceramic planter for indoor olive or citrus tree"),
tb("med-whitewash-bench","白洗實木廊道長椅","chair",["mediterranean"],
   ["outdoor bench","whitewash wood","Mediterranean seating"],["whitewash","driftwood"],
   8800,"W150xD45xH48","whitewashed solid wood garden bench, Mediterranean coastal outdoor"),
tb("med-seashell-lamp","貝殼串飾燈（暖光）","lighting",["mediterranean"],
   ["shell lamp","coastal light","beach decor"],["natural shell","warm white"],
   2800,"H40","natural seashell and driftwood table lamp, coastal Mediterranean"),
tb("med-olive-tree","仿真橄欖樹（室內裝飾）","plant",["mediterranean"],
   ["fake olive tree","artificial tree","indoor tree"],["natural green","grey-green"],
   8800,"H150","lifelike artificial olive tree, Mediterranean indoor statement plant"),
tb("med-blue-bench","深藍色軟墊戶外長椅","chair",["mediterranean"],
   ["outdoor bench","blue cushion","patio bench"],["deep sea blue","white frame"],
   12000,"W160xD55xH85","blue upholstered outdoor garden bench, white iron frame"),
tb("med-ceramic-sun","陶瓷太陽壁飾（橙黃）","accessory",["mediterranean"],
   ["sun decor","wall ceramic","Mediterranean art"],["terracotta","golden yellow"],
   3800,"Dia50","hand-painted ceramic sun wall medallion, Mediterranean outdoor decor"),
tb("med-wicker-chair-set","藤編餐椅4件組（白坐墊）","chair",["mediterranean","boho"],
   ["wicker dining chair","rattan chair set","natural chair"],["natural rattan","white cushion"],
   16000,"W55xD57xH85 each","natural rattan dining chair set of 4, white waterproof cushion"),
tb("med-bistro-table","法式鑄鐵圓形雙人咖啡桌","table",["mediterranean"],
   ["bistro table","cafe table","iron round table"],["matte black","white"],
   6800,"Dia60xH72","cast iron round bistro cafe table, French Mediterranean outdoor"),
tb("med-striped-towel","藍白條紋浴巾組","accessory",["mediterranean"],
   ["stripe towel","bath towel","coastal textile"],["Mediterranean blue","white"],
   1200,"70x140 each","blue and white stripe Turkish cotton towel, coastal bathroom"),
tb("med-terrace-lights","戶外藤球串燈（20m）","lighting",["mediterranean","boho"],
   ["globe string lights","patio lights","outdoor fairy"],["warm amber","rattan globe"],
   2800,"20m/20bulbs","rattan globe warm bulb string lights for terrace or balcony"),
tb("med-cement-rug","藍白幾何水泥花磚地毯","rug",["mediterranean"],
   ["cement tile rug","blue white geometric","encaustic pattern"],["cobalt blue","white"],
   8800,"160x230","vinyl or cotton flat-weave Mediterranean encaustic tile pattern rug"),
tb("med-drift-art","漂流木牆飾藝術品","accessory",["mediterranean"],
   ["driftwood art","coastal wall decor","wood sculpture"],["natural driftwood","grey white"],
   5500,"W80xH40","natural driftwood wall sculpture, coastal Mediterranean accent"),
tb("med-outdoor-sofa","白色藤框戶外沙發組（4件）","sofa",["mediterranean"],
   ["outdoor sofa set","wicker sofa","patio furniture"],["white rattan","grey cushion"],
   42000,"complete set","4-piece white rattan outdoor sofa set, Mediterranean terrace"),
tb("med-arch-window","仿白拱形牆框鏡","mirror",["mediterranean","boho"],
   ["arch mirror","window mirror","decorative arch"],["white plaster","natural wood"],
   9800,"W60xH120","arch-shaped white plaster-texture frame mirror, Mediterranean interior"),
tb("med-sea-glass-vase","海玻璃花瓶組（3件）","accessory",["mediterranean"],
   ["sea glass vase","coastal vase","aqua glass"],["sea green","aqua","cobalt"],
   2400,"various","frosted sea glass bud vase set of 3, coastal Mediterranean table"),
tb("med-rattan-lamp","藤球吊燈（大圓形）","lighting",["mediterranean","boho","nordic"],
   ["rattan ball pendant","natural shade","round pendant"],["natural rattan"],
   3800,"Dia50","oversized rattan ball pendant shade, warm filtered glow, coastal"),
tb("med-wicker-storage","藤編收納矮方桌（兼茶几）","table",["mediterranean","boho"],
   ["wicker coffee table","rattan storage","dual purpose"],["natural rattan","light brown"],
   8800,"W80xD80xH45","wicker rattan storage chest coffee table, Mediterranean living"),
tb("med-pendant-blue","深藍陶瓷燈罩吊燈","lighting",["mediterranean"],
   ["ceramic pendant","blue pendant","artisan light"],["cobalt blue","Mediterranean blue"],
   4200,"Dia20","cobalt blue hand-glazed ceramic bell pendant, Mediterranean kitchen"),
tb("med-cotton-rug","純棉藍白條編織地毯","rug",["mediterranean"],
   ["cotton rug","stripe rug","flat weave"],["blue","white","aqua"],
   4800,"160x230","handwoven cotton flat-weave stripe rug, Mediterranean coastal home"),
tb("med-arch-shelf","拱形白色壁掛展示架","shelving",["mediterranean","boho"],
   ["arch shelf","wall decor shelf","white display"],["white","cream"],
   3800,"W50xH60","arched white wall-mount display shelf, Mediterranean bohemian"),
tb("med-star-light","摩洛哥星形燈籠（金屬）","lighting",["mediterranean"],
   ["star lantern","Moroccan light","geometric lantern"],["antique gold","brass"],
   2800,"Dia25","geometric star-pattern metal lantern, Moroccan Mediterranean candlelight"),

# ══════════════════════════════════════════════════════════
# MUJI 無印風 — 補充 30 件
# ══════════════════════════════════════════════════════════
tb("muji-acrylic-boxes","壓克力透明收納盒組（6件）","storage",["muji"],
   ["acrylic box","clear organizer","desktop storage"],["clear transparent"],
   2400,"various","stackable clear acrylic desktop organizer set, Muji-style minimal"),
tb("muji-cotton-bedding","有機棉四件組寢具（米白）","accessory",["muji"],
   ["organic cotton bedding","duvet cover","natural bedding"],["off-white","natural","light grey"],
   4800,"180x210","100% organic cotton duvet cover set, stonewash finish, Muji natural"),
tb("muji-wall-hooks","無痕壁掛式木質掛勾（5入）","storage",["muji","nordic"],
   ["wall hook","wood hook","no-nail hook"],["natural beech","white"],
   980,"W6 each","adhesive natural wood wall hooks, no-nail Muji functional"),
tb("muji-memo-board","軟木公告板（木框）","storage",["muji","nordic"],
   ["cork board","memo board","notice board"],["natural cork","pine frame"],
   1200,"W60xH40","natural cork bulletin board, pine frame, Muji workspace"),
tb("muji-acrylic-display","壓克力文具收納格盒","storage",["muji"],
   ["desk organizer","pen holder","acrylic tray"],["clear","frosted"],
   1600,"W25xD15xH12","clear acrylic desk organizer with dividers, Muji study table"),
tb("muji-portable-fan","手持充電小風扇（白）","accessory",["muji"],
   ["portable fan","USB fan","quiet fan"],["white","grey"],
   680,"W12xH8","quiet handheld rechargeable fan, clean minimal, Muji summer"),
tb("muji-scent-candle","植物性大豆蠟蠟燭（薰衣草）","accessory",["muji","nordic"],
   ["soy candle","scented candle","aromatherapy"],["cream white"],
   880,"Dia7xH8","natural soy wax scented candle, lavender or cedarwood, Muji calm"),
tb("muji-towel-set","有機棉毛巾組（浴+手+臉）","accessory",["muji"],
   ["cotton towel","organic towel","bathroom set"],["off-white","light grey","natural"],
   2200,"set of 3","natural undyed organic cotton towel set, Muji bathroom simplicity"),
tb("muji-slim-wardrobe","窄身PP收納衣物格架","storage",["muji"],
   ["drawer unit","PP drawer","closet organizer"],["white","translucent"],
   3800,"W26xD37xH88","polypropylene slim drawer unit, stackable, Muji wardrobe interior"),
tb("muji-floor-mirror-wood","原木斜靠全身鏡","mirror",["muji","nordic","japanese"],
   ["floor mirror","wood frame mirror","leaning mirror"],["natural oak","beech"],
   4800,"W50xH160","natural wood frame full-length leaning mirror, Muji bedroom"),
tb("muji-linen-pillow","水洗亞麻枕頭套（2入）","accessory",["muji","japanese"],
   ["linen pillowcase","washed linen","pillow cover"],["natural linen","off-white","light grey"],
   1600,"50x70 each","stonewashed linen pillowcase pair, relaxed texture, Muji minimal"),
tb("muji-tray-set","天然竹質托盤組（3件套疊）","storage",["muji","japanese"],
   ["bamboo tray","serving tray","organizing tray"],["natural bamboo"],
   2200,"various","natural bamboo nesting tray set of 3, Muji functional display"),
tb("muji-aroma-ring","木質擴香竹條組","accessory",["muji","japanese"],
   ["reed diffuser","aroma sticks","fragrance"],["natural wood","golden rod"],
   1200,"100ml","natural rattan reed diffuser, subtle scent, Muji-style wellness"),
tb("muji-magazine-wall","壁掛鐵線雜誌報架","storage",["muji"],
   ["wall magazine rack","iron holder","minimalist storage"],["matte black","white"],
   1400,"W30xH35","wall-mount wire magazine rack, clean lines, Muji minimal kitchen"),
tb("muji-pp-shelving","模組PP抽屜高收納組","storage",["muji"],
   ["PP storage","polypropylene shelf","modular"],["white","translucent grey"],
   6800,"W40xD26xH175","tall polypropylene modular drawer shelving, Muji signature"),
tb("muji-drying-rack","摺疊晾衣架（原木夾桿）","accessory",["muji"],
   ["drying rack","clothes horse","laundry rack"],["natural pine"],
   2200,"W80xH120 folded","folding natural pine laundry drying rack, Muji utility"),
tb("muji-cotton-slippers","棉質室內拖鞋","accessory",["muji"],
   ["cotton slippers","house slippers","indoor shoes"],["natural","off-white","grey"],
   580,"various","cotton terry cloth indoor slippers, Muji home comfort"),
tb("muji-kitchen-mat","棉質廚房吸水腳墊","accessory",["muji"],
   ["kitchen mat","cotton mat","anti-fatigue"],["beige","grey","natural"],
   880,"W45xD75","washable cotton kitchen floor mat, thin profile, Muji functional"),
tb("muji-file-box","A4文件收納盒（白）","storage",["muji"],
   ["file box","document storage","white box"],["white"],
   680,"A4 size","white PP file storage box, clean minimal, Muji study organization"),
tb("muji-notebook","空白/橫線筆記本組","accessory",["muji"],
   ["blank notebook","journal","sketchbook"],["natural paper","cream"],
   360,"A5","clean kraft or white cover notebook, Muji study essential"),
tb("muji-round-stool","圓形木質坐凳（可堆疊）","chair",["muji","nordic","japanese"],
   ["round stool","wood stool","stackable"],["beech","ash"],
   1800,"Dia30xH44","solid beech round stackable stool, minimal Muji functional"),
tb("muji-iron-bed-white","白色細框鐵床架","bed",["muji"],
   ["iron bed","white metal bed","simple bed"],["white"],
   8800,"W150xD200","white powder-coat iron tube bed frame, slim profile, Muji clean"),
tb("muji-storage-box-set","PP收納箱組（大/中/小）","storage",["muji"],
   ["storage box","PP box","closet storage"],["white","translucent","grey"],
   3600,"various","polypropylene lidded storage box set 3 sizes, Muji wardrobe/closet"),
tb("muji-bath-robe","有機棉浴袍（米白）","accessory",["muji"],
   ["cotton robe","bathrobe","spa robe"],["off-white","natural"],
   2800,"one size","soft organic cotton towelling bathrobe, Muji spa feel at home"),
tb("muji-plant-pot-set","陶瓷植物盆組（3件 白）","plant",["muji","nordic"],
   ["ceramic pot","white planter","minimalist pot"],["matte white","off-white"],
   1600,"Dia10/14/18","set of 3 matte white ceramic pots with drainage, Muji minimal"),
tb("muji-drawer-dividers","PP抽屜分格板（可調）","storage",["muji"],
   ["drawer divider","organizer insert","adjustable"],["clear","white"],
   480,"adjustable width","adjustable polypropylene drawer dividers, Muji organization"),
tb("muji-beech-stool","山毛櫸木高腳梳妝椅","chair",["muji"],
   ["vanity stool","beech stool","round seat"],["natural beech"],
   2800,"Dia35xH60","solid beech counter-height stool, clean round seat, Muji vanity"),
tb("muji-hanging-lights","白色紙質球燈組（10入）","lighting",["muji","nordic"],
   ["paper ball light","globe string","party lights"],["white","warm white"],
   1200,"Dia15 x10","white paper globe fairy light string, 10 balls, warm white Muji"),
tb("muji-corner-shelf","轉角三角形壁掛置物架","shelving",["muji"],
   ["corner shelf","triangle shelf","wall corner"],["white","pine"],
   1400,"W30xD30","wall-mount corner triangle shelf, Muji bathroom or bedroom corner"),
tb("muji-bamboo-mat","竹質沐浴地板防滑墊","accessory",["muji","japanese"],
   ["bamboo mat","bath mat","shower mat"],["natural bamboo"],
   880,"W50xD80","split bamboo anti-slip bath mat, natural, Muji bathroom"),

# ══════════════════════════════════════════════════════════
# ART-DECO — 補充 25 件
# ══════════════════════════════════════════════════════════
tb("ad-feather-lamp","羽毛吊燈（黑+金）","lighting",["art-deco","luxury"],
   ["feather pendant","Art Deco lamp","glam light"],["black feather","gold"],
   12000,"Dia40","black feather pendant lamp, gold ring armature, Art Deco glamour"),
tb("ad-geometric-vase","幾何切割玻璃花瓶","accessory",["art-deco"],
   ["geometric vase","glass vase","angular vase"],["clear glass","amber","smoke"],
   3200,"H35","faceted geometric glass vase, Art Deco angles, table display"),
tb("ad-leopard-rug","豹紋圖案地毯（黑金）","rug",["art-deco","luxury"],
   ["leopard rug","animal print","glamour rug"],["black","gold","cream"],
   16000,"200x290","abstract leopard print area rug, black and gold, Art Deco drama"),
tb("ad-velvet-headboard-panel","絨布波浪形床頭板牆","bed",["art-deco"],
   ["curved headboard","scalloped panel","Art Deco bed"],["emerald","navy","champagne"],
   22000,"W200xH150","scalloped curved velvet headboard wall panel, Art Deco Hollywood"),
tb("ad-statue-lamp","女神雕像桌燈（鍍金）","lighting",["art-deco"],
   ["figurine lamp","statue light","Art Deco table lamp"],["gold","champagne","chrome"],
   15000,"H55","Art Deco female figurine table lamp, brushed gold, glamour bedroom"),
tb("ad-brass-magazine","黃銅雜誌架（直立式）","storage",["art-deco","luxury"],
   ["brass magazine rack","gold holder","Art Deco"],["brushed brass","gold"],
   4500,"W30xD15xH50","standing brushed brass magazine rack, Art Deco study"),
tb("ad-starburst-clock","放射形金色壁鐘","accessory",["art-deco","luxury"],
   ["starburst clock","sunburst clock","gold wall clock"],["gold","champagne"],
   5500,"Dia55","gold starburst wall clock, Art Deco sunray design"),
tb("ad-marble-fireplace","大理石仿壁爐框（裝飾）","accessory",["art-deco","luxury"],
   ["fireplace surround","marble frame","decorative mantel"],["white marble","black marble"],
   28000,"W120xH100","decorative marble fireplace surround mantel, Art Deco classic"),
tb("ad-trellis-wallpaper","金色鑽石格紋牆布","accessory",["art-deco"],
   ["geometric wallpaper","trellis pattern","feature wall"],["gold","cream","black"],
   5500,"per roll","metallic gold trellis geometric wallpaper, Art Deco feature wall"),
tb("ad-velvet-robe","絨布浴袍（孔雀藍）","accessory",["art-deco","luxury"],
   ["velvet robe","luxury bathrobe","Art Deco"],["peacock blue","burgundy"],
   4800,"one size","velvet-texture luxury robe, bold Art Deco color, boudoir"),
tb("ad-hexagon-mirror","六邊形黃銅邊框鏡組","mirror",["art-deco"],
   ["hexagon mirror","brass mirror","geometric wall"],["brushed brass"],
   8800,"W35xH40 each(set3)","brushed brass hexagonal mirror set of 3, Art Deco wall cluster"),
tb("ad-cocktail-table","圓形玻璃黃銅邊茶几","table",["art-deco","luxury"],
   ["cocktail table","glass coffee table","brass edge"],["clear glass","brushed brass"],
   18000,"Dia80xH42","round bevelled glass top coffee table, brushed brass frame, Art Deco"),
tb("ad-black-marble-bath","黑大理石紋浴室配件組","accessory",["art-deco","luxury"],
   ["bathroom set","black marble accessories","luxury hardware"],["nero marble","gold"],
   6800,"set","black marble and gold bathroom accessory set: soap dish+tumbler+tray"),
tb("ad-tassel-throw","金線流蘇裝飾毯","accessory",["art-deco","luxury"],
   ["tassel throw","luxury blanket","gold trim"],["champagne","ivory","midnight navy"],
   4200,"130x180","gold tassel trim luxury throw blanket, Art Deco glamour"),
tb("ad-cinema-light","膠卷燈（老電影風格）","lighting",["art-deco"],
   ["film reel light","cinema decor","vintage lamp"],["antique bronze","warm amber"],
   5500,"Dia40","vintage cinema film reel desk lamp, Art Deco Hollywood"),
tb("ad-emerald-bedding","祖母綠絲絨被套組","accessory",["art-deco","luxury"],
   ["emerald bedding","velvet duvet","luxury bedroom"],["emerald green","gold piping"],
   8800,"180x210","deep emerald faux-velvet duvet cover set, gold trim, Art Deco boudoir"),
tb("ad-brass-curtain-rod","黃銅窗簾桿組（附配件）","curtain",["art-deco","luxury"],
   ["brass curtain rod","gold rod","luxury hardware"],["brushed brass","gold"],
   3200,"W120-200 adjustable","adjustable brushed brass curtain rod with finials, Art Deco"),
tb("ad-arch-cabinet","拱形頂部展示酒柜","storage",["art-deco","luxury"],
   ["arched cabinet","display cabinet","Art Deco cabinet"],["walnut","glass","gold"],
   42000,"W90xD45xH200","arched glass-front display cabinet, walnut veneer, Art Deco"),
tb("ad-plume-decor","孔雀羽毛展示擺件","accessory",["art-deco"],
   ["peacock feather","decorative plume","Art Deco decor"],["iridescent","teal","gold"],
   2200,"H80","peacock feather arrangement in brass vase, Art Deco statement"),
tb("ad-star-tile-rug","星形幾何地毯（藍金）","rug",["art-deco"],
   ["star pattern rug","geometric","luxury rug"],["navy","gold","cream"],
   12000,"160x230","star geometric medallion rug, navy and gold, Art Deco classic"),
tb("ad-hammered-bowl","手錘銅碗（桌面展示）","accessory",["art-deco"],
   ["hammered copper bowl","decorative bowl","metal bowl"],["hammered copper","bronze"],
   3800,"Dia30xH10","hammered copper decorative bowl, Art Deco table centrepiece"),
tb("ad-dressing-mirror","梳妝台橢圓立鏡（金框）","mirror",["art-deco","luxury"],
   ["oval vanity mirror","gold stand mirror","tilting mirror"],["champagne gold"],
   9800,"W40xH60","oval tilting vanity stand mirror, brushed gold frame, Art Deco boudoir"),
tb("ad-striped-wallpaper","Art Deco 金條紋壁紙","accessory",["art-deco"],
   ["stripe wallpaper","metallic wallpaper","feature wall"],["gold","cream","black"],
   4800,"per roll","classic Art Deco vertical gold stripe wallpaper, feature wall"),
tb("ad-ceramic-tiger","陶瓷老虎擺件（藝術品）","accessory",["art-deco","luxury"],
   ["tiger figurine","ceramic animal","luxury decor"],["gold","ivory","black"],
   8800,"W30xH20","gilded ceramic tiger sculpture, Art Deco table statement piece"),
tb("ad-sconce-pair","扇形壁燈一對（霧鉻）","lighting",["art-deco"],
   ["wall sconce pair","frosted chrome","fan lamp"],["chrome","frosted glass"],
   8800,"H25 each","pair of fan-shaped frosted glass chrome wall sconces, Art Deco"),

# ══════════════════════════════════════════════════════════
# BOHO 波希米亞 — 補充 30 件
# ══════════════════════════════════════════════════════════
tb("boho-canopy-bed","波西米亞帳篷感床幔","accessory",["boho"],
   ["bed canopy","mosquito net","bohemian bed"],["cream white","blush"],
   2800,"W250xH260","sheer cotton bed canopy, flowy boho bedroom romantic vibe"),
tb("boho-pampas-grass","乾燥芒草装饰花束（大）","plant",["boho","nordic"],
   ["pampas grass","dried flowers","natural decor"],["cream","blush","sage"],
   1800,"H80","natural dried pampas grass bouquet, boho neutral palette"),
tb("boho-hammered-bell","銅鈴風鈴（手工）","accessory",["boho","mediterranean"],
   ["wind chime","copper bell","handmade"],["hammered copper","bronze"],
   1200,"H30","hand-hammered copper bell wind chime, boho porch or garden"),
tb("boho-cactus-garden","玻璃多肉仙人掌園組","plant",["boho"],
   ["succulent garden","glass terrarium","cactus set"],["green","terracotta pot"],
   2400,"various","glass container succulent and cactus mini garden, boho shelf display"),
tb("boho-print-tapestry","曼陀羅掛毯（牆飾/床蓋）","accessory",["boho"],
   ["tapestry","mandala wall hanging","bohemian textile"],["multicolor","terracotta","indigo"],
   2200,"W230xH200","mandala print large tapestry, wall art or bed cover, boho bedroom"),
tb("boho-rattan-mirror","藤編框橢圓掛鏡","mirror",["boho","mediterranean","nordic"],
   ["rattan mirror","natural mirror","wicker frame"],["natural rattan"],
   3800,"W50xH70","handwoven rattan oval wall mirror, boho coastal bedroom"),
tb("boho-batik-pillow","蠟染布藝抱枕（印度手工）","accessory",["boho"],
   ["batik pillow","hand-printed cushion","Indian textile"],["indigo","terracotta","mustard"],
   1200,"45x45","hand block-printed batik cotton throw pillow, boho India textile"),
tb("boho-leaf-print","巨型葉片藝術印刷海報","accessory",["boho","nordic"],
   ["leaf print","botanical poster","wall art"],["deep green","cream","terracotta"],
   1800,"50x70","oversized botanical leaf illustration print, boho gallery wall"),
tb("boho-hanging-planter","麻繩懸吊植物架（3個）","plant",["boho"],
   ["macrame plant hanger","hanging pot","rope planter"],["natural cotton","cream"],
   1600,"H50 each","hand-knotted macramé hanging plant holders set of 3, boho green wall"),
tb("boho-rattan-daybed","藤編日床坐榻（含軟墊）","chair",["boho","mediterranean"],
   ["rattan daybed","boho lounger","chaise"],["natural rattan","cream cushion"],
   22000,"W200xD85","woven rattan outdoor-style daybed, thick cushion, boho relaxation"),
tb("boho-incense-holder","孔雀尾形陶瓷線香架","accessory",["boho"],
   ["incense holder","peacock holder","ceramic burner"],["iridescent","teal"],
   980,"W15xH5","peacock feather-shaped ceramic incense holder, boho scent ritual"),
tb("boho-fringe-lamp","流蘇桌燈（彩色絲線）","lighting",["boho"],
   ["tassel lamp","fringe table lamp","colorful lamp"],["cream","mustard","terracotta"],
   3200,"H35","colorful fabric tassel table lamp, boho bedroom"),
tb("boho-tie-dye-sheet","紮染床單組（薑黃/靛藍）","accessory",["boho"],
   ["tie-dye bedding","shibori","boho bedroom"],["mustard tie-dye","indigo shibori"],
   3800,"180x200+pillowcase","hand tie-dye cotton bed sheet set, boho bedroom texture"),
tb("boho-seashell-mirror","貝殼拼貼圓鏡","mirror",["boho","mediterranean"],
   ["shell mirror","coastal mirror","boho decor"],["natural shell","cream"],
   4800,"Dia50","natural seashell mosaic circular wall mirror, boho coastal"),
tb("boho-wood-beads","木珠串門簾（自然色）","accessory",["boho","mediterranean"],
   ["bead curtain","wooden beads","room divider"],["natural wood","walnut","painted"],
   2200,"W90xH200","natural wood bead curtain door or window partition, boho"),
tb("boho-gallery-wall","混搭波西米亞牆面掛飾套組","accessory",["boho"],
   ["gallery wall kit","boho wall set","mixed decor"],["various","earth tone"],
   6800,"various","boho gallery wall starter kit: macramé+frame+pressed flower+print"),
tb("boho-ethnic-chair","民族風高背扶手椅（彩色織品）","chair",["boho"],
   ["ethnic armchair","folk pattern","colorful chair"],["multicolor folk","wood frame"],
   12000,"W65xD70xH100","high-back armchair, folk embroidered upholstery, boho statement"),
tb("boho-monstera-plant","龜背竹（大型，附藤編盆）","plant",["boho","nordic"],
   ["monstera","split leaf","tropical plant"],["deep green"],
   3800,"H120","large monstera deliciosa in natural rattan pot, boho jungle corner"),
tb("boho-cushion-floor-lg","波西米亞大地板懶骨頭","chair",["boho"],
   ["floor cushion","bean bag","oversized cushion"],["terracotta","mustard","cream"],
   5800,"W90xD90xH30","oversized Moroccan floor cushion, patchwork cover, boho seating"),
tb("boho-rattan-shelf","藤編架格層架（三層）","shelving",["boho","mediterranean"],
   ["rattan shelf","wicker bookcase","natural storage"],["natural rattan"],
   6800,"W80xD30xH120","3-tier wicker rattan open shelf unit, boho living storage"),
tb("boho-african-mask","非洲面具牆飾（手工）","accessory",["boho"],
   ["African mask","tribal decor","wall mask"],["natural wood","hand-painted"],
   2800,"H30","hand-carved African tribal wooden mask, boho eclectic wall art"),
tb("boho-tie-dye-curtain","紮染棉布窗簾（靛藍）","curtain",["boho"],
   ["tie-dye curtain","shibori drape","indigo"],["indigo blue","white","teal"],
   4200,"W250xH270","hand-dyed shibori tie-dye cotton curtain, boho window treatment"),
tb("boho-rope-chair","繩編懸吊搖椅（戶外/室內）","chair",["boho","mediterranean"],
   ["rope swing chair","hammock chair","hanging seat"],["natural cotton rope","brown"],
   8800,"Dia80","hand-woven cotton rope hammock swing chair, ceiling mount, boho"),
tb("boho-jute-lamp","黃麻編織桌燈","lighting",["boho","nordic"],
   ["jute lamp","natural fiber lamp","woven shade"],["natural jute","warm brown"],
   2800,"H40","natural jute hand-woven table lamp shade, warm 3000K, boho"),
tb("boho-ceramic-jugs","陶罐組合展示品（3件）","accessory",["boho","japanese"],
   ["ceramic jug","pottery vessel","organic"],["cream","terracotta","sage"],
   3200,"various","hand-thrown ceramic jug set of 3, organic forms, boho shelf display"),
tb("boho-dream-mobile","月亮星星金屬壁掛裝飾","accessory",["boho"],
   ["wall mobile","moon stars","metal decor"],["gold","brass","matte black"],
   1600,"W40xH50","crescent moon and star metal wall mobile, boho celestial decor"),
tb("boho-rattan-bed-head","藤編圓形床頭板","bed",["boho","mediterranean"],
   ["rattan headboard","wicker bed","boho bed"],["natural rattan"],
   12000,"W180xH80","round arch natural rattan headboard, boho tropical bedroom"),
tb("boho-indigo-rug","手染靛藍菱格紋地毯","rug",["boho"],
   ["indigo rug","hand-dyed","diamond pattern"],["indigo blue","white"],
   9800,"160x230","hand block-printed indigo diamond-pattern cotton rug, boho"),
tb("boho-fringe-curtain","棉線流蘇半透明布簾","curtain",["boho"],
   ["fringe curtain","macrame curtain","boho divider"],["cream","natural white"],
   3200,"W100xH200","hand-knotted macramé cotton fringe door curtain, boho divider"),
tb("boho-plant-wall","植物掛牆多袋植生袋架","plant",["boho","nordic"],
   ["plant pocket","wall garden","vertical garden"],["natural canvas","terracotta"],
   2800,"W30xH80","canvas wall pocket planter, 6 pockets, boho vertical garden"),
]

def main():
    # 讀取現有 catalog
    catalog_path = os.path.join(os.path.dirname(__file__), "furniture_catalog.json")
    existing = []
    if os.path.exists(catalog_path):
        with open(catalog_path, "r", encoding="utf-8") as f:
            existing = json.load(f)
    print(f"現有目錄：{len(existing)} 件")

    # 去重（用 name_zh 避免重複）
    existing_names = {item["name_zh"] for item in existing}
    new_items = [item for item in EXTRA if item["name_zh"] not in existing_names]
    print(f"新增項目：{len(new_items)} 件")

    merged = existing + new_items
    print(f"合併後總計：{len(merged)} 件")

    # 統計各風格數量
    style_count = {}
    for item in merged:
        primary = item.get("style_tags", ["unknown"])[0]
        style_count[primary] = style_count.get(primary, 0) + 1
    for style, count in sorted(style_count.items()):
        print(f"  {style:15s}: {count} 件")

    # 寫入
    with open(catalog_path, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print(f"\n✅ furniture_catalog.json 已更新")

if __name__ == "__main__":
    main()
