"""
Catalog Batch 7 — final batch to reach 2000+
Target: ~80+ per style, focusing on art-deco, boho, industrial, luxury, mediterranean
"""
import json, os

CATALOG_PATH = os.path.join(os.path.dirname(__file__), "furniture_catalog.json")

def tb(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "Taobao", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.taobao.com/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

def ik(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "IKEA", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.ikea.com/tw/zh/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

BATCH7 = [
    # ── LUXURY (50 items) ──────────────────────────────────────────────────
    tb("lux3-gold-wall-art-3d","3D立體金色牆飾","accessory",["luxury"],
       ["3D wall art","gold leaf","relief"],["gold","antique gold","champagne"],
       12000,"W80xH60","3D gold-leaf relief wall art panel, sculptural luxury wall decor"),
    tb("lux3-onyx-slab-console","黑瑪瑙石板桌","table",["luxury"],
       ["onyx console","stone","unique"],["honey onyx","gold veins"],
       55000,"W120xD35xH82","backlit honey onyx stone slab console table, one-of-a-kind luxury foyer"),
    tb("lux3-bedframe-crushed-velvet","碎絲絨特大床架","bed",["luxury"],
       ["crushed velvet bed","super king","glamour"],["silver crushed velvet","chrome"],
       68000,"W200xD215 (super king)","silver crushed velvet super-king platform bed with tall headboard, luxury glamour"),
    tb("lux3-gold-bath-faucet-set","拱形黃金浴缸龍頭組","accessory",["luxury"],
       ["gold bath faucet","freestanding","arched"],["polished 24k gold"],
       22000,"Standard","polished gold arched freestanding bath faucet and hand shower set, luxury en-suite"),
    tb("lux3-wall-panel-gold","金色壓花牆板（一套）","accessory",["luxury"],
       ["embossed wall panel","gold","decorative"],["gold","champagne"],
       18000,"4 panels per set","gold embossed 3D wall panel set for feature wall, luxury interior"),
    tb("lux3-velvet-sofa-royale","皇家三人沙發（深紫絲絨）","sofa",["luxury"],
       ["royal purple sofa","velvet","3-seater"],["royal purple","deep violet"],
       75000,"W225xD90xH88","deep royal purple velvet 3-seater sofa with gold carved wood frame, luxury showroom"),
    tb("lux3-marble-lamp-pair","大理石台燈一對","lighting",["luxury"],
       ["marble lamp pair","white marble","brass shade"],["white marble","brushed brass"],
       18000,"Pair, H55","matched pair of white marble column table lamps with brushed brass shades, luxury bedroom"),
    tb("lux3-crystal-wall-art","水晶鑲嵌裝飾畫","accessory",["luxury"],
       ["crystal art","mosaic","sparkle"],["clear crystal","silver frame"],
       22000,"W60xH80","Swarovski-style crystal mosaic wall art, light-catching luxury statement"),
    tb("lux3-gold-mirror-sunburst-lg","大型金色射線鏡（100cm）","mirror",["luxury","art-deco"],
       ["sunburst mirror","large","gold"],["antique gold","champagne"],
       18000,"Dia100","large antique gold sunburst ray mirror, luxury living room or foyer"),
    tb("lux3-velvet-chaise","天鵝絨貴妃椅（米色）","chair",["luxury"],
       ["chaise longue","velvet","cream"],["warm cream velvet","champagne legs"],
       35000,"W180xD70xH78","cream velvet chaise longue with gold leg frame, luxury boudoir or living room"),
    tb("lux3-ornate-picture-frame","精雕金色畫框（超大）","accessory",["luxury","art-deco"],
       ["ornate frame","oversized","gold"],["antique gold","carved detail"],
       8500,"W100xH130","deeply carved antique gold picture frame, A/B grade gesso finish, luxury gallery"),
    tb("lux3-silk-embroid-cushion","絲綢刺繡靠枕（對裝）","textile",["luxury"],
       ["silk cushion","embroidered","pair"],["ivory silk","gold thread embroidery"],
       6500,"Pair, 50x50cm","pair of ivory silk cushions with hand-embroidered gold floral motifs, luxury bedroom"),
    tb("lux3-floating-shelf-marble","大理石浮牆架（120cm）","storage",["luxury"],
       ["marble shelf","large floating","120cm"],["white Carrara marble","gold brackets"],
       22000,"W120xD25","white Carrara marble 120cm floating shelf on gold wall brackets, luxury bathroom or foyer"),
    tb("lux3-gold-leaf-table","金箔茶几（玻璃面）","table",["luxury"],
       ["gold leaf table","glass top","glamour"],["gold leaf base","clear glass"],
       28000,"W100xD60xH42","gold-leaf applied sculptural coffee table base with clear tempered glass top"),
    tb("lux3-persian-runner","手工波斯走廊地毯","rug",["luxury"],
       ["persian runner","hand-knotted","narrow"],["ruby red","navy","ivory"],
       28000,"80x250cm","hand-knotted Persian wool runner rug, ruby red and navy medallion pattern, luxury hallway"),
    tb("lux3-crystal-sconce-pair","水晶壁燈（對裝，5頭）","lighting",["luxury"],
       ["crystal sconce pair","5-arm","chrome"],["chrome","crystal drops"],
       22000,"Pair, W30xH50","pair of 5-arm crystal wall sconces on chrome, luxury bedroom or dining room"),
    tb("lux3-luxury-bedding-7piece","奢華7件式寢具組（金絲）","textile",["luxury"],
       ["bedding set","7-piece","gold thread"],["champagne gold","ivory"],
       28000,"King size 7-piece","7-piece luxury king bedding set with gold jacquard duvet cover, shams and runners"),
    tb("lux3-antique-bookcase","古典書房書架（深胡桃木）","storage",["luxury"],
       ["classical bookcase","dark walnut","antique"],["dark walnut","brass handles"],
       65000,"W180xD40xH220","floor-to-ceiling dark walnut classical bookcase with brass hardware, luxury study"),
    tb("lux3-champagne-bath-set","香檳色浴室5件配件組","accessory",["luxury"],
       ["bathroom accessories","champagne gold","5-piece"],["champagne gold","soft pink"],
       12000,"Set of 5","5-piece champagne gold bathroom set (soap pump, tray, cup, tissue box, bath tray), luxury"),
    tb("lux3-pendant-drop-rain","垂雨型水晶吊燈","lighting",["luxury"],
       ["raindrop chandelier","crystal","long drop"],["crystal clear","chrome frame"],
       55000,"Dia60xH120","multi-tier crystal raindrop chandelier, cascading long drops, grand luxury foyer"),
    tb("lux3-velvet-door-curtain","天鵝絨門簾（寶石紅）","textile",["luxury"],
       ["velvet door curtain","jewel red","arch"],["jewel red","deep ruby"],
       8000,"W80xH240","jewel-red velvet heavy arch doorway curtain, luxury interior room divider or portal"),
    tb("lux3-gold-coat-stand-orn","裝飾黃銅衣帽架（球頂）","storage",["luxury"],
       ["coat stand","ornamental","brass"],["polished brass"],
       12000,"H185","ornamental polished brass coat stand with ball finials, luxury entryway"),
    tb("lux3-malachite-side-table","孔雀石紋邊桌","table",["luxury"],
       ["malachite table","green stone","side"],["malachite green","gold base"],
       22000,"Dia40xH60","malachite-effect stone veneer round side table on gold pedestal, luxury statement"),
    tb("lux3-fur-throw-silver","銀色仿皮草毯","textile",["luxury"],
       ["faux fur throw","silver","glamour"],["silver grey","pearl"],
       6500,"130x160cm","silver grey faux fur throw blanket, lustrous sheen, luxury bed or sofa drape"),
    tb("lux3-backlit-onyx-wall","背光蜂蜜瑪瑙牆板","accessory",["luxury"],
       ["backlit onyx","feature wall","amber"],["honey amber","warm backlight"],
       85000,"W100xH200 per panel","backlit honey onyx marble wall panel, creates glowing amber feature wall, luxury"),
    tb("lux3-gold-bookend-elephant","黃金大象書擋","accessory",["luxury"],
       ["elephant bookend","gold","brass"],["polished gold","aged brass"],
       4500,"Pair, H15","pair of gold-finish elephant figurine bookends, luxury study desk or shelf"),
    tb("lux3-marble-soap-dish-set","白大理石浴室配件（5件）","accessory",["luxury"],
       ["marble bathroom","5-piece","white"],["white marble","brass detail"],
       15000,"Set of 5","5-piece white marble bathroom accessory set with brass fittings, luxury spa"),
    tb("lux3-velvet-throw-emerald","翡翠綠天鵝絨毯","textile",["luxury"],
       ["velvet throw","emerald","luxury"],["deep emerald green","jewel tone"],
       5500,"130x160cm","deep emerald green velvet throw blanket, rich drape and sheen, luxury sofa or bed"),
    tb("lux3-vanity-mirror-smart","智慧梳妝鏡（LED調光）","mirror",["luxury","modern"],
       ["smart vanity mirror","LED","dimmable"],["brushed gold frame","LED"],
       22000,"W100xH75","gold-framed HD smart vanity mirror with adjustable colour-temp LED lighting, luxury dressing"),
    tb("lux3-rose-gold-vase","玫瑰金幾何花器（大）","accessory",["luxury"],
       ["rose gold vase","geometric","large"],["rose gold","blush"],
       5500,"H45","large rose gold geometric ceramic vase, luxury shelf or table display"),
    tb("lux3-velvet-armchair-pair","天鵝絨單椅一對（香檳色）","chair",["luxury"],
       ["armchair pair","champagne velvet","gold legs"],["champagne velvet","brushed gold"],
       35000,"Pair","pair of champagne velvet armchairs on brushed gold legs, luxury living or bedroom seating"),
    tb("lux3-crystal-ashtray","重型水晶菸灰缸","accessory",["luxury"],
       ["crystal ashtray","heavy","decorative"],["clear crystal"],
       3500,"Dia15","heavy clear cut-crystal decorative ashtray, luxury study or living room accent"),
    tb("lux3-marble-console-sm","大理石玄關窄桌（小）","table",["luxury"],
       ["marble console","small","narrow"],["white marble","gold edge"],
       12000,"W80xD25xH82","small white marble console table with gold edge, luxury compact foyer or corridor"),
    tb("lux3-gold-light-switch","黃金開關面板（大理石框）","accessory",["luxury"],
       ["light switch","gold","marble surround"],["polished gold","white marble"],
       2500,"Standard socket","polished gold rocker switch with white marble surround plate, luxury interior detail"),
    tb("lux3-silk-rug-round","圓形絲質地毯","rug",["luxury"],
       ["silk rug","round","lustrous"],["ivory","champagne silk"],
       35000,"Dia200","hand-finished circular silk area rug in champagne ivory, ultra-fine luxury sheen"),
    tb("lux3-gold-serving-set","黃銅餐桌服務組（6件）","accessory",["luxury"],
       ["serving set","brass","dinnerware"],["polished brass","gold"],
       8500,"Set of 6","6-piece polished brass luxury serving set (bread basket, tongs, salt/pepper, condiment), luxury dining"),
    tb("lux3-large-crystal-bowl","大型水晶果碗","accessory",["luxury"],
       ["crystal bowl","large","decorative"],["clear cut crystal"],
       5500,"Dia30","large clear cut-crystal decorative fruit bowl, luxury dining table centrepiece"),
    tb("lux3-velvet-bench-gold-lg","大型天鵝絨長凳（金脚）","chair",["luxury"],
       ["velvet bench","large","gold legs"],["midnight navy velvet","brushed gold"],
       18000,"W160xD45xH50","large midnight navy velvet upholstered bench on brushed gold legs, luxury corridor"),
    tb("lux3-alabaster-floor-lamp","雪花石膏落地燈","lighting",["luxury"],
       ["alabaster floor lamp","stone","warm glow"],["natural alabaster","gold stem"],
       35000,"H160","natural alabaster stone shade floor lamp on gold stem, warm glow, luxury living room"),
    tb("lux3-bamboo-silk-throw","竹絲毯（奶油金色）","textile",["luxury"],
       ["bamboo silk","throw","soft"],["cream gold","champagne shimmer"],
       9500,"130x170cm","bamboo silk blend throw blanket, cream with gold shimmer, lightweight luxury"),
    tb("lux3-crystal-night-lamp","水晶夜燈（充電）","lighting",["luxury"],
       ["crystal night lamp","rechargeable","ambient"],["clear crystal","warm amber"],
       5500,"H20","genuine crystal rechargeable ambient night lamp, warm amber glow, luxury bedside"),
    tb("lux3-gold-magazine-rack","黃銅雜誌架（落地）","storage",["luxury"],
       ["magazine rack","brass","floor"],["polished brass"],
       6500,"W30xD15xH65","polished brass floor-standing magazine and newspaper rack, luxury living room"),
    tb("lux3-velvet-curtain-blush","胭脂粉天鵝絨窗簾","textile",["luxury"],
       ["blush velvet curtain","powder pink","soft"],["powder blush","rose pink"],
       12000,"W140xH260 per panel","powder blush velvet curtain panel, soft powder pink, luxury romantic bedroom"),
    tb("lux3-gold-tissue-box","黃銅組合面紙盒","accessory",["luxury"],
       ["tissue box cover","brass","geometric"],["polished brass","gold"],
       2500,"Standard tissue box","polished brass geometric tissue box cover, luxury bathroom or bedroom"),
    tb("lux3-marble-plinth-tall","大理石展示柱（高）","accessory",["luxury"],
       ["marble plinth","tall","sculpture"],["white marble","grey veins"],
       18000,"Dia20xH120","tall white marble round pedestal plinth for sculpture or plant, luxury gallery or foyer"),
    tb("lux3-satin-bed-skirt","緞面床裙（象牙，多層）","textile",["luxury"],
       ["bed skirt","ivory satin","layered"],["ivory satin"],
       5500,"Queen size","multi-layer ivory satin bed skirt/valance, hides box spring, luxury bedroom"),
    tb("lux3-door-knocker-brass","鍍金門環（獅頭型）","accessory",["luxury"],
       ["door knocker","lion","brass"],["polished brass","antique gold"],
       3500,"H15","solid polished brass lion-head door knocker, luxury front door hardware"),
    tb("lux3-gold-floor-bookstand","黃銅落地書架（展示型）","storage",["luxury"],
       ["floor book stand","brass","display"],["polished brass","smoked glass shelf"],
       18000,"W50xH120","polished brass 3-shelf floor book display stand with smoked glass shelves, luxury study"),
    tb("lux3-feather-cushion-royal","皇家藍羽毛靠枕（對裝）","textile",["luxury"],
       ["feather cushion","royal blue","pair"],["royal blue velvet","feather detail"],
       5500,"Pair, 50x50cm","pair of royal blue velvet cushions with feather-edge trim, luxury bedroom accents"),
    tb("lux3-marble-bath-basin","大理石洗手盆（台上盆）","accessory",["luxury"],
       ["marble basin","countertop","vessel"],["white Carrara marble","polished"],
       18000,"Dia40xH15","white Carrara marble above-counter vessel basin, luxury bathroom vanity"),
    tb("lux3-crystal-photo-frame","水晶相框組（3件，金邊）","accessory",["luxury"],
       ["crystal photo frame","set of 3","gold edge"],["clear crystal","gold"],
       4500,"Set of 3, 4x6/5x7/8x10","set of 3 crystal and gold edge photo frames in graduating sizes, luxury display"),

    # ── ART-DECO (45 items) ────────────────────────────────────────────────
    tb("ad3-tiger-velvet-chair","老虎紋天鵝絨單椅","chair",["art-deco"],
       ["tiger velvet","animal print","accent chair"],["tiger orange velvet","gold"],
       18000,"W75xD70xH85","tiger-pattern velvet accent chair on gold tulip base, Hollywood Regency art deco"),
    tb("ad3-geometric-pendant-cluster","幾何吊燈叢（7頭）","lighting",["art-deco"],
       ["geometric cluster","7-light","pendant"],["gold","black wire frame"],
       22000,"Span70xH70","7-arm gold geometric wire-frame pendant cluster, art deco statement ceiling"),
    tb("ad3-velvet-bar-stool-pair","天鵝絨吧台椅（一對，黑金）","chair",["art-deco"],
       ["bar stool pair","velvet","black gold"],["black velvet","gold legs"],
       16000,"Pair","pair of black velvet button-tufted bar stools on gold base, art deco bar or kitchen"),
    tb("ad3-art-deco-headboard","扇形裝飾藝術床頭板（象牙）","bed",["art-deco"],
       ["fan headboard","ivory","art deco"],["ivory velvet","gold nail-head"],
       18000,"W180xH150","ivory velvet fan-shaped headboard with gold nail-head stud trim, art deco bedroom"),
    tb("ad3-abstract-gold-frame-art","金色抽象版畫（裱框）","accessory",["art-deco"],
       ["framed art","gold","abstract"],["gold ornate frame","sepia"],
       6500,"W60xH80","sepia abstract art print in ornate gold art-deco frame, living room or study"),
    tb("ad3-brass-lamp-tripod","黃銅三腳架台燈","lighting",["art-deco"],
       ["tripod lamp","brass","3-leg"],["polished brass","white shade"],
       8500,"H60","polished brass tripod table lamp with white drum shade, art deco or mid-century"),
    tb("ad3-animal-print-rug","豹紋短毛地毯","rug",["art-deco","luxury"],
       ["leopard rug","animal print","short pile"],["amber gold","dark brown spots"],
       18000,"160x240cm","amber gold leopard-print short-pile area rug, art deco or glam living room"),
    tb("ad3-velvet-curtain-plum","李子色天鵝絨窗簾","textile",["art-deco"],
       ["velvet curtain","plum","purple"],["deep plum","aubergine"],
       12000,"W140xH270 per panel","deep plum velvet blackout curtain, rich jewel-tone, art deco bedroom"),
    tb("ad3-crystal-decanter-set","切割水晶威士忌套裝（6件）","accessory",["art-deco"],
       ["crystal decanter","whisky","6-piece"],["cut crystal","clear"],
       9500,"Set (decanter + 4 glasses + tray)","cut crystal decanter, 4 whisky glasses and tray set, art deco bar display"),
    tb("ad3-mirror-arch-art","弓拱形金框鏡","mirror",["art-deco"],
       ["arch mirror","gold frame","art deco"],["antique gold","ornate"],
       15000,"W80xH130","ornate antique-gold arched wall mirror, art deco or baroque-inspired bedroom or hallway"),
    tb("ad3-velvet-headboard-fan2","粉紅扇形床頭板（2.1m）","bed",["art-deco"],
       ["fan headboard","pink","tall"],["powder pink velvet","gold stud"],
       22000,"W210xH150","extra-wide powder pink velvet fan headboard with gold stud trim, art deco boudoir"),
    tb("ad3-bold-print-sofa","大膽印花沙發（黑金花）","sofa",["art-deco"],
       ["print sofa","black gold floral","glamour"],["black and gold floral jacquard"],
       65000,"W225xD88xH85","black and gold floral jacquard 3-seater sofa, bold art deco statement living room"),
    tb("ad3-sconce-gold-arm","金色雙臂壁燈（一對）","lighting",["art-deco"],
       ["wall sconce","double arm","gold"],["brushed gold","ivory shade"],
       9500,"Pair, W30xH40","pair of brushed gold double-arm wall sconces with ivory pleated shades, art deco"),
    tb("ad3-velvet-sofa-mauve","藕荷色三人沙發","sofa",["art-deco","luxury"],
       ["mauve sofa","velvet","3-seater"],["dusty mauve velvet","gold legs"],
       58000,"W230xD92xH82","dusty mauve velvet 3-seater sofa with curved back and gold legs, art deco glamour"),
    tb("ad3-ceramic-art-deco-lamp","藝術裝飾陶瓷台燈（幾何）","lighting",["art-deco"],
       ["ceramic lamp","geometric","art deco"],["cream ceramic","gold geometric"],
       7500,"H50","cream ceramic geometric art deco table lamp with gold diamond pattern, living or bedroom"),
    tb("ad3-zebra-cushion-set","斑馬紋靠枕組（4件）","textile",["art-deco"],
       ["zebra cushion","set of 4","black white"],["black white zebra","velvet"],
       4500,"Set of 4, 45x45cm","set of 4 zebra-print velvet cushions, Hollywood Regency art deco living room"),
    tb("ad3-chevron-rug-small","人字形地毯（金黑）","rug",["art-deco"],
       ["chevron rug","herringbone","gold black"],["gold","black"],
       9500,"120x180cm","gold and black chevron herringbone wool rug, art deco bedroom or living"),
    tb("ad3-vintage-radio-functional","復古藍牙音響（仿收音機）","accessory",["art-deco"],
       ["vintage radio","bluetooth speaker","art deco"],["walnut brown","gold trim"],
       6500,"W30xH18","walnut and gold Bluetooth speaker in vintage radio form, functional art deco decor"),
    tb("ad3-velvet-ottoman-lg","大型天鵝絨茶几矮凳","chair",["art-deco"],
       ["velvet ottoman","large","coffee table"],["deep teal velvet","gold trim"],
       22000,"W100xD70xH42","large deep teal velvet tufted ottoman doubling as coffee table, art deco lounge"),
    tb("ad3-glass-smoked-shelf","煙燻玻璃浮架（一組3片）","storage",["art-deco"],
       ["smoked glass shelf","floating","set of 3"],["smoked glass","brass bracket"],
       9500,"Set of 3 (60/80/100cm)","smoked glass floating shelves on brass brackets, set of 3, art deco display"),
    tb("ad3-gold-bathtub-freestand","金色爪腳浴缸","accessory",["art-deco","luxury"],
       ["claw foot tub","gold feet","freestanding"],["white matte","polished gold claws"],
       95000,"W170xD80xH60","matte white freestanding bathtub with polished gold claw feet, art deco luxury bathroom"),
    tb("ad3-velvet-sofa-armless","無扶手天鵝絨2人沙發（翡翠綠）","sofa",["art-deco"],
       ["armless sofa","emerald","2-seater"],["emerald green","forest velvet"],
       38000,"W175xD80xH75","armless emerald green velvet 2-seater sofa, art deco minimal silhouette"),
    tb("ad3-velvet-footstool-gold","黃金圓矮墩（香檳）","chair",["art-deco"],
       ["footstool","champagne","round velvet"],["champagne velvet","polished gold"],
       7000,"Dia50xH42","champagne velvet round button-tufted footstool on polished gold legs, art deco"),
    tb("ad3-brass-coat-rack-art","黃銅裝飾衣帽架（5頭）","storage",["art-deco"],
       ["coat rack","brass","5-hook"],["polished brass"],
       8500,"H185","5-hook polished brass floor coat and hat stand, art deco entryway elegance"),
    tb("ad3-velvet-chaise-teal","孔雀藍貴妃椅","chair",["art-deco"],
       ["chaise longue","teal","velvet"],["peacock teal velvet","gold legs"],
       38000,"W180xD70xH80","peacock teal velvet chaise longue on gold legs, art deco boudoir statement piece"),
    tb("ad3-bold-tile-bathroom","黑金六角浴室磚（方案）","accessory",["art-deco"],
       ["hexagon tile","black gold","bathroom"],["matte black","gold grout"],
       9000,"Box (1m2)","matte black hexagonal floor tiles with gold grout, art deco bathroom design"),
    tb("ad3-1920s-lamp-pair","1920年代風台燈（一對）","lighting",["art-deco"],
       ["1920s style lamp","pair","amber glass"],["amber glass","antique brass base"],
       12000,"Pair, H45","pair of 1920s-inspired amber glass table lamps on antique brass base, art deco"),
    tb("ad3-velvet-wallpaper","天鵝絨壓紋壁紙（一卷）","accessory",["art-deco"],
       ["velvet wallpaper","textured","bold"],["deep plum","gold shimmer"],
       6000,"W70cmxL10m per roll","deep plum velvet-textured gold-shimmer wallpaper, art deco feature wall"),
    tb("ad3-gold-serving-trolley","黃銅點心推車","storage",["art-deco"],
       ["serving trolley","brass","3-tier"],["polished brass","black glass"],
       16000,"W65xD40xH90","3-tier polished brass and smoked glass serving trolley, art deco afternoon tea"),
    tb("ad3-ceramic-art-vase","黑金陶瓷藝術花器","accessory",["art-deco"],
       ["ceramic vase","black gold","art deco"],["black matte","gold geometric"],
       4500,"H40","matte black ceramic vase with gold geometric art deco pattern, shelf or table display"),
    tb("ad3-velvet-chair-low","低背天鵝絨椅（藍）","chair",["art-deco"],
       ["low chair","velvet","blue"],["sapphire blue velvet","gold legs"],
       14000,"W80xD75xH70","low-back sapphire blue velvet accent chair on slender gold legs, art deco lounge"),
    tb("ad3-art-deco-floor-stand","黃銅書報架（藝術裝飾）","storage",["art-deco"],
       ["book stand","brass","art deco"],["antique brass","art deco cutout"],
       6500,"W35xH100","antique brass floor-standing magazine rack with art deco cutout pattern, study"),
    tb("ad3-layered-table-lamp","多層玻璃台燈（漸層藍）","lighting",["art-deco"],
       ["layered glass lamp","ombre","art deco"],["graduated blue glass","brass"],
       9500,"H55","graduated cobalt-to-clear glass layered table lamp, brass fitting, art deco bedroom"),
    tb("ad3-velvet-room-divider","天鵝絨屏風（3扇，黑金）","accessory",["art-deco"],
       ["room divider","velvet","3-panel"],["black velvet panel","gold frame"],
       22000,"W240xH180 (open)","3-panel black velvet and gold-frame room divider, art deco stage-prop aesthetic"),
    tb("ad3-marble-floor-lamp","大理石落地燈（白）","lighting",["art-deco","luxury"],
       ["marble floor lamp","white","column"],["white marble","gold"],
       28000,"H160","white marble column floor lamp with gold crown, art deco luxury living room"),
    tb("ad3-velvet-throw-blk-gold","黑色天鵝絨金線毯","textile",["art-deco"],
       ["velvet throw","black gold","jacquard"],["black velvet","gold thread"],
       5500,"130x160cm","black velvet throw with gold jacquard art deco vine pattern, glamorous sofa drape"),
    tb("ad3-gold-storage-cube","金色收納方格架（9格）","storage",["art-deco"],
       ["cube shelf","gold","9-cube"],["brushed gold frame"],
       18000,"W90xD30xH90","brushed gold metal 9-cube open shelving unit, art deco living room display"),
    tb("ad3-crystal-garland","水晶串珠裝飾串（3米）","accessory",["art-deco"],
       ["crystal garland","string","decorative"],["clear crystal","silver thread"],
       2500,"300cm","3m clear crystal bead garland for mantel or staircase, art deco glamour"),
    tb("ad3-checkerboard-floor","棋盤格大理石地磚（箱裝）","accessory",["art-deco"],
       ["checkerboard tile","black white marble","floor"],["black marble","white marble"],
       6000,"Box 4 tiles (60x60cm)","black and white marble checkerboard floor tiles (60x60cm), art deco foyer or bathroom"),
    tb("ad3-peacock-rug","孔雀紋地毯（藍綠）","rug",["art-deco"],
       ["peacock rug","pattern","teal blue"],["teal","green","peacock feather"],
       28000,"200x300cm","peacock feather pattern area rug in teal and navy, art deco jewel-tone living room"),
    tb("ad3-gold-bedside-pair","黃銅床頭燈一對（圓罩）","lighting",["art-deco"],
       ["bedside lamp pair","brass","round shade"],["polished brass","dome shade"],
       12000,"Pair, H45","pair of polished brass table lamps with round cream shade, art deco bedside"),
    tb("ad3-velvet-tuxedo-sofa","燕尾服絲絨沙發（香檳）","sofa",["art-deco"],
       ["tuxedo sofa","velvet","champagne"],["champagne velvet","gold legs"],
       62000,"W230xD88xH82","tuxedo-arm champagne velvet 3-seater sofa, strict geometric silhouette, art deco"),
    tb("ad3-art-poster-gold-frame","裝飾藝術風海報（金框，A1）","accessory",["art-deco"],
       ["art deco poster","A1","gold frame"],["gold frame","art print"],
       5500,"A1 with gold frame","A1 classic art deco travel or fashion poster print in ornate gold frame"),
    tb("ad3-chain-side-table","金屬鏈掛邊桌","table",["art-deco"],
       ["chain table","hanging","accent"],["polished gold chain","smoked glass"],
       8500,"Dia40xH60","smoked glass round side table suspended by decorative gold chain, art deco drama"),
    tb("ad3-velvet-pillow-fringe","流蘇天鵝絨靠枕（黑金，對裝）","textile",["art-deco"],
       ["velvet pillow","black gold fringe","pair"],["black velvet","gold fringe"],
       4000,"Pair, 50x50cm","pair of black velvet cushions with long gold fringe trim, Hollywood Regency art deco"),
    tb("ad3-floor-mirror-art","站立式工藝鏡（金銅框）","mirror",["art-deco"],
       ["standing mirror","copper gold","full length"],["antique copper gold"],
       22000,"W80xH200","antique copper-gold ornate carved full-length standing mirror, art deco statement"),

    # ── BOHO (40 items) ────────────────────────────────────────────────────
    tb("boho3-rattan-dining-table","藤編餐桌（圓形）","table",["boho"],
       ["rattan dining table","round","natural"],["natural rattan","honey brown"],
       22000,"Dia120xH75","natural rattan round dining table with glass top, boho dining room centrepiece"),
    tb("boho3-sunburst-mirror","太陽放射鏡（自然木色）","mirror",["boho"],
       ["sunburst mirror","natural wood","rays"],["natural driftwood","honey"],
       9500,"Dia80","natural driftwood sunburst ray wall mirror, boho or coastal bedroom"),
    tb("boho3-patchwork-cushion-lg","大型布藝拼布靠枕","textile",["boho"],
       ["patchwork cushion","large","mixed fabric"],["multicolour vintage fabric"],
       2500,"60x60cm","oversized patchwork mixed-fabric floor cushion, boho eclectic living room accent"),
    tb("boho3-seagrass-sofa","海草編沙發（3人）","sofa",["boho"],
       ["seagrass sofa","natural fibre","3-seater"],["natural seagrass","cream cushion"],
       32000,"W210xD85xH78","natural seagrass 3-seater sofa with cream cushions, boho coastal living room"),
    tb("boho3-jute-chair","黃麻編織單椅","chair",["boho"],
       ["jute chair","woven","natural"],["natural jute","dark wood frame"],
       8500,"W65xD68xH80","natural jute woven accent chair on dark wood frame, boho living room"),
    tb("boho3-cactus-tallpot","高身仙人掌盆栽","plant",["boho"],
       ["tall cactus","large","statement"],["green","terracotta pot"],
       4500,"H100 (approx)","large statement cactus in terracotta pot, boho desert interior design"),
    tb("boho3-wooden-bed-crate","木箱床頭矮几","table",["boho","industrial"],
       ["crate side table","rustic","wood box"],["reclaimed pine","wax finish"],
       3500,"W35xD35xH38","reclaimed pine wooden crate side table, rustic boho or industrial bedside"),
    tb("boho3-wicker-suitcase-deco","復古柳條手提箱裝飾","accessory",["boho"],
       ["wicker suitcase","vintage","decorative"],["natural wicker","vintage leather trim"],
       5000,"W60xH40","vintage wicker suitcase prop, boho shelf or tabletop decorative accent"),
    tb("boho3-feather-lamp-3tier","三層羽毛吊燈","lighting",["boho"],
       ["feather chandelier","3-tier","boho"],["cream feathers","gold frame"],
       12000,"Dia60xH80","3-tier cream feather pendant chandelier, Hollywood boho glamour, dining or bedroom"),
    tb("boho3-earth-tone-rug-3x5","地球色系地毯（3x5）","rug",["boho"],
       ["earth tone rug","3x5","tribal"],["terracotta","burnt orange","dark navy"],
       15000,"90x150cm","terracotta and navy tribal pattern wool rug, 3x5, boho living room or bedroom"),
    tb("boho3-palm-leaf-hanging","棕櫚葉掛飾（金屬）","accessory",["boho"],
       ["palm leaf art","metal","gold"],["brushed gold metal"],
       4500,"W60xH90","brushed gold metal palm leaf wall hanging, boho or tropical wall art"),
    tb("boho3-rattan-pendant-sm","小型藤球吊燈","lighting",["boho"],
       ["small rattan pendant","globe","warm"],["natural rattan","honey"],
       2500,"Dia25","small natural rattan globe pendant, warm boho kitchen or hallway overhead light"),
    tb("boho3-tribal-runner","部落走廊地毯","rug",["boho"],
       ["tribal runner","hallway","runner"],["rust red","cream","black"],
       5500,"60x200cm","rust red and cream tribal-pattern woven wool hallway runner, boho or ethnic interior"),
    tb("boho3-rope-light-indoor","麻繩球燈串（室內）","lighting",["boho"],
       ["rope ball light","indoor","warm"],["natural rope","warm LED"],
       3000,"300cm, 10 balls","3m natural rope ball string lights, warm LED, boho indoor bedroom or living"),
    tb("boho3-macrame-table-runner","麻繩編織桌旗","textile",["boho"],
       ["macrame runner","table","natural rope"],["natural cotton rope","cream"],
       2200,"W30xL150","natural cotton macrame table runner, boho dining table or dresser display"),
    tb("boho3-beaded-chandelier","木珠流蘇吊燈（大）","lighting",["boho"],
       ["bead chandelier","large","natural"],["natural wood beads","cream tassel"],
       15000,"Dia70xH80","large natural wood bead and cream tassel pendant chandelier, boho dining room statement"),
    tb("boho3-cotton-rope-basket-xl","超大棉繩收納籃","storage",["boho"],
       ["cotton rope basket","XL","storage"],["natural white rope"],
       4500,"Dia60xH50","extra-large hand-woven natural cotton rope storage basket, boho living room"),
    tb("boho3-dipped-candle-set","漸層蠟燭組（5支，手工）","accessory",["boho"],
       ["dipped candle","ombre","set of 5"],["terracotta","rust","cream","natural wax"],
       2200,"Set of 5, H25","set of 5 hand-dipped taper candles in ombre earthy tones, boho table styling"),
    tb("boho3-wicker-pot-stand","柳條花器底座（3件，高低）","plant",["boho"],
       ["wicker pot stand","woven","3-piece"],["natural wicker","honey"],
       3500,"Set of 3, H15/25/40","set of 3 natural wicker plant pot stands in ascending heights, boho indoor garden"),
    tb("boho3-printed-textile-wall","印花布藝掛畫（手工）","accessory",["boho"],
       ["textile wall art","hand-printed","fabric"],["saffron yellow","rust","navy"],
       4500,"W80xH100","hand-block-printed cotton textile wall hanging, boho colours on natural fabric"),
    tb("boho3-carved-wood-bowl","手工雕刻木碗（非洲橄欖）","accessory",["boho"],
       ["carved wood bowl","African olive","handmade"],["dark olive wood","golden grain"],
       5500,"Dia30","hand-carved African olive wood decorative bowl, boho or global-style centrepiece"),
    tb("boho3-fabric-wall-banner","手工布藝壁旗（赭石+白）","accessory",["boho"],
       ["wall banner","fabric","ochre"],["ochre yellow","white cotton"],
       2800,"W60xH120","hand-dyed cotton wall banner in ochre and white, boho wall art"),
    tb("boho3-ammonite-fossil-decor","菊石化石裝飾擺件","accessory",["boho"],
       ["ammonite fossil","natural","display"],["natural stone","cream spiral"],
       3500,"Dia15","polished ammonite fossil display piece, boho or global natural curio shelf decor"),
    tb("boho3-rattan-storage-map","藤編地圖收納盒（帶蓋）","storage",["boho"],
       ["rattan box","lidded","map pattern"],["natural rattan","vintage map"],
       4000,"W40xD30xH25","natural rattan storage box with vintage map-print lid insert, boho living room"),
    tb("boho3-incense-holder-soapstone","皂石薰香座","accessory",["boho"],
       ["incense holder","soapstone","carved"],["grey soapstone"],
       1500,"W15xH5","carved grey soapstone flat incense holder with carved pattern, boho or zen ritual"),
    tb("boho3-twig-wall-art","樹枝組合牆飾","accessory",["boho"],
       ["twig art","natural","wall hanging"],["natural dried twigs","cream wool"],
       3000,"W70xH50","natural dried branch and cream wool wall sculpture, boho organic wall art"),
    tb("boho3-linen-shower-curtain","棉麻淋浴簾（自然色）","textile",["boho","nordic"],
       ["shower curtain","linen cotton","natural"],["natural linen","oatmeal"],
       3000,"W180xH200","natural linen-cotton blend shower curtain with bronze rings, boho bathroom"),
    tb("boho3-mud-cloth-pillow","泥染布抱枕（一對）","textile",["boho"],
       ["mud cloth","pair","African"],["black white mudcloth pattern","natural"],
       4000,"Pair, 50x50cm","pair of West African mud cloth (bogolan) pattern cushion covers, boho global"),
    tb("boho3-large-rattan-mirror","大型藤編牆鏡（圓）","mirror",["boho"],
       ["large rattan mirror","round","statement"],["natural rattan","large"],
       12000,"Dia100","oversized natural rattan round wall mirror, boho statement bedroom or living room"),
    tb("boho3-orange-resin-pendant","橙色樹脂球形吊燈","lighting",["boho"],
       ["resin pendant","orange","sphere"],["amber orange resin","gold fitting"],
       6000,"Dia30","amber orange resin sphere pendant, warm glow like sunset, boho or earthy interior"),
    tb("boho3-jute-curtain-tab","粗黃麻桿頭窗簾（一對）","textile",["boho"],
       ["jute curtain","tab top","pair"],["natural jute","honey brown"],
       6000,"W140xH250 per panel (pair)","natural jute tab-top curtain pair, semi-opaque, boho natural light living room"),
    tb("boho3-carved-wood-mirror","手工雕刻木框圓鏡","mirror",["boho"],
       ["carved wood mirror","handmade","round"],["natural carved wood","warm brown"],
       9000,"Dia65","hand-carved natural wood circular wall mirror, boho or global artisan decor"),
    tb("boho3-boho-bed-canopy","波西米亞帳篷蚊帳（雙人）","textile",["boho"],
       ["bed canopy","mosquito net","boho"],["white gauze","macrame trim"],
       5000,"W150 (queen)","white gauze bed canopy with macrame trim, queen size, boho tropical bedroom"),
    tb("boho3-hammered-copper-pot","手工銅器花盆","plant",["boho"],
       ["hammered copper","pot","handmade"],["hammered copper","warm tone"],
       3500,"Dia25xH25","hand-hammered copper plant pot, aged patina finish, boho earthy plant display"),
    tb("boho3-shell-wind-chime","貝殼風鈴","accessory",["boho","mediterranean"],
       ["shell wind chime","natural","coastal"],["natural shells","driftwood"],
       1500,"H50","natural shell and driftwood wind chime, boho coastal porch or window decor"),
    tb("boho3-palm-leaf-rattan-wall","棕櫚葉藤板裝飾","accessory",["boho"],
       ["rattan panel","palm leaf","woven"],["natural rattan","leaf pattern"],
       5500,"W60xH90","woven rattan wall panel with palm leaf motif, boho tropical statement"),
    tb("boho3-ikat-cushion-4pack","印尼イカット紋抱枕（4件）","textile",["boho"],
       ["ikat cushion","Indonesian","4-piece"],["earth tones","hand-dyed"],
       5000,"Set of 4, 45x45cm","set of 4 Indonesian ikat-pattern cotton cushions in earthy hand-dyed tones, boho"),
    tb("boho3-floor-cushion-camel","駱駝色大落地坐墊","textile",["boho"],
       ["floor cushion","camel","large"],["camel tan","leather trim"],
       4500,"W70xD70xH20","large camel-colour round floor cushion with leather trim, boho Moroccan seating"),
    tb("boho3-terracotta-garland","赭石色陶珠串","accessory",["boho"],
       ["terracotta beads","garland","mantel"],["terracotta","clay orange"],
       1200,"300cm","terracotta clay bead garland, boho mantel or shelf styling string"),
    tb("boho3-woven-bed-skirt","編織床裙（黑白條紋）","textile",["boho"],
       ["bed skirt","woven stripe","black white"],["black white woven"],
       3000,"Queen size","handwoven black and white striped bed skirt/valance, boho bedroom base"),

    # ── INDUSTRIAL (40 items) ──────────────────────────────────────────────
    tb("ind3-black-iron-daybed","黑色鐵管日床（帶床墊）","bed",["industrial"],
       ["daybed","black iron","sofa bed"],["matte black iron","grey mattress"],
       18000,"W100xD200xH70","matte black iron pipe daybed frame with thin grey mattress, industrial loft"),
    tb("ind3-raw-steel-bench","生鋼長條工作凳","chair",["industrial"],
       ["work bench","raw steel","backless"],["raw steel","brushed"],
       9500,"W180xD30xH45","raw brushed steel flat bar long work bench, industrial office, gallery or kitchen"),
    tb("ind3-brick-cladding-panel","仿紅磚外掛牆板（大）","accessory",["industrial"],
       ["brick cladding","PU","wall panel"],["red brick","grey mortar"],
       6000,"W60xH120 per panel","large PU faux red brick wall panel, lightweight DIY, industrial or rustic wall"),
    tb("ind3-rusted-metal-wall","做舊金屬牆飾（大）","accessory",["industrial"],
       ["rustic metal art","large","oxidised"],["rust brown","oxidised steel"],
       9500,"W100xH70","large oxidised rust-effect steel wall art panel, industrial statement"),
    tb("ind3-cage-lampshade-set","鐵籠燈罩套裝（3種尺寸）","lighting",["industrial"],
       ["cage shade","3-size","black"],["matte black iron"],
       3000,"Set of 3 (S/M/L)","set of 3 matte black iron cage lamp shades for industrial pendant conversion"),
    tb("ind3-pipe-and-wood-bed","鐵管木板雙人床架","bed",["industrial"],
       ["pipe bed","wood plank","black iron"],["black iron pipe","natural pine"],
       18000,"W153xD213 (queen)","black iron pipe and natural pine plank queen bed, industrial loft"),
    tb("ind3-metal-grid-room-divider","金屬網格隔間牆","accessory",["industrial","modern"],
       ["metal grid","room divider","partition"],["matte black steel grid"],
       22000,"W150xH200","matte black steel grid room divider panel, industrial or modern loft partition"),
    tb("ind3-vintage-sink-industrial","工業風陶瓷農家水槽","accessory",["industrial"],
       ["farmhouse sink","ceramic","apron"],["white ceramic","matte black faucet"],
       18000,"W70xD50","classic white apron-front fireclay farmhouse sink, industrial kitchen or mudroom"),
    tb("ind3-factory-pendant-10head","工廠燈籠10頭吊燈","lighting",["industrial"],
       ["factory pendant","10-light","warehouse"],["matte black","warm Edison"],
       28000,"W200xH30","10-head industrial warehouse-style pendant light bar, matte black with Edison bulbs"),
    tb("ind3-old-sewing-table","仿古縫紉機腳架桌","table",["industrial","boho"],
       ["sewing machine table","vintage","iron legs"],["aged cast iron legs","reclaimed wood"],
       12000,"W120xD60xH76","reclaimed wood table top on vintage cast iron sewing machine trestle legs, industrial"),
    tb("ind3-steel-tool-chest","工業鋼製工具台（滾輪，7格）","storage",["industrial"],
       ["tool chest","rolling","7-drawer"],["gloss black","chrome handles"],
       22000,"W60xD35xH85","7-drawer gloss black rolling steel tool chest, industrial garage or utility room"),
    tb("ind3-wire-lamp-ball","鐵絲球吊燈（DIY款）","lighting",["industrial"],
       ["wire ball lamp","DIY","Edison bulb"],["black iron wire","bare bulb"],
       2200,"Dia20","matte black iron wire globe pendant lamp, exposed Edison bulb, industrial minimalist"),
    tb("ind3-concrete-side-table-cube","方形水泥方塊邊桌","table",["industrial","modern"],
       ["concrete cube","side table","industrial"],["raw grey concrete"],
       6000,"W35xD35xH40","solid cast concrete cube side table, industrial loft or modern minimalist"),
    tb("ind3-vintage-locker-bench","金屬置物凳（2門）","storage",["industrial"],
       ["locker bench","2-door","metal"],["gunmetal grey","chrome"],
       8500,"W80xD35xH50","2-door gunmetal metal locker-style bench with padded seat, industrial entryway"),
    tb("ind3-pipe-desk-lamp-clip","夾式鐵管台燈","lighting",["industrial"],
       ["clip lamp","pipe","clamp"],["matte black iron","bare bulb"],
       2500,"H35","matte black iron pipe clip-on desk lamp, industrial home office or workshop clamp"),
    tb("ind3-iron-magazine-holder","鐵製牆掛雜誌架","storage",["industrial"],
       ["wall magazine rack","iron","2-slot"],["matte black iron"],
       2000,"W35xH30","2-slot matte black iron wall-mounted magazine holder, industrial office or kitchen"),
    tb("ind3-steel-drinks-trolley","鋼製酒水推車（2層）","storage",["industrial"],
       ["drinks cart","black steel","2-shelf"],["matte black steel","dark walnut"],
       9500,"W60xD35xH85","2-shelf matte black steel drinks cart with walnut shelf boards, industrial bar"),
    tb("ind3-concrete-bathroom-kit","水泥浴室配件組（4件）","accessory",["industrial"],
       ["concrete bathroom","4-piece","matte grey"],["raw grey concrete"],
       5500,"Set of 4","4-piece raw concrete bathroom accessory set (soap pump, tray, toothbrush, cup), industrial"),
    tb("ind3-metal-pegboard-black-kit","金屬洞洞板收納套件（黑）","storage",["industrial","muji"],
       ["pegboard kit","black","accessories"],["matte black steel"],
       4500,"W60xH90 board + accessories","matte black metal pegboard with 12-piece hook and shelf accessory kit, industrial"),
    tb("ind3-factory-stool-set","工廠凳4張套裝","chair",["industrial"],
       ["factory stool","4-pack","industrial seating"],["matte black","raw steel"],
       16000,"Set of 4","set of 4 matte black raw steel industrial stools, stackable, factory or loft dining"),
    tb("ind3-raw-iron-headboard","生鐵床頭板（黑，加大）","bed",["industrial"],
       ["iron headboard","raw","king"],["raw matte iron","welded"],
       9500,"W183xH80 (king)","hand-welded raw matte iron king size headboard, industrial loft bedroom"),
    tb("ind3-copper-pendant-set","銅色紗罩吊燈（3頭組）","lighting",["industrial"],
       ["copper pendant","3-head","soft light"],["antique copper","mesh shade"],
       9500,"3-head bar W60","3-head antique copper mesh shade pendant bar light, industrial warm kitchen"),
    tb("ind3-vintage-map-print","工業風世界地圖掛畫（復古）","accessory",["industrial","boho"],
       ["vintage map","framed","world"],["sepia brown","distressed frame"],
       4500,"W80xH60","sepia vintage world map art print in distressed dark frame, industrial study or living"),
    tb("ind3-rustic-shelf-bracket","做舊鐵製層架支架（一對）","storage",["industrial"],
       ["shelf bracket","rustic iron","pair"],["aged iron","rust brown"],
       1200,"Pair, W25","pair of rustic aged-iron angled shelf brackets, industrial DIY shelf project"),
    tb("ind3-tin-bucket-trio","鍍鋅鐵桶花器組（3件）","plant",["industrial"],
       ["tin bucket","galvanized","3-piece"],["galvanized silver","aged tin"],
       2200,"Set of 3, various","set of 3 galvanized tin bucket planters in varying heights, industrial garden"),
    tb("ind3-pipe-lamp-wall-pair","工業管道壁燈（一對）","lighting",["industrial"],
       ["pipe sconce pair","wall","industrial"],["matte black iron","amber bulb"],
       6000,"Pair, W25xH20","pair of matte black iron pipe wall sconces with Edison bulbs, industrial corridor"),
    tb("ind3-duct-pipe-bookend","鐵管書擋（一對）","accessory",["industrial"],
       ["pipe bookend","iron","heavy"],["matte black iron pipe"],
       2000,"Pair H15","pair of matte black iron pipe section bookends, industrial desk or shelf"),
    tb("ind3-metal-sign-retro","復古鐵質標語牌（英文）","accessory",["industrial"],
       ["metal sign","vintage","typography"],["aged rust","embossed"],
       2000,"W40xH20","aged rust-finish embossed iron vintage typography wall sign, industrial bar or kitchen"),
    tb("ind3-industrial-fan-chrome","工業鉻色立扇（復古）","accessory",["industrial"],
       ["chrome fan","vintage","standing"],["chrome","brushed nickel"],
       6500,"H120","vintage-style chrome finish freestanding industrial pedestal fan, decorative and functional"),
    tb("ind3-metal-toilet-roll-holder","鐵製廁紙架（牆掛，工業）","accessory",["industrial"],
       ["toilet roll holder","black iron","wall mount"],["matte black iron"],
       1500,"Standard","matte black iron wall-mounted toilet paper holder, industrial bathroom"),
    tb("ind3-raw-oak-coat-hooks","粗獷橡木牆面掛鉤板","accessory",["industrial"],
       ["coat hook","raw oak","plank"],["raw oak","black iron hooks"],
       3500,"W80xH15","raw oak plank with 6 matte black iron hooks, industrial entryway or mudroom"),
    tb("ind3-metal-document-tray","金屬文件分類架（3格）","storage",["industrial"],
       ["document tray","3-tier","metal"],["matte black","industrial"],
       1500,"W25xH35","3-tier matte black metal stacking document tray, industrial office desk organiser"),
    tb("ind3-iron-coffee-press","鑄鐵咖啡法壓壺","accessory",["industrial"],
       ["french press","cast iron","coffee"],["matte black cast iron"],
       3500,"800ml","800ml matte black cast iron French press coffee maker, industrial kitchen counter styling"),
    tb("ind3-copper-bath-accessories","銅色浴室配件（5件）","accessory",["industrial"],
       ["copper bathroom","5-piece","metallic"],["antique copper","warm metal"],
       7000,"Set of 5","5-piece antique copper bathroom accessory set, industrial steampunk bathroom styling"),
    tb("ind3-distressed-leather-sofa","做舊皮革3人沙發","sofa",["industrial"],
       ["distressed leather","3-seater","aged"],["aged cognac","dark brown"],
       65000,"W220xD90xH82","distressed genuine leather 3-seater sofa, aged cognac, industrial club-style living room"),
    tb("ind3-bolt-side-table","螺栓型邊桌（鋼，圓形）","table",["industrial"],
       ["bolt table","round","steel"],["raw steel","bolt detail"],
       5500,"Dia40xH55","round raw steel side table with visible bolt detail, industrial loft accent piece"),
    tb("ind3-hanging-chain-shelf","鏈條懸吊展示架（3層）","storage",["industrial"],
       ["chain shelf","hanging","3-tier"],["matte black chain","reclaimed pine"],
       6500,"W80, 3 shelves","3-tier reclaimed pine shelves suspended from matte black chains, industrial wall display"),
    tb("ind3-iron-newspaper-rack","鑄鐵地板報架（立式）","storage",["industrial"],
       ["newspaper rack","cast iron","freestanding"],["matte black iron"],
       5500,"W40xH65","freestanding matte black cast iron newspaper and magazine rack, industrial study"),
    tb("ind3-rustic-ceiling-lamp","做舊天花木燈（5頭）","lighting",["industrial"],
       ["ceiling lamp","rustic wood","5-head"],["reclaimed wood","vintage bulb"],
       12000,"W80xH25","5-head reclaimed wood and aged iron ceiling light fixture, rustic industrial dining"),
    tb("ind3-riveted-headboard-king","大型鉚釘鋼板床頭板","bed",["industrial"],
       ["riveted headboard","king","steel"],["brushed steel","rivet detail"],
       12000,"W200xH90 (king)","brushed steel king headboard with rivet detail, industrial loft master bedroom"),
    tb("ind3-pipe-shelf-bathroom","水管浴室置物架（2層）","storage",["industrial"],
       ["pipe shelf","bathroom","black iron"],["black iron pipe","pine board"],
       3500,"W60xH50","2-tier black iron pipe and pine board bathroom wall shelf, industrial"),

    # ── MEDITERRANEAN (40 items) ────────────────────────────────────────────
    tb("med3-white-terracotta-planter","白色赭石組合花盆（5件）","plant",["mediterranean"],
       ["terracotta planter","5-piece","white"],["chalk white","terracotta"],
       4500,"Set of 5, Dia10-30","5-piece set of chalk-white terracotta pots in graduating sizes, Mediterranean garden"),
    tb("med3-blue-linen-sofa","天藍亞麻四人沙發","sofa",["mediterranean"],
       ["linen sofa","sky blue","4-seater"],["sky blue linen","coastal blue"],
       45000,"W250xD90xH82","sky blue washed linen 4-seater sofa, coastal Mediterranean or Nordic living"),
    tb("med3-arch-door-headboard","拱形藍漆木板床頭板","bed",["mediterranean"],
       ["arch headboard","blue","rustic wood"],["distressed ocean blue"],
       12000,"W160xH130","arched distressed ocean-blue painted wood panel headboard, Mediterranean bedroom"),
    tb("med3-spanish-tile-coaster","西班牙陶磚杯墊（6件組）","accessory",["mediterranean"],
       ["tile coaster","6-pack","Spanish"],["hand-painted blue","white"],
       1200,"Set of 6, 10x10cm","set of 6 hand-painted Spanish azulejo ceramic coasters, Mediterranean table styling"),
    tb("med3-white-rope-table","白色麻繩圓邊桌","table",["mediterranean","boho"],
       ["rope table","white","round"],["white cotton rope","white lacquer"],
       8000,"Dia60xH72","white lacquer round bistro table with cotton rope-wrapped base, Mediterranean café"),
    tb("med3-outdoor-canopy-sail","三角遮陽帆（米白）","accessory",["mediterranean"],
       ["shade sail","triangle","outdoor"],["off-white","natural"],
       4500,"300x300cm","triangular outdoor sun shade sail in off-white, Mediterranean terrace or garden"),
    tb("med3-fish-scale-tile-blue","魚鱗藍色牆磚（廚房）","accessory",["mediterranean"],
       ["fish scale tile","blue","kitchen"],["cobalt blue","sky blue"],
       4500,"Sheet 30x30cm","cobalt blue fish-scale ceramic kitchen wall tile sheet, Mediterranean splash back"),
    tb("med3-olive-tree-large","大型橄欖樹（仿真）","plant",["mediterranean"],
       ["olive tree","artificial","large"],["silver green","natural trunk"],
       9500,"H180","realistic artificial olive tree in terracotta pot, Mediterranean living room focal plant"),
    tb("med3-linen-tablecloth-natural","米白亞麻餐桌布（大）","textile",["mediterranean"],
       ["tablecloth","natural linen","large"],["natural linen","oatmeal"],
       2500,"W160xH260","large natural linen tablecloth for 8-10 seater table, Mediterranean al fresco dining"),
    tb("med3-santorini-wall-art","聖托里尼藍頂教堂畫","accessory",["mediterranean"],
       ["Santorini art","blue dome","canvas"],["cobalt blue","white","sky"],
       6500,"W80xH60","Santorini blue-dome church watercolour canvas print, Mediterranean wall art"),
    tb("med3-woven-rug-stripe-natural","天然條紋編織地毯","rug",["mediterranean"],
       ["woven rug","natural stripe","cotton"],["natural beige","white stripe"],
       7000,"160x240cm","natural beige and white cotton woven stripe rug, Mediterranean or Nordic floor"),
    tb("med3-door-bell-ceramic","藍色陶瓷門鈴裝飾","accessory",["mediterranean"],
       ["door bell","ceramic","blue"],["cobalt blue","hand-painted"],
       1200,"H15","hand-painted cobalt blue ceramic decorative door bell, Mediterranean villa entrance"),
    tb("med3-whitewash-console","白石灰玄關桌","table",["mediterranean"],
       ["console","whitewash","entryway"],["whitewash white"],
       9500,"W120xD35xH82","whitewash finish rustic wood console table, Mediterranean or coastal entryway"),
    tb("med3-sun-shaped-mirror","太陽形陶瓷鏡","mirror",["mediterranean"],
       ["sun mirror","ceramic rays","Mediterranean"],["terracotta","yellow gold"],
       7500,"Dia75","ceramic ray sun mirror with terracotta and yellow glaze, Mediterranean wall art"),
    tb("med3-outdoor-table-mosaic","馬賽克戶外方桌","table",["mediterranean"],
       ["mosaic outdoor table","square","patio"],["blue white mosaic","iron legs"],
       9500,"W70xD70xH75","hand-laid blue and white mosaic-top square outdoor table, Mediterranean patio"),
    tb("med3-ceramic-flower-pot","手繪花紋陶盆（一對）","plant",["mediterranean"],
       ["ceramic pot","pair","hand-painted"],["white","cobalt blue pattern"],
       2500,"Pair, Dia20","pair of white ceramics with hand-painted cobalt blue pattern pots, Mediterranean display"),
    tb("med3-terracotta-tile-shelf","赭石磁磚展示架","storage",["mediterranean"],
       ["tile display shelf","terracotta","wall"],["terracotta tile","black iron"],
       4500,"W60xH40","wall-mounted iron shelf with terracotta tile back panel, Mediterranean kitchen display"),
    tb("med3-fisherman-lantern","漁夫風格玻璃燈籠","lighting",["mediterranean"],
       ["fisherman lantern","glass","coastal"],["aged brass","green glass"],
       5500,"H45","aged brass fisherman-style glass lantern, green glass panels, Mediterranean coastal lighting"),
    tb("med3-blue-stripe-bedding","蔚藍條紋棉寢具組","textile",["mediterranean"],
       ["bedding","blue stripe","cotton"],["azure blue","white stripe"],
       5000,"Queen size set","azure blue and white stripe cotton 4-piece bedding set, Mediterranean bedroom"),
    tb("med3-wooden-shutter-pair","粗糙木百葉窗（一對，藍）","accessory",["mediterranean"],
       ["shutters","rustic wood","blue"],["ocean blue","distressed"],
       7000,"Pair W45xH120","pair of rustic distressed ocean-blue wood shutters, Mediterranean room divider or decor"),
    tb("med3-sun-flower-cushion","向日葵圖案靠枕（4件）","textile",["mediterranean"],
       ["sunflower cushion","4-piece","cotton"],["yellow","green stem","white ground"],
       3500,"Set of 4, 45x45cm","set of 4 cotton sunflower print cushion covers, Mediterranean table or sofa styling"),
    tb("med3-blue-lamp-classic","地中海藍色台燈（古典型）","lighting",["mediterranean"],
       ["ceramic table lamp","blue","Mediterranean"],["cobalt blue","white shade"],
       5500,"H45","cobalt blue ceramic base table lamp with white linen shade, Mediterranean bedroom"),
    tb("med3-round-mirror-tiles","圓形馬賽克鏡（浴室）","mirror",["mediterranean"],
       ["mosaic mirror","round","bathroom"],["cobalt blue mosaic","white"],
       5000,"Dia60","round cobalt and white mosaic tile framed wall mirror, Mediterranean bathroom"),
    tb("med3-white-outdoor-lantern","白色戶外提燈（大）","lighting",["mediterranean"],
       ["outdoor lantern","white","large"],["chalk white","clear glass"],
       3500,"H60","large chalk white outdoor garden lantern with clear glass panels, Mediterranean porch"),
    tb("med3-pottery-bowl-set","陶瓷釉碗套裝（4件）","accessory",["mediterranean"],
       ["pottery bowl","4-piece","glazed"],["Mediterranean blue glaze","terracotta"],
       3500,"Set of 4","set of 4 hand-thrown pottery bowls with Mediterranean blue glaze and terracotta body"),
    tb("med3-whitewash-cabinet-2door","白石灰雙門小廚房柜","storage",["mediterranean"],
       ["cabinet","whitewash","2-door"],["whitewash white","coastal"],
       9500,"W80xD40xH90","2-door whitewash distressed wood cabinet for kitchen or dining, Mediterranean coastal"),
    tb("med3-blue-wall-hooks-set","藍白陶瓷鉤板（5鉤）","accessory",["mediterranean"],
       ["ceramic hooks","blue white","5-hook"],["cobalt blue","white"],
       1500,"W50","hand-painted cobalt and white ceramic 5-hook wall mount, Mediterranean entryway or kitchen"),
    tb("med3-coastal-rug-nat-stripe","海岸自然色條紋地毯（小）","rug",["mediterranean"],
       ["coastal rug","natural stripe","small"],["natural cotton","blue accent"],
       4500,"120x180cm","natural cotton flat-weave rug with thin blue coastal stripe, Mediterranean room"),
    tb("med3-ceramic-oil-bottle","橄欖油瓶裝飾組（3件）","accessory",["mediterranean"],
       ["oil bottle","ceramic","3-piece"],["terracotta","olive green","cobalt"],
       2000,"Set of 3","3-piece ceramic olive oil and condiment bottles in Mediterranean colours, kitchen styling"),
    tb("med3-white-lantern-3size","白色鐵製燈籠（3件，大中小）","lighting",["mediterranean"],
       ["iron lantern","3-size set","white"],["chalk white iron","clear glass"],
       5500,"Set of 3","set of 3 chalk white iron lanterns in large, medium, small, Mediterranean terrace display"),
    tb("med3-natural-seagrass-rug","天然海草地毯（大）","rug",["mediterranean","boho"],
       ["seagrass rug","large","natural"],["natural seagrass","dark border"],
       12000,"200x280cm","large natural seagrass area rug with dark binding border, Mediterranean or boho"),
    tb("med3-vintage-blue-print","復古地中海藍調版畫","accessory",["mediterranean"],
       ["vintage print","blue tones","Mediterranean"],["deep sea blue","cream","frame"],
       4500,"W50xH70 with frame","vintage Mediterranean scenic blue-tone etching print in natural frame, wall art"),
    tb("med3-arch-bookcase-white","拱形書架（白色）","storage",["mediterranean"],
       ["arch bookcase","white","Mediterranean"],["white chalk paint","arch top"],
       18000,"W80xD30xH160","arched white chalk-painted wood open bookcase, Mediterranean interior display unit"),
    tb("med3-ceramic-serving-platter","大陶瓷服務盤（手繪）","accessory",["mediterranean"],
       ["serving platter","ceramic","hand-painted"],["cobalt blue","white","terracotta rim"],
       3000,"Dia40","large hand-painted cobalt and white ceramic serving platter, Mediterranean table centrepiece"),
    tb("med3-cobalt-outdoor-vase","鈷藍色戶外花器（大）","plant",["mediterranean"],
       ["outdoor vase","cobalt blue","large"],["cobalt blue glaze","terracotta body"],
       6500,"H60xDia30","large cobalt-blue glazed outdoor ceramic floor vase, Mediterranean garden or terrace"),
    tb("med3-wicker-chest","柳條儲物箱（帶蓋）","storage",["mediterranean","boho"],
       ["wicker chest","lidded","storage"],["natural wicker","leather handle"],
       8000,"W90xD50xH45","natural wicker lidded chest with leather handles, Mediterranean or boho blanket box"),
    tb("med3-arch-window-decor","裝飾拱形窗框（白）","accessory",["mediterranean"],
       ["arch window","decorative","white"],["chalk white"],
       9500,"W60xH110","decorative chalk-white arched wooden window frame wall art panel, Mediterranean accent"),
    tb("med3-hand-painted-tile-frame","手繪磁磚相框（5x7）","accessory",["mediterranean"],
       ["tile frame","hand-painted","photo"],["cobalt blue","white tile"],
       1500,"5x7 photo frame","hand-painted cobalt blue ceramic tile photo frame (5x7), Mediterranean home photo display"),
    tb("med3-sea-glass-light","海玻璃壁燈（藍綠）","lighting",["mediterranean"],
       ["sea glass light","coastal","sconce"],["sea glass blue-green","driftwood"],
       5500,"H25","natural driftwood and sea glass wall sconce, coastal Mediterranean or boho bathroom"),
    tb("med3-tile-top-bench","馬賽克磁磚座椅（室外）","chair",["mediterranean"],
       ["tile bench","mosaic top","outdoor"],["hand-laid mosaic","wrought iron"],
       12000,"W80xD35xH45","wrought iron outdoor bench with hand-laid cobalt mosaic tile seat, Mediterranean garden"),
    tb("med3-basket-wall-hanging","地中海壁掛籃飾（3個）","accessory",["mediterranean","boho"],
       ["basket wall art","3-piece","hanging"],["natural seagrass","dyed blue"],
       4000,"Set of 3, Dia20-35","3-piece seagrass wall-hanging basket set, Mediterranean or boho gallery wall"),
]

def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    print(f"Current: {len(existing)}")
    existing_names = {item["name_zh"] for item in existing}
    new_items = [item for item in BATCH7 if item["name_zh"] not in existing_names]
    print(f"Adding: {len(new_items)}")
    merged = existing + new_items
    print(f"Total: {len(merged)}")
    style_count = {}
    for item in merged:
        s = item.get("style_tags", ["unknown"])[0]
        style_count[s] = style_count.get(s, 0) + 1
    for s, c in sorted(style_count.items()):
        print(f"  {s:15s}: {c}")
    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print("Done.")

if __name__ == "__main__":
    main()
