"""
Catalog Batch 3 — ~350 more items (luxury/art-deco/boho/industrial/mediterranean focus)
Run: python catalog_batch3.py
"""
import json, os

CATALOG_PATH = os.path.join(os.path.dirname(__file__), "furniture_catalog.json")

def ik(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "IKEA", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.ikea.com/tw/zh/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

def tb(id, name_zh, category, style_tags, keywords, colors, price_twd, dimensions, flux_descriptor):
    return {
        "id": id, "name_zh": name_zh, "brand": "Taobao", "category": category,
        "style_tags": style_tags, "keywords": keywords, "colors": colors,
        "price_twd": price_twd, "image_url": "", "purchase_url": "https://www.taobao.com/",
        "dimensions": dimensions, "flux_descriptor": flux_descriptor
    }

BATCH3 = [
    # ── LUXURY (40 items) ──────────────────────────────────────────────────
    tb("lux-canopy-bed","四柱天篷床（金屬金色）","bed",["luxury"],
       ["canopy bed","4-poster","gold"],["brushed gold","champagne"],
       85000,"W183xD213xH230 (king)","brushed gold metal 4-poster canopy bed, king size, opulent luxury bedroom"),
    tb("lux-velvet-headboard","絲絨拱形床頭（深祖母綠）","bed",["luxury"],
       ["velvet headboard","arched","emerald"],["deep emerald","forest green"],
       18000,"W180xH120","deep emerald velvet curved arched headboard, luxury statement bedroom"),
    tb("lux-marble-dresser","大理石面梳妝台（金腳）","storage",["luxury"],
       ["dressing table","marble top","gold legs"],["white marble","brushed gold"],
       28000,"W120xD45xH80","white marble-top dressing table with gold leaf legs and oval mirror, luxury vanity"),
    tb("lux-crystal-chandelier","水晶吊燈（12頭）","lighting",["luxury"],
       ["crystal chandelier","12-light","grand"],["crystal clear","chrome"],
       45000,"Dia80xH90","12-arm crystal drop chandelier, chrome frame, grand luxury dining or foyer"),
    tb("lux-gold-frame-sofa","法式金框三人沙發（玫瑰粉）","sofa",["luxury","art-deco"],
       ["French sofa","gold frame","blush pink"],["blush pink","rose gold"],
       55000,"W220xD85xH95","French Louis-XVI style carved gold-leaf frame sofa in blush velvet, 3-seater"),
    tb("lux-mirror-ornate","鍍金巴洛克装飾鏡","mirror",["luxury","art-deco"],
       ["ornate mirror","baroque","gold frame"],["antique gold","champagne"],
       22000,"W90xH130","heavily carved baroque-style antique gold wall mirror, luxury entryway statement"),
    tb("lux-bar-cabinet-art","雞翅木雞尾酒吧櫃","storage",["luxury"],
       ["bar cabinet","walnut","drinks cabinet"],["dark wenge","gold handles"],
       35000,"W90xD45xH120","wenge-finish cocktail bar cabinet with brass-inlay interior and stemware rack"),
    tb("lux-art-sculpture-abstract","抽象金屬雕塑（桌上型）","accessory",["luxury"],
       ["sculpture","abstract","brass"],["brushed brass","gold"],
       8500,"H35","brushed brass abstract figurative sculpture, luxury coffee table or shelf art"),
    tb("lux-persian-rug","手工波斯地毯（紅藍）","rug",["luxury"],
       ["persian rug","hand-knotted","wool"],["deep red","cobalt blue","ivory"],
       65000,"240x340cm","hand-knotted wool Persian rug with medallion pattern, luxurious living room"),
    tb("lux-velvet-curtain-pair","絲絨全遮光窗簾（寶石藍，一對）","textile",["luxury"],
       ["velvet curtain","blackout","sapphire blue"],["sapphire blue","jewel tone"],
       12000,"W140xH280 per panel (pair)","sapphire blue velvet blackout curtain pair with gold rod, luxury bedroom"),
    tb("lux-gold-vase-tall","高身黃金陶瓷花瓶（對裝）","accessory",["luxury"],
       ["gold vase","pair","tall","ceramic"],["gold","champagne"],
       9500,"Pair, H60","pair of tall gold-glazed ceramic floor vases, luxury entryway or living room"),
    tb("lux-marble-coffee-table","圓形白大理石茶几（金底）","table",["luxury"],
       ["marble coffee table","round","gold base"],["Carrara white","brushed gold"],
       32000,"Dia90xH42","Carrara white marble round coffee table on gold tulip pedestal, luxury statement"),
    tb("lux-bedside-gold","金色床頭燈（絲絨燈罩）","lighting",["luxury"],
       ["bedside lamp","gold base","velvet shade"],["brushed gold","cream velvet"],
       6500,"H55","brass table lamp with cream velvet empire shade, luxury bedside lighting"),
    tb("lux-dining-table-marble","白大理石12人餐桌","table",["luxury"],
       ["dining table","marble","large","12-seater"],["white marble","polished"],
       120000,"W300xD110xH76","white Carrara marble top 12-seater dining table on chrome X-base, luxury dining"),
    tb("lux-arm-chair-lion","獅腳單人椅（絲絨）","chair",["luxury"],
       ["lion paw chair","carved legs","velvet"],["deep burgundy velvet","gold"],
       18000,"W72xD75xH90","deep burgundy velvet armchair with hand-carved gold lion-paw legs, baroque luxury"),
    tb("lux-gold-stair-rail","黃銅扶手裝飾套件","accessory",["luxury"],
       ["brass rail","staircase","handrail"],["polished brass"],
       45000,"Per metre","polished brass staircase handrail system, classic luxury residential"),
    tb("lux-silk-throw","蠶絲提花毯（香檳金）","textile",["luxury"],
       ["silk throw","jacquard","gold shimmer"],["champagne gold","ivory"],
       8500,"130x160cm","100% silk jacquard throw blanket in champagne gold pattern, luxury bed or sofa"),
    tb("lux-wine-rack-floor","落地紅酒架（金屬，50瓶）","storage",["luxury"],
       ["wine rack","floor standing","50-bottle"],["matte black","gold accents"],
       18000,"W80xD30xH120","matte black iron 50-bottle floor wine rack with gold finials, luxury dining room"),
    tb("lux-velvet-bench-bedroom","臥室絲絨床尾凳（金腳）","chair",["luxury"],
       ["bedroom bench","velvet","gold legs"],["blush pink velvet","gold"],
       12000,"W120xD40xH48","blush pink velvet upholstered bedroom bench on gold legs, luxury foot-of-bed"),
    tb("lux-led-mirror-round","LED圓形智慧浴鏡（金框）","mirror",["luxury"],
       ["LED mirror","smart mirror","gold frame"],["brushed gold","backlit"],
       15000,"Dia80","brushed gold frame LED backlit smart bathroom mirror with anti-fog, luxury en-suite"),
    tb("lux-satin-bedding","緞面純棉寢具組（象牙）","textile",["luxury"],
       ["sateen bedding","cotton","ivory"],["ivory","pearl white"],
       12000,"King size set","400TC long-staple sateen cotton duvet cover set, ivory, luxury sleep"),
    tb("lux-console-gold-glass","金邊玻璃玄關桌","table",["luxury","art-deco"],
       ["console table","glass","gold edge"],["gold","clear tempered glass"],
       22000,"W120xD35xH82","gold-edged tempered glass console table on sculpted gold legs, art deco or luxury"),
    tb("lux-plush-carpet","超厚毛毛地毯（米色，3x4m）","rug",["luxury"],
       ["shaggy rug","plush","thick pile"],["warm beige","cream"],
       35000,"300x400cm","ultra-plush 6cm pile shaggy area rug in warm beige, luxury living room indulgence"),
    tb("lux-wall-sconce-crystal","水晶壁燈（2頭）","lighting",["luxury"],
       ["wall sconce","crystal","2-arm"],["chrome","crystal drops"],
       8500,"W25xH40","2-arm crystal wall sconce with chrome backplate, luxury bedroom or corridor"),
    tb("lux-freestanding-bath","獨立式橢圓浴缸（白啞光）","accessory",["luxury"],
       ["freestanding bathtub","oval","white matte"],["matte white","glossy white"],
       85000,"W170xD80xH60","matte white oval freestanding soaking bathtub, luxury bathroom centrepiece"),
    tb("lux-gold-towel-rail","黃銅暖毛巾架（電熱）","accessory",["luxury"],
       ["heated towel rail","brass","electric"],["polished brass"],
       18000,"W60xH120","polished brass electric heated towel rail, luxury bathroom fixture"),
    tb("lux-marble-fireplace","壁爐裝飾架（白大理石）","accessory",["luxury"],
       ["fireplace surround","marble","decorative"],["white marble","black veining"],
       45000,"W150xH120","white marble decorative fireplace surround with mantel shelf, luxury living room"),
    tb("lux-velvet-stool-round","圓形天鵝絨矮凳（金腳）","chair",["luxury"],
       ["round stool","velvet","gold legs"],["deep teal velvet","gold"],
       5500,"Dia45xH42","deep teal velvet button-tufted round stool on gold legs, luxury accent piece"),
    tb("lux-art-print-gold","金箔版畫（限量）","accessory",["luxury"],
       ["gold leaf art","limited edition","framed print"],["gold","cream","black frame"],
       15000,"W80xH100","gold leaf abstract limited-edition art print in black shadow-box frame, luxury wall art"),
    tb("lux-brass-planter-set","黃銅幾何花器組（3件）","plant",["luxury"],
       ["brass planter","geometric","set of 3"],["polished brass","gold"],
       5500,"Various H15-30","set of 3 polished brass geometric planters, luxury shelf or table decor"),
    tb("lux-marble-bathroom-set","大理石浴室配件組（4件）","accessory",["luxury"],
       ["marble bathroom set","accessories","4-piece"],["white marble","brushed gold"],
       8000,"Set of 4","4-piece white marble and brushed gold bathroom accessories (soap pump, tray, cup, bin)"),
    tb("lux-gold-door-handle-set","黃銅門把手組（10件）","accessory",["luxury"],
       ["door handle","brass","lever"],["polished brass","satin gold"],
       8000,"Set of 10","solid polished brass lever door handles set of 10, luxury residential hardware"),
    tb("lux-velvet-rug-round","圓形天鵝絨地毯（祖母綠）","rug",["luxury"],
       ["round rug","velvet","emerald"],["emerald green","jewel"],
       18000,"Dia200","emerald green velvet-pile round area rug, luxury bedroom or dressing room"),
    tb("lux-floating-tv-wall","浮空電視牆板（胡桃+金）","storage",["luxury"],
       ["floating TV wall","walnut","gold accent"],["dark walnut","gold strip"],
       55000,"W300xH200","full-wall dark walnut TV feature panel with floating shelves and gold accent strips"),
    tb("lux-crystal-table-lamp","水晶台燈（金座）","lighting",["luxury"],
       ["crystal lamp","gold base","table lamp"],["crystal","brushed gold","champagne"],
       9500,"H55","K9 crystal body table lamp on brushed gold base with cream shade, luxury bedside"),
    tb("lux-round-ottoman-tufted","鈕扣圓形坐墩（酒紅天鵝絨）","chair",["luxury"],
       ["tufted ottoman","round","burgundy"],["deep burgundy","wine red"],
       8500,"Dia80xH45","button-tufted burgundy velvet round ottoman, gold bun feet, luxury lounge"),
    tb("lux-gold-ceiling-rose","金色石膏天花裝飾盤","accessory",["luxury"],
       ["ceiling rose","plaster","gold"],["antique gold","off-white"],
       3500,"Dia50","ornate antique-gold plaster ceiling rose medallion, luxury period-style room"),
    tb("lux-marble-stool","圓形大理石矮凳","chair",["luxury"],
       ["marble stool","side table","stone"],["white marble","grey veining"],
       8500,"Dia35xH45","solid white marble round pedestal stool, doubles as side table, luxury bathroom or living"),
    tb("lux-grand-vase-floor","落地大花器（黑釉金邊）","plant",["luxury"],
       ["floor vase","large","black glaze","gold rim"],["black glaze","gold"],
       15000,"Dia40xH80","large black-glazed ceramic floor vase with gold rim, luxury statement living room"),
    tb("lux-pendant-malachite","孔雀石綠玻璃吊燈","lighting",["luxury"],
       ["pendant light","malachite glass","green"],["malachite green","gold fitting"],
       12000,"Dia30xH40","malachite-green mouth-blown glass pendant with gold ceiling rose, luxury accent light"),

    # ── ART-DECO (40 items) ────────────────────────────────────────────────
    tb("ad-sofa-curved-emerald","弧形翡翠綠天鵝絨沙發","sofa",["art-deco"],
       ["curved sofa","emerald velvet","glamour"],["emerald green","deep jewel"],
       55000,"W220xD90xH78","curved emerald green velvet 3-seater sofa, gold legs, art deco glamour"),
    tb("ad-mirror-sunburst","太陽放射鏡（金色）","mirror",["art-deco"],
       ["sunburst mirror","gold rays","decorative"],["gold","champagne"],
       12000,"Dia90","gold sunburst mirror with radiating metal rays, art deco statement wall piece"),
    tb("ad-bar-trolley-brass","黃銅茶水推車","storage",["art-deco"],
       ["bar trolley","brass","drinks cart"],["polished brass","black glass"],
       18000,"W65xD40xH90","polished brass bar trolley with smoked black glass shelves, art deco entertaining"),
    tb("ad-geometric-rug","幾何拼色地毯（黑金）","rug",["art-deco"],
       ["geometric rug","black gold","pattern"],["black","gold","cream"],
       28000,"200x300cm","art deco geometric wool rug, black and gold chevron pattern, bold statement floor"),
    tb("ad-velvet-chair-gold","金脚天鵝絨單椅（祖母綠）","chair",["art-deco"],
       ["velvet accent chair","gold legs","emerald"],["emerald velvet","polished gold"],
       16000,"W72xD70xH82","emerald velvet wingback accent chair, polished gold legs, art deco living room"),
    tb("ad-globe-lamp","世界儀球形台燈（金銅色）","lighting",["art-deco"],
       ["globe table lamp","brass","sphere"],["antique brass","amber glass"],
       8500,"Dia25xH45","antique brass globe table lamp with amber glass sphere, art deco desk or side table"),
    tb("ad-zigzag-shelf","鋸齒形書架（黑金）","storage",["art-deco"],
       ["zigzag shelf","geometric","black gold"],["matte black","gold shelf"],
       12000,"W80xH120","asymmetric zigzag open bookshelf, matte black frame with gold shelf surfaces, art deco"),
    tb("ad-velvet-curtain-black","黑色絲絨窗簾（金流蘇）","textile",["art-deco"],
       ["black velvet curtain","gold tassel","glamour"],["black","gold tassel"],
       15000,"W140xH280 per panel","black velvet curtain with gold tassel trim, luxurious art deco room darkening"),
    tb("ad-smoked-glass-table","煙薰玻璃茶几（黃銅架）","table",["art-deco"],
       ["smoked glass coffee table","brass frame","art deco"],["smoked glass","brass"],
       22000,"W100xD60xH42","smoked-glass top coffee table on geometric brass frame, art deco sophistication"),
    tb("ad-pendant-gatsby","蓋茨比風吊燈（煙薰玻璃）","lighting",["art-deco"],
       ["gatsby pendant","smoked glass","chandelier"],["smoked amber","brass"],
       18000,"Dia50xH60","multi-tier smoked glass and brass Art Deco pendant chandelier, dining or foyer"),
    tb("ad-bedframe-velvet","菱格天鵝絨床頭板（黑）","bed",["art-deco"],
       ["diamond tufted bed","black velvet","platform"],["black velvet","gold stud"],
       38000,"W183xD213xH110 (king)","black velvet diamond-tufted king platform bed with gold nail-head trim, art deco"),
    tb("ad-perfume-tray-vanity","梳妝台黃銅托盤組","accessory",["art-deco"],
       ["vanity tray","brass","mirror tray"],["polished brass","mirror glass"],
       3500,"W30xD20","polished brass and mirrored glass vanity tray, art deco dressing table display"),
    tb("ad-geometric-cushion","幾何金黑刺繡靠枕（對裝）","textile",["art-deco"],
       ["geometric cushion","embroidered","black gold"],["black","gold thread"],
       2500,"50x50cm x2","pair of black velvet cushions with gold geometric embroidery, art deco accent"),
    tb("ad-marble-lamp-base","大理石台燈底座（金屬罩）","lighting",["art-deco"],
       ["marble lamp","metal shade","geometric"],["black marble","gold"],
       9500,"H50","black marble column table lamp with gold geometric metal shade, art deco"),
    tb("ad-art-print-cubist","立體派裝飾畫（金框）","accessory",["art-deco"],
       ["cubist art","framed print","geometric"],["gold frame","multicolour"],
       8500,"W60xH80","framed cubist-style art deco geometric art print in ornate gold frame"),
    tb("ad-dressing-chair","梳妝椅（菱形天鵝絨）","chair",["art-deco"],
       ["dressing stool","tufted","velvet"],["blush velvet","gold legs"],
       7500,"W50xD50xH45","blush velvet diamond-tufted dressing stool on gold legs, art deco vanity"),
    tb("ad-firescreen-brass","黃銅孔雀屏風","accessory",["art-deco"],
       ["fire screen","peacock","brass"],["polished brass","verdigris"],
       12000,"W80xH90","ornamental polished brass peacock fire screen, art deco or eclectic statement"),
    tb("ad-gold-clock-mantle","壁爐台黃銅鐘","accessory",["art-deco"],
       ["mantle clock","brass","ornamental"],["polished brass","black dial"],
       5500,"W30xH25","vintage-style art deco brass mantel clock with roman numeral face"),
    tb("ad-wall-light-fan","扇形壁燈（金色，2只）","lighting",["art-deco"],
       ["fan wall sconce","gold","art deco"],["polished gold","frosted glass"],
       7000,"Set of 2, W20xH30","pair of gold fan-shaped wall sconces with frosted glass diffuser, art deco"),
    tb("ad-velvet-bed-runner","天鵝絨床旗（黑金條紋）","textile",["art-deco"],
       ["bed runner","velvet","black gold stripe"],["black velvet","gold stripe"],
       2500,"W50xL200","black velvet bed runner with gold stripe edge, art deco bed styling"),
    tb("ad-console-zebra","斑馬紋大理石玄關桌","table",["art-deco"],
       ["console table","zebra marble","bold"],["zebra marble","black white"],
       28000,"W120xD35xH85","zebra-stripe marble-top console table on polished gold legs, art deco foyer"),
    tb("ad-carpet-bold-circle","圓形大地毯（黑白幾何）","rug",["art-deco"],
       ["round rug","geometric","black white"],["black","white"],
       22000,"Dia250","oversized round area rug with bold black-white geometric rings, art deco floor"),
    tb("ad-cabinet-lacquer-black","黑色亮面漆皮櫃（4門）","storage",["art-deco"],
       ["lacquer cabinet","black gloss","gold handles"],["black gloss","gold"],
       45000,"W160xD45xH85","high-gloss black lacquer 4-door sideboard with gold bar handles, art deco glamour"),
    tb("ad-velvet-armchair-blue","寶石藍單椅（管型金脚）","chair",["art-deco"],
       ["velvet armchair","sapphire blue","gold tube legs"],["sapphire blue","gold"],
       14000,"W75xD72xH80","sapphire blue velvet armchair with gold tubular base legs, Hollywood Regency art deco"),
    tb("ad-mural-wallpaper","黑金幾何壁紙（一卷）","accessory",["art-deco"],
       ["geometric wallpaper","black gold","art deco pattern"],["black","gold"],
       3500,"W52cmxL10m per roll","art deco geometric black and gold foil wallpaper, feature wall application"),
    tb("ad-feather-lamp","羽毛裝飾台燈（粉）","lighting",["art-deco"],
       ["feather lamp","pink","glamour"],["blush pink","gold base"],
       6500,"H50","blush pink feather-trimmed table lamp on gold base, Hollywood Regency art deco"),
    tb("ad-velvet-headboard-fan","扇形天鵝絨床頭板（藍綠）","bed",["art-deco"],
       ["fan headboard","velvet","teal"],["peacock teal","gold nail head"],
       18000,"W180xH140","fan-shaped peacock-teal velvet headboard with gold nail head border, art deco bedroom"),
    tb("ad-black-gold-credenza","黑金飾面邊櫃","storage",["art-deco"],
       ["credenza","black gold","art deco"],["black lacquer","gold hardware"],
       38000,"W180xD45xH75","black lacquer credenza with geometric gold hardware and inlay, art deco dining"),
    tb("ad-marble-side-table","烏金大理石邊桌","table",["art-deco"],
       ["marble side table","nero marquina","black marble"],["black marble","gold veins"],
       12000,"W50xH55","nero marquina black marble top side table on thin gold legs, art deco drama"),
    tb("ad-ecru-velvet-sofa","奶油色雙人沙發（弧背）","sofa",["art-deco"],
       ["love seat","ecru velvet","curved back"],["ecru","cream","ivory"],
       32000,"W155xD85xH80","curved-back ecru velvet love seat with gold nail-head trim, art deco boudoir"),
    tb("ad-brass-stair-light","黃銅階梯壁燈（10只組）","lighting",["art-deco"],
       ["step light","brass","staircase wall"],["brass","warm white"],
       15000,"Set of 10","brass half-sphere stair step wall lights set of 10, art deco staircase drama"),
    tb("ad-velvet-pouf-round","圓形天鵝絨矮墩（孔雀藍）","chair",["art-deco"],
       ["round pouf","velvet","peacock"],["peacock blue","teal"],
       6500,"Dia60xH35","peacock blue velvet round tufted pouf, gold bun feet, art deco lounge accent"),
    tb("ad-geometric-bookend","黃銅幾何書擋（一對）","accessory",["art-deco"],
       ["bookend","brass","geometric"],["polished brass","gold"],
       2500,"Pair, H15","pair of polished brass geometric triangular bookends, art deco desk styling"),
    tb("ad-enamel-clock","琺瑯掛鐘（黑金）","accessory",["art-deco"],
       ["enamel clock","black","gold hands"],["black enamel","gold"],
       2800,"Dia35","matte black enamel wall clock with gold Roman numeral face, art deco study"),
    tb("ad-feather-wall-art","羽毛装飾畫（金框）","accessory",["art-deco"],
       ["feather art","framed","glamour"],["black feather","gold frame"],
       8000,"W60xH80","black ostrich feather framed wall art, gold shadow-box frame, art deco boudoir"),
    tb("ad-velvet-dining-chair-set","絲絨餐椅（6張，孔雀綠）","chair",["art-deco"],
       ["dining chair set","velvet","peacock green"],["peacock green","gold legs"],
       36000,"Set of 6","set of 6 peacock green velvet dining chairs with gold legs, art deco dining room"),
    tb("ad-floor-lamp-crane","丹頂鶴造型落地燈","lighting",["art-deco"],
       ["crane floor lamp","sculptural","art deco"],["gold","white"],
       22000,"H180","sculptural gold crane floor lamp, art deco statement piece for living room corner"),
    tb("ad-smoked-mirror-wall","煙薰玻璃鏡面牆板","mirror",["art-deco"],
       ["smoked mirror","wall panel","glamour"],["smoked glass","gold edging"],
       35000,"Custom size per panel","smoked glass mirror wall panel with gold edge trim, art deco accent wall"),
    tb("ad-lacquer-bed-side","黑漆金邊床頭櫃（一對）","storage",["art-deco"],
       ["nightstand pair","black lacquer","gold edge"],["black gloss","gold"],
       16000,"Pair, W50xD40xH55","pair of black gloss lacquer nightstands with gold edge trim, art deco bedroom"),
    tb("ad-vintage-radio-decor","裝飾復古收音機（金棕）","accessory",["art-deco"],
       ["vintage radio","decorative","art deco prop"],["gold","walnut brown"],
       3500,"W25xH15","decorative vintage-style art deco radio prop, gold and walnut finish, shelf accent"),

    # ── BOHO (35 items) ────────────────────────────────────────────────────
    tb("boho-macrame-wall-large","大型繩編掛飾（三角）","accessory",["boho"],
       ["macrame wall hanging","large","triangle"],["natural cotton","cream"],
       5500,"W120xH180","large natural cotton macrame triangle wall hanging, boho bedroom statement"),
    tb("boho-rattan-chair-egg","橢圓藤製蛋形椅","chair",["boho"],
       ["egg chair","rattan","hanging"],["natural rattan","white cushion"],
       15000,"Dia80xH120 (with frame)","natural rattan egg-shaped hanging chair with white cushion, boho porch or living"),
    tb("boho-jute-rug-large","黃麻天然地毯（大，3x4m）","rug",["boho"],
       ["jute rug","natural fibre","large"],["natural jute","golden brown"],
       18000,"300x400cm","large natural jute area rug, chunky weave texture, boho living room or bedroom"),
    tb("boho-hanging-plant-cluster","懸吊植物群組（6個）","plant",["boho"],
       ["hanging planters","cluster","macrame"],["terracotta","natural rope"],
       5000,"Set of 6","set of 6 terracotta hanging planters with macrame ropes, boho indoor jungle"),
    tb("boho-floor-lamp-beaded","串珠流蘇落地燈","lighting",["boho"],
       ["beaded floor lamp","fringe","eclectic"],["cream beads","natural rope"],
       8500,"H155","floor lamp with beaded fringe shade, warm ambient glow, boho eclectic living room"),
    tb("boho-layered-rug-set","多層地毯組合（2件）","rug",["boho"],
       ["layered rugs","mix match","boho floor"],["rust orange","natural cream"],
       8000,"Set (80x120 + 160x230)","rust orange patterned rug layered with natural cream jute, boho rug styling"),
    tb("boho-rattan-shelf","藤編展示書架（3層）","storage",["boho"],
       ["rattan shelf","3-tier","natural"],["natural rattan","light wood"],
       6500,"W70xD35xH120","natural rattan 3-tier open bookshelf with solid wood frame, boho living room"),
    tb("boho-canopy-bed-linen","白色棉麻天篷床（皇后）","bed",["boho"],
       ["canopy bed","cotton","linen","white"],["white","off-white"],
       28000,"W153xD213xH220 (queen)","white cotton canopy bed with gauze draping, relaxed boho bedroom"),
    tb("boho-cotton-hammock","室內棉編吊床（彩條）","accessory",["boho"],
       ["hammock","indoor","cotton"],["multicolour stripes","cream"],
       5500,"L200xW140","indoor cotton woven hammock with wooden spreader bars, boho bedroom or patio"),
    tb("boho-pampas-grass-bunch","乾燥蒲葦草（大束）","plant",["boho"],
       ["pampas grass","dried","natural"],["cream","golden beige"],
       2000,"H100cm","large bundle of dried natural pampas grass stems, boho vase or floor display"),
    tb("boho-ceramic-table-lamp","不對稱手拋陶瓷台燈（赭石）","lighting",["boho"],
       ["ceramic lamp","ochre","earthy"],["ochre","terracotta"],
       6500,"H40","hand-thrown ochre ceramic table lamp with linen shade, boho earthy bedroom"),
    tb("boho-rattan-mirror","藤編編織圓鏡","mirror",["boho","nordic"],
       ["rattan mirror","woven","natural"],["natural rattan","brown"],
       4500,"Dia70","circular natural rattan woven-frame wall mirror, boho or coastal bedroom"),
    tb("boho-tapestry-mandala","曼陀羅掛毯（砖紅）","accessory",["boho"],
       ["tapestry","mandala","wall hanging"],["brick red","rust","ivory"],
       2500,"W150xH130","block-print mandala tapestry in rust red and cream, boho bedroom wall or bedspread"),
    tb("boho-vintage-kilim-rug","土耳其基利姆地毯（暖色）","rug",["boho"],
       ["kilim rug","Turkish","vintage"],["rust","terracotta","cream"],
       22000,"160x240cm","vintage Turkish kilim flat-weave wool rug, warm rust and terracotta tones, boho"),
    tb("boho-rattan-dining-chair","藤編餐椅（含坐墊）","chair",["boho"],
       ["rattan dining chair","cushion seat","natural"],["natural rattan","off-white cushion"],
       5500,"W50xD55xH82","natural rattan dining chair with removable off-white cushion, boho dining room"),
    tb("boho-hanging-moon-chair","月亮形吊椅（棉麻）","chair",["boho"],
       ["moon chair","hanging","cotton linen"],["oatmeal","cream","natural"],
       12000,"Dia100xH150 (with rope)","crescent moon-shaped hanging swing chair in cotton linen, boho outdoor or bedroom"),
    tb("boho-dreamcatcher-large","大型夢境捕手（羽毛）","accessory",["boho"],
       ["dreamcatcher","large","feathers"],["cream","natural feathers","wood beads"],
       2800,"Dia40xH120","large handmade dreamcatcher with natural feathers and wood beads, boho bedroom"),
    tb("boho-floor-seating-set","落地坐墊組合（4件，摩洛哥）","textile",["boho"],
       ["floor cushion set","Moroccan","pouf"],["saffron yellow","coral","teal"],
       9500,"Set of 4","set of 4 Moroccan-style floor cushions in saffron, coral and teal, boho floor seating"),
    tb("boho-rattan-pendant-large","大型藤編球燈（Dia50）","lighting",["boho"],
       ["rattan pendant","large","globe"],["natural rattan","amber glow"],
       6500,"Dia50","oversized natural rattan globe pendant lamp, warm ambient dining or living light"),
    tb("boho-cactus-planter-set","仙人掌組合盆栽（5件）","plant",["boho"],
       ["cactus","succulent","desert plants"],["green","terracotta pots"],
       2500,"Set of 5","5-piece cactus and succulent arrangement in terracotta pots, boho desert vibe"),
    tb("boho-moroccan-lantern","摩洛哥鏤空提燈（銅色）","lighting",["boho"],
       ["Moroccan lantern","copper","cutwork"],["antique copper","amber glass"],
       3500,"H40","antique copper cutwork Moroccan lantern with amber glass panels, boho patio or living"),
    tb("boho-tribal-print-pillow-set","部落花紋靠枕組（4件）","textile",["boho"],
       ["tribal pillow","mixed patterns","boho"],["terracotta","navy","cream"],
       4000,"Set of 4, 45x45cm","set of 4 mixed tribal-print cotton cushion covers in earthy tones, boho living"),
    tb("boho-weave-basket-set","竹編收納籃套裝（3件）","storage",["boho"],
       ["basket set","seagrass","storage"],["natural seagrass","black pattern"],
       3500,"Set of 3","3-piece nesting seagrass woven storage baskets with geometric black pattern, boho"),
    tb("boho-linen-duvet-terracotta","赭石色水洗亞麻被套","textile",["boho"],
       ["linen duvet","terracotta","washed"],["terracotta","rust orange"],
       5000,"Queen size","washed linen duvet cover in terracotta, relaxed crumpled texture, boho bedroom"),
    tb("boho-wood-bead-chandelier","木珠串吊燈","lighting",["boho"],
       ["wood bead chandelier","boho pendant","natural"],["natural wood beads","cream"],
       9500,"Dia50xH60","natural wood bead chandelier with fringe strands, warm boho dining or bedroom light"),
    tb("boho-plant-wall-frame","植物牆框（苔蘚藝術）","plant",["boho","nordic"],
       ["moss wall art","preserved","green frame"],["forest green","natural wood"],
       8500,"W60xH40","preserved natural moss wall art in wooden frame, living wall accent, boho style"),
    tb("boho-rattan-bar-stool","藤編吧台高椅","chair",["boho"],
       ["rattan bar stool","counter height","natural"],["natural rattan","white cushion"],
       6000,"W45xD50xH75","natural rattan counter-height bar stool with cushion seat, boho kitchen island"),
    tb("boho-woven-throw","多彩編織毯（手工）","textile",["boho"],
       ["woven throw","handmade","multicolour"],["mustard yellow","rust","cream"],
       2800,"130x160cm","handwoven cotton throw blanket in mustard, rust and cream stripes, boho bed or sofa"),
    tb("boho-terracotta-floor-lamp","赭石陶瓦落地燈","lighting",["boho"],
       ["terracotta lamp","floor lamp","earthy"],["terracotta clay","linen shade"],
       9000,"H160","terracotta-coloured ceramic base floor lamp with natural linen shade, boho earthy"),
    tb("boho-gallery-wall-set","藝術畫組（6件混搭）","accessory",["boho"],
       ["gallery wall","mixed media","eclectic"],["earthy tones","natural"],
       5500,"Set of 6, various","6-piece gallery wall art set with mixed media botanical and abstract prints, boho"),
    tb("boho-rattan-storage-chest","藤編儲物箱（帶蓋）","storage",["boho"],
       ["rattan chest","wicker storage","lidded box"],["natural rattan"],
       8000,"W80xD45xH45","natural rattan lidded storage chest, vintage-inspired, boho living room blanket box"),
    tb("boho-velvet-curtain-terra","赭石色天鵝絨窗簾","textile",["boho"],
       ["velvet curtain","terracotta","earthy"],["terracotta velvet","rust"],
       7000,"W140xH260 per panel","terracotta velvet curtain panel, rich texture, boho bedroom or living room"),
    tb("boho-crystal-wind-chime","天然水晶風鈴","accessory",["boho"],
       ["crystal wind chime","amethyst","quartz"],["purple amethyst","clear quartz"],
       2200,"H45","natural amethyst and clear quartz crystal wind chime, boho spiritual decor"),
    tb("boho-rattan-headboard","藤編床頭板（雙人）","bed",["boho"],
       ["rattan headboard","woven","natural"],["natural rattan","honey brown"],
       12000,"W150xH120","natural rattan woven panel headboard for queen bed, boho bedroom centrepiece"),
    tb("boho-moroccan-pouffe","摩洛哥手工皮革椅墩","chair",["boho"],
       ["moroccan pouffe","leather","embossed"],["tan leather","natural dye"],
       4500,"Dia45xH30","hand-stitched Moroccan leather floor pouf in tan with embossed pattern, boho lounge"),

    # ── INDUSTRIAL (40 items) ──────────────────────────────────────────────
    tb("ind-sofa-leather-black","黑色真皮三人沙發（工業）","sofa",["industrial"],
       ["leather sofa","black","3-seater"],["black genuine leather","matte black metal"],
       48000,"W220xD90xH78","black genuine leather 3-seater sofa with exposed rivets and matte black metal legs"),
    tb("ind-factory-shelf","工廠金屬置物架（5層）","storage",["industrial"],
       ["factory shelf","metal","5-tier"],["matte black steel","reclaimed wood"],
       12000,"W120xD35xH180","5-tier matte black steel angle shelf with reclaimed wood boards, industrial warehouse"),
    tb("ind-concrete-coffee-table","水泥面茶几（鐵腳）","table",["industrial"],
       ["concrete coffee table","steel legs","heavy duty"],["grey concrete","matte black"],
       15000,"W100xD60xH42","polished concrete top coffee table on welded black steel pipe legs, industrial loft"),
    tb("ind-edison-pendant-cluster","愛迪生燈泡集群吊燈（12頭）","lighting",["industrial"],
       ["Edison cluster pendant","12-bulb","exposed","ceiling"],["bronze","amber bulb"],
       18000,"Span80xH60","12-bulb exposed Edison filament cluster pendant chandelier, industrial ceiling statement"),
    tb("ind-pipe-bookcase","水管支架書架（4層）","storage",["industrial"],
       ["pipe shelf","pipe bookcase","dark steel"],["dark iron pipe","reclaimed walnut"],
       9500,"W100xD30xH160","reclaimed walnut shelves on hand-bent black iron pipe frame, industrial bookcase"),
    tb("ind-riveted-dining-table","鉚釘钢板餐桌","table",["industrial"],
       ["steel dining table","riveted","industrial"],["brushed steel","raw steel"],
       35000,"W200xD90xH76","brushed steel top dining table with riveted apron, factory-floor industrial style"),
    tb("ind-wire-basket-storage","鐵絲網收納籃（套裝3件）","storage",["industrial"],
       ["wire basket","metal mesh","storage"],["matte black"],
       2500,"Set of 3","set of 3 matte black wire mesh storage baskets, stackable, industrial office or kitchen"),
    tb("ind-concrete-wall-lamp","水泥壁燈（1頭）","lighting",["industrial"],
       ["concrete wall lamp","sconce","cement"],["raw concrete","black cord"],
       3500,"H20","raw concrete wall lamp with exposed black braided cord, industrial loft bathroom or corridor"),
    tb("ind-vintage-locker","復古金屬置物柜（6格）","storage",["industrial"],
       ["metal locker","vintage","6-door"],["army green","grey","matte black"],
       22000,"W90xD45xH180","vintage-style metal 6-door locker cabinet, industrial garage or mudroom storage"),
    tb("ind-factory-stool","工廠圓形鐵凳（可調高）","chair",["industrial"],
       ["factory stool","adjustable","metal"],["raw steel","matte black"],
       3500,"Dia36xH56-75","adjustable-height raw steel industrial factory stool, vintage workshop aesthetic"),
    tb("ind-track-light-4head","軌道燈（4頭，黑色）","lighting",["industrial"],
       ["track light","4-spot","black"],["matte black","white bulb"],
       5500,"90cm track, 4 heads","matte black 4-head track lighting system, industrial kitchen or gallery"),
    tb("ind-metal-bed-black","黑色金屬管框床架（雙人）","bed",["industrial"],
       ["metal bed frame","black","pipe style"],["matte black metal"],
       15000,"W153xD213 (queen)","matte black steel pipe-frame bed, exposed corner joints, industrial loft bedroom"),
    tb("ind-chalkboard-wall","大黑板牆面板（木框）","accessory",["industrial"],
       ["chalkboard","blackboard","magnetic"],["black chalkboard","dark wood frame"],
       6500,"W120xH90","full-surface blackboard with wood frame, industrial office or kitchen memo wall"),
    tb("ind-caged-floor-lamp","鐵籠落地燈（黃銅燈泡）","lighting",["industrial"],
       ["cage floor lamp","wire cage","industrial"],["matte black","aged brass"],
       8500,"H160","matte black iron cage floor lamp with aged brass socket and Edison bulb, industrial"),
    tb("ind-scaffold-table","腳手架課桌（可折疊）","desk",["industrial"],
       ["scaffold table","folding","industrial desk"],["silver steel","pine board"],
       8000,"W120xD60xH75","folding scaffold-style steel and pine writing desk, industrial home office"),
    tb("ind-distressed-leather-chair","做舊皮革單人椅","chair",["industrial"],
       ["distressed leather","club chair","vintage"],["aged cognac","brown"],
       22000,"W82xD80xH78","aged cognac distressed genuine leather club chair with nail-head trim, industrial bar"),
    tb("ind-duct-lamp","工業風管道燈（3頭）","lighting",["industrial"],
       ["duct lamp","pipe fixture","3-light"],["matte black pipe","vintage brass"],
       9500,"W80xH30","matte black iron duct pipe 3-light ceiling fixture, industrial kitchen or dining"),
    tb("ind-brick-wall-panel","仿磚牆壁板（砂漿色）","accessory",["industrial"],
       ["faux brick","wall panel","texture"],["red-brown brick","mortar grey"],
       3500,"W100xH50 per panel","faux exposed brick PU wall panel, lightweight, industrial accent wall DIY"),
    tb("ind-welded-coffee-table","焊接角鋼茶几（木板面）","table",["industrial"],
       ["welded coffee table","angle iron","wood top"],["raw black steel","natural oak"],
       12000,"W90xD60xH45","hand-welded black steel angle-iron coffee table with solid oak plank top, industrial"),
    tb("ind-factory-cart","工廠推車茶几（3層）","table",["industrial"],
       ["factory cart","trolley","industrial coffee"],["black iron wheels","reclaimed wood"],
       9000,"W80xD45xH55","vintage factory trolley repurposed as 3-tier coffee table, iron casters, industrial"),
    tb("ind-wall-clock-gear","齒輪掛鐘（鐵鏽色）","accessory",["industrial"],
       ["gear clock","iron rust","wall clock"],["rust iron","antique"],
       2200,"Dia45","oversized rust-iron gear design wall clock, industrial loft or workspace statement"),
    tb("ind-pendant-mesh-shade","網狀金屬燈罩吊燈（5頭）","lighting",["industrial"],
       ["mesh shade pendant","5-head","bar light"],["matte black","mesh"],
       12000,"W100xH20","5-head matte black mesh shade bar pendant light, industrial kitchen island or bar"),
    tb("ind-open-concept-wardrobe","開放式蒸汽管衣架","storage",["industrial"],
       ["open wardrobe","pipe rack","clothes rail"],["black iron pipe","reclaimed wood"],
       8500,"W150xD45xH200","black iron pipe open wardrobe system with reclaimed wood shelf, industrial bedroom"),
    tb("ind-wire-chair-dining","鐵絲網餐椅（復古白）","chair",["industrial"],
       ["wire chair","Bertoia style","dining"],["chrome wire","white powder coat"],
       4500,"W48xD55xH75","Bertoia-inspired chrome wire dining chair, industrial-mid-century hybrid"),
    tb("ind-neon-sign-custom","霓虹燈牌（客製化）","lighting",["industrial"],
       ["neon sign","LED","custom word"],["warm white neon","black backing"],
       8000,"W50xH20","custom LED neon sign on matte black acrylic backing, industrial bar or home office"),
    tb("ind-pegboard-tool-wall","工具掛板系統（黑）","storage",["industrial"],
       ["pegboard tools","wall storage","black metal"],["matte black"],
       4500,"W90xH60","matte black metal pegboard with hooks and accessory kit, industrial workshop or garage"),
    tb("ind-bar-stool-mesh","網狀金屬吧台椅","chair",["industrial"],
       ["bar stool","mesh seat","footrest"],["matte black","mesh"],
       3800,"W42xD42xH75","matte black mesh seat bar stool with ring footrest, industrial kitchen or bar"),
    tb("ind-concrete-floor-vase","混凝土地板花器（大）","plant",["industrial"],
       ["concrete planter","large","floor vase"],["grey concrete","raw finish"],
       5000,"Dia30xH60","raw grey concrete tall floor planter, industrial loft statement plant display"),
    tb("ind-metal-wall-art-gears","齒輪裝飾壁掛","accessory",["industrial"],
       ["gear wall art","metal decor","industrial"],["rusted iron","oxidised"],
       4500,"W60xH60","hand-welded rusted iron gear and cog wall art panel, industrial statement piece"),
    tb("ind-steamer-trunk","航海行李箱茶几","table",["industrial","boho"],
       ["trunk coffee table","vintage","storage"],["aged olive green","brass rivets"],
       12000,"W100xD55xH45","vintage-style olive canvas and brass-riveted steamer trunk repurposed as coffee table"),
    tb("ind-enamel-lamp-shade","琺瑯燈罩台燈（綠）","lighting",["industrial"],
       ["enamel shade","green lamp","gooseneck"],["factory green","black"],
       2200,"H40","classic factory green enamel shade gooseneck desk lamp, industrial office or workshop"),
    tb("ind-wire-pendant-cage","裸燈泡鐵籠吊燈（3頭）","lighting",["industrial"],
       ["wire cage pendant","3-head","exposed bulb"],["matte black cage","amber bulb"],
       6500,"Span50xH40","3-head matte black wire cage pendant light with Edison bulbs, industrial bar or kitchen"),
    tb("ind-reclaimed-wood-dining","回收老木板餐桌","table",["industrial"],
       ["reclaimed wood table","dining","live edge"],["reclaimed pine","black steel"],
       38000,"W180xD90xH76","hand-finished reclaimed pine plank dining table on black steel trestle, industrial"),
    tb("ind-rug-distressed-grey","做舊灰色地毯","rug",["industrial"],
       ["distressed rug","grey","vintage look"],["charcoal grey","dark grey"],
       12000,"200x300cm","machine-washed distressed grey area rug, vintage industrial look for loft spaces"),
    tb("ind-vintage-suitcase-shelf","復古手提箱層架","storage",["industrial","boho"],
       ["suitcase shelf","vintage luggage","display"],["aged brown leather","brass"],
       6000,"W60xH90 (3-tier stacked)","stacked vintage leather suitcases converted to display shelves, industrial boho"),
    tb("ind-gunmetal-bathroom","槍鐵灰浴室配件組（5件）","accessory",["industrial"],
       ["gunmetal bathroom","matte black fittings","5-piece"],["gunmetal","matte black"],
       5500,"Set of 5","5-piece gunmetal bathroom accessory set (toothbrush holder, soap pump, tray, towel ring, hook)"),
    tb("ind-pipe-mirror","鍍黑鐵管框全身鏡","mirror",["industrial"],
       ["pipe frame mirror","black iron","full length"],["matte black iron pipe"],
       8500,"W60xH180","matte black iron pipe-frame full-length leaning mirror, industrial bedroom or bathroom"),
    tb("ind-hexagon-tile","六角形水泥磚地板磚（箱裝）","accessory",["industrial"],
       ["hexagon tile","cement tile","floor"],["charcoal grey","white"],
       3500,"Box of 11 tiles (1m2)","charcoal hexagonal cement tile, DIY floor or feature wall, industrial kitchen"),
    tb("ind-copper-pipe-lamp","銅管壁燈（1頭）","lighting",["industrial"],
       ["copper pipe sconce","wall lamp","exposed"],["antique copper","amber bulb"],
       3200,"H30","antique copper pipe wall sconce with bare Edison filament bulb, industrial or steam-punk"),

    # ── MEDITERRANEAN (35 items) ────────────────────────────────────────────
    tb("med-arch-mirror","拱形白色石灰牆鏡","mirror",["mediterranean"],
       ["arch mirror","white plaster","Mediterranean"],["white chalk","plaster white"],
       8500,"W70xH140","arch-shaped white plastered wall mirror, Santorini Mediterranean whitewash"),
    tb("med-blue-ceramic-vase","藍釉彩繪陶瓷花器（大）","accessory",["mediterranean"],
       ["blue glaze","ceramic vase","Mediterranean"],["cobalt blue","white","terracotta"],
       3500,"Dia20xH35","large cobalt blue hand-painted ceramic vase, Mediterranean coastal display"),
    tb("med-rattan-chair-white","白色藤椅（圓背）","chair",["mediterranean"],
       ["white rattan chair","round back","coastal"],["white painted rattan"],
       6500,"W60xD65xH85","white-painted rattan round-back dining chair, Mediterranean coastal dining room"),
    tb("med-terracotta-pot-set","赭石大型陶土盆組（3件）","plant",["mediterranean"],
       ["terracotta pot","large","set of 3"],["terracotta","clay red"],
       5500,"Set of 3, Dia25-40","set of 3 unglazed terracotta outdoor/indoor pots, authentic Mediterranean garden"),
    tb("med-mosaic-table-round","馬賽克圓形邊桌（藍白）","table",["mediterranean"],
       ["mosaic table","blue white","round"],["cobalt blue mosaic","white grout"],
       8000,"Dia60xH70","hand-laid cobalt blue and white mosaic tile round bistro table, Mediterranean patio"),
    tb("med-linen-sofa-white","白色亞麻四人沙發","sofa",["mediterranean"],
       ["white sofa","linen","4-seater"],["white","pure linen"],
       42000,"W250xD90xH82","pure white linen oversized sofa, relaxed coastal Mediterranean living room"),
    tb("med-tile-side-table","西班牙花磚邊桌","table",["mediterranean"],
       ["tile table","Spanish tile","side table"],["hand-painted tile","blue white"],
       5500,"Dia40xH55","hand-painted Spanish azulejo tile-top round side table, Mediterranean accent"),
    tb("med-driftwood-mirror","漂流木圓鏡","mirror",["mediterranean","boho"],
       ["driftwood mirror","coastal","natural"],["natural driftwood","bleached wood"],
       6500,"Dia70","driftwood-frame round wall mirror, bleached coastal Mediterranean or boho"),
    tb("med-blue-shutter-headboard","藍色百葉窗板改造床頭板","bed",["mediterranean"],
       ["shutter headboard","blue","Mediterranean"],["shuttered blue","ocean blue"],
       12000,"W180xH100","repurposed blue wood louvered shutters as statement queen bed headboard, Mediterranean"),
    tb("med-canopy-outdoor-chair","戶外白色帆布涼椅","chair",["mediterranean"],
       ["director chair","canvas","outdoor"],["white canvas","natural wood"],
       4500,"W60xD55xH90","white canvas and solid acacia wood director chair, Mediterranean terrace or patio"),
    tb("med-wrought-iron-lamp","鍛鐵壁燈（地中海藍）","lighting",["mediterranean"],
       ["wrought iron sconce","blue glass","lantern"],["black iron","cobalt glass"],
       4500,"H25","black wrought-iron wall lantern with cobalt blue glass panels, Mediterranean villa"),
    tb("med-white-shelving-niche","白色拱形壁龕置物架","storage",["mediterranean"],
       ["niche shelf","arch","white plaster"],["plaster white"],
       8000,"W60xH90","arched white plaster-finish wall niche shelf unit, Mediterranean interior feature"),
    tb("med-stripe-cotton-rug","藍白條紋棉地毯","rug",["mediterranean"],
       ["stripe rug","blue white","cotton"],["cobalt blue","white"],
       5000,"160x240cm","blue and white thick-stripe cotton flatweave rug, Mediterranean fresh living room"),
    tb("med-olive-wood-bowl","橄欖木沙拉碗（大）","accessory",["mediterranean"],
       ["olive wood bowl","salad bowl","kitchen"],["natural olive wood","golden"],
       2500,"Dia35","large hand-carved olive wood salad bowl, Mediterranean kitchen table centrepiece"),
    tb("med-lemon-tree-planter","室內檸檬樹（連花盆）","plant",["mediterranean"],
       ["lemon tree","indoor citrus","potted"],["dark green leaves","yellow fruit"],
       6500,"H120 (approx)","indoor potted lemon tree, Mediterranean sunroom or bright living room"),
    tb("med-fishnet-wall-decor","漁網牆面裝飾","accessory",["mediterranean"],
       ["fishnet decor","coastal","rope net"],["natural rope","white","sea shells"],
       2000,"W100xH80","decorative rope fishnet with shells and starfish, Mediterranean coastal wall art"),
    tb("med-blue-door-cabinet","地中海藍色書櫃（4門）","storage",["mediterranean"],
       ["blue cabinet","4-door","Mediterranean"],["ocean blue","antiqued white"],
       22000,"W160xD45xH85","Mediterranean blue distressed-finish 4-door sideboard, antiqued white surround"),
    tb("med-rattan-pendant-coastal","沿海白色藤製吊燈","lighting",["mediterranean"],
       ["white rattan pendant","coastal","hanging"],["painted white rattan"],
       5000,"Dia40","white-painted rattan woven pendant lamp, coastal Mediterranean dining room"),
    tb("med-hammock-cotton-stripe","戶外條紋棉吊床","accessory",["mediterranean"],
       ["hammock","outdoor","stripe"],["blue white stripe","natural cotton"],
       4500,"L200","blue and white striped cotton outdoor hammock, Mediterranean patio lounging"),
    tb("med-vintage-tiles-set","復古陶磁磚壁掛（12片組）","accessory",["mediterranean"],
       ["vintage tiles","decorative","wall art"],["hand-painted","blue white"],
       4500,"Set of 12, 15x15cm each","set of 12 hand-painted azulejo decorative tiles, Mediterranean kitchen or bathroom"),
    tb("med-rush-seat-chair","燈芯草坐面餐椅","chair",["mediterranean"],
       ["rush seat chair","natural","bistro"],["natural rush","white painted wood"],
       4000,"W46xD48xH88","white painted wood bistro chair with woven rush seat, Mediterranean kitchen"),
    tb("med-blue-striped-cushion","地中海藍白條紋靠枕（4件）","textile",["mediterranean"],
       ["stripe cushion","blue white","Mediterranean"],["cobalt blue","white"],
       2500,"Set of 4, 45x45cm","4-piece cobalt blue and white stripe outdoor/indoor cushion set, Mediterranean patio"),
    tb("med-terracotta-floor-tile","赭石色六角花磚（箱裝）","accessory",["mediterranean"],
       ["terracotta floor tile","hexagonal","Mediterranean"],["terracotta","clay"],
       3500,"Box 10 tiles (1m2)","handmade terracotta hexagonal floor tiles, authentic Mediterranean kitchen or patio"),
    tb("med-alabaster-lamp","雪花石膏吊燈","lighting",["mediterranean"],
       ["alabaster pendant","stone lamp","warm glow"],["natural alabaster","stone white"],
       18000,"Dia30","natural alabaster stone pendant lamp, warm glowing diffuse light, Mediterranean villa"),
    tb("med-whitewash-bedframe","白色石灰塗裝床架","bed",["mediterranean"],
       ["whitewash bed","lime finish","coastal"],["whitewash white","rustic wood"],
       18000,"W153xD213 (queen)","whitewash-finish solid wood queen bed frame, rustic Mediterranean coastal bedroom"),
    tb("med-linen-tablecloth","亞麻餐桌布（白/藍條紋）","textile",["mediterranean"],
       ["linen tablecloth","white blue","dining"],["white linen","blue stripe"],
       1500,"W140xH240","white linen tablecloth with blue stripe border, Mediterranean alfresco dining"),
    tb("med-wicker-dining-chair","藤條編織餐椅（白框）","chair",["mediterranean"],
       ["wicker chair","dining","white frame"],["white frame","natural wicker"],
       5500,"W50xD54xH84","white wood-frame wicker woven dining chair, Mediterranean outdoor or indoor dining"),
    tb("med-painted-wood-shutter","手繪藍色木製百葉窗裝飾","accessory",["mediterranean"],
       ["decorative shutter","blue painted","wall art"],["distressed blue","white"],
       2500,"W30xH80","pair of decorative hand-painted blue distressed wood shutter panels, Mediterranean wall decor"),
    tb("med-water-jug-ceramic","大型陶瓷水罐（土色）","accessory",["mediterranean"],
       ["ceramic jug","terracotta","amphora"],["terracotta red","earth tones"],
       3500,"H45","large terracotta-finish ceramic amphora-style jug, Mediterranean hallway or garden"),
    tb("med-coastal-bench","海岸風木質長凳","chair",["mediterranean"],
       ["coastal bench","driftwood","white"],["bleached white pine","sand"],
       8000,"W120xD35xH45","bleached white pine coastal bench, distressed finish, Mediterranean entryway"),
    tb("med-olive-wood-cutting","橄欖木砧板（L型把手）","accessory",["mediterranean"],
       ["cutting board","olive wood","serving"],["natural olive","golden wood"],
       2200,"W35xH25","large L-handle olive wood chopping and serving board, Mediterranean kitchen styling"),
    tb("med-blue-outdoor-rug","地中海藍戶外地毯","rug",["mediterranean"],
       ["outdoor rug","blue","Mediterranean patio"],["blue","white stripe"],
       6500,"150x240cm","UV-resistant blue striped outdoor rug, Mediterranean terrace or patio"),
    tb("med-whitewash-dresser","白灰塗裝6抽梳妝台","storage",["mediterranean"],
       ["whitewash dresser","6-drawer","coastal"],["whitewash white","brushed chrome handles"],
       18000,"W110xD50xH130","6-drawer whitewash solid wood dresser, distressed coastal Mediterranean bedroom"),
    tb("med-lantern-hanging-set","懸掛式玻璃燈籠組（3件）","lighting",["mediterranean"],
       ["hanging lantern","glass","set of 3"],["clear glass","black iron"],
       5000,"Set of 3, H30","set of 3 clear glass and black iron hanging lanterns, Mediterranean porch or dining"),
    tb("med-coastal-mirror-round","海岸風圓鏡（貝殼框）","mirror",["mediterranean"],
       ["seashell mirror","coastal","round"],["natural shells","white frame"],
       5500,"Dia60","round mirror with natural seashell mosaic frame, Mediterranean coastal bathroom or bedroom"),
]

def main():
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)
    print(f"Current items: {len(existing)}")
    existing_names = {item["name_zh"] for item in existing}
    new_items = [item for item in BATCH3 if item["name_zh"] not in existing_names]
    print(f"Adding: {len(new_items)}")
    merged = existing + new_items
    print(f"Total: {len(merged)}")
    style_count = {}
    for item in merged:
        s = item.get("style_tags", ["unknown"])[0]
        style_count[s] = style_count.get(s, 0) + 1
    for s, c in sorted(style_count.items()):
        print(f"  {s:15s}: {c}")
    with open(CATALOG_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print("Done.")

if __name__ == "__main__":
    main()
