"""生成 225 件家具目錄（9 風格 × 25 件）"""
import json

def tb(id_, name_zh, cat, styles, keywords, colors, price, dims, flux):
    return {"id": f"tb-{id_}", "name_zh": name_zh, "brand": "淘寶精選",
            "category": cat, "style_tags": styles, "keywords": keywords,
            "colors": colors, "price_twd": price, "image_url": "",
            "purchase_url": f"https://s.taobao.com/search?q={name_zh.replace(' ','+')[:20]}",
            "dimensions": dims, "flux_descriptor": flux}

def ik(id_, name_zh, cat, styles, keywords, colors, price, dims, flux, pid=""):
    img = f"https://www.ikea.com/tw/zh/images/products/{id_}__s5.jpg"
    # Google search always works — "IKEA SODERHAMN 台灣" finds the correct TW product page
    product_code = id_.split("-")[0].upper()
    url = f"https://www.google.com/search?q=IKEA+{product_code}+台灣"
    return {"id": f"ikea-{id_}", "name_zh": name_zh, "brand": "IKEA",
            "category": cat, "style_tags": styles, "keywords": keywords,
            "colors": colors, "price_twd": price, "image_url": img,
            "purchase_url": url, "dimensions": dims, "flux_descriptor": flux}

ITEMS = [
# ── MODERN 現代簡約 ──────────────────────────────────────────────────────────
ik("soderhamn-sofa","SÖDERHAMN 沙發（亞麻米白）","sofa",["modern","nordic","muji"],
   ["linen sofa","minimalist sofa","low profile sofa"],["beige","off-white","linen"],
   22900,"W186xD99xH83","low-profile linen sofa, beige fabric, minimalist clean legs","s79306585"),
ik("lack-coffee-white","LACK 茶几（白色）","table",["modern","muji"],
   ["white coffee table","minimalist table"],["white","off-white"],
   799,"W90xD55xH45","flat white coffee table, minimalist rectangular","20011408"),
ik("kallax-oak","KALLAX 層架（橡木紋）","shelving",["modern","nordic","muji"],
   ["open shelving","oak shelving","modular storage"],["oak","light wood"],
   3999,"W77xD39xH77","oak modular shelf unit, open storage grid","80275887"),
ik("hektar-pendant","HEKTAR 吊燈（深灰）","lighting",["modern","industrial"],
   ["metal pendant","industrial pendant","dark pendant"],["dark grey","charcoal"],
   1499,"Dia38","metal dome pendant, dark grey matte, industrial style","00336239"),
ik("besta-tv-white","BESTÅ 電視櫃（白）","storage",["modern","muji"],
   ["TV console","floating cabinet","white storage"],["white"],
   4999,"W180xD42xH38","white floating TV console, handle-less modern cabinet","49295595"),
ik("billy-bookcase-white","BILLY 書架（白）","shelving",["modern","muji","nordic"],
   ["bookcase","white shelf","tall storage"],["white"],
   1990,"W80xD28xH202","white bookcase, clean vertical lines, adjustable shelves","00263850"),
ik("malm-6drawer","MALM 六斗櫃（白）","storage",["modern","muji"],
   ["white dresser","6 drawer","bedroom storage"],["white"],
   9990,"W160xD48xH78","white 6-drawer dresser, clean horizontal lines","90174773"),
ik("lisabo-dining-table","LISABO 餐桌（梣木貼皮）","table",["modern","nordic"],
   ["ash veneer dining table","slim legs","minimalist dining"],["ash","light wood","warm wood"],
   6990,"W140xD78xH74","ash veneer dining table, slim black legs, Scandinavian modern","70301704"),
ik("henriksdal-chair","HENRIKSDAL 餐椅（白/棉麻）","chair",["modern","nordic"],
   ["upholstered dining chair","linen chair","white frame chair"],["white","beige","linen"],
   3990,"W56xD59xH95","white frame dining chair, linen upholstery, Scandinavian modern","39119643"),
ik("symfonisk-lamp-speaker","SYMFONISK 音箱燈（白）","lighting",["modern"],
   ["speaker lamp","smart lamp","table lamp"],["white"],
   6990,"Dia22xH37","white lamp with built-in speaker, minimalist modern tech","39286765"),
ik("sinnerlig-pendant-bamboo","SINNERLIG 吊燈（竹/自然色）","lighting",["modern","japanese","nordic"],
   ["bamboo pendant","natural pendant","warm pendant"],["bamboo","natural"],
   1499,"Dia35","bamboo weave pendant, warm diffused light, natural modern","10261726"),
ik("skarsta-desk","SKARSTA 升降桌（白）","table",["modern","muji"],
   ["standing desk","adjustable desk","white desk"],["white"],
   10900,"W120xD70xH70-120","white height-adjustable desk, minimalist workspace","29239561"),
tb("modern-oak-tv","白橡木浮動電視櫃（推拉門）","storage",["modern"],
   ["floating TV console","white oak","wall-mounted cabinet"],["white oak","warm white"],
   8900,"W160xD35xH50","white oak floating TV console, push-open doors, modern Taiwanese apartment"),
tb("modern-concrete-side","霧面水泥感邊几","table",["modern","industrial"],
   ["concrete side table","matte concrete","minimalist side table"],["matte concrete grey"],
   2800,"Dia40xH55","matte concrete texture side table, industrial-modern hybrid"),
tb("modern-oak-diningchair","原木細腿餐椅（白橡木坐墊）","chair",["modern","nordic"],
   ["oak dining chair","slim legs chair","Scandinavian chair"],["oak","beige"],
   3200,"W45xD50xH80","solid oak dining chair, slim tapered legs, linen cushion"),
tb("modern-slim-bed","極簡白橡木床架（低床頭）","bed",["modern","muji"],
   ["slim bed frame","white oak bed","platform bed"],["white oak","warm white"],
   18000,"W150xD210xH25","low-profile white oak platform bed, minimal headboard"),
tb("modern-frosted-pendant","霧面玻璃吊燈（圓球）","lighting",["modern","muji"],
   ["frosted glass pendant","globe pendant","minimalist pendant"],["frosted white"],
   2200,"Dia20","frosted glass globe pendant, soft diffused glow, clean modern"),
tb("modern-linen-curtain","棉麻遮光窗簾（米白）","curtain",["modern","muji","nordic"],
   ["linen curtain","blackout curtain","minimalist curtain"],["off-white","linen"],
   3600,"W250xH270","linen semi-sheer curtain, off-white, minimal drape"),
tb("modern-al-floorlamp","拉絲鋁管落地燈","lighting",["modern"],
   ["brushed aluminum lamp","arc floor lamp","metal floor lamp"],["brushed silver","aluminum"],
   4500,"H165","brushed aluminum arc floor lamp, matte finish, task lighting"),
tb("modern-white-sofa","簡約白色布藝三人沙發","sofa",["modern"],
   ["white sofa","minimalist sofa","clean sofa"],["white","light grey"],
   16800,"W220xD90xH80","white fabric 3-seater sofa, straight arms, minimalist Taiwanese living room"),
tb("modern-marble-vase","大理石紋陶瓷花器（圓柱）","accessory",["modern","luxury"],
   ["marble vase","ceramic vase","modern vase"],["white marble","grey veins"],
   1200,"Dia12xH30","marble-patterned cylindrical ceramic vase, modern minimalist"),
tb("modern-led-strip","間接照明 LED 燈條套組","lighting",["modern"],
   ["LED strip","cove lighting","indirect lighting"],["warm white"],
   1500,"500cm","warm 3000K LED cove strip, indirect wall wash, modern ceiling detail"),
tb("modern-oak-coffee","橡木色長方形茶几（黑腳）","table",["modern"],
   ["oak coffee table","black legs","rectangular coffee table"],["oak","black"],
   5800,"W120xD60xH42","oak-finish rectangular coffee table, matte black metal legs"),
tb("modern-curtain-sheer","輕薄紗窗簾（白色飄逸）","curtain",["modern","mediterranean"],
   ["sheer curtain","voile curtain","light curtain"],["white","sheer"],
   2200,"W250xH270","white voile sheer curtain, airy drape, maximize natural light"),
tb("modern-wall-mirror","圓形黑框掛鏡（大）","mirror",["modern","industrial"],
   ["black round mirror","wall mirror","bathroom mirror"],["black","matte black"],
   3200,"Dia80","large round mirror, matte black thin frame, modern minimal"),

# ── JAPANESE 日式侘寂 ─────────────────────────────────────────────────────────
ik("nordkisa-bamboo-wardrobe","NORDKISA 開放式衣櫥（竹）","storage",["japanese","muji","nordic"],
   ["bamboo storage","open wardrobe","zen storage"],["bamboo","natural"],
   7999,"W120xD47xH180","bamboo open wardrobe, natural grain, Japanese minimalist","60458805"),
ik("knixhult-bamboo-lamp","KNIXHULT 落地燈（竹）","lighting",["japanese","boho","nordic"],
   ["paper lantern","bamboo lamp","natural lamp"],["bamboo","natural"],
   1999,"H150","bamboo floor lamp, paper shade, warm diffused glow","90458903"),
ik("sollinge-rug","SÖLLINGE 平織地毯（米白/棕）","rug",["japanese","muji","modern"],
   ["flat woven rug","natural rug","jute rug"],["natural","beige"],
   2999,"160x230","flat-woven natural fiber rug, beige minimalist texture","50518452"),
ik("sinnerlig-pendant-cork","SINNERLIG 吊燈（軟木）","lighting",["japanese","nordic","muji"],
   ["cork pendant","natural pendant","warm pendant"],["cork","natural brown"],
   1499,"Dia35","cork pendant lamp, organic texture, warm ambient glow","00261726"),
tb("jp-low-sofa","日式低矮沙發組（深灰麻布）","sofa",["japanese","boho"],
   ["low platform sofa","floor sofa","tatami sofa"],["dark grey","charcoal"],
   8500,"W180xD80xH30","low platform floor sofa, charcoal linen, Japanese minimalist seating"),
tb("jp-dining-table","日式矮腳餐桌（原木）","table",["japanese"],
   ["low dining table","Japanese dining table","natural wood table"],["natural wood","warm brown"],
   12000,"W160xD80xH35","solid wood low dining table, natural grain, floor-seating Japanese style"),
tb("jp-washi-pendant","和紙吊燈（圓球）","lighting",["japanese","muji"],
   ["washi paper lamp","paper lantern","Japanese pendant"],["cream","warm white"],
   1800,"Dia35","washi paper globe pendant, handmade texture, soft warm glow"),
tb("jp-cedar-shelf","杉木壁掛層板（一組3片）","shelving",["japanese","muji"],
   ["cedar shelf","wall shelf","floating shelf"],["cedar","natural wood"],
   3600,"W60xD20","natural cedar floating wall shelves, visible grain, wabi-sabi"),
tb("jp-stone-sidetable","石板面邊几（黑胡桃木腳）","table",["japanese","luxury"],
   ["stone side table","slate top","natural stone"],["dark slate","black walnut"],
   6800,"Dia45xH50","slate stone top side table, black walnut legs, Japanese Zen"),
tb("jp-bamboo-curtain","竹簾捲簾（自然色）","curtain",["japanese","muji"],
   ["bamboo blind","roll-up curtain","natural shade"],["bamboo","natural"],
   1800,"W120xH180","bamboo roll-up blind, natural tone, filter light Japanese style"),
tb("jp-low-bed","日式低矮床架（原木）","bed",["japanese","muji"],
   ["low bed frame","platform bed","natural wood bed"],["natural wood","light oak"],
   15000,"W150xD210","low-profile solid wood platform bed, minimal headboard, wabi-sabi"),
tb("jp-zabuton","方形坐墊（厚款，亞麻）","chair",["japanese"],
   ["floor cushion","zabuton","meditation cushion"],["dark grey","earth tone","linen"],
   2400,"W70xD70xH15","thick floor meditation cushion, linen cover, Japanese tatami seating"),
tb("jp-ceramic-tea-table","陶燒茶几（不規則邊緣）","table",["japanese"],
   ["ceramic table","wabi-sabi table","irregular edge"],["muted clay","earthy tone"],
   9500,"W80xD50xH40","hand-formed ceramic coffee table, irregular organic edge, wabi-sabi"),
tb("jp-pottery-vase","手拋陶器花瓶組（3件）","accessory",["japanese"],
   ["hand-thrown pottery","ceramic vessels","wabi-sabi vase"],["muted clay","ash grey","earth"],
   3200,"various","hand-thrown pottery vessels, earthy ash glaze, Japanese craft"),
tb("jp-shoji-divider","和風格子屏風隔斷","accessory",["japanese"],
   ["shoji screen","room divider","paper screen"],["natural wood","white paper"],
   8800,"W90xH180","shoji-style screen divider, natural wood frame, translucent paper"),
tb("jp-jute-runner","黃麻走道地毯（長條）","rug",["japanese","muji"],
   ["jute runner","natural rug","corridor rug"],["natural jute","beige"],
   1900,"W70xL200","jute fiber runner rug, natural texture, minimalist Japanese"),
tb("jp-linen-sofa-cover","亞麻沙發套（米白/淺灰）","accessory",["japanese","muji","nordic"],
   ["linen sofa cover","slipcover","sofa protector"],["off-white","light grey","linen"],
   2800,"universal","washable linen sofa slipcover, relaxed drape, Japanese natural aesthetic"),
tb("jp-oak-coffee","原木深色茶几（矮腳）","table",["japanese"],
   ["aged oak table","dark wood table","low coffee table"],["dark walnut","aged wood"],
   7200,"W100xD60xH38","aged oak low coffee table, natural grain, Japanese living room"),
tb("jp-sand-curtain","沙色麻布窗簾","curtain",["japanese","muji"],
   ["sand curtain","linen drape","natural curtain"],["sand","warm beige"],
   3400,"W250xH270","sand-colored linen curtain, heavy drape, block harsh sunlight"),
tb("jp-bamboo-rack","竹製雜誌架","storage",["japanese","muji"],
   ["bamboo magazine rack","natural storage","slim rack"],["bamboo","natural"],
   1400,"W30xD20xH50","bamboo magazine and book rack, natural finish, floor-standing"),
tb("jp-unfinished-lamp","原木圓柱落地燈","lighting",["japanese","muji"],
   ["unfinished wood lamp","cylindrical lamp","natural floor lamp"],["natural wood","cream"],
   4200,"H140","unfinished solid wood base floor lamp, linen shade, warm 3000K"),
tb("jp-clay-vessels","陶土花器組（高/低款）","plant",["japanese"],
   ["clay pot","ceramic planter","organic shape"],["matte clay","ash"],
   2600,"various","matte clay planters set, organic irregular forms, wabi-sabi display"),
ik("ikea-ofelia-throw","OFELIA 毯子（白色）","accessory",["japanese","nordic","muji"],
   ["soft throw","white blanket","bedroom throw"],["white","off-white"],
   799,"130x170","soft white knit throw, minimal fold, bedroom layering"),
tb("jp-tatami-rug","仿榻榻米藺草地毯（方形）","rug",["japanese"],
   ["tatami mat","rush grass rug","Japanese mat"],["natural green","grass"],
   4500,"200x200","rush grass woven square mat, tatami-inspired texture, natural fragrance"),
tb("jp-teak-stool","柚木浴室小矮凳","chair",["japanese","muji"],
   ["teak stool","wood bench","bathroom stool"],["teak","warm brown"],
   2200,"W35xD25xH45","solid teak small stool, indoor/outdoor, Japanese spa aesthetic"),

# ── LUXURY 輕奢現代 ──────────────────────────────────────────────────────────
tb("lux-marble-table","卡拉拉大理石茶几（黃銅腳）","table",["luxury","art-deco"],
   ["marble coffee table","Carrara marble","brass legs"],["white marble","brass"],
   15800,"W100xD60xH40","Carrara white marble coffee table, brushed brass legs, luxury"),
tb("lux-velvet-sofa","弧形絲絨沙發（墨綠/勃艮第）","sofa",["luxury","art-deco"],
   ["curved velvet sofa","luxury sofa","sculptural sofa"],["emerald green","burgundy"],
   38000,"W220xD90xH80","curved velvet sofa, deep emerald, sculptural silhouette, luxury"),
tb("lux-brass-pendant","黃銅幾何吊燈（多頭）","lighting",["luxury","art-deco"],
   ["brass pendant","chandelier","gold pendant"],["brass","gold"],
   12000,"Dia60","brushed brass multi-arm chandelier, geometric design, luxury"),
tb("lux-travertine-side","洞石邊几（圓柱腳）","table",["luxury"],
   ["travertine side table","stone side table","luxury side table"],["travertine","cream beige"],
   9800,"Dia50xH55","travertine stone top side table, natural pore texture, luxury warm"),
tb("lux-velvet-diningchair","天鵝絨餐椅（香檳金腳）","chair",["luxury"],
   ["velvet dining chair","upholstered chair","luxury chair"],["champagne","deep navy","blush"],
   8800,"W50xD56xH90","velvet dining chair, button tufted back, champagne gold legs"),
tb("lux-marble-dining","大理石餐桌（黑框腳）","table",["luxury"],
   ["marble dining table","luxury dining","stone table"],["white marble","black steel"],
   45000,"W200xD100xH76","white marble dining table, black steel pedestal base, luxury"),
tb("lux-crystal-chandelier","水晶串珠吊燈（多層）","lighting",["luxury"],
   ["crystal chandelier","luxury chandelier","statement lighting"],["crystal","chrome"],
   28000,"Dia80","multi-tier crystal bead chandelier, chrome frame, dramatic luxury"),
tb("lux-brass-floorlamp","黃銅弧形落地燈（大理石底座）","lighting",["luxury"],
   ["brass arc lamp","marble base lamp","luxury floor lamp"],["brass","white marble"],
   8500,"H180","brass arc floor lamp, marble base, warm spotlight, luxury interior"),
tb("lux-velvet-curtain","絲絨遮光窗簾（午夜藍/墨綠）","curtain",["luxury"],
   ["velvet curtain","blackout curtain","luxury curtain"],["midnight blue","emerald","charcoal"],
   7800,"W250xH280","heavy velvet blackout curtain, deep color, floor-puddling luxury drape"),
tb("lux-cashmere-throw","喀什米爾混紡毯子","accessory",["luxury"],
   ["cashmere throw","luxury blanket","soft throw"],["champagne","ivory","dark grey"],
   5800,"130x180","cashmere blend throw blanket, ultra-soft, luxury bedroom layering"),
tb("lux-faux-fur-rug","仿狐狸毛地毯（米白）","rug",["luxury"],
   ["faux fur rug","luxury rug","plush rug"],["ivory","cream","champagne"],
   12000,"160x230","faux fox fur area rug, ultra-plush pile, luxury bedroom floor"),
tb("lux-lacquer-sideboard","黑胡桃木亮面側板櫃","storage",["luxury"],
   ["lacquered sideboard","dark sideboard","luxury cabinet"],["dark walnut","high gloss"],
   32000,"W180xD45xH75","lacquered dark walnut sideboard, high-gloss finish, luxury dining"),
tb("lux-sculptural-chair","雕塑感絨布休閒椅","chair",["luxury"],
   ["sculptural lounge chair","velvet accent chair","statement chair"],["dusty rose","deep blue"],
   18000,"W70xD78xH80","sculptural organic-form lounge chair, velvet upholstery, luxury accent"),
tb("lux-marble-bedside","大理石紋床頭櫃（鏡面）","storage",["luxury"],
   ["marble bedside","mirrored cabinet","luxury nightstand"],["white marble","mirror"],
   7200,"W55xD40xH55","marble-top bedside table, mirrored door, gold handle, luxury bedroom"),
tb("lux-gold-mirror","金色橢圓掛鏡（波浪框）","mirror",["luxury"],
   ["gold wall mirror","oval mirror","luxury mirror"],["champagne gold"],
   9500,"W70xH100","champagne gold oval wall mirror, ripple frame, luxury vanity"),
tb("lux-dark-ottoman","深色絨布腳凳（大）","chair",["luxury"],
   ["velvet ottoman","footstool","luxury ottoman"],["midnight navy","charcoal","burgundy"],
   6800,"W80xD80xH42","large square velvet ottoman, brass pin legs, luxury lounge"),
tb("lux-marble-lamp","大理石紋桌燈","lighting",["luxury"],
   ["marble table lamp","luxury lamp","stone lamp"],["white marble","brass"],
   4500,"H40","marble-base table lamp, brass socket, linen shade, luxury bedside"),
tb("lux-black-steel-shelf","黑鋼烤漆玻璃展示架","shelving",["luxury"],
   ["black steel shelf","glass shelf","display cabinet"],["matte black","clear glass"],
   15000,"W90xD35xH180","black powder-coat steel open display shelving, tempered glass shelves"),
tb("lux-champagne-side","香檳金幾何邊几","table",["luxury","art-deco"],
   ["gold side table","geometric table","accent table"],["champagne gold"],
   5500,"Dia40xH55","champagne gold geometric side table, hexagonal top, luxury accent"),
tb("lux-platform-bed","輕奢床架（布藝床頭牆）","bed",["luxury"],
   ["luxury bed frame","upholstered bed","platform bed"],["champagne","dark grey","navy"],
   42000,"W180xD220","upholstered platform bed, tufted headboard wall panel, luxury bedroom"),
tb("lux-velvet-headboard","天鵝絨嵌入式床頭板","bed",["luxury"],
   ["velvet headboard","upholstered headboard","tufted headboard"],["dusty rose","navy","champagne"],
   12000,"W180xH120","deep-button tufted velvet headboard, gold nail trim, luxury bedroom"),
tb("lux-brass-frames","黃銅畫框組（三聯）","accessory",["luxury"],
   ["brass picture frame","gallery wall","luxury frame"],["brass","gold"],
   3200,"various","set of 3 brushed brass picture frames, clean profile, luxury gallery wall"),
tb("lux-blackout-velvet","全遮光絲絨窗簾（勃艮第）","curtain",["luxury"],
   ["blackout curtain","luxury drape","velvet curtain"],["burgundy","deep wine"],
   8800,"W250xH280","full blackout velvet drape, heavy weight, rich burgundy, luxury hotel feel"),
tb("lux-sculpture","金屬抽象雕塑擺件","accessory",["luxury","art-deco"],
   ["sculpture decor","abstract art","metal sculpture"],["gold","brass","black"],
   6500,"H35","abstract brushed brass sculpture, luxury shelf or console display"),

# ── NORDIC 北歐 Scandinavian ─────────────────────────────────────────────────
ik("poang-armchair","POÄNG 扶手椅（樺木/棉麻）","chair",["nordic","modern"],
   ["hygge armchair","birch armchair","lounge chair"],["birch","light beige"],
   5990,"W68xD82xH100","birch veneer lounge armchair, beige cushion, Scandinavian hygge","s09156773"),
ik("stockholm-rug","STOCKHOLM 地毯（羊毛/米白）","rug",["nordic","modern","boho"],
   ["wool rug","handmade rug","geometric rug"],["beige","off-white"],
   14999,"170x240","handmade wool rug, geometric pattern, off-white, Scandinavian","70478243"),
ik("ranarp-floor-lamp","RANARP 落地燈（米色）","lighting",["nordic","modern","muji"],
   ["floor lamp","reading lamp","adjustable lamp"],["off-white","cream"],
   2499,"H149","classic floor reading lamp, off-white metal shade, adjustable arm","60291446"),
ik("hemnes-bed-white","HEMNES 床架（白）","bed",["nordic","muji"],
   ["white bed frame","pine bed","classic bed"],["white"],
   12900,"W150xD210","solid wood white bed frame, clean classic lines, Scandinavian","s89002498"),
ik("vedbo-armchair","VEDBO 扶手椅（深灰）","chair",["nordic"],
   ["accent chair","dark armchair","nordic chair"],["dark grey","anthracite"],
   15990,"W64xD62xH84","dark grey accent armchair, clean Scandinavian lines, bold accent","10322179"),
ik("hemnes-daybed","HEMNES 日床（白）","bed",["nordic"],
   ["daybed","sofa bed","guest bed"],["white"],
   14990,"W80xD200","white solid wood daybed, doubles as single sofa, Scandinavian","20011701"),
ik("sinnerlig-cork-pendant","SINNERLIG 吊燈（軟木）","lighting",["nordic","japanese"],
   ["cork pendant","organic pendant","natural pendant"],["cork","warm brown"],
   1499,"Dia35","cork pendant lamp, organic grain texture, warm ambient light","00261726"),
ik("ingolf-chair-white","INGOLF 餐椅（白）","chair",["nordic","muji","modern"],
   ["white dining chair","simple chair","functional chair"],["white"],
   1790,"W47xD50xH90","classic white dining chair, simple wooden frame","80103539"),
tb("no-birch-table","白樺木餐桌（細腳）","table",["nordic"],
   ["birch dining table","white table","nordic dining"],["white birch","off-white"],
   12000,"W160xD80xH75","white birch dining table, tapered slim legs, bright Scandinavian dining"),
tb("no-sheepskin-rug","純白羊毛皮地墊","rug",["nordic","boho"],
   ["sheepskin rug","fluffy rug","natural rug"],["ivory","cream white"],
   4800,"90x150","genuine sheepskin floor rug, plush natural pile, hygge Scandinavian"),
tb("no-knit-throw","粗針編織毛毯（奶白色）","accessory",["nordic"],
   ["knit throw","cable knit blanket","cozy throw"],["cream","off-white","dusty sage"],
   2800,"130x160","chunky cable-knit cotton throw, natural cream, Scandinavian hygge"),
tb("no-pine-bench","松木長椅凳（附收納）","chair",["nordic"],
   ["storage bench","pine bench","hallway bench"],["pine","natural wood"],
   5500,"W120xD40xH48","pine wood storage bench, lift-top seat, Scandinavian entryway"),
tb("no-cotton-curtain","純棉全遮光窗簾（白/米）","curtain",["nordic","modern"],
   ["blackout curtain","cotton curtain","white curtain"],["white","off-white","powder blue"],
   4200,"W250xH270","heavy cotton blackout curtain, clean drape, Scandinavian window treatment"),
tb("no-felt-pendant","羊毛氈燈罩吊燈（大）","lighting",["nordic"],
   ["felt pendant","wool pendant","oversized pendant"],["dusty grey","sage green","charcoal"],
   5500,"Dia50","oversized wool felt pendant shade, soft acoustic, Scandinavian"),
tb("no-plywood-chair","成型夾板餐椅（自然色）","chair",["nordic"],
   ["plywood chair","molded chair","design chair"],["natural plywood","beige"],
   4500,"W48xD52xH80","molded plywood dining chair, ergonomic shell, Scandinavian design"),
tb("no-pine-shelf","松木模組層板架","shelving",["nordic"],
   ["pine shelf","modular shelving","open shelf"],["pine","natural wood"],
   3800,"W80xD25","natural pine adjustable shelf, peg system, Scandinavian storage"),
tb("no-round-cushion","圓形地板坐墊（羊毛氈）","chair",["nordic","japanese"],
   ["floor cushion","round pouf","wool felt"],["dusty pink","sage green","grey"],
   3200,"Dia50xH25","round wool felt floor cushion, hygge floor seating"),
tb("no-candle-set","石蠟蠟燭組（多高度）","accessory",["nordic"],
   ["candle set","hygge candle","pillar candle"],["white","cream","pale grey"],
   1200,"various","Nordic hygge pillar candle set, unscented, varying heights"),
tb("no-natural-bed","淡木色床架（寬床頭板）","bed",["nordic"],
   ["nordic bed","wide headboard","natural wood bed"],["light oak","birch"],
   22000,"W180xD210","light oak bed frame, wide flat headboard, Scandinavian bedroom"),
tb("no-powder-chair","粉藍色布藝餐椅","chair",["nordic"],
   ["powder blue chair","fabric chair","color accent chair"],["powder blue","light blue"],
   3800,"W48xD52xH85","powder blue upholstered dining chair, tapered legs, Scandinavian pop"),
tb("no-rattan-basket","原色藤籃收納組（三件）","storage",["nordic","boho","japanese"],
   ["rattan basket","wicker basket","storage basket"],["natural rattan"],
   2400,"various","natural rattan basket set of 3, Scandinavian living room storage"),
tb("no-abstract-rug","北歐抽象圖案地毯（灰藍）","rug",["nordic"],
   ["abstract rug","geometric rug","Scandinavian rug"],["grey blue","cream","dusty sage"],
   8800,"200x300","low-pile abstract geometric rug, grey-blue palette, Scandinavian modern"),
tb("no-edison-pendant","北歐風愛迪生燈泡吊燈","lighting",["nordic","industrial"],
   ["Edison bulb pendant","vintage bulb","warm pendant"],["brass","amber","gold"],
   2800,"H30 adj","Edison filament pendant, warm 2700K amber glow, Scandinavian modern"),
tb("no-white-sofa","白色三人布藝沙發（木腳）","sofa",["nordic","modern"],
   ["white sofa","fabric sofa","Scandinavian sofa"],["white","off-white"],
   24000,"W210xD88xH80","white fabric 3-seater sofa, solid oak legs, Scandinavian hygge"),
tb("no-storage-stool","儲物布藝腳凳（灰）","chair",["nordic"],
   ["storage ottoman","fabric stool","square pouf"],["light grey","dusty pink"],
   3500,"W50xD50xH40","fabric storage ottoman, lift-top, Scandinavian multifunctional"),

# ── INDUSTRIAL 工業風 ─────────────────────────────────────────────────────────
ik("fjallbo-shelf","FJÄLLBO 層架（黑色鐵件）","shelving",["industrial","modern"],
   ["iron bookshelf","black metal shelf","pipe shelf"],["black","matte black"],
   4999,"W60xD36xH150","black steel open shelving, industrial pipe design","20338215"),
tb("ind-dining-table","復古工業風餐桌（實木+黑鐵腳）","table",["industrial"],
   ["reclaimed wood table","industrial table","black iron legs"],["dark walnut","black iron"],
   18000,"W180xD80xH76","reclaimed wood dining table, black iron hairpin legs, loft industrial"),
tb("ind-edison-pendant","Edison 燈泡復古吊燈（3頭）","lighting",["industrial","boho"],
   ["Edison filament","factory pendant","vintage pendant"],["bronze","antique black"],
   3500,"Dia50(3heads)","Edison filament 3-arm pendant, antique bronze, exposed bulb"),
tb("ind-chesterfield","切斯特菲爾德皮革沙發（深棕）","sofa",["industrial"],
   ["Chesterfield sofa","leather sofa","tufted sofa"],["dark brown","cognac leather"],
   35000,"W210xD90xH82","deep-button tufted Chesterfield leather sofa, dark brown, industrial"),
tb("ind-wire-chair","工業風金屬網椅","chair",["industrial"],
   ["wire mesh chair","metal chair","industrial chair"],["black","chrome"],
   2800,"W48xD52xH80","wire mesh dining chair, powder-coat black, industrial cafe style"),
tb("ind-reclaimed-coffee","工業風拼木茶几（輪子）","table",["industrial"],
   ["reclaimed coffee table","caster table","rolling table"],["weathered oak","black casters"],
   8800,"W120xD60xH45","reclaimed wood coffee table, black iron frame, industrial casters"),
tb("ind-pipe-wall-shelf","鐵管壁掛書架（4層）","shelving",["industrial"],
   ["pipe shelf","iron wall shelf","industrial shelving"],["black iron","reclaimed wood"],
   5500,"W80xD20xH120","black iron pipe wall-mounted shelving unit, reclaimed wood boards"),
tb("ind-track-light","軌道燈（3頭可調向）","lighting",["industrial","modern"],
   ["track lighting","spotlight","adjustable lighting"],["matte black"],
   3800,"L100","matte black 3-head track lighting, adjustable direction, industrial"),
tb("ind-bar-stool","工業風金屬高腳凳（可調高）","chair",["industrial"],
   ["bar stool","adjustable stool","metal stool"],["black","rust orange"],
   3200,"H60-80","adjustable height metal bar stool, footrest ring, industrial cafe"),
tb("ind-leather-armchair","做舊皮革扶手椅","chair",["industrial"],
   ["aged leather chair","vintage armchair","leather lounge"],["cognac","dark brown"],
   12000,"W75xD80xH85","distressed leather armchair, exposed rivets, industrial gentleman"),
tb("ind-concrete-side","粗獷水泥邊几","table",["industrial","modern"],
   ["concrete side table","raw concrete","industrial table"],["raw concrete grey"],
   3500,"Dia35xH55","raw concrete side table, rough texture, industrial-modern"),
tb("ind-black-bed","工業風黑鐵床架","bed",["industrial"],
   ["iron bed frame","black metal bed","industrial bed"],["matte black"],
   16000,"W150xD210","matte black iron tube bed frame, industrial loft bedroom"),
tb("ind-factory-cart","工廠搬運車改造咖啡桌","table",["industrial"],
   ["cart table","industrial cart","rolling coffee table"],["black iron","oak top"],
   7500,"W80xD50xH42","vintage factory trolley coffee table, iron wheels, reclaimed oak top"),
tb("ind-metal-cabinet","金屬文件抽屜櫃（5層）","storage",["industrial"],
   ["metal filing cabinet","industrial storage","steel cabinet"],["matte grey","black"],
   8800,"W46xD62xH132","industrial-style metal filing cabinet, label pull handles, workshop feel"),
tb("ind-task-lamp","工業風夾式工作燈","lighting",["industrial"],
   ["task lamp","clip lamp","industrial desk lamp"],["antique brass","matte black"],
   1800,"H35","articulated arm task lamp, factory-style shade, industrial desk"),
tb("ind-galvanized-pendant","鍍鋅桶形吊燈","lighting",["industrial"],
   ["galvanized pendant","warehouse pendant","industrial light"],["galvanized silver"],
   2200,"Dia25","galvanized steel dome pendant, warehouse factory style, Edison compatible"),
tb("ind-tv-reclaimed","工業風舊木電視櫃（鐵架）","storage",["industrial"],
   ["reclaimed wood TV","industrial TV console","iron frame"],["weathered oak","black iron"],
   12000,"W160xD40xH55","reclaimed wood TV console, black iron open frame, industrial loft"),
tb("ind-wire-basket","金屬網籃收納（3件組）","storage",["industrial"],
   ["wire basket","metal storage","industrial basket"],["black","chrome"],
   2400,"various","wire mesh storage baskets set of 3, powder-coat black, industrial"),
tb("ind-charcoal-rug","深炭灰短毛地毯","rug",["industrial"],
   ["charcoal rug","dark rug","concrete grey rug"],["charcoal","dark grey"],
   5500,"200x290","charcoal grey low-pile rug, concrete-tone, industrial loft floor"),
tb("ind-vintage-map","復古城市地圖掛畫","accessory",["industrial"],
   ["vintage map art","wall art","industrial decor"],["sepia","aged paper"],
   1800,"60x90","vintage-style city blueprint framed print, industrial wall art"),
tb("ind-iron-bookend","齒輪造型書擋（一對）","accessory",["industrial"],
   ["gear bookend","iron decor","industrial accessory"],["antique iron"],
   1200,"W10xH15","cast iron gear-shaped bookends, antique finish, industrial shelf"),
tb("ind-rust-pillow","鐵鏽橙工業風抱枕","accessory",["industrial","boho"],
   ["rust orange pillow","throw pillow","accent pillow"],["rust orange","mustard"],
   850,"45x45","rust orange textured throw pillow, earthy industrial accent"),
tb("ind-linen-curtain","炭灰亞麻遮光窗簾","curtain",["industrial"],
   ["charcoal curtain","linen blackout","dark curtain"],["charcoal","dark grey"],
   5200,"W250xH270","charcoal linen blackout curtain, industrial dark palette"),
tb("ind-plank-shelf","舊木板牆面層板（120cm）","shelving",["industrial","boho"],
   ["reclaimed plank shelf","wall shelf","rustic shelf"],["weathered grey","reclaimed wood"],
   2800,"W120xD22","single reclaimed plank wall shelf, raw edge, industrial-rustic"),
tb("ind-pipe-lamp","黑鐵管壁燈（工廠風）","lighting",["industrial"],
   ["wall sconce","pipe lamp","industrial sconce"],["matte black","aged steel"],
   2500,"H30","black iron pipe wall lamp, adjustable angle, industrial factory style"),

# ── MEDITERRANEAN 地中海 ─────────────────────────────────────────────────────
tb("med-mosaic-table","手工馬賽克磁磚咖啡桌（藍白）","table",["mediterranean"],
   ["mosaic tile table","Mediterranean table","blue white tile"],["blue","white","turquoise"],
   9800,"W80xD80xH45","hand-painted mosaic tile coffee table, Mediterranean blue-white"),
ik("buskbo-rattan","BUSKBO 扶手椅（藤）","chair",["mediterranean","boho","japanese"],
   ["rattan chair","wicker chair","natural chair"],["natural rattan","light brown"],
   4999,"W73xD65xH76","handwoven rattan armchair, natural finish, Mediterranean boho","70458753"),
tb("med-terracotta-lamp","陶土圓柱落地燈（摩洛哥風）","lighting",["mediterranean","boho"],
   ["terracotta lamp","Moroccan lamp","clay lamp"],["terracotta","warm orange"],
   5500,"H150","terracotta clay floor lamp, Moroccan cut-out pattern, warm amber glow"),
tb("med-sea-glass-art","海玻璃馬賽克壁飾","accessory",["mediterranean"],
   ["sea glass art","mosaic wall","coastal decor"],["turquoise","sea green","cobalt"],
   4200,"W60xH60","sea glass mosaic wall art panel, Mediterranean coastal"),
tb("med-whitewash-table","白洗舊木餐桌（地中海風）","table",["mediterranean"],
   ["whitewash dining table","Mediterranean table","coastal dining"],["whitewash","driftwood"],
   14000,"W160xD85xH75","whitewashed solid wood dining table, aged Mediterranean coastal"),
tb("med-iron-sconce","鍛鐵壁燈（西班牙風格）","lighting",["mediterranean"],
   ["wrought iron sconce","wall lamp","Mediterranean lighting"],["antique black iron","amber"],
   3500,"H30","wrought iron wall sconce, candelabra style, Mediterranean Spanish"),
tb("med-arch-mirror","白色拱形掛鏡","mirror",["mediterranean","boho"],
   ["arched mirror","whitewash mirror","arch decor"],["white","whitewash"],
   6800,"W60xH120","white arch-top wall mirror, smooth plaster-look frame, Mediterranean boho"),
tb("med-stripe-rug","藍白條紋地毯","rug",["mediterranean"],
   ["stripe rug","blue white rug","coastal rug"],["Mediterranean blue","white"],
   5800,"160x230","blue and white stripe woven rug, Mediterranean coastal"),
tb("med-voile-curtain","白色薄紗窗簾（飄逸）","curtain",["mediterranean","modern"],
   ["voile curtain","sheer curtain","white drape"],["white","sheer"],
   2800,"W250xH270","white voile sheer curtain, breezy Mediterranean drape, maximize sunlight"),
tb("med-terracotta-pot","陶土花器（大型，適合棕櫚）","plant",["mediterranean","boho"],
   ["terracotta planter","large pot","clay pot"],["terracotta","burnt orange"],
   2200,"Dia35xH45","large terracotta floor planter, hand-formed clay, Mediterranean garden"),
tb("med-wicker-sofa","藤編戶外風沙發組","sofa",["mediterranean","boho"],
   ["wicker sofa","rattan sofa","outdoor-style sofa"],["natural rattan","white cushion"],
   28000,"W200xD85xH80","wicker rattan sofa set, Mediterranean terrace-style, indoor use"),
tb("med-ceramic-tiles","手繪馬賽克磁磚壁飾板","accessory",["mediterranean"],
   ["ceramic tile art","hand painted tile","decorative tiles"],["blue","white","yellow"],
   3600,"30x30(set4)","hand-painted Mediterranean ceramic decorative tile set of 4"),
tb("med-rattan-daybed","藤編日床（度假風）","bed",["mediterranean","boho"],
   ["rattan daybed","wicker daybed","boho bed"],["natural rattan","white cushion"],
   18000,"W90xD200","wicker rattan daybed, tropical Mediterranean relaxation"),
tb("med-iron-lantern","鍛鐵燈籠吊燈","lighting",["mediterranean"],
   ["lantern pendant","iron lantern","Moroccan lantern"],["antique black","amber glass"],
   4500,"H40","wrought iron lantern pendant, amber glass panels, Moroccan Mediterranean"),
tb("med-cobalt-vase","深藍陶瓷花器（高型）","accessory",["mediterranean"],
   ["cobalt vase","blue ceramic","Mediterranean vase"],["cobalt blue","Mediterranean blue"],
   2800,"Dia18xH50","tall cobalt blue ceramic vase, hand-glazed, Mediterranean accent"),
tb("med-driftwood-coffee","漂流木邊緣茶几","table",["mediterranean","boho"],
   ["driftwood table","natural edge table","coastal table"],["driftwood","natural grey"],
   9500,"W100xD55xH42","driftwood natural-edge coffee table, Mediterranean coastal chic"),
tb("med-stone-side","天然石材邊几（圓形）","table",["mediterranean"],
   ["stone side table","natural stone","round side"],["stone grey","travertine"],
   7800,"Dia45xH55","natural stone disc side table, rough hewn edge, Mediterranean earthy"),
tb("med-whitewash-bed","白洗木床架（地中海風）","bed",["mediterranean"],
   ["whitewash bed","Mediterranean bed","coastal bedroom"],["whitewash","driftwood white"],
   18000,"W150xD210","whitewashed wood bed frame, plank headboard, Mediterranean coastal"),
tb("med-palmleaf-fan","棕櫚葉吊扇燈","lighting",["mediterranean","boho"],
   ["ceiling fan light","palm fan","tropical light"],["natural palm","bamboo"],
   8800,"Dia100","palm leaf ceiling fan with light, tropical Mediterranean, quiet motor"),
tb("med-shell-curtain","貝殼串珠門簾","accessory",["mediterranean"],
   ["shell curtain","bead curtain","coastal partition"],["natural shell","cream"],
   2200,"W90xH200","natural shell beaded door curtain, coastal Mediterranean divider"),
tb("med-blue-sofa","地中海藍色亞麻沙發","sofa",["mediterranean"],
   ["blue sofa","Mediterranean sofa","coastal sofa"],["Mediterranean blue","ocean blue"],
   22000,"W210xD88xH80","Mediterranean blue linen sofa, white piping trim, coastal living"),
tb("med-terracotta-rug","磚紅色仿陶土地毯","rug",["mediterranean","boho"],
   ["terracotta rug","earth tone rug","warm rug"],["terracotta","burnt sienna"],
   6800,"160x230","terracotta-tone flat-weave rug, Mediterranean warm palette"),
tb("med-woven-pendant","藤編圓形吊燈罩","lighting",["mediterranean","boho","nordic"],
   ["woven pendant","rattan shade","natural pendant"],["natural rattan","warm brown"],
   3200,"Dia45","woven rattan dome pendant, warm filtered light, Mediterranean coastal"),
tb("med-sea-pillow","海洋藍抱枕組（刺繡）","accessory",["mediterranean"],
   ["ocean pillow","embroidered pillow","coastal pillow"],["sea blue","white","turquoise"],
   1800,"45x45(set2)","embroidered Mediterranean coastal throw pillow set, anchor motif"),
tb("med-ceramic-stool","陶瓷鼓形邊几/凳（藍白）","chair",["mediterranean"],
   ["ceramic stool","garden stool","decorative stool"],["blue","white","hand-painted"],
   4800,"Dia33xH48","hand-painted blue-white ceramic garden stool, Mediterranean accent"),

# ── MUJI 無印風 ───────────────────────────────────────────────────────────────
ik("alex-drawer","ALEX 抽屜櫃（白）","storage",["muji","modern"],
   ["white drawer","modular storage","functional storage"],["white"],
   5490,"W36xD58xH116","slim white drawer unit, handle-less, minimalist functional","00473546"),
ik("ingolf-chair","INGOLF 餐椅（白）","chair",["muji","modern","nordic"],
   ["white dining chair","simple chair","functional chair"],["white"],
   1790,"W47xD50xH90","classic white dining chair, simple wooden frame","80103539"),
ik("ivar-shelf","IVAR 松木層架","shelving",["muji","nordic"],
   ["pine shelf","open shelving","natural wood"],["pine","natural"],
   2990,"W89xD30xH124","solid pine open shelving, adjustable, natural functional","60283003"),
ik("raskog-trolley","RÅSKOG 廚房推車（白）","storage",["muji"],
   ["rolling cart","kitchen trolley","white storage"],["white"],
   1490,"W35xD45xH78","white 3-tier rolling cart, bathroom or kitchen utility","30346220"),
ik("hemnes-linen-cabinet","HEMNES 亞麻收納櫃","storage",["muji","nordic"],
   ["linen cabinet","white storage","bedroom storage"],["white"],
   8990,"W70xD35xH130","solid wood white linen cabinet, classic clean lines","30488498"),
ik("lersta-floor-lamp","LERSTA 落地/讀書燈","lighting",["muji","modern","nordic"],
   ["floor lamp","reading lamp","task lamp","simple lamp"],["aluminum","silver"],
   999,"H149","aluminum adjustable floor lamp, minimal industrial design","90241334"),
ik("knopparp-sofa","KNOPPARP 雙人沙發（米白）","sofa",["muji","modern"],
   ["small sofa","loveseat","compact sofa"],["off-white","beige"],
   6990,"W120xD88xH80","compact 2-seater sofa, removable cover, minimalist Muji style","40482108"),
tb("muji-beech-shelf","山毛櫸木壁掛展示架","shelving",["muji"],
   ["beech shelf","wall shelf","display shelf"],["beech","warm wood"],
   3200,"W80xD20","natural beech wood floating wall shelf, functional minimalist"),
tb("muji-folding-stool","摺疊圓凳（山毛櫸）","chair",["muji","japanese"],
   ["folding stool","wooden stool","compact stool"],["beech","natural"],
   1800,"Dia30xH45","solid beech folding stool, compact storage, Muji functional design"),
tb("muji-low-bed","原木低矮床架（無印風格）","bed",["muji","japanese"],
   ["low bed frame","natural wood bed","minimal bed"],["beech","ash","natural wood"],
   16000,"W150xD210","low-profile natural wood bed, minimal headboard, Muji aesthetic"),
tb("muji-canvas-basket","帆布收納籃組（3件）","storage",["muji"],
   ["canvas basket","fabric storage","organizing basket"],["natural beige","off-white"],
   2200,"various","natural cotton canvas storage baskets, minimal label design, Muji"),
tb("muji-recycled-pendant","再生紙吊燈（大圓球）","lighting",["muji","japanese"],
   ["paper pendant","recycled paper lamp","globe pendant"],["natural cream","warm white"],
   2800,"Dia40","handmade recycled paper globe pendant, warm ambient, Muji eco"),
tb("muji-cotton-curtain","棉質米色窗簾","curtain",["muji","nordic","japanese"],
   ["cotton curtain","beige drape","natural curtain"],["off-white","beige","light grey"],
   3400,"W250xH270","cotton semi-sheer curtain, off-white natural tone, Muji window"),
tb("muji-ash-table","白蠟木餐桌（四人用）","table",["muji","modern"],
   ["ash dining table","natural wood table","simple table"],["ash","light warm wood"],
   12000,"W140xD75xH72","solid ash dining table, tapered legs, natural grain, Muji functional"),
tb("muji-bedside","無印風床頭小几（抽屜）","storage",["muji"],
   ["bedside table","nightstand","drawer table"],["beech","light oak"],
   3800,"W40xD40xH55","compact bedside table with drawer, natural wood, Muji minimalist"),
tb("muji-wall-desk","壁掛折疊書桌","table",["muji"],
   ["wall desk","fold-down desk","space-saving desk"],["white","beige"],
   4500,"W80xD40foldout","wall-mounted fold-down desk, space-saving, Muji functional"),
tb("muji-cotton-rug","棉質素色地毯（淺灰）","rug",["muji","modern","nordic"],
   ["cotton rug","plain rug","simple rug"],["light grey","off-white","beige"],
   3200,"160x230","flat-weave cotton rug, plain neutral tone, Muji minimal floor"),
tb("muji-linen-throw","天然亞麻毯子（米白）","accessory",["muji","japanese"],
   ["linen throw","natural blanket","unbleached throw"],["natural linen","off-white"],
   2600,"130x170","unbleached natural linen throw, relaxed fold, Muji organic texture"),
tb("muji-cube-storage","模組立方收納盒組","storage",["muji"],
   ["cube storage","modular box","organizing system"],["white","off-white"],
   4800,"30x30x30each","stackable cube storage modules, clean grid system, Muji"),
tb("muji-ceramic-holder","陶瓷筆筒/收納罐組","accessory",["muji"],
   ["ceramic organizer","stationery holder","desk accessory"],["matte white","light grey"],
   1200,"various","matte white ceramic desk organizers, Muji functional minimal"),
tb("muji-globe-lamp","紙質球形燈罩（落地）","lighting",["muji","japanese"],
   ["paper globe lamp","Muji lamp","simple floor lamp"],["cream","warm white"],
   3600,"H155","natural paper globe floor lamp, warm glow, Muji bedroom"),
tb("muji-pine-chair","松木餐椅（自然色）","chair",["muji","nordic"],
   ["pine dining chair","simple chair","natural wood"],["pine","natural"],
   2400,"W44xD48xH82","solid pine dining chair, straightforward functional, Muji natural"),
tb("muji-slim-mirror","原木細框掛鏡（長型）","mirror",["muji","japanese"],
   ["wood framed mirror","slim mirror","functional mirror"],["beech","natural wood"],
   3800,"W45xH120","natural beech framed full-length mirror, slim profile, Muji"),
tb("muji-storage-unit","寬版抽屜收納高櫃","storage",["muji"],
   ["tall storage","drawer tower","bedroom storage"],["white","light beige"],
   12000,"W60xD40xH120","tall slim storage tower with multiple drawers, handle-less, Muji"),

# ── ART-DECO ─────────────────────────────────────────────────────────────────
tb("ad-sunburst-mirror","Art Deco 太陽放射形金色掛鏡","mirror",["art-deco","luxury"],
   ["sunburst mirror","gold mirror","Art Deco mirror"],["gold","champagne"],
   8800,"Dia80","sunburst gold wall mirror, geometric Art Deco rays, statement"),
tb("ad-chandelier","幾何黃銅吊燈（Art Deco 扇形）","lighting",["art-deco"],
   ["geometric chandelier","Art Deco chandelier","brass chandelier"],["gold","brass"],
   22000,"Dia70","Art Deco fan-shaped chandelier, stepped brass geometry"),
tb("ad-velvet-armchair","絲絨鈕扣扶手椅（孔雀藍）","chair",["art-deco","luxury"],
   ["tufted velvet armchair","button tufted","luxury chair"],["peacock blue","emerald","burgundy"],
   15000,"W75xD80xH85","deep-button tufted velvet armchair, Art Deco silhouette"),
tb("ad-credenza","階梯形黑漆木側板櫃","storage",["art-deco"],
   ["stepped credenza","lacquer sideboard","Art Deco cabinet"],["gloss black","ebony"],
   28000,"W180xD45xH80","stepped profile lacquered ebony credenza, Art Deco geometry"),
tb("ad-marble-table","黑金大理石幾何茶几","table",["art-deco","luxury"],
   ["black marble table","geometric table","Art Deco table"],["black marble","gold veins"],
   18000,"W100xD60xH42","nero marquina black marble coffee table, gold brass base, Art Deco"),
tb("ad-gold-side","金葉鑲嵌邊几（六邊形）","table",["art-deco","luxury"],
   ["gold leaf side table","hexagonal table","luxury accent"],["champagne gold","gold leaf"],
   7200,"Dia45xH55","gold leaf hexagonal side table, hand-applied gilt, Art Deco"),
tb("ad-mirror-dresser","鏡面梳妝台（Art Deco 款）","storage",["art-deco","luxury"],
   ["mirrored dresser","vanity table","Art Deco dresser"],["mirror glass","chrome"],
   25000,"W120xD45xH75","full-mirror dresser, chrome geometric handles, Art Deco glamour"),
tb("ad-fan-sconce","扇形鍍鉻壁燈（一對）","lighting",["art-deco"],
   ["fan wall sconce","Art Deco sconce","chrome lamp"],["chrome","frosted glass"],
   6500,"H25(set2)","fan-shaped chrome wall sconce pair, frosted glass panel, Art Deco"),
tb("ad-chevron-rug","人字紋幾何地毯（黑金）","rug",["art-deco"],
   ["chevron rug","geometric rug","Art Deco rug"],["black","gold","ivory"],
   14000,"200x290","chevron geometric area rug, black and gold ivory, Art Deco dramatic"),
tb("ad-chrome-bar","鍍鉻移動吧台車","storage",["art-deco","luxury"],
   ["bar cart","chrome trolley","drinks cabinet"],["chrome","mirror glass"],
   8800,"W60xD40xH90","chrome and mirrored glass bar cart, Art Deco cocktail party"),
tb("ad-ebony-bed","亮黑漆木床架（裝飾鑲嵌）","bed",["art-deco","luxury"],
   ["lacquer bed","ebony bed","Art Deco bed"],["gloss black","gold trim"],
   45000,"W180xD220","lacquered ebony platform bed, gold inlay headboard, Art Deco drama"),
tb("ad-velvet-sofa","絨布孔雀藍雙人沙發","sofa",["art-deco","luxury"],
   ["velvet loveseat","Art Deco sofa","tuxedo sofa"],["peacock blue","midnight navy"],
   28000,"W170xD80xH82","peacock blue velvet tuxedo sofa, pin-leg, Art Deco glamour"),
tb("ad-geo-pendant","黑金幾何球形吊燈","lighting",["art-deco"],
   ["geometric pendant","gold pendant","Art Deco pendant"],["matte black","gold"],
   9500,"Dia35","geometric polyhedron pendant, matte black with gold edges, Art Deco"),
tb("ad-marble-console","大理石台面玄關桌（金腳）","table",["art-deco","luxury"],
   ["marble console","gold console","entry table"],["white marble","gold","brass"],
   22000,"W120xD40xH82","white marble console table, gold metal geometric base, Art Deco"),
tb("ad-emerald-curtain","祖母綠天鵝絨窗簾","curtain",["art-deco","luxury"],
   ["emerald velvet","velvet curtain","luxury drape"],["emerald green","deep green"],
   9500,"W250xH280","emerald green velvet full-length curtain, dramatic Art Deco window"),
tb("ad-octagon-table","八角大理石茶几","table",["art-deco"],
   ["octagon table","geometric coffee","Art Deco table"],["cream marble","black","gold"],
   16000,"Dia90xH42","octagonal cream marble coffee table, black and gold accent edge"),
tb("ad-gold-floorlamp","刷金落地燈（圓柱式）","lighting",["art-deco","luxury"],
   ["gold floor lamp","brushed gold lamp","luxury lamp"],["brushed gold","champagne"],
   8200,"H180","brushed gold column floor lamp, drum shade, Art Deco classic"),
tb("ad-diamond-headboard","鑽石菱格紋床頭板","bed",["art-deco","luxury"],
   ["diamond tufted headboard","velvet headboard","Art Deco bed"],["midnight navy","champagne"],
   14000,"W180xH130","diamond-tufted velvet headboard, gold nail trim, Art Deco bedroom"),
tb("ad-black-lacquer-side","黑漆圓筒邊几","table",["art-deco"],
   ["black lacquer side","cylindrical table","Art Deco side"],["gloss black"],
   4800,"Dia35xH55","high-gloss black lacquered cylindrical side table, Art Deco minimal"),
tb("ad-crystal-drop","水晶垂飾球形吊燈","lighting",["art-deco","luxury"],
   ["crystal pendant","drop pendant","glamour lighting"],["crystal","chrome","gold"],
   18000,"Dia50","crystal drop sphere pendant, chrome armature, Art Deco Hollywood"),
tb("ad-gold-geo-mirror","金色幾何切割掛鏡","mirror",["art-deco","luxury"],
   ["geometric mirror","gold decor mirror","Art Deco mirror"],["gold","mirror"],
   11000,"W80xH80","geometric segmented mirror, gold frame dividers, Art Deco feature"),
tb("ad-peacock-sofa","孔雀尾羽圖案沙發","sofa",["art-deco"],
   ["Art Deco sofa","patterned sofa","luxury sofa"],["peacock blue","emerald","gold"],
   35000,"W210xD85xH80","peacock feather pattern velvet sofa, gold tapered legs, Art Deco"),
tb("ad-bookcase-stepped","階梯形開放書架","shelving",["art-deco"],
   ["stepped bookcase","Art Deco shelf","geometric bookcase"],["walnut","gold trim"],
   18000,"W90xD35xH180","stepped asymmetric open bookcase, walnut veneer, gold metal trim"),
tb("ad-marble-top-console","大理石桌面梳妝台","storage",["art-deco"],
   ["marble vanity","console storage","Art Deco vanity"],["white marble","chrome"],
   28000,"W100xD45xH78","marble top console with bevelled mirror, chrome legs, Art Deco"),
tb("ad-hollywood-mirror","好萊塢球泡燈鏡","mirror",["art-deco"],
   ["Hollywood mirror","vanity mirror","bulb mirror"],["chrome","warm bulbs"],
   8500,"W70xH90","Hollywood vanity mirror, surround bulbs, Art Deco glam dressing"),

# ── BOHO 波希米亞 ────────────────────────────────────────────────────────────
ik("sandskadda-throw","SANDSKÄDDA 毯子（米白/流蘇）","accessory",["boho","nordic","japanese"],
   ["fringe throw","woven blanket","boho textile"],["natural","beige","cream"],
   999,"130x170","fringed woven throw blanket, natural cream, boho layered textile","20541381"),
tb("boho-rattan-chair","藤編懸掛椅（附棉墊）","chair",["boho","mediterranean"],
   ["hanging rattan chair","egg chair","swing chair"],["natural rattan","brown"],
   12000,"Dia100","hanging rattan egg chair, natural weave, cotton cushion, bohemian"),
tb("boho-kilim-rug","土耳其 Kilim 幾何地毯（混色）","rug",["boho"],
   ["kilim rug","Turkish rug","tribal rug"],["terracotta","mustard","rust","multicolor"],
   7500,"160x230","vintage Turkish kilim rug, geometric tribal, terracotta-mustard"),
tb("boho-macrame-wall","大型麻繩編織壁掛（60cm）","accessory",["boho"],
   ["macrame wall hanging","fiber art","wall decor"],["cream","natural cotton"],
   3800,"W60xH90","large hand-knotted macramé wall hanging, cotton rope, boho statement"),
tb("boho-jute-rug","黃麻圓形地毯（自然色）","rug",["boho","mediterranean"],
   ["jute rug","natural fiber rug","round rug"],["natural jute","warm beige"],
   4200,"Dia150","round jute area rug, chunky braid, natural earthy boho"),
tb("boho-floor-cushion","波西米亞地板大坐墊（印花）","chair",["boho"],
   ["floor cushion","pouf","Moroccan floor pillow"],["terracotta","mustard","indigo"],
   2800,"W80xD80xH20","large floor meditation cushion, Moroccan block-print cover"),
tb("boho-terracotta-pots","陶土花器組（大/中/小）","plant",["boho","mediterranean"],
   ["terracotta pot","clay planter","earthy pot"],["terracotta","burnt orange"],
   2600,"various","set of 3 terracotta planters, handmade finish, boho earthy display"),
tb("boho-fairy-lights","暖光銅線串燈（10m）","lighting",["boho","nordic"],
   ["fairy lights","string lights","LED string"],["warm amber","copper wire"],
   1200,"10m","warm copper wire fairy lights, warm 2200K amber, boho bedroom magic"),
tb("boho-wicker-basket","大型藤編收納籃","storage",["boho","nordic","mediterranean"],
   ["wicker basket","large basket","storage"],["natural wicker"],
   2800,"Dia50xH60","large wicker belly basket, boho living room throw storage"),
tb("boho-tassel-pillow","流蘇裝飾抱枕組（2件）","accessory",["boho"],
   ["tassel pillow","fringe pillow","boho cushion"],["mustard","terracotta","rust","sage"],
   1600,"45x45each","block-print tassel throw pillow set, earthy boho palette"),
tb("boho-dreamcatcher","手工捕夢網掛飾（大）","accessory",["boho"],
   ["dreamcatcher","wall hanging","feather decor"],["cream","feather","natural"],
   1800,"Dia40","hand-crafted dreamcatcher with feathers, boho bedroom wall"),
tb("boho-low-coffee","矮腳木質茶几（不規則邊）","table",["boho","japanese"],
   ["low coffee table","natural edge table","boho table"],["natural wood","dark walnut"],
   6800,"W110xD60xH35","natural edge slab low coffee table, organic form, boho living"),
tb("boho-rattan-side","藤編側桌（小）","table",["boho","mediterranean"],
   ["rattan side table","wicker table","round side"],["natural rattan"],
   2200,"Dia40xH55","woven rattan round side table, natural finish, boho accent"),
tb("boho-trunk-table","復古皮革行李箱茶几","table",["boho","industrial"],
   ["vintage trunk","storage table","bohemian table"],["caramel brown","brass"],
   8500,"W90xD55xH45","vintage-style leather trunk coffee table, brass corner guards, boho"),
tb("boho-embroid-curtain","刺繡波西米亞窗簾","curtain",["boho"],
   ["embroidered curtain","boho drape","pattern curtain"],["cream","mustard","terracotta"],
   5500,"W250xH270","hand-embroidered boho curtain, folk pattern, warm earthy tones"),
tb("boho-linen-sofa","棉麻布藝低矮沙發（鬆弛感）","sofa",["boho"],
   ["low sofa","linen sofa","casual sofa"],["cream","natural linen","rust"],
   18000,"W220xD100xH70","oversized low linen sofa, relaxed cushions, boho casual living"),
tb("boho-plant-stand","黑色不規則鐵藝花架","plant",["boho","industrial"],
   ["plant stand","floor planter","monstera stand"],["matte black"],
   2400,"Dia30xH120","slim matte black iron plant stand, boho indoor jungle display"),
tb("boho-globe-lights","藤球串燈（10顆）","lighting",["boho"],
   ["rattan ball light","globe string lights","warm string"],["natural rattan","warm white"],
   1800,"10globes/5m","rattan globe string lights, warm 3000K, boho bedroom ceiling"),
tb("boho-wood-tray","手繪圖騰木質托盤","accessory",["boho"],
   ["painted tray","wooden tray","decorative tray"],["terracotta","indigo","cream"],
   1400,"W40xD30","hand-painted folk-pattern wooden serving tray, boho display"),
tb("boho-cactus-pot","多肉仙人掌陶瓷花盆（臉型）","plant",["boho"],
   ["cactus pot","face planter","succulent pot"],["terracotta","blush","sage"],
   980,"Dia12","face-shaped ceramic succulent planter, boho quirky plant display"),
tb("boho-fringe-runner","流蘇桌旗（印花）","accessory",["boho"],
   ["fringe table runner","boho textile","decorative runner"],["mustard","terracotta","cream"],
   1200,"W35xL180","hand block-printed cotton table runner with knotted fringe, boho"),
tb("boho-rattan-mag","藤編雜誌架","storage",["boho","mediterranean","nordic"],
   ["rattan magazine rack","wicker holder","floor rack"],["natural rattan"],
   1800,"W30xD20xH50","woven rattan magazine and book floor rack, boho living room"),
tb("boho-botanical-art","植物拓印裝飾畫（4聯）","accessory",["boho","nordic"],
   ["botanical print","wall art","plant illustration"],["sage green","cream","dusty rose"],
   3200,"30x40each(set4)","botanical leaf illustration print set of 4, boho gallery wall"),
tb("boho-crochet-blanket","手工鉤織毯子（漸層色）","accessory",["boho"],
   ["crochet blanket","handmade throw","colorful throw"],["mustard","rust","terracotta","sage"],
   4200,"150x180","hand-crochet cotton blanket, boho earthy gradient, sofa throw"),
tb("boho-gallery-frame","波西米亞混材質相框組（6件）","accessory",["boho"],
   ["gallery frame set","boho frames","mixed material frames"],["rattan","macrame","wood","rope"],
   2800,"various","mixed material gallery wall frame set, rattan, wood, rope, boho eclectic"),
tb("lux-marble-tray","大理石托盤（黃銅邊框）","accessory",["luxury","art-deco"],
   ["marble tray","decorative tray","luxury tray"],["white marble","brass"],
   2800,"W35xD25","white marble serving tray, brushed brass rim, luxury coffee table"),
tb("muji-aroma-diffuser","陶瓷超聲波香氛機","accessory",["muji","japanese"],
   ["aroma diffuser","humidifier","ceramic diffuser"],["matte white","off-white"],
   2400,"Dia10xH15","matte white ceramic ultrasonic diffuser, Muji wellness minimalist"),
]

print(f"Total items: {len(ITEMS)}")

# 驗證每個風格有多少件
style_count = {}
for item in ITEMS:
    primary = item["style_tags"][0]
    style_count[primary] = style_count.get(primary, 0) + 1

for style, count in sorted(style_count.items()):
    print(f"  {style}: {count} items")

with open("furniture_catalog.json", "w", encoding="utf-8") as f:
    json.dump(ITEMS, f, ensure_ascii=False, indent=2)

print("\nfurniture_catalog.json written.")
